jekyll/jekyll

- lib/site_template/_layouts/page.html
- lib/site_template/_layouts/post.html
*note*: This is a resubmission of https://github.com/jekyll/jekyll/pull/2963
Currently the post and page header elements lies outside of the article element, meaning they have no actual relation to the given article at all, beyond an implied visual relationship.
This PR moves page and post `<header>` elements within the `<article>` element to restore the semantic relationship between the two.
There are no visual differences in rendered output after this change. But the html5 outliner will be much happier.
--- 
It's probably worth also pointing to the spec detailing sectioning content http://www.w3.org/html/wg/drafts/html/master/dom.html#sectioning-content and the usage examples http://www.w3.org/html/wg/drafts/html/master/sections.html#usage-summary-0 for the header element.
You can also …
> [imp] Semantic structure improvements - rebased

- Rakefile
*  Automate creating gh-pages directory
*  Ensure gh-pages dir always has correct branch checked out
*  Purge gh-pages of files so that a sync of site truly occurs
*  Ensure dot files are synced
*  Be exact with our exclusions to eliminate guess work
> Update rake task site:publish to fix minor bugs.

- README.markdown
This way we have consistent badges.
Note that I didn't use the flat badges, which personally, I prefer, since shields.io doesn't support [hakiri (yet)](https://github.com/badges/shields/issues/270).
> Switch to shields.io for the README badges.

- Rakefile
@penibelst mentioned maybe using Rake::FileList in https://github.com/jekyll/jekyll/pull/3254
I think that's a smart move - plus any chance to use splat arguments is fun!
> Use FileList instead of Dir.glob

- lib/jekyll/collection.rb
- lib/jekyll/site.rb
- test/source/_slides/non-outputted-slide.html
- test/test_document.rb
Allow documents to override the collection's `output` property in its front-matter. Fixes #2956. Should be a non-breaking change.
> Allow documents to override output property in front-matter

- lib/site_template/_sass/_layout.scss
With the default theme, when you have multiple pages and thus "nav items", they span over multiple rows.
Problem: the nav items are misaligned
Solution: use margin-right instead of margin-left
> Fix nav items alignment when on multiple rows

- site/_docs/plugins.md
The jekyll-asciidoc plugin enables AsciiDoc used for Jekyll site generation. It is now available for download as a v1.0.0 release gem on Rubygems, and is being used in production for a number of websites (for example, see my [jekyll-asciidoc gem release announcement post](http://thepaulrayner.com/blog/2015/01/05/jekyll-asciidoc-gem-published/). It would be great if it could be added to the list of Jekyll plugins.
> Add new AsciiDoc plugin gem to list of Jekyll plugins.

- lib/jekyll/tags/highlight.rb
- test/test_tags.rb
This PR expands on the work @kevinushey did in #3275. It includes tests.
> Highlight: Only Strip Newlines/Carriage Returns, not Spaces

- lib/jekyll/tags/highlight.rb
This modifies the `render` function to only strip leading / trailing newlines, rather than all whitespace.
(This change could be contentious for some, so I do wonder if it could / should be hidden behind a configuration setting in `_config.yaml`, perhaps...)
This PR is not complete (ie -- needs tests), but hopefully it can be finished off with help from the more experienced contributors.
> only strip newlines when rendering highlight blocks (#3265)

- site/_docs/collections.md
Clarifying what happens if no YAML front matter exists. The current explanation says that Jekyll will generate a file without Front Matter, but it appears this isn't the case.
I'm still not sure if this is the intended behaviour, but this clarifies how it currently works.
> Change collection documentation based on #223

- site/_includes/anchor_links.html
- site/_includes/footer.html
- site/_includes/header.html
- site/_includes/news_item.html
- site/_layouts/news_item.html
- site/_sass/_style.scss
- site/index.html
> Docs: Assorted accessibility tweaks.

- site/_docs/configuration.md
Clarify ability to retain generated content in `destination` via the `keep_files` configuration directive.
> Update configuration.md docs - retain content in `destination` via `keep_files`

- site/_includes/docs_ul.html
So in liquid 2.5.0 they added break and continue support: https://github.com/Shopify/liquid/blob/master/History.md#250--2013-03-06
So our build time loop that invokes this code looks something like this:
for every page:
for every section in our docs.yml
for every doc in our yaml section
for every doc in our site.docs collection
build a link {sadly, we need the page title so this nested mess is needed}
Without the break we iterate through every doc for every link, this will at least stop the last doc loop once we've built the link.
Non-scientific performance measurement/improvement:
Without break:
$ time jekyll build
Configuration file: /home/flyinprogrammer/Development/jekyll/site/_config.yml
Source: /home/flyinprogrammer/Development/jekyll/site
Destination: …
> Break when we successfully generate nav link.

- lib/jekyll/filters.rb
- test/test_filters.rb
As uncovered in #3298, the `date` method in `filters.rb` should accept a Date object.
> Date method in filters.rb should accept a Date object

- lib/jekyll/static_file.rb
- test/test_site.rb
Use the `preserve` option when copying static files using `FileUtils.cp`; this will preserve the file's original mtime. To preserve the original mtime of a file is important, for example, when syncing the _site folder.
> Preserve original mtime when copying static files

- site/_docs/plugins.md
- Add command to list of types of plugins
- Made "command" plural to be consistent with other types
- Made the types into links within the page
> Formatting fixes

- features/post_data.feature
- lib/jekyll/post.rb
- test/source/_posts/2013-07-22-post-excerpt-with-layout.markdown
- test/source/_posts/2013-12-20-properties.text
- test/source/_posts/2014-07-05-another-mixed-case-category.markdown
- test/source/_posts/2014-07-05-mixed-case-category.markdown
- test/test_excerpt.rb
- test/test_generated_site.rb
- test/test_post.rb
- test/test_site.rb
Resolves #1739.
It preserves letter case of category, but return `category.downcase` for `url_placeholders`. Also added some proper tests. If there are needed updates for documentation, please let me know.
> Use category in downcase only for URL

- site/_docs/configuration.md
> Added versioning comment to configuration file

- features/frontmatter_defaults.feature
- lib/jekyll/post.rb
This basically will fix https://github.com/jekyll/jekyll/issues/2371. Please check/reproduce there.
When FrontmatterDefaults tries to find matching sets from config file, lookup by path fails if it also contains "_posts" part. So instead of matching path like "/all/pages/2014-01-01-test.md" it will try to also match "/all/pages/_posts/2014-01-01-test.md".
Without the fix, we won't be able to customize via _config.yml files not assigned to any category (located at root /_posts)
> Find variables in _config.yaml by searching with relative file path.

- lib/jekyll/document.rb
- test/source/_methods/yaml_with_dots.md
- test/test_collections.rb
- test/test_document.rb
Posts can have YAML front matter that ends with three dots instead of dashes since 52ac2b3 but that only applies to posts. This PR adds the ability for the YAML front matter of collections files to end with dots as well.
I don't have very much experience in writing ruby code and tests, but I managed to write one. It probably can be improved but I just don't have enough experience to know how to do that yet.
> Allow collections YAML to end with dots

- features/frontmatter_defaults.feature
- features/permalink_default.feature
> Allow variables (e.g `:categories`) in YAML front matter permalinks

- lib/jekyll/filters.rb
- lib/jekyll/utils.rb
- site/_docs/templates.md
- site/_sass/_style.scss
- test/test_filters.rb
- test/test_utils.rb
Add `mode` parameter to `slugify` Liquid filter. The default value is `default`.
SLUGIFY STYLE       | DESCRIPTION                
--------------------|----------------------------
`none`              | Convert to lowercase.
`raw`               | Convert to lowercase, and replace every sequence of **spaces** with a hyphen.
`default`           | Convert to lowercase, and replace every sequence of **spaces and non-alphanumeric characters** with a hyphen.
`pretty`            | Convert to lowercase, and replace every sequence of **spaces and non-alphanumeric characters (except for `._~!$&'()+,;=@`)** with a hyphen.
Examples:
```
{{ "The _config.yml file?" | slugify }}
#=> the-config-yml-file
{{ "The _config.yml file?" | slugify:'none' }}
#=> the _config.yml file?
{{ "The _config.yml file?" | …
```
> Add mode parameter to slugify Liquid filter

- features/collections.feature
- lib/jekyll/converters/markdown.rb
- lib/jekyll/utils.rb
- `Markdown#matches` should avoid regexp
- Use frozen regular expressions for `Utils#slugify`
> Performance upgrades

- lib/site_template/_sass/_layout.scss
Before:
After:
(Screenshots from iPhone 4s simulator)
Considering [the site title is 15px away from the left screen border](https://github.com/jekyll/jekyll/blob/v2.5.3/lib/site_template/_sass/_base.scss#L169) ($spacing-unit is 30px) on small screens:
```CSS
.wrapper {
@include media-query($on-laptop) {
padding-right: $spacing-unit / 2;
padding-left: $spacing-unit / 2;
}
}
```
site-nav (the "burger" menu) should be 15px from the right screen border instead of the hardcoded value of 30px.
> Fix site-nav alignment on small screens

- site/_docs/plugins.md
Hi folks, would like to request the jekyll-minifier plugin be added to the Jekyll Plugins page to make life a bit easier for Jekyll users.
jekyll-minifier has also been published on rubygems.org at https://rubygems.org/gems/jekyll-minifier
> Add jekyll-minifier to the plugins page

- site/_posts/2015-01-20-jekyll-meet-and-greet.markdown
Address was pointing to "85" Colin P Kelly, but should be "88". Via https://github.com/jekyll/jekyll/pull/3332#issuecomment-70858765
cc @alfredxing (good :eyes:) @parkr @gjtorikian
> Fix Google Maps link to GitHub HQ in Jekyll meetup blog post

- lib/jekyll/url.rb
- test/test_url.rb
This will make it cleaner to generate urls with optional keys in the permalink template.
> Strip slashes on nil url tokens

- lib/site_template/_sass/_layout.scss
I have introduced a bug with [this pull request](https://github.com/jekyll/jekyll/pull/3264) when the menu is in "burger" mode:
Original CSS rule:
```CSS
.page-link {
&:not(:first-child) {
margin-left: 20px;
}
}
```
[First pull request](https://github.com/jekyll/jekyll/pull/3264) to fix nav items on multiple lines:
```CSS
.page-link {
&:not(:last-child) {
margin-right: 20px;
}
}
```
And we also need this to fix the "burger" menu:
```CSS
@include media-query($on-palm) {
.page-link {
margin-right: 0 !important;
margin-left: 20px;
}
}
```
> Fix nav items alignment when in "burger" mode

- lib/site_template/css/main.scss
Helvetica Neue (1983) features multiple improvements over the original Helvetica font (1957), 'neue' means 'new' in German
If the OS does not include Helvetica Neue, then it falls back to Helvetica and if ...
FYI
- Bootstrap: [`"Helvetica Neue", Helvetica, Arial, sans-serif`](https://github.com/twbs/bootstrap/blob/v3.3.2/less/variables.less#L45) (here a discussion about it: https://github.com/twbs/bootstrap/issues/13823)
- Ionic: [`"Helvetica Neue", "Roboto", sans-serif !default`](https://github.com/driftyco/ionic/blob/v1.0.0-beta.14/scss/_variables.scss#L19)
- Foundation: [`"Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif !important`](https://github.com/zurb/foundation/blob/v5.5.0/doc/assets/scss/_global.scss#L45) (<- curious about why they double name Helvetica...)
- Disqus: …
> Switch default font to Helvetica Neue

- lib/jekyll/document.rb
- site/_docs/permalinks.md
- test/source/_slides/example-slide-6.html
- test/test_document.rb
This mimicks posts most closely. It can be overridden by the `slug` YAML front matter element.
Undoes some of #2864, but fixes a consistency problem shown in #3372.
> The :title URL placeholder for collections should be the filename slug.

- lib/jekyll/site.rb
- test/test_site.rb
I actually need this for a monkey-patch I am planning. :wink: But it does look cleaner, no?
/cc @parkr
> Factor out a `read_data_file` call to keep things clean

- Gemfile
- features/markdown.feature
- features/pagination.feature
- features/rendering.feature
- features/step_definitions/jekyll_steps.rb
- jekyll.gemspec
- lib/jekyll.rb
- lib/jekyll/configuration.rb
- lib/jekyll/related_posts.rb
- lib/jekyll/tags/highlight.rb
- site/_docs/configuration.md
- test/test_coffeescript.rb
- test/test_configuration.rb
This moves the following gems to as-wanted:
- pygments.rb
- redcarpet
- toml
- jekyll-paginate
- jekyll-gist
- jekyll-coffeescript
- classifier-reborn
~~I'm on the fence about also taking `jekyll-watch` away...~~ We're going to keep it.
> Remove most runtime deps & move to Rouge as default highlighter

- lib/jekyll/commands/serve.rb
This shows people how to kill Jekyll without knowing the PID using `pkill` (you could also do `kill -9 $(pgrep -f jekyll)` but that is just the long way around doing `pkill -f` so it shouldn't be shown in the Jekyll logger but can be documented here for people.
> Fixes #3339 Add `pkill -f jekyll` to ways to kill.

- lib/site_template/_sass/_base.scss
- lib/site_template/css/main.scss
This PR introduces a new $base-font-weight variable, as we already have a var for other base font values, and then declares the `<body>` font properties with a single declaration in place of four.
Easier to configure, less css, same visual output.
> A lighter, smarter, font declaration

- site/_docs/templates.md
`The are as follows (with what they filter):`
should read:
`They are as follows (with what they filter):`
> fix missing char in template docs

- lib/site_template/_sass/_base.scss
`overflow-x: scroll;` makes scrollbar visible always whether the content does overflow or not.
- `overflow-x: scroll`:
- `overflow-x: auto`:
> Change `overflow-x` value to `auto` of `pre` in the site template

- Rakefile
In an effort to :dog2: food our features, let's compile jekyllrb.com with jekyll/jekyll HEAD rather than with Jekyll 2.4.0 or whatever GitHub Pages is using. If we're actively using the tool to build our documentation, we'll encounter the pain points and bugs and (hopefully) fix those before HEAD is released into the wild.
> Release jekyllrb.com as a locally-compiled site.

- lib/jekyll/tags/highlight.rb
- test/test_tags.rb
Caused some bullshit on our website:
Ref: https://github.com/jneen/rouge/issues/230
> The highlight tip should only clip the newlines before and after the *entire* block, not in between

- lib/jekyll/tags/highlight.rb
- test/test_tags.rb
Found by @EdMcBane in https://github.com/jekyll/jekyll/pull/3435
The strange regexp we were doing to replace the `<pre><code></pre></code>`
bits in the Pygments output were wreaking havoc on Rouge output
because Rouge uses `<pre>`'s to wrap line numbers.
To be consistent, the output from `render_*` should *not* include
the wrapping `<div>` and `<pre>` tags. It should just be what was
inside. We can then wrap it in our own custom tags without using
any regular expressions, as God intended. Death to regular
expressions and HTML manipulation!
> highlight: fix problem with linenos and rouge.

- site/_docs/resources.md
`jordanthornque.st` should be `jordanthornquest.com`. That's been remedied!
> Fix broken link in resources

- lib/site_template/_includes/footer.html
There is no class text defined in the CSS
> Remove class="text"

- lib/site_template/_sass/_base.scss
- site/_sass/_style.scss
Add `text-rendering: optimizeLegibility` to enable kerning and ligatures. This applies to the site template as well as the jekyllrb.com site.
For the site template, this should produce a more desirable result for the site header when combined with #3379.
:sparkles: Kerning! :sparkles: Ligatures! :sparkles:
> Optimize text rendering for legibility

- lib/jekyll/commands/serve.rb
This modifies the WEBrick server started by `jekyll serve` such that a file "/foo.html" can be requested at "/foo". The behavior mirrors the GitHub Pages server configuration closely: first check for a file in the original location and then fallback to checking for file + `.html` extension.
The response's Content-Type ("text/html"), Content-Length, ETag, and Last-Modified headers are all set appropriately, as if the request was made with the `.html` suffix.
See the individual commits for additional remarks on the implementation.
/cc https://github.com/jekyll/jekyll/issues/156, https://github.com/jekyll/jekyll/issues/2021, https://github.com/holman/feedback/issues/231
> Mimic GitHub Pages .html extension stripping behavior

- lib/jekyll/site.rb
> Site#read_data_file: read CSV's with proper file encoding

- lib/jekyll/post.rb
This is useful in development scenarios where you are building with `--drafts`, and want to identify which posts are the drafts.  As an example, I have a [`/drafts`](https://github.com/willnorris/willnorris.com/blob/master/src/drafts.html) page that simply lists all of my current draft posts.
> add draft? method to identify if Post is a draft

- lib/jekyll/site.rb
For a full rebuild, we certainly don't want to *read* from `.jeykll-metadata`, but we should still write it.  Otherwise, a subsequent incremental build would have to do a full rebuild again since there is no metadata file to start from.
/cc @alfredxing @mattr- to confirm
> write .jekyll-metadata even on full_rebuild

- site/help/index.md
See issue #3465
Changed the link on the help page to directly link to the Twitter @jekyllrb account.
> Change Twitter link to link directly to @jekyllrb.

- site/_docs/templates.md
Initial wording was kind of clunky and hard to read. Also there was an unnecessary semi-colon.
> Fix wording in code snippet highlighting section

- site/_docs/pagination.md
If this '/' is not present, then the second pagination code snippet
under the "Render the paginated Posts" section will have a bug.
Let's say my page 1 is located at host:port/blog/index.html and my
paginate_path setting in _config.yml is "blog/page:num/". The
observation if the paginate_path does not start with a '/' is that the href generated for the page numbers will have 2 'blog's, i.e. for page 2 the href will
incorrectly appear as 'host:port/blog/blog/page2' instead of just
'host:port/blog/page2'.
This will be resolved by prepending a '/' to the paginate_path configuration. Note that adding a '/' will also be consistent with the format of `paginator.next_page_path` and `paginator.previous_page_path` since they also start with a '/'.
> Add a '/' to paginate_path in the Documentation on the Pagination page

- lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb
See issue #3501
Changed the doc link in the template to link to /docs/home instead of /
Signed-off-by: Joop Aué <joopaue@gmail.com>
> Changed doc link in template

- test/test_document.rb
Use the `fixture_site` helper in the Document tests instead of `Site.new(Jekyll.configuration(overrides))`. It turns out `fixture_site` already defaulted to `full_rebuild: false`
Should fix #3500
> Use `fixture_site` for Document tests

- lib/site_template/_config.yml
When I followed the example in the _config.yml for the base url:
baseurl: "" # the subpath of your site, e.g. /blog/
Jekyll put two slashes in the URL like this: http://yourdomain.com/blog//
I figured the comment might as well be updated.
> Removed the trailing slash from the example "/blog/" basurl comment.

- site/_docs/plugins.md
Added to the plugin list: jekyll-auto-image. A generator that makes available the first image of a post.
By installing the plugin you will be able to access the first image with {{ @page.image }}. This plugin is useful to Include an image on your list of posts or to set a twitter card for each post/page.
> Updated plugins: added jekyll-auto-image generator

- site/_posts/2015-02-26-introducing-jekyll-talk.markdown
Add a blog post on the site introducing the new Jekyll Talk forums (ref #3517).
@parkr :eyes:
> Add blog post introducing Jekyll Talk

- site/_docs/plugins.md
Replaced a picture element link with @parkr's suggestion.
Fixes #3521.
> Replaced link caught by htmlproofer.

- Gemfile
- benchmark/end-with-vs-regexp
- lib/jekyll/document.rb
- lib/jekyll/page.rb
- lib/jekyll/post.rb
Turns out `end_with?` is about twice as fast.
```
~/jekyll/jekyll#master$ be ruby benchmark/end-with-vs-regexp
Calculating -------------------------------------
no slash regexp    55.397k i/100ms
no slash end_with?   114.876k i/100ms
-------------------------------------------------
no slash regexp    906.003k (± 5.8%) i/s -      4.543M
no slash end_with?      4.467M (± 8.9%) i/s -     22.171M
Calculating -------------------------------------
slash regexp    60.033k i/100ms
slash end_with?   112.577k i/100ms
-------------------------------------------------
slash regexp      1.042M (± 6.2%) i/s -      5.223M
slash end_with?      4.496M (± 9.5%) i/s -     22.290M
```
> Use String#end_with?("/") instead of regexp

- site/_docs/frontmatter.md
I saw [this question](http://stackoverflow.com/q/18362317/677526) on StackOverflow, and realized that having the answer in the documentation would be beneficial.
> docs: Add frontmatter date formatting information

- site/_docs/permalinks.md
ordinal was actually added back in April 2013 in ea753130
> document 'ordinal' built-in permalink style

- lib/jekyll/commands/doctor.rb
- lib/jekyll/configuration.rb
- lib/jekyll/site.rb
Replaced occasions where the logger was used to report deprecations.
Deprecator is now used instead.
see #3534
> Removed deprecation inconsistency

- features/permalinks.feature
- lib/jekyll/document.rb
- lib/jekyll/page.rb
- lib/jekyll/post.rb
- test/source/_posts/2015-02-20-extensionless-permalink.markdown
- test/source/deal.with.dots.html
- test/test_document.rb
- test/test_generated_site.rb
- test/test_page.rb
- test/test_post.rb
This is an initial take at always including file extensions on destination files written to disk.  This is a continuation of the discussion that's happened on #2294 and #3463, and coincides with the WEBrick changes in #3452.  
This should only have any impact when the site or post permalink setting is configured without either a trailing slash or the file extension for that file type.  In that case, the file written to disk will contain the correct extension for that type, while the URL will remain as specified in the permalink setting.
Notably, this does break the test that was added in #2925 to support files ending in ".htm" rather than ".html" (cc @pathawks to discuss), because this is using the `output_ext` value to determine the expected extension for the destination file.  I believe …
> always include file extension on destination files

- lib/jekyll/command.rb
> Added build --destination and --source flags

- lib/jekyll/url.rb
- Single Quotes
- Fixed typo in variable name.
- Removed Redundant Escaping in Regular Expression.
> Refactored url.rb to be compliant with Ruby Style Guide.

- lib/jekyll/collection.rb
- lib/jekyll/page.rb
- lib/jekyll/utils.rb
- test/test_document.rb
- test/test_page.rb
- test/test_utils.rb
This updates the default permalink style for pages and collections to match the site-wide 'permalink' setting (more detailed notes in the commit message).
I'm not wild about the method name `Utils.append_permalink_ending`, but at least it's accurate.  I'm certainly open to suggestions for a better name there.
I also have not yet written the user-facing docs describing how this works.  I'll certainly do that as part of this PR, but wanted to go ahead and get some :eyes: on the implementation before then.  I also wasn't quite sure how we handle docs for features that aren't yet in the current stable release.  Do we just hold off pushing those live?  Or do we just say that the docs on jekyllrb.com correspond to the latest master branch, not necessarily any particular released version?
> Improved permalinks for pages and collections

- lib/site_template/_layouts/post.html
The post from the site template does not have `meta` in its front matter. 
Related to #3536.
> Removing unused code from post layout

- lib/jekyll/configuration.rb
- lib/jekyll/site.rb
- test/test_configuration.rb
- test/test_site.rb
I noticed Jekyll generates some warnings on Travis build: https://travis-ci.org/yous/yous.github.io/builds/52976809
- Remove duplicated range from regex
`/\w/` is equivalent to `[a-zA-Z0-9_]`. See http://ruby-doc.org/core-2.2.0/doc/regexp_rdoc.html#label-Character+Classes.
- Replace `File.exists?` with `File.exist?`
`File.exists?` is deprecated method. See http://ruby-doc.org//core-2.2.0/File.html#exists-3F-method.
> Resolve warnings

- lib/jekyll/filters.rb
- test/test_filters.rb
Sort will now throw an error when a nil object array is given as input.
See issue #3491 for more information.
> Sort will now raise error on nil object array input.

- site/_docs/pagination.md
Fixes https://github.com/jekyll/jekyll-paginate/issues/25
> Add permalink warning to pagination docs

- Gemfile
- features/support/env.rb
- test/helper.rb
- test/test_command.rb
- test/test_configuration.rb
- test/test_entry_filter.rb
- test/test_generated_site.rb
- test/test_layout_reader.rb
- test/test_log_adapter.rb
- test/test_new_command.rb
- test/test_path_sanitization.rb
- test/test_related_posts.rb
- test/test_site.rb
- test/test_tags.rb
`rr` gem is not maintained anymore. We can replace it with rspec-mock, and stop using mocking in a few spots.
review @parkr @envygeeks 
[fixes #3549]
> Use rspec-mock instead of rr

- site/_docs/frontmatter.md
- site/_docs/permalinks.md
This adds docs for two new permalink features coming in Jekyll 3:
- improved default permalinks for pages and collections (#3538)
- support for extensionless URLs (#3490)
There are a few places where I feel that the language isn't as smooth as it could be, but I want to go ahead and get these out for review.
> update permalinks docs

- site/_docs/contributing.md
With #3552, Jekyll is now using **[RSpec Mocks](https://github.com/rspec/rspec-mocks/)** instead of **[RR](https://github.com/btakita/rr/)**.
This updates the documentation to reflect that change.
> RR replaced with RSpec Mocks

- site/_docs/structure.md
I put this after `_site` because it's *probably* the least important file in this list.
It would be nice to link to a more detailed explanation of incremental regeneration, and document `-f` or `--full-rebuild` options, but I could not find any existing docs.
#3595
> Add information .jekyll-metadata

- lib/jekyll/regenerator.rb
- lib/jekyll/site.rb
- test/test_regenerator.rb
- test/test_site.rb
To address part of #3591, clear the regenerator's cache every time the
site is processed. This ensures that the regenerator doesn't incorrectly
believe a file hasn't changed based on stale information.
> Clear the regenerator cache every time we process

- script/test
- test/test_tags.rb
Rather than use script/test to create the tmp directory, create it in a setup block for the appropriate context in the `TestTags` test.
> Create 'tmp' dir for test_tags if it doesn't exist

- site/_docs/templates.md
> Document addition of variable parameters to an include.

- lib/jekyll/log_adapter.rb
The name 'Jekyll' is removed a few times from the comments, because this isn't useful. This was a suggestion made in pull request [#3611](https://github.com/jekyll/jekyll/pull/3611).
> Removed the word 'Jekyll' a few times from the comments

- lib/jekyll/regenerator.rb
- test/test_regenerator.rb
- test/test_site.rb
Incremental build doesn't check if the destination file is present (#3591). This means that if the file is accidentally deleted, or the configuration changes what the output file should be, the incremental build will not regenerate the file.
> Incremental build if destination file missing

- script/test
Added the `--profile` flag to make use of the minitest-profile tool as requested after the unmerged pull request [#3627](https://github.com/jekyll/jekyll/pull/3627). Profiling the slowest 10 tests was accidentally removed in [this](https://github.com/jekyll/jekyll/commit/c6d62828baeb260c208a04057b68407a2f4a6938) commit.
> Minitest-profile

- site/_docs/collections.md
The current documentation refers to a location below for a discussion of accessing document variables, but does not provide anything concrete. I have persevered with the albums example, and given something slightly complex in order to show how to access nested attributes (since I found it difficult to find documentation on this).
I also noted a method for setting default variables in collections and fixed a minor typo.
It would also be useful to add an example of how to access nested attributes on the current collection item without using a for loop (I am embarrassed to say that I don't know how to do it myself).
> Expand collections documentation.

- test/test_static_file.rb
Added tests for `Jekyll:StaticFile` this should solve issue [#3626](https://github.com/jekyll/jekyll/issues/3626).
> Added tests for Jekyll:StaticFile

- lib/jekyll/static_file.rb
I have removed the unused method `StaticFile::extname`. The method is not used by any test and doesn't add value. Everywhere `File.extname(path)` is called directly, therefore `StaticFile::extname is useless`.
> Removed unused method StaticFile::extname

- lib/jekyll/regenerator.rb
- test/test_regenerator.rb
When adding a dependency, also add the dependency to the metadata hash.
Addresses part 1 of #3591. Prior to this fix, the regnerator only paid attention the mtime of the first dependency it checked, so for posts/pages with N multiple dependencies (i.e., every layout file used to render them), it continues to regenerate the post/page approximately N times, at which point it's seen all of the dependencies.
> Process metadata for all dependencies

- site/_docs/upgrading.md
Per #3324 and comments in #3602, docs changes related to the upgrade process for 3.0 can land here. In their current state, there is some duplication on the [Upgrading][] page and the information is (obviously) in need of an update.
[Upgrading]: http://jekyllrb.com/docs/upgrading/
> Upgrade guide for Jekyll 3

- site/_docs/datafiles.md
- site/_docs/variables.md
This patch is an update to the docs showing how to access specific data items via front matter variables.
> Showing how to access specific data items

- Gemfile
*Note*: Please release a new gem version of jekyll after merging this.
More information at: http://osvdb.org/show/osvdb/120415
`redcarpet Gem for Ruby contains a flaw that allows a cross-site scripting (XSS) attack. This flaw exists because the parse_inline() function in markdown.c does not validate input before returning it to users. This may allow a remote attacker to create a specially crafted request that would execute arbitrary script code in a user's browser session within the trust relationship between their browser and the server.`
https://github.com/diaspora/diaspora/commit/9fc00d0814807064e2dc7343fc330f7cdcf8112a
https://github.com/fiedl/your_platform/commit/8e707ebb947dd4277704849bcc4a383401d4bd0e
http://social.schiessle.org/display/b38b1460c2b201329b1f4860008dbc6c …
> Security fix: OSVDB-120415 - Upgrade redcarpet to 3.2

- lib/jekyll/related_posts.rb
- test/test_related_posts.rb
When looking for related posts, Jekyll was *indexing* `Jekyll::Post`
objects, but *finding* related posts based on `Jekyll::Post#content`. This
caused two problems:
1. Ruby 2.2 will warn on `==` if `<=>` throws an exception (and future Ruby
versions will surface that exception). Because `String`s can't be
compared with `Jekyll::Post`s, this warning was appearing all the time
while searching for related posts.
2. LSI won't return a post itself when searching for related posts. But
LSI could never tell that we were searching on a post, since Jekyll
passed post content, not a post object. With this fix, we can remove the
`- [post]` from `Jekyll::RelatedPosts#find_related`.
This is a more accurate fix for #3484.
> Use `Jekyll::Post`s for both LSI indexing and lookup.

- Gemfile
- test/helper.rb
- test/test_command.rb
/cc @parkr @arthurnn @alfredxing
> Create #mock_expects that goes directly to RSpec Mocks.

- lib/jekyll/mime.types
```
$ curl http://localhost:4000/feed.xml -I
HTTP/1.1 200 OK
Etag: 64af8c-2356-552805aa
Content-Type: text/xml; charset=utf-8
Content-Length: 9046
Last-Modified: Fri, 10 Apr 2015 17:17:30 GMT
Server: WEBrick/1.3.1 (Ruby/2.2.1/2015-02-26)
Date: Fri, 10 Apr 2015 17:17:34 GMT
Connection: Keep-Alive
```
Originally contributed to https://github.com/fitztrev/jekyll-utf8/pull/3
> Fix header for RSS feeds with UTF8 characters.

- lib/jekyll/commands/build.rb
- lib/jekyll/configuration.rb
- lib/jekyll/log_adapter.rb
- test/test_log_adapter.rb
Adds Jekyll::LogAdapter#adjust_verbosity which ensures that --quiet always wins. Also refactors Jekyll::Configuration minorly to dry up the #source, #quiet?, and new #verbose? methods.
Tests included; all tests pass.
> Set log level to debug when verbose flag is set

- lib/jekyll/commands/doctor.rb
- lib/jekyll/configuration.rb
- lib/jekyll/page.rb
- lib/jekyll/site.rb
- site/_config.yml
- site/_docs/configuration.md
- site/_docs/upgrading.md
Remove relative permalinks support for 3.0. Still provides an error message when the configuration option is set (this can be removed in a couple more minor/patch versions).
Ref #2744.
> Remove relative permalinks

- Gemfile
- script/rubyprof
Inspired by [script/stackprof](https://github.com/jekyll/jekyll/blob/63792ad322183f159c530e9f1112b94bc333d200/script/stackprof), this adds a script to generate [ruby-prof](https://github.com/ruby-prof/ruby-prof) profiles in KCachegrind calltree format (can be opened using qcachegrind under Mac OS X).
Output looks something like this:
Thoughts @parkr?
> Add script/rubyprof to generate cachegrind callgraphs

- lib/jekyll/document.rb
I'm probably overlooking something, but this passes tests and (on my machine) shaves off about ~1.5 seconds of build time for the page in "site". Turns out `Document#to_liquid` is called a lot, which calls `url`, which calls `url_placeholders` which calls `slugify`, which apparently is kinda expensive.
I don't know how "representative" the site in "site" is and if this PR has any value to "real" and bigger Jekyll pages.
```
==================================
Mode: cpu(100)
Samples: 1345 (1.10% miss rate)
GC: 92 (6.84%)
==================================
TOTAL    (pct)     SAMPLES    (pct)     FRAME
104   (7.7%)         104   (7.7%)     Jekyll::Utils#slugify
98   (7.3%)          97   (7.2%)     Jekyll::Tags::IncludeTag#read_file
135  (10.0%)          63   (4.7%) …
```
> Cache Document#to_liquid

- features/hooks.feature
- lib/jekyll.rb
- lib/jekyll/convertible.rb
- lib/jekyll/document.rb
- lib/jekyll/hooks.rb
- lib/jekyll/page.rb
- lib/jekyll/post.rb
- lib/jekyll/renderer.rb
- lib/jekyll/site.rb
- site/_docs/plugins.md
This is a second attempt at #3498 (adding hooks to Jekyll). In my last attempt @envygeeks had some complaints about the lack of encapsulation. This PR is an attempt to address those concerns and try out a new idea. This is definitely not ready to merge, but I wanted to get some eyes on it before I implement and write tests for the whole thing. The hooks concept is inspired by, but in this instance not perfectly compatible with octopress-hooks, so it's a bit of a departure from #3392 by @parkr, but I think it nicely encapsulates the hook logic.
Here's a practical example of how you could use one of these hooks to do something useful: https://github.com/stevecrozz/featherblade
> prototype of jekyll hooks, encapsulated

- lib/jekyll/cleaner.rb
Small micro-optimization. Will probably not make a big difference for most sites, but on our ~6000 files site, it shaves off about a second off build time.
The optimization is to not call the `keep_file_regex` and `keep_dirs` methods in every single iteration of the block but only once at the beginning. Also use `Regexp.union` instead of that ugly hack.
@parkr
> Make Jekyll::Cleaner#existing_files more lazy

- site/help/index.md
In #3694 I assume you meant this file, site/help/index.md.
Is there anything you want me to add though? The only obvious change to me was the presence of jekyll/jekyll-help.
> Omit jekyll/jekyll-help from list of resources.

- lib/jekyll/commands/doctor.rb
- lib/jekyll/utils.rb
- lib/jekyll/utils/platforms.rb
This is just a basic test (as implied through a lot of the conversation) and will probably not suffice for all but according to what I have read, this basic test can detect most anomalies so we can warn you but it's not bulletproof by any means.
Ref: #3624
/cc @cjerdonek
> Fix #3653: Add a doctor helper to test pwd's.

- lib/jekyll/reader.rb
Fixes https://github.com/jekyll/jekyll/issues/3705.
Turns out the reason that it was slow for me was not that it was sorting at all but that it was sorting the same list of files over and over again.
Solution: Sort only once at the end of `#read`, not every time we load more files from a directory (those functions are called recursively via `#read_directories`). This also ensures backwards compatibility for the regular code path (unless you have a plugin that directly calls `#retrieve_posts` etc. or stuff like that).
@envygeeks @parkr @alfredxing
> Performance: Sort files only once

- lib/jekyll/regenerator.rb
- test/test_regenerator.rb
When doing some profiling, I noticed that for large sites, a considerable amount of time is spend in `read_metadata` and `write_metadata` of `Jekyll::Regenerator`. Most of that is in Psych (the YAML library that Jekyll uses).
You are probably not going to like this PR, since it's not backwards compatible, but I want to propose it anyway: Marshal is considerably faster and I don't really see why the metadata file needs to be human-readable.
My naive measurements: On a ~6000 pages site (which has a ~1MB metadata file with about 15k lines), this reduces the build time for incremental builds by about 400-500ms on my machine (from a total of about 5s).
@parkr @envygeeks thoughts?
> Performance: Marshal metadata

- lib/jekyll/regenerator.rb
- test/test_regenerator.rb
@parkr @envygeeks, missed a small detail in the other PR. Should have tested this better :-(
> Don't crash when reading/writing Marshal

- site/_docs/configuration.md
Fixed the documentation for redcarpet, as Jekyll updated to v3.2.x many more extensions are supported.
> Docs now reflect correct redcarpet version

- lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb
Previously the link pointed to the jekyll-help repository on github
which no longer accepts issues.
> Update link in welcome post to talk.jekyllrb.com

- lib/jekyll/regenerator.rb
- test/test_regenerator.rb
Should fix #3716. Added a test as well.
First PR in a long long time! :tada:
> Incremental: handle deleted/renamed/moved dependencies

- site/_docs/plugins.md
Added a link to my [asciinema liquid tag plugin](https://github.com/mnuessler/jekyll-asciinema).
> Add asciinema tag plugin

- bin/jekyll
- lib/jekyll.rb
- lib/jekyll/convertible.rb
- lib/jekyll/liquid_renderer.rb
- lib/jekyll/liquid_renderer/file.rb
- lib/jekyll/liquid_renderer/table.rb
- lib/jekyll/renderer.rb
- lib/jekyll/site.rb
- lib/jekyll/tags/include.rb
- test/test_liquid_renderer.rb
- test/test_site.rb
This PR adds a `--profile` flag to Jekyll which generates a Liquid performance profile. I found this very helpful when trying to figure out why our site was so slow and which pages are the most worthwhile to optimize.
The output shows the number of times a certain file is being rendered and the total time it took to render that file (only the 50 worst offenders are shown).
Looks like this on the Jekyll site:
```
$ bundle exec jekyll build -s site --profile
Configuration file: site/_config.yml
Source: site
Destination: /home/vagrant/src/jekyll/_site
Incremental build: enabled
Generating...
Filename | Count | Total time
------------------------------------+-------+-----------
_layouts/docs.html |    31 |      1.339
_includes/docs_contents_mobile.html |    31 |      0.754 …
```
> Liquid profiler

- lib/jekyll/liquid_renderer/file.rb
Fixes https://github.com/jekyll/jekyll/issues/3808.
Problem is that the block that is being `yield`ed can raise an exception (`Liquid::SyntaxError` for example), in which case `str` is `nil` and the `ensure` part will try to call `nil.bytesize`. This makes it harder to debug the Liquid Errors.
The `ensure` is actually unnecessary, this PR removes it. A Liquid::SyntaxError should now just bubble up like we want to.
@parkr @envygeeks
> Remove unnecessary `ensure` in LiquidRenderer

- site/_docs/windows.md
Jekyll dependency hitimes does not support Ruby 2.2 on Windows yet
> Update windows.md with Ruby version info

- lib/jekyll/static_file.rb
- test/test_static_file.rb
This enables files such as images and PDFs to show up in the same relative output directory as other HTML and Markdown documents in the same collection.
It also enables static files to be hidden using defaults from _config.yml in the same way that other documents in the same collection and directories may be hidden using `published: false`.
Extracted from 18F/hub#332.
cc: @afeld @gboone @jeremiak @dhcole
> Adapt StaticFile for collections, config defaults

- lib/jekyll/regenerator.rb
Looks like Windows is having problems with reading binary files using `File#read`. Not sure why this works on Linux and Mac OS X.
Closes https://github.com/jekyll/jekyll/issues/3842 (hopefully).
@mmistakes or @envygeeks, could you confirm that this fixes the problem?
> Fix reading of binary metadata file

- lib/site_template/_includes/header.html
> Fixes #3836. Fix site template header menu iteration variables

- site/_docs/deployment-methods.md
Suggest to provide more extended documentation on rsync-approach. It also mentions rrsync wrapper script which restricts access for rsync to the server. Based on my blog post here: http://vrepin.org/vr/JekyllDeploy/
> Detailed instructions for rsync deployment method

- lib/jekyll/tags/highlight.rb
- test/test_tags.rb
Fixes #3776 by changing to the correct name for whitelisting.
> Change non-existent hl_linenos to hl_lines to allow passthrough in safe mode

- CONTRIBUTING.markdown
See #3893 
I believe the bundle exec here is probably significant if the user has other versions of cucumber installed.
> Contributing.md should refer to script/cucumber

- site/_docs/assets.md
as seen on:
http://blog.davepoon.net/2015/01/19/setting-up-sass-with-jekyll/
http://markdotto.com/2014/09/25/sass-and-jekyll/#create-a-sass-stylesheet
> I think you made a typo there

- lib/jekyll/convertible.rb
- lib/jekyll/document.rb
- lib/jekyll/hooks.rb
- lib/jekyll/page.rb
- lib/jekyll/post.rb
- lib/jekyll/renderer.rb
- lib/jekyll/site.rb
Addresses #3870 by changing the trigger interface to work with symbol owners rather than object owners, making the hooks system more flexible.
> #3870 trigger hooks by owner symbol

- lib/jekyll/filters.rb
- test/test_filters.rb
Non-string input was being missed as a result of poor comparison.
Converting inputs to strings ensure numerical and boolean values are
properly compared.
Fixes #3911.
> filters: `where` should compare stringified versions of input & comparator

- site/README.md
I noticed this little typo, I thought I could fix it.
> Just fixed markdown list in `site/README.md`

- site/_docs/configuration.md
Information about Jekyll environment variables was missing from the documentation. This seemed like a good place to include it.
> Added documentation for Jekyll environment variables

- lib/site_template/_config.yml
The first thing new users to Jekyll do is open _config.yml, so this
change adds a simple welcome message to the top of it. Additionally,
it informs the user that the file is not automatically reloaded when
changed, which is a point of confusion for new users.
Related issue: https://github.com/jekyll/jekyll/issues/2302
> Add header message to _config.yml

- lib/jekyll/tags/highlight.rb
For those who like to do tests with `warning = true` or `ruby -w`.
> Avoid "mismatched indentations" warning for ruby -w

- site/_docs/troubleshooting.md
I added the solution I used to install Jekyll after updating to El Capitan.  Brew isn't always my first choice...  This solution redirects the install to a folder that you do have access to after the new security updates in El Capitan.
gem install -n /usr/local/bin jekyll
I was not able to test this on a clean install of El Capitan.
> added alternative jekyll gem installation instructions

- site/_docs/troubleshooting.md
> Fixed a typo, wrap at 80 characters

- site/_docs/permalinks.md
Following what the documentation specifies above for the pretty permalink format (`/:categories/:year/:month/:day/:title/`), it should result for the example to `/2009/04/29/slap-chop/` and not `/2009/04/29/slap-chop/index.html`. Well, at least if I've understood correctly ;-)
> Fix pretty permalink example

- features/post_excerpts.feature
- lib/jekyll/excerpt.rb
- test/test_excerpt.rb
When a post does not contain an `excerpt_separator`, meaning the excerpt includes the entire post, the excerpt should contain exactly the post content.  This is desirable both from a correctness standpoint, that the excerpt should not introduce any new content, and more practically to allow fast and easy detection of whole-post excerpts in Liquid templates using `post.excerpt == post.content`.  A common use-case is deciding whether to render "Read More" links to a post on a page containing post excerpts.
Currently whole-post excerpts include additional newlines at the end of the excerpt content, which makes it difficult to detect whether an excerpt includes the whole post (unless there is an easy method I am overlooking).  This PR fixes the issue and adds tests to ensure it stays fixed. …
> Whole-post excerpts should match the post content

- test/helper.rb
Fix the code coverage reporting when using `.bundle` to store my gems in by having SimpleCov ignore that directory. Use of `.bundle` to store my gems consolidates things since since that directory also holds the bundler config file. It also keeps a `vendor` directory out of the project tree for non-Rails projects.  Simplecov was not ignoring that directory though, which meant that the code coverage numbers I were seeing locally were wrong (and very frightening). With this change, all is right with the world once again. :smiley:
> Ignore `.bundle` when generating test coverage

- site/_docs/usage.md
_config.yml not reloaded during automatic regeneration
> Update usage.md re: _config.yml not reloaded during regeneration

- site/_docs/usage.md
Referring to _config.yml consistently with <code>
> Remove brackets around _config.yml

- lib/jekyll/cleaner.rb
A raw regular expression isn't very expressive, IMHO. Rather than having people who read this code parse the regular expression to figure out what it's for, let's give a name. This way, it becomes more obvious what exactly it is we're doing here.
This was something that I saw when I was working on #4011 that I didn't want to change in that PR but did want to come back to and change later.
> Make a constant for the regex to find hidden files

- site/_docs/contributing.md
> Apply the highlight class

- lib/site_template/_sass/_layout.scss
- lib/site_template/css/main.scss
Change default font weight in site template to 400 (normal), except for the site title, which remains at 300.
Should fix #4042.
Not sure if we're still going for #3921 though.
> Change default font weight to 400 to fix bold/strong text issues

- features/rendering.feature
- features/step_definitions/jekyll_steps.rb
- features/support/env.rb
- lib/jekyll/convertible.rb
/cc @benbalter @fw42 @jekyll/core 
https://travis-ci.org/envygeeks/jekyll-symlink-test/builds/88182863
> Fix #4066: Move Convertible#render_liquid to using render!

- features/collections.feature
- lib/jekyll/converters/markdown/kramdown_parser.rb
- test/test_kramdown.rb
A fix for https://github.com/jekyll/jekyll/issues/3371
I’ve added a test that checks to see that code fenced syntax is rendered using Rouge. However, this test (and fix?) assumes you have Rouge as your preferred highlighter. I tried enabling Coderay highlighting, but this appeared to have no effect, either on syntax within `{% highlight %}` or `~~~` code fences. Is this a bug, or intended behaviour?
Also, as kramdown only accepts Rouge and Coderay as syntax highlighters, maybe we should only allow those options to be passed to the `kramdown: syntax_highlighter` config?
> Fix #3371 - kramdown:syntax_highlighter should take value of highlighter

- site/_docs/templates.md
I've been using the docs as I develop my own site and ran into errors trying to embed gists. I discovered you have to add the `jekyll-gist` gem to your site in order to have the `gist` tag work, so I've updated the templates page docs accordingly.
> Adds a note about installing the jekyll-gist gem to make gist tag work

- lib/jekyll/hooks.rb
- lib/jekyll/site.rb
- site/_docs/plugins.md
- add site post_render hook, which was documented but wasn't being
called
- define documents post_init hook, which was documented but caused an
error when called (fixes #4102)
- add docs for site post_read hook, which was being called but wasn't
documented
- fix container name in example: s/post/posts/
> align hooks documentation and implementation

- site/_docs/plugins.md
Added a new listing for a plugin that embeds Flickr photos in a Jekyll blog. As the plugin provides both tag and generator features, I have added it to both the Tags and Generator categories of the page.
> Update plugins.md. Added Jekyll Flickr Plugin.

- features/post_data.feature
- lib/jekyll/document.rb
- test/test_site.rb
- test/test_tags.rb
Fixes https://github.com/jekyll/jekyll/issues/4084
> Document: only superdirectories of the collection are categories

- lib/jekyll/commands/doctor.rb
Think this should be `site.posts.docs` instead. Does it need a test? - works with jekyllrb.com and `script/cibuild` passed locally.
> Fix the warning

- site/_docs/resources.md
The link leading to this blog post is now dead, so it should be removed from the resources page.
> Remove link to now-deleted blog post

- lib/jekyll.rb
Seems like this got missed. Referencing `Jekyll::Post` results in a `LoadError`
> Remove Post autoload

- site/_docs/plugins.md
I have created a Jekyll 3.0-compatible plugin for multilingual websites which is capable of creating multiple translations for one page or post. Beware that this plugin extends the `PageReader` and `PostReader` as well as `Page` and `Document` classes.
> Add jekyll-language-plugin to plugins.md

- site/_docs/assets.md
Included Jekyll 3 specific update to mention that jekyll-coffeescript gem must be installed and the gem added to the `_config.yml` file
> Updated to reflect feedback in #4129

- features/permalinks.feature
- lib/jekyll/document.rb
- lib/jekyll/filters.rb
- lib/jekyll/utils.rb
- site/_docs/permalinks.md
- test/source/_slides/example-slide-Upper-Cased.html
- test/test_document.rb
- test/test_utils.rb
The only difference between `slug` and `title` is that uppercase letters are not converted to their lowercase counterparts in `slug`. After adding this property, the final permalink of `_posts/2015-10-27-Jekyll.md` with permalink style `/:year/:month/:day/:slug` will be `/2015/10/27/Jekyll/`.
This pr is related to issue #4072 and it's my first time writing ruby, correct me if I made anything wrong.
> Add a new property `slug` to document url_placeholders.

- Rakefile
- jekyll-docs.gemspec
Run `bundle exec rake docs:build` or `bundle exec rake docs:release` to release `jekyll-docs` at the current `jekyll` version. Should eventually hook into `task :release` so `jekyll` and `jekyll-docs` are release simultaneously.
> jekyll-docs gem should be easily integrated with jekyll's site.

- features/include_tag.feature
- lib/jekyll/tags/include.rb
This is mainly inspired by [Shopify Liquid include tag](https://github.com/Shopify/liquid/blob/3-0-stable/lib/liquid/tags/include.rb), reducing redundant include file parsing time.
> Cache include file to save liquid parsing time.

- site/_docs/plugins.md
Added three plugins to the directory listing:
- jekyll-roman
- jekyll-typogrify
- jekyll-figure
Provided as separate commits, as suggested previously.
> Add three plugins to directory

- lib/jekyll/url.rb
/cc #4167 @jekyll/core @parkr @vwochnik
> Slightly speed up url sanitization and handle multiples of ///.

- lib/jekyll/commands/clean.rb
This is just a turnaround of pull request #3828 , which add build options in clean command but forget to pass it into process phase.
It should fix #4175 .
> Pass build options into clean command

- lib/jekyll/tags/highlight.rb
- test/test_tags.rb
..you could also just remove this line entirely, but I don't know what versions of liquid that'll work with.
> don't clobber `@options` in HighlightBlock. fixes #4173

- lib/jekyll/collection.rb
This should address #4178 . I'm not sure how to write a test for something as minor as issuing a log message though. If this is not acceptable to the standards, let me know and I'll retract the pr.
> added debug message to collection.read when document is skipped, addresses #4178

- site/_docs/plugins.md
> Update Plugin Docs

- features/include_tag.feature
- lib/jekyll/tags/include.rb
I'm playing around Ruby regex these days and happen to see #4028 , this PR gives it a quick fix. 
@envygeeks might have a big refactor of Jekyll own tags referring to what he mentioned in #4028 , so it's ok if this doesn't get merged.
> Allow users to input multiple variables in include tag

- lib/jekyll/commands/serve.rb
Hi Jekyll maintainers,
We were setting up a new Jekyll blog to play around and thought it would be helpful to add a "-o" option to the serve command. This option would open the URL of the server on the device's default browser. We used the "system" ruby method, but we're not sure if that's your preferred approach to opening URL's. It's also unclear if this would work on Windows, as we only tested this on OS X.
We're happy to modify this request to open the URL in a different way, if there are issues with the current implementation. All the unit tests passed when we ran them locally.
cc @ckearns1210
> add "-o" option to serve command which opens server URL

- site/_docs/deployment-methods.md
Hey guys,
I wish to add the Kickster gem and documentation to the deployment methods as it is a viable solution for people wanting to deploy worry-free and/or automated using Travis CI or Circle CI while using unsupported plugins (in Github Pages).
Next to easy deploying, Kickster also ships with automated testing, a project template, Jekyll Assets plugin and much more. More information about Kickster can be found here: http://kickster.nielsenramon.com/ or on the GitHub page. I also wrote a blog post about it [here](https://medium.com/@nielsenramon/automated-deployment-of-jekyll-projects-to-github-pages-using-kickster-and-circle-ci-6ccc0b6cb872#.matjzamr4).
Let me know what you think!
> Add Kickster to deployment methods in documentation

- lib/jekyll/cleaner.rb
- lib/jekyll/collection.rb
- lib/jekyll/utils.rb
- test/test_utils.rb
the absolute path including '[', '{', '?', or '*'
could change the outcome
> Avoid using Dir.glob with absolute path

- site/_docs/deployment-methods.md
- site/_sass/_style.scss
Some code blocks are still using GitHub's code block syntax **```**, which lacks proper x-overflow css. Here I change it to `highlight` tag.
> Change GitHub code block to highlight tag to avoid it overlaps parent div

- site/_docs/resources.md
This link used to point to a generic landing page. Now it links to a guide written specifically for Jekyll users.
> Link to less generic FormKeep page

- site/_docs/resources.md
Just a small thing. Feel free to close if it's a bother.
#4243 updated this link to a jekyll-specific page. This commit adds utm params to the link so we can tell that users came to us from the Jekyll documentation. Among other things, this will help us provide better support to Jekyll users who sign up, since we'll know what site generator they're using.
> Add utm params to link in docs

- lib/jekyll/frontmatter_defaults.rb
- test/test_front_matter_defaults.rb
> Allow quoted date in front matter defaults

- lib/jekyll/configuration.rb
- test/test_configuration.rb
This is my first PR for jekyll and i tried to follow @parkr 's suggestion given in #4030.
`SafeYAML.load_file` returns `false` when processing empty files so we convert this into an empty hash for further processing. I wasn't sure if we should log a warning on empty config files, so i left it out for now.
> Handle empty config files

- lib/jekyll/commands/doctor.rb
- test/source/_urls_differ_by_case_invalid/page1.html
- test/source/_urls_differ_by_case_invalid/page2.html
- test/source/_urls_differ_by_case_valid/page1.html
- test/test_doctor_command.rb
Those URLs are problematic on case-insensitive file systems because one of the URLs is overwritten by the other. Fixes #3035.
Note: I can't seem to find tests for doctor, I'm assuming there are none?
> Add a Jekyll doctor warning for URLs that only differ by case

- features/collections.feature
- features/hooks.feature
- features/post_data.feature
- lib/jekyll.rb
- lib/jekyll/collection.rb
- lib/jekyll/convertible.rb
- lib/jekyll/document.rb
- lib/jekyll/drops/collection_drop.rb
- lib/jekyll/drops/document_drop.rb
- lib/jekyll/drops/immutable_drop.rb
- lib/jekyll/drops/jekyll_drop.rb
- lib/jekyll/drops/mutable_drop.rb
- lib/jekyll/drops/site_drop.rb
- lib/jekyll/drops/unified_payload_drop.rb
- lib/jekyll/drops/url_drop.rb
- lib/jekyll/page.rb
- lib/jekyll/renderer.rb
- lib/jekyll/site.rb
- lib/jekyll/url.rb
- lib/jekyll/utils.rb
- test/test_excerpt.rb
- test/test_page.rb
- test/test_url.rb
This requires test updates but it compiles all the (rudimentary) sites on my machine.
Fixes #3224.
@jekyll/core, please review.
> Use Liquid::Drops instead of Hashes in #to_liquid

- site/_docs/plugins.md
[jekyll-responsive_image](https://github.com/wildlyinaccurate/jekyll-responsive-image) has been gaining popularity recently. I thought it would be worth adding it to the documentation.
> Add jekyll-responsive_image to plugins list

- lib/jekyll/converters/markdown.rb
> Refactor: lib/jekyll/convertor/markdown.rb - tests: no additions/breaks.

- site/_docs/plugins.md
>- [jekyll-commonmark](https://github.com/pathawks/jekyll-commonmark): Markdown converter that uses [libcmark](https://github.com/jgm/CommonMark), the reference parser for CommonMark.
> Add link to jekyll-commonmark

- site/_docs/configuration.md
Add some documentation regarding the feature of the docs site (on the Configuration page). Covers what the feature does, a basic overview of its specification (where it works and where it doesn't), and how to enable it.
Addresses #4057.
> Add some documentation for incremental regeneration

- features/hooks.feature
- lib/jekyll/convertible.rb
- lib/jekyll/page.rb
- lib/jekyll/renderer.rb
Fixes https://github.com/jekyll/jekyll/issues/4298 and https://github.com/jekyll/jekyll-archives/issues/55
Alternative is to wrap every hash in a drop class for every method, but that might
get pretty expensive.
> Convertible/Page/Renderer: use payload hash accessor & setter syntax

- features/layout_data.feature
- lib/jekyll/drops/drop.rb
@evgenyneu, this fixes your issue as defined here: https://github.com/jekyll/jekyll/issues/4246#issuecomment-168367510
> Drops should use content setters if they exist

- lib/jekyll/utils.rb
- test/source/_posts/2015-12-27-extra-spaces.markdown
- test/test_generated_site.rb
- test/test_utils.rb
Occasionally, extra spaces at the end of the YAML front matter prologue are
saved to a file and it goes missing without telling the user why. This
should simply accept those changes without any detriment to the user,
allowing anyone to add as many spaces as they like to the end of their
front matter prologues.
Fixes #4017
> utils: has_yaml_header? should accept files with extraneous spaces

- bin/jekyll
- lib/jekyll/external.rb
Basically doing #4253 but for Jekyll 3.
> For blessed gems, shim their commands so users know how to use them.

- History.markdown
- lib/jekyll/commands/serve/servlet.rb
- lib/jekyll/converters/markdown.rb
- site/_docs/configuration.md
- site/_docs/deployment-methods.md
- site/_docs/github-pages.md
- site/_docs/history.md
- site/_docs/plugins.md
- site/_docs/variables.md
* Github -> GitHub
* GitHub pages -> GitHub Pages
> Fix spelling of GitHub in docs and history

- lib/jekyll/converters/smartypants.rb
- lib/jekyll/filters.rb
- test/test_filters.rb
Is there a better place to put the `Kramdown::Parser::SmartyPants` class?
Am I on the right track with this?
> Add smartify Liquid filter for SmartyPants

- site/_docs/templates.md
Add documentation for jekyll/jekyll#4323
Sorry, this probably should have been part of that PR.
> Add documentation for smartify Liquid filter

- lib/jekyll/configuration.rb
- lib/jekyll/document.rb
- lib/jekyll/page.rb
- lib/jekyll/renderer.rb
- lib/jekyll/utils.rb
- test/source/_slides/example-slide-7.md
- test/source/dynamic_file.php
- test/test_document.rb
- test/test_filters.rb
- test/test_generated_site.rb
- test/test_page.rb
- test/test_site.rb
- test/test_utils.rb
Still a failing test. Fixes #4182 once it's passing.
What I'm trying to do is have `output_ext` return `File.extname(doc.permalink)` in the case that the doc has a permalink. This means that checking if the path ends with the output extension will always return true, thus skipping the addition.
I'm running into an issue where `permalink = /slides/example-slide-7.php`, but `output_ext = .html`, so it's being appended. If I print the document, the data hasn't been read, which is awfully strange. `permalink = nil`, actually, when we ask for the `output_ext` for the first time. Super weird.
@envygeeks, have a second to look at this? Super weird – why would `@site.process` in the tests not yield a fully-read document?
> Allow custom file extensions if defined in `permalink` YAML front matter

- .travis.yml
- Gemfile
- features/step_definitions/jekyll_steps.rb
- features/support/env.rb
* Removes posix-spawn in favor of Open3#popen3
* Encapsulates all the paths into a single easy class.
* Moves to %r{} to avoid ambiguious warnings per-Cucumber suggestion.
* Starts passing around Pathname to make some actions faster.
* Clean's up some methods to make them easier to read.
* AUTOMATIC: Add "#" between each method.
> Move Cucumber to using RSpec-Expections and furthering JRuby support.

- test/helper.rb
The line has been commented out [since October](https://github.com/jekyll/jekyll/blame/v3.1.0.pre.beta1/test/helper.rb#L36), so I guess we really *didn't* need this.
> Remove old FIXME

- .travis.yml
- Gemfile
- script/travis
The problem last time was that we removed Pry and Pry brings in CodeRay, we were
testing legacy stuff and didn't have CodeRay in our dependencies, which resulted
in those tests failing.
This also quietly announces the intention to move to RSpec by moving the old
test dependencies to ":test_legacy" and is slightly less agressive in it's
organization than before.
> Clean up the Gemfile (and keep all the necessary dependencies)

- site/_docs/configuration.md
The Precedence section referred to the "last example" where it should have referred to the "second to last."
> Documentation: correct reference in Precedence section of Configuration docs

- site/_docs/github-pages.md
- site/_docs/resources.md
Nearly every day, when I get the report of visitors to jekyllrb.com, I see jmcglone's excellent guide. Reading through it today makes me think it is one of the finest if not _the_ finest guide to getting started with Git, GitHub, and Jekyll in order to publish successfully and happily on GitHub Pages.
@jmcglone, mind if I add this to our GitHub Pages doc page?
> Add @jmcglone's guide to github-pages doc page

- features/post_data.feature
- lib/jekyll/document.rb
- lib/jekyll/site.rb
Fixes #4375.
/cc @jekyll/gh-pages @jekyll/core
> Document: throw a useful error when an invalid date is given

- site/_docs/plugins.md
Adds Contentful Extension into Plugins page
This plugin is already added in https://github.com/jekyll/plugins
> Add Contentful Extension to list of third-party plugins

- lib/jekyll/page.rb
- test/test_page.rb
- Remove extra OR condition since a missing hash key will return a nil anyway and made it a 1 liner
- Added a test to catch this nil condition since it was missing to begin with
- Reduced line length in test_page.rb
Hope the change makes sense. I noticed there wasn't a test case to check for the sad path for `.permalink`. Does where I added this test make sense?
> Refactor Page#permalink method

- features/post_data.feature
- lib/jekyll/drops/drop.rb
> Drop#[]: only use public_send for keys in the content_methods array

- lib/jekyll/renderer.rb
- test/source/_with.dots/permalink.with.slash.tho.md
- test/test_collections.rb
- test/test_document.rb
Previously, even if the document permalink was a folder, it would look for
an extension on that.  For example, if I have:
```text
permalink: "/new-version-jekyll-v3.0.0/"
```
the output_ext would be `".0"`.  Now, the output_ext honors the trailing
slash and will report based on the converters instead.
Fixes #4397.
> Renderer#output_ext: honor folders when looking for ext

- CONDUCT.md
The Contributor Code of Conduct is now at version 1.3.0 and has several
changes. Many of these are simply wording changes, but an important note
is added that project maintainers must maintain confidentiality when
dealing with any code of conduct violations. Additionally, a note is
added that states violations will be investigated and dealt with in a
way that is deemed necessary and appropriate based on the circumstances.
Signed-off-by: David Celis <me@davidcel.is>
> Update the Code of Conduct to the latest version

- benchmark/end-with-vs-regexp
- benchmark/file-dir-ensure-trailing-slash
- lib/jekyll/page.rb
- test/test_page.rb
Fixes #3974.
/cc @envygeeks, because I'm sure you have a faster/more elegant/more performant solution for this problem.
/cc @jekyll/core for review!
> Page#dir: ensure it ends in a slash

- test/test_site.rb
The test was spewing out some whitespace ¯\_(ツ)_/¯
This just suppresses output to STDOUT for this test only.
Previously:
> Suppress stdout in liquid profiling test

- lib/jekyll/convertible.rb
- lib/jekyll/document.rb
- lib/jekyll/utils.rb
- test/test_utils.rb
This _might_ fix #2853.
/cc @jekyll/core for review.
> Add Utils.merged_file_read_opts to unify reading & strip the BOM

- site/_docs/quickstart.md
Thought this would be helpful in scenarios where folks want to create a new Jekyll project in an existing folder that is non-empty.
> Docs: Quickstart - added documentation about the `--force` option

- rake/site.rake
- site/_posts/2015-10-26-jekyll-3-0-released.markdown
- site/_posts/2016-01-28-jekyll-3-1-1-released.markdown
- Fix broken site generation caused by renamed `CONDUCT.markdown` file.
- Fix old URL that was pointing to a missing file in GitHub.
- Update links to use `[Code of Conduct](/docs/conduct/)`
> Fix broken links to the Code of Conduct

- jekyll.gemspec
By including `.rubocop.yml` in the Gem, plugins can inherit the Jekyll rules with
```yml
inherit_gem:
jekyll: .rubocop.yml
```
> Include .rubocop.yml in Gem

- lib/jekyll/liquid_renderer/file.rb
Re-implements https://github.com/jekyll/jekyll/pull/4452 for 3.0.x.
Fixes #4431.
> LiquidRenderer#parse: parse with line numbers.

- script/proof
The `script/proof` command fails under 3.1.1.
Related discussion: #4059.
Can the new flag just get swapped in? 
/cc @gjtorikian
> Remove old flag which breaks htmlproof

- site/_docs/upgrading/2-to-3.md
I was linked to the [upgrade page](http://jekyllrb.com/docs/upgrading/2-to-3/) from Github blog and there's no warning or note specifying the requirement of Jekyll 3 on Ruby ver. >=2.0.0 on this page 
I wrote a script to upgrade jekyll, rebuild the sites and push them live on my development server but it failed because I missed the requirement. 
Hope this helps others who will only read the 'upgrading/2-to-3' article.
> [add note] Jekyll 3 requires newer version of Ruby.

- lib/jekyll/entry_filter.rb
this is a 3.1 change that i'd love to have in 3.0. will help clear up verbose logs which get mighty verbose when every file jekyll looks at is printed :/
/cc @jekyll/gh-pages
> EntryFilter: only include 'excluded' log on excluded files

- lib/jekyll.rb
- test/test_path_sanitization.rb
> Jekyll.sanitized_path: escape tildes before sanitizing a questionable path

- site/_docs/deployment-methods.md
The https://github.com/jimweirich/rake/ repository is retired, so I've changed the link to https://github.com/ruby/rake
> Update Rake link

- site/_docs/sites.md
I am making this pull request as I think that this page could do with an indicator of when each of these sites were last updated as this gives one an idea as to whether or not these sites are still valid examples to follow (as it is possible that their code has become outdated and so has their layout, due to new releases of Jekyll).
> Update & prune the short list of example sites

- lib/jekyll.rb
- test/test_path_sanitization.rb
Fixes #4457 (and duplicates #4468) on `master`, targeted for v3.1.2.
> Jekyll.sanitized_path: sanitizing a questionable path should handle tildes

- lib/jekyll/deprecator.rb
The deprecation message that presents when you use switches says jekyll now uses subcommands. Then it prompts you to learn more by running jekyll with a switch for `--help`. Conveniently Jekyll supports both, but the message seems self-contradictory.
This proposes to make the message internally consistent without otherwise changing behavior.
> add consistency to the deprecation message

- Gemfile
Hi,
`script/bootstrap` installed / used cucumber version 2.0.2 for me, which resulted in a `wrong number of arguments (given 1, expected 2)` exception while executing the features because [ensure_io](https://github.com/jekyll/jekyll/blob/99b9c8486cb5fe1984a7a5979422d292aeb366c8/features/support/formatter.rb#L27) is called with only one argument. This is only correct for cucumber 2.1.0 and newer ( https://github.com/cucumber/cucumber-ruby/commit/c1768eb91f9399c6533cf2ff22608886514ee5f8 )
> require at least cucumber version 2.1.0

- lib/jekyll/utils.rb
- test/test_utils.rb
Previously `titleize` used `capitalize!` which has the side effect of
returning `nil` for anything already starting with a capital letter. This
commit changes it to just `capitalize`.
Example, before:
A file "2016-01-01-This-is-a-title-with-Capitals.markdown" would return "Is A
Title With" for `post.title`
Example, after:
A file "2016-01-01-This-is-a-title-with-Capitals.markdown" will return "This Is A
Title With Capitals" for `post.title`
Note: this is based off tag v3.1.1 as at the time of cloning this master
was causing me problems with markdown parsing on one of my posts and I
only ended up looking into this because I was trying to write a blog
post after updating Jekyll to 3.1.1.
Not sure if tests are in the right place. Seems to be correct place as
have added tests for differently …
> Fix titleize so already capitalized words are not dropped

- site/_docs/plugins.md
Add jekyll-tagging-related_posts plugin to plugin list.
> Add jekyll-tagging-related_posts plugin

- site/index.html
Updated "custom domain name" link on the homepage from https://help.github.com/articles/setting-up-a-custom-domain-with-pages to https://help.github.com/articles/about-supported-custom-domains/.
> Updated "custom domain name" link on homepage

- lib/jekyll/document.rb
- test/source/_with.dots/mit.txt
- test/source/contacts/humans.txt
- test/test_collections.rb
- test/test_filters.rb
- test/test_site.rb
Duplicates #4493 for 3.1.1. Ports a fix we did for 3.0.3 to `master`.
> Permalinks which end in a slash should always output HTML

- Gemfile
- site/_config.yml
- site/_includes/news_item.html
- site/_includes/top.html
- site/_layouts/news_item.html
- site/index.html
This pull request adds three plugins to the `jekyllrb.com` site with a few targeted improvements:
This plugin improves the contributor avatars used in the news feed, specifically:
* Avatars will load directly from the GitHub avatar server, avoiding the need for a 301 redirect from `/username.png`.
* Avatars load in parallel across 3 different avatar servers, using the same hashing function used within GitHub, improving the likelihood that they're already cached on the visitor's machine
* Avatars upgrade to Retina-size images, where supported
To use Jekyll Avatar, there's a small template change, but no change in behavior/use.
This adds a sitemaps.org compliant sitemap at `/sitemap.xml`. That's it. No configuration or fuss. It'll help Google and other search engines better index some of …
> Add jekyll-seo-tag, jekyll-avatar, and jekyll-sitemap to the site

- Gemfile
- site/_config.yml
To allow us to register the site with Google webmaster tools to register the sitemap added via https://github.com/jekyll/jekyll/pull/4553.
> Add Google site verification meta

- site/help/index.md
"Upgrading Documentation" reads to me like "upgrading the documentation" rather than "documentation for upgrading".
There's a link in the site navigation to documentation, but seems worth a mention here, even though the Google option will often bring one to it. :smile:
> Upgrading, documentation

- lib/site_template/_includes/footer.html
- lib/site_template/_includes/head.html
- lib/site_template/_includes/header.html
- lib/site_template/_layouts/page.html
- lib/site_template/_layouts/post.html
- lib/site_template/index.html
Follows after #4307. `site.title`, `page.title`, and `site.description` are usually written in plaintext, so escaping is needed.
> Site template: Escape title and description where it is used in HTML

- features/collections.feature
- lib/jekyll/collection.rb
- test/source/_methods/collection/entries
- test/test_collections.rb
- test/test_document.rb
Duplicates #4544 for `master`. Fixes one item from #4534.
> Allow collections to have documents that have no file extension

- lib/jekyll/document.rb
> Document#date: drafts which have no date should use source file mtime

- site/help/index.md
Sometimes the best help is seeing how others' have done.
Just an idea...
I notice there's also https://talk.jekyllrb.com/t/showcase-sites-made-using-jekyll/18 and https://github.com/showcases/github-pages-examples but this Help page seems to use links exclusively in headings and second link probably includes non-Jekyll sites.
> Add 'view source' entry

- lib/jekyll/filters.rb
- test/test_filters.rb
This allows you to do `{% assign subset = site.pages | group_by:"author" | sort:"size" %}` so that you can list the groups in order of the number of items they have.
If there's a way to do this already please let me know; I don't see how it would be possible without this.
> Add size property to group_by result

- test/test_kramdown.rb
Fixes #4250, one occurence of #4617
> Fix state leakage in Kramdown test

- features/create_sites.feature
- lib/jekyll/renderer.rb
Prior to this change, the related posts for the most recently rendered post
stayed set on the `site` object. This could result in pages that showed related
posts even when the page represented an entire collection of posts, such as on
an index page.  This change restores the functionality from Jekyll V2.
> Ensures related_posts are only set for a post

- lib/site_template/_layouts/default.html
Omitting the `lang` attribute is [an accessibility concern](https://twitter.com/stevefaulkner/status/705767128163606528), and given how popular Jekyll is I thought it would be a good idea to set a default `lang` attribute to the `html` element. I went with `en` as I figured out it would be a meaningful default.
> Added a default lang attribute

- site/_docs/deployment-methods.md
Aerobatic is a static host with built in CD Jekyll builds
> Adding Aerobatic to list of deployment options

- site/_docs/continuous-integration.md
Version 3.0 of HTMLProofer has renamed the CLI command `htmlproof` to `htmlproofer` (https://github.com/gjtorikian/html-proofer/issues/246).
This commit updates documentation to reflect this change.
> Update documentation: HTMLProofer CLI command

- lib/jekyll/publisher.rb
- lib/jekyll/readers/post_reader.rb
For https://github.com/jekyll/jekyll/issues/4507
All tests pass, but didn't add any new tests for the log line.  There's only one test that looks at log output at this point, and I didn't know enough to write a good test of this change.
One thing I wasn't sure was okay - this change places a requirement on all things to be published to have a `#relative_path` method.  I'm not sure how to validate if this is a good assumption or not.  Guidance here would be appreciated.
Sample output of `jekyll build --verbose`:
```text
Logging at level: debug
Configuration file: /Users/zspencer/Code/testblog/_config.yml
Requiring: kramdown
Source: /Users/zspencer/Code/testblog
Destination: /Users/zspencer/Code/testblog/_site
Generating...
Reading: …
```
> Adding a debug log statment for skipped future documents.

- lib/jekyll/filters.rb
- test/test_filters.rb
In addition to `where` supporting basic string matches (ie. `category == "foo"`) this allows the `where` filter to work on array values, ie. `category contains "foo"`. So whether the page has
```yaml
---
category: Foo
---
```
or
```yaml
---
category:
- Foo
---
```
The `where` filter will still work (`{{ site.pages | where:"category", "foo" }}`)
Note that this should not have an effect on any existing (string-match) use of `where` (non-breaking change)
Resolves #4385 (feature request)
> Add array support to `where` filter

- site/_docs/continuous-integration.md
Updates the continuous-integration docs to provide information about the `sudo: false` behavior which can route builds to the faster container-based infrastructure. https://docs.travis-ci.com/user/workers/container-based-infrastructure/#Routing-your-build-to-container-based-infrastructure
> Update continuous-integration docs with sudo: false information

- site/_includes/news_item.html
There's an oddness with the way Liquid passes context to Jekyll plugins, which means that sometimes, when called in loops, if you're passing a variable to the plugin, you'll get the variable that's rendered by the first loop, not the current iteration.
This fixes that, by passing the avatar user directly to jekyll-avatar, ensuring that on `/news`, all avatars render accurately, not that they're all @parkr. :trollface:
> Ensure avatars properly render on /news

- lib/jekyll/commands/clean.rb
Fixes #4649. /cc @ctubbsii
/cc @jekyll/build @jekyll/stability
> 'jekyll clean': also remove .sass-cache

- site/_docs/collections.md
There was a line referring to the `render` key in `_config.yml` but the actual name of the key is `output`.
> Fixes typo on collections

- lib/jekyll/errors.rb
- lib/jekyll/tags/post_url.rb
- lib/jekyll/utils.rb
- test/test_tags.rb
- test/test_utils.rb
Inspired by a review of #4470. Cleans up `PostUrl` and `PostComparer` a bit.
> Clean up Tags::PostUrl a bit, including better errors and date parsing

- site/_docs/troubleshooting.md
After running:
sudo dnf install ruby ruby-devel rubygems nodejs
sudo dnf group install "C Development and Tools"
I was unable to install Jekyll via `gem` due to an error:
The compiler failed to generate an executable file. (RuntimeError) You have to install development tools first.
Taken from the [fedoraproject.org](https://developer.fedoraproject.org/tech/languages/ruby/gems-installation.html) Gem page:
>If you installed all the above, but the extensions would still not compile, you are probably running a Fedora image that misses `redhat-rpm-config` >package. In that case gcc compiler would complain about one of the following:
gcc: error: conftest.c: No such file or directory
gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory << What I saw
>To solve this, …
> Additional package needed for Fedora 23 Workspace

- site/_docs/windows.md
> Fix typo on Chocolatey name in Windows documentation

- lib/jekyll/filters.rb
- test/test_filters.rb
Is there a reason to use `CGI.escapeHTML` over `encode`?
> Use String#encode for xml_escape filter instead of CGI.escapeHTML

- lib/jekyll/commands/serve.rb
- lib/jekyll/configuration.rb
- test/test_commands_serve.rb
This is a replacement for PR jekyll/jekyll/pull/4503, which I will close momentarily.
This PR adds the ```--show-dir-listing``` CLI option, which can also be included in the config as ```show_dir_listing```, to show the WEBrick default directory listing instead of loading an index file (e.g. index.html). When testing, I find it much more convenient to be able to navigate to a specific file by clicking through a directory list instead of typing in the file name (which may not be linked from index.html).
This PR also fixes the default directory index file list to maintain parity with the file names supported by GitHub Pages (I tested to verify that the order is correct).
I changed the negative option ```--no-directory-index``` from PR jekyll/jekyll/pull/4503 to the affirmative …
> Add show_dir_listing option for serve command and fix index file names

- lib/jekyll/commands/new.rb
- test/test_new_command.rb
> Site Template: write a Gemfile which is educational to the new site

- site/_docs/assets.md
Just because developer are lazy and tools like this is for move forward faster, normally we don't read (it's a fact) and because of that I missed this super important sentence. At least this should help.
> Bold-italicize note in assets documentation about needing yaml front matter

- lib/site_template/_config.yml
Fixes #4556. Supersedes #4570.
> Site template: add explanation of site variables in the example `_config.yml`

- lib/jekyll/static_file.rb
This patch enables symlinks for static files. Now you can do something like this:
```
news/
new-pc.jpg -> ../images/DSC0001.jpg (21 bytes)
_posts/
2016-03-06-new-pc.md
images/
DSC0001.jpg (1,2 MiB)
```
The generated page could be something like that:
```
_site/
news/
2016-03-06-new-pc.html
new-pc.jpg -> ../images/DSC0001.jpg (21 bytes, 1,2 MiB with jekyll 3.1.2)
images/
DSC0001.jpg (1,2 MiB)
```
- no need to `grep` for invalid URLs (e.g. DSC0001.jpg becomes dsc0001.jpg), written things can stay untouched when filenames or folders change
- detecting broken symlinks is easy (file explorer, `ls -l`, etc.)
- nice hyperlinks for visitors (/news/new-pc.jpg) without grown webspace requirements and reduced jekyll build time
> Allow static files to be symlinked in unsafe mode or non-prod environments

- lib/jekyll/hooks.rb
- lib/jekyll/site.rb
- site/_docs/plugins.md
@benbalter and I were working through https://github.com/github/pages-gem/pull/209
and realized that it'd be way nicer to have a one-time hook which could run after initialization
but before generators/converters/etc are initialized for the site. It would also be nice to have
a "safe" way to set `@config` knowing that it'd fan out properly.
This PR adds `:after_init` to the list of `:site` hooks and adds `Site#config=` to make all that much easier.
/cc @jekyll/stability @jekyll/ecosystem
> Add `:after_init` hook & add `Site#config=` to make resetting config easy

- Gemfile
- test/helper.rb
Update Rake and disable verbosity when running the specs because we have some
deprecated usage (for now -- however, see: jekyll/jekyll#4719) and because
Rouge, and Liquid throw out thousands (probably hyperbolic) of warnigns when the
specs are being ran.  We need upstream to fix their problems while we fix ours
or we'll all have a bad day, not that we aren't already.
> Update Rake & disable warnings when running tests

- lib/jekyll/configuration.rb
- lib/jekyll/converter.rb
- lib/jekyll/converters/markdown.rb
- lib/jekyll/converters/markdown/kramdown_parser.rb
- lib/jekyll/frontmatter_defaults.rb
- lib/jekyll/plugin.rb
- lib/jekyll/regenerator.rb
- test/test_convertible.rb
- test/test_filters.rb
- test/test_new_command.rb
- test/test_site.rb
- test/test_tags.rb
- test/test_url.rb
Hi,
you can see all the warnings this PR removes in the commit message. This commit does not remove the following warnings:
- `lib/jekyll/url.rb:119:in 'escape_path': warning: URI.escape is obsolete`
- ` lib/jekyll/url.rb:133:in 'unescape_path': warning: URI.unescape is obsolete`
which were mentioned in #4476 . I tried to replace the calls with `CGI.escape` /  `CGI.unescape` but i couldn't get them to return the same results as the current implementation and i thought it would be too risky to replace it with a different behavior just to get rid of those warnings.
> Fix many warnings

- lib/jekyll/commands/serve.rb
As it was we assumed that any system that wasn't Windows or OS X must be Linux
but the reality of that can be very unlikely. BSD is popular in some places and
it's not Linux and this would cause an error there.  If we do not know the
launcher for a platform we should ship an error and have the user file
a bug if they feel it necessary and skip the launch otherwise.
> Don't blindly assume the last system when determining "open" cmd

- .github/CONTRIBUTING.markdown
The `<your-username>` was breaking the plain text. I switched it to pre text.
Also removed the ending `/` as GitHub don't use it at the end of URLs.
> Fixed the example fork url in CONTRIBUTING

- .github/CONTRIBUTING.markdown
- site/_docs/contributing.md
List of modified files: 
- `site/_docs/contributing.md`;
- `.github/CONTRIBUTING.markdown`.
> Fixed a typo in 'contributing'.

- site/_docs/variables.md
I notice the documentation differentiates "page" and "Page". Here is a typo if I understand it right.
> Fix a typo in pagination doc

- lib/jekyll/drops/document_drop.rb
> DocumentDrop: add `#<=>` which sorts by date (falling back to path)

- .github/CONTRIBUTING.markdown
- site/_docs/contributing.md
lcoally => locally
Changes to be committed:
modified:   .github/CONTRIBUTING.markdown
modified:   site/_docs/contributing.md
> Fix "locally" typo in contributing documentation

- site/_docs/datafiles.md
The doc read “These files must be YAML files,” then lists a few extensions that are not YAML.
> Explain data file format requirements more clearly in documentation

- lib/jekyll.rb
- lib/jekyll/configuration.rb
- lib/jekyll/site.rb
- test/helper.rb
- test/test_configuration.rb
- test/test_front_matter_defaults.rb
- test/test_generated_site.rb
- test/test_site.rb
…instead of overwriting with permalink.
If you have a config file with
```yaml
permalink: date
collections:
posts:
output: true
permalink: /blog/:title/
```
then Post permalinks will match `permalink` (i.e. `"/:categories/:year/:month/:day/:title:output_ext"`) instead of `collections.posts.permalink` (i.e. `"/blog/:title/"`)
I'd like to ship a 3.0.4 for this and push it out to GitHub Pages.
/cc @benbalter @jekyll/gh-pages @jekyll/core
> Configuration: allow users to specify a collections.posts.permalink directly

- lib/jekyll/filters.rb
- site/_docs/templates.md
- test/test_filters.rb
This commit introduces a where_exp filter, which can be used as follows:
`{{ array | where_exp: "item", "item == 10" }}`
`{{ array | where_exp: "item", "item.field > 10" }}`
`{{ site.posts | where_exp: "post", "post.keys contains 'field'" }}`
`{{ site.posts | where_exp: "post", "post.array contains 'giraffes'" }}`
This permits a variety of use cases, such as reported in: jekyll#4467,
jekyll#4385, jekyll#2787.
> Add a where_exp filter for filtering by expression

- site/_docs/configuration.md
I've copied note structure and content from **usage.md**. I've just changed the title of the note. But it's ok if a native speaker changes it with a better one.
I've confused while reading docs and trying to change my defaults. So I thought a little message would be good.
> Added an explicit rerun note to configuration.md, defaults section

- site/_docs/deployment-methods.md
Failed to deploy to heroku by following old blog post,
but after stumbling up on https://github.com/adaoraul/rack-jekyll/issues/20
managed to do it and would like to avoid the trouble for others.
> Update Rack-Jekyll Heroku deployment blog post url

- lib/jekyll/convertible.rb
Replaces #4736, which was my commit in a PR but with some git conflict.
> convertible: use Document::YAML_FRONT_MATTER_REGEXP to parse transformable files

- features/frontmatter_defaults.feature
- lib/jekyll/document.rb
- test/test_document.rb
It was using "url" to determine the path, which isn't how it should work, per the
`default_proc` in the initializer.
Fixes #4458.
/cc @jekyll/build @jekyll/stability
> 3.0.x: Fix defaults for Documents (posts/collection docs)

- features/frontmatter_defaults.feature
- lib/jekyll/document.rb
- test/test_document.rb
Ports #4806 forwards to the 3.1.x line.
It was using "url" to determine the path, which isn't how it should work, per the `default_proc` in the initializer.
Fixes #4458.
/cc @jekyll/build @jekyll/stability
> 3.1.x: Fix defaults for Documents (posts/collection docs)

- site/_docs/deployment-methods.md
The rsync command was missing a single quote around the --rsh='ssh -p2222' parameter.
> Added missing single quote on rsync client side command

- site/_docs/configuration.md
Add an apostrophe so that "projects" becomes a possessive noun instead of a plural.
> Fixed typo on Configuration page

- site/_docs/plugins.md
This plugin integrates autoprefixer into Jekyll with virtually no effort.
> Add jekyll-autoprefixer to list of third-party plugins

- lib/site_template/_config.yml
yourdomain(dot)com is a deceptive website. If a jekyll user does not change this in their config, they will default to this website and it appears in places like the RSS feed. I've just experienced this with another jekyll user's blog.
> Example in the site template should be IANA-approved example.com

- lib/jekyll.rb
- lib/jekyll/filters.rb
- lib/jekyll/renderer.rb
As it stands Jekyll does not globalize it's filters.  So anybody wishing to go
into Jekyll's context to process their own Liquid (say in a plugin) may be taken
aback when they find out that Jekyll's filters are not available.
See: jekyll/jekyll-assets#252.
/cc @jekyll/core @jekyll/stability
> Globalize Jekyll's Filters.

- features/frontmatter_defaults.feature
- lib/jekyll/document.rb
- test/test_document.rb
Ports #4806 forwards to the 3.2.x/`master` line.
It was using "url" to determine the path, which isn't how it should work, per the `default_proc` in the initializer.
Fixes #4458.
/cc @jekyll/build @jekyll/stability
> 3.2.x/master: Fix defaults for Documents (posts/collection docs)

- lib/jekyll/collection.rb
- lib/jekyll/entry_filter.rb
- lib/jekyll/readers/data_reader.rb
- test/test_collections.rb
- test/test_entry_filter.rb
- test/test_site.rb
* Follow up of https://github.com/jekyll/jekyll/pull/4363
* [especially this comment](https://github.com/jekyll/jekyll/pull/4363#issuecomment-201077152)
* Attempts to solve https://github.com/jekyll/jekyll/issues/233
Tests are failing, working on updating them.
There are a couple places where the previous implementation of `EntryFilter#symlink?` was "inlined". I'm wondering if this code should be updated too?
```ruby
lib/jekyll/collection.rb:97:            File.directory?(path) || (File.symlink?(f) && site.safe)
lib/jekyll/collection.rb:138:      File.directory?(directory) && !(File.symlink?(directory) && site.safe)
lib/jekyll/readers/data_reader.rb:29:      return unless File.directory?(dir) && (!site.safe || !File.symlink?(dir))
lib/jekyll/readers/data_reader.rb:37:        next if …
```
> Allow symlinks if they point to stuff inside site.source

- site/_docs/resources.md
The current URL for FormKeep on the resource page is 404ing. This PR updates the URL to one that is working.
> Update FormKeep URL on the Resources doc

- lib/jekyll/configuration.rb
- test/test_configuration.rb
In Jekyll 3.0.4, using the `--watch` flag doesn't work. The way configurations are read using `Jekyll.configuration`, `Configuration#backwards_compatibilize` is called on the flag input as well as the file input. It's only meant to be applied to the file input. A call is made in `Configuration#read_config_files` so we'll leave that as the only place it should be called.
Tested on my site https://byparker.com and it regenerates as expected. 👍 
Fixes #4831. :pray:
Targets v3.0.4 for a v3.0.5 release.
/cc @jekyll/stability @jekyll/gh-pages
> Remove call to #backwards_compatibilize in Configuration.from

- lib/jekyll/plugin_manager.rb
When it comes to bundler it's smart enough to know what to require, and in casees it's not, it's smart enough to accept :require.  In most cases when bundler has a LoadError (or otherwise) it's because there is a problem inside of the Gem itself and when this happens, Jekyll will happily let that error slip when it shouldn't, resulting in a badly placed error that is actually wrong. This corrects that so errors can surface properly.
> Don't rescue LoadError or bundler load errors for Bundler.

- site/_docs/plugins.md
Jade has been moved to Pug https://github.com/pugjs/pug
This was forked from the previous Jade plugin and merged the pug update to maintain the newer version and avoid deprecation usage.
> Added Pug converter to list of third-party plugins

- site/_docs/plugins.md
A Liquid tag plugin for Jekyll to create image sliders using Ideal Image Slider.
> Add jekyll-ideal-image-slider to list of third-party plugins

- jekyll.gemspec
- lib/jekyll.rb
- lib/jekyll/entry_filter.rb
- test/test_entry_filter.rb
* Allow users to filter directories by ending their path with "/"
* Allow users to filter with a Regexp, some scenariors can really require it.
* Use Pathutil#in_path? for Symlink verification, it real/expand.
This also requires some downstream work in "jekyll-watch" which at this time is
not very robust, it doesn't recognize the difference either, and should probably
start doing so (what I mean is detecting "/" and using the full path.)
> Move EntryFilter to use Pathutil & fix `glob_include?`

- .rubocop.yml
- .travis.yml
- Gemfile
- script/fmt
This merges the rule set from [github/pages-gem `.rubocop.yml`](https://github.com/github/pages-gem/blob/master/.rubocop.yml) with our set here, overriding what we have with what is present in `pages-gem`'s Rubocop rules.
I sorted the keys so they're grouped a bit more logically and excluded all the files so we can enable one-by-one. It'd be an easy pull request to fix the rubocop errors and enable the file. :smile: Tracking in #4885.
@jekyll/core Will you please take a look? There are likely things we should tweak here.
> Update Rubocop rules

- .github/ISSUE_TEMPLATE.md
This makes the issue template more robust, making check boxes so users can submit and check or check as they go.  It also starts using HTML comments so that directions for the users aren't always displayed to us (gotta love Markdown.) And provides the users with more hints on what we would like from them when filing a ticket.
> Flesh out the issue template to be much more detailed

- site/_docs/permalinks.md
It seems there's an extra </p> in the html code, in the line number 104.
> Removed extra `</p>` from `site/_docs/permalinks.md`

- site/_docs/deployment-methods.md
A lot of Nitrous and PubStorm users are developing and hosting Jekyll projects, we thought it would be helpful to have the instructions here. PTAL, thanks!
> Add pubstorm deployment instructions to docs

- site/_docs/pagination.md
The latest release of [Jekyll-Pagination v1.1.0](https://github.com/jekyll/jekyll-paginate/releases/tag/v1.1.0) allows you to exclude published posts from pagination using `hidden: true` (last requested in #912). This is not reflected in the current Jekyll docs, which in fact says that this type of behavior is not possible.
On my page, I had two types of posts, blog-posts and project pages and I wanted to split them up. Although I was filtering out the project posts from the blog page, the pagination plugin was still counting them in the total count, leading to empty pagination pages (the 'total pages 7' text was for debugging) ![ss2](https://cloud.githubusercontent.com/assets/14143246/15299348/f7f16dd4-1b71-11e6-8bf8-82614020a9b1.png).
Adding `hidden: true` to the YAML of my project …
> Corrected pagination docs for hidden: true feature

- .travis.yml
- lib/jekyll/drops/drop.rb
- lib/jekyll/drops/excerpt_drop.rb
- lib/jekyll/excerpt.rb
- test/helper.rb
- test/test_excerpt_drop.rb
This fixes the bug in v3.1.3 described in https://github.com/jekyll/jekyll/issues/4906.
> Add ExcerptDrop and remove excerpt's ability to refer to itself in Liquid

- lib/jekyll.rb
- lib/jekyll/configuration.rb
- lib/jekyll/drops/drop.rb
- lib/jekyll/drops/site_drop.rb
- lib/jekyll/plugin_manager.rb
- lib/jekyll/utils.rb
- test/helper.rb
- test/test_configuration.rb
- test/test_front_matter_defaults.rb
- test/test_generated_site.rb
- test/test_site.rb
This duplicates #4753 for v3.1. It:
- Adds `Configuration.from`, which is a means of creating a `Jekyll::Configuration` from a hash instead of files
- Adds ability to overwrite `collections.posts.permalink` if `permalink` doesn't work well for it
- Sorts `{{ site.collections }}` by label, so iterating gets collections in alphabetical order by name
- Duplicates #4846 which fixes a bug where `Configuration.from` would strip `watch` and other CLI-based options from the configuration.
This targets v3.1.4.
> 3.1: Configuration permalink fix and addition of Configuration.from and sorting `site.collections` by label

- features/layout_data.feature
- lib/jekyll/convertible.rb
- lib/jekyll/renderer.rb
This pull request fixes two bugs:
1. #4433, which describes a bug where if you have a variable in a layout "special" that inherits from "default," you will see the data value from "default" instead of "special." The inheritance should mean that more specific layouts' data override the less specific layouts' data.
2. #4897, which describes a bug where the rendering of a page means its `{{ layout }}` variables exist for pages rendered later without the same data hierarchy (they "overflow" from one page to the next without being specified by the subsequent page)
This is slated for v3.1.4. 😄
> 3.1: Fix `{{ layout }}` oddities (proper inheritance & fixing overflow of old data)

- lib/jekyll.rb
Filesystems behave differently when performing glob listings.
In my environment, they are listed alphabetically. On my Mac, when asking for a list of files in a directory, those files are returned as a nicely sorted list. Alphabetized, like you'd want them to be. Like you'd expect them to be.
In some environments, quite different from my own, the return of a similar operation is quite random. Perhaps q comes before a, or e before d; the filesystem will choose its order of the day and you, the fare user, tired and weary from work, must bare the brunt of this.
And so, with this commit, I do hereby request that the noble makers of Dir[] provide for us, the downtrodden and ravaged users, some consistency. As a user of Ruby, I shouldn't have to know or consider the behaviour of an individual …
> Sort the results of the require_all glob.

- lib/jekyll/drops/document_drop.rb
- lib/jekyll/drops/drop.rb
- lib/jekyll/drops/jekyll_drop.rb
- lib/jekyll/site.rb
- test/test_document.rb
- test/test_filters.rb
Previously you could do, e.g. `{{ site | jsonify }}`, but with the introduction of Liquid Drops, this didn't work anymore.
This PR adds the ability to render drops as JSON. You can safely run drop.to_json and it should Do the Right Thing.
This fixes #4668 for the v3.1 series and should be ported to the `master` branch whenever convenient.
> 3.1: Add ability to render drops as JSON

- features/theme.feature
- lib/jekyll.rb
- lib/jekyll/commands/new_theme.rb
- lib/jekyll/errors.rb
- lib/jekyll/theme_builder.rb
- lib/theme_template/CODE_OF_CONDUCT.md.erb
- lib/theme_template/Gemfile
- lib/theme_template/LICENSE.txt.erb
- lib/theme_template/README.md.erb
- lib/theme_template/Rakefile.erb
- lib/theme_template/example/_config.yml.erb
- lib/theme_template/example/_post.md
- lib/theme_template/example/index.html
- lib/theme_template/example/style.scss
- lib/theme_template/theme.gemspec.erb
This command allows users to create new themes _very_ easily:
```text
$ jekyll new-theme THEME_NAME
$ cd THEME_NAME
$ # add files
$ # commit files
$ bundle exec rake release
```
Just saving my place for now.
> Add 'jekyll new-theme' command to help users get up and running creating a theme

- .rubocop.yml
- lib/jekyll/utils/ansi.rb
- lib/jekyll/version.rb
- test/test_related_posts.rb
- test/test_sass.rb
- test/test_static_file.rb
- test/test_theme.rb
- test/test_url.rb
More cleanup for #4885
Files addressed:
lib/jekyll/utils/ansi.rb
lib/jekyll/utils/platforms.rb
lib/jekyll/version.rb
test/test_related_posts.rb
test/test_sass.rb
test/test_static_file.rb
test/test_theme.rb
test/test_url.rb
> Rubocop cleanup for some utils and further test files

- lib/jekyll.rb
- lib/jekyll/configuration.rb
- lib/jekyll/drops/drop.rb
- lib/jekyll/drops/site_drop.rb
- lib/jekyll/plugin_manager.rb
- lib/jekyll/utils.rb
- test/helper.rb
- test/test_configuration.rb
- test/test_front_matter_defaults.rb
- test/test_generated_site.rb
- test/test_site.rb
Merge #4910 into **master**
#4911
> Forward-port: Configuration permalink fix and addition of Configuration.from and sorting `site.collections` by label

- lib/jekyll.rb
> Forward-port: Sort the results of the require_all glob

- lib/jekyll/drops/document_drop.rb
- lib/jekyll/drops/drop.rb
- lib/jekyll/drops/jekyll_drop.rb
- lib/jekyll/site.rb
- test/test_document.rb
- test/test_filters.rb
Merge #4914 into **master**
#4911
> Forward-port: Add ability to render drops as JSON

- .rubocop.yml
- lib/jekyll/stevenson.rb
> Rubocop: Stevenson

- .rubocop.yml
- test/test_configuration.rb
- test/test_document.rb
- test/test_entry_filter.rb
- test/test_filters.rb
- test/test_kramdown.rb
- test/test_liquid_renderer.rb
- test/test_page.rb
- test/test_regenerator.rb
- test/test_site.rb
- test/test_tags.rb
- test/test_utils.rb
> Rubocop: test/*

- features/support/formatter.rb
- features/support/helpers.rb
> Rubocop: features

- .rubocop.yml
- lib/jekyll/drops/site_drop.rb
> Rubocop: Site Drop

- .rubocop.yml
- lib/jekyll/tags/highlight.rb
- lib/jekyll/tags/include.rb
- lib/jekyll/tags/link.rb
- lib/jekyll/tags/post_url.rb
> Rubocop: tags

- site/_docs/plugins.md
The refheap_tag repository no longer exists, and I am not able to find a duplicate repository to replace the link.
> Remove a Broken Link for Refheap Plugin

- lib/jekyll/filters.rb
- test/test_filters.rb
If I have a page with the following front matter:
```yaml
layout: default
title: 404
```
and a layout called `_layouts/default.html` with the following contents:
```text
{{ page.title | markdownify }}
```
Jekyll will fail to build the site, throwing the error:
```text
NoMethodError: undefined method `gsub' for 404:Fixnum
```
> markdownify and smartify should convert input to string before conversion

- .rubocop.yml
- lib/jekyll/frontmatter_defaults.rb
#4885 
- fixed code style
- renamed `has_precedence?` to `precedence?`
> rubocop: jekyll/lib/frontmatter_defaults.rb

- lib/jekyll/commands/serve.rb
- test/test_commands_serve.rb
**Before**:
**After**:
The config option is removed in the [build process](https://github.com/jekyll/jekyll/blob/632f3fd8de0c63813f46240216cb12905d829968/lib/jekyll/configuration.rb#L146) so it was not available for the serve command anymore. I tried to replace the `delete` in this line with a `fetch` at first but this was causing other tests to fail. 
fixes #4850
> `Serve.process` should receive same config as `Build.process`

- .rubocop.yml
- features/step_definitions.rb
Fixes in features/step_definitions.rb
#4885
> rubocop: features/step_definitions.rb

- .rubocop.yml
- lib/jekyll/theme.rb
- lib/jekyll/url.rb
Quick pass at trying to get lib/jekyll/theme and lib/jekyll/url passing rubocop for #4885
> Rubocop theme and url jekyll libs

- .rubocop.yml
- lib/jekyll.rb
fixes one file from #4964 
yet to fix below offence reported by rubocop
```
lib/jekyll.rb:119:9: C: Do not prefix writer method names with set_.
def set_timezone(timezone)
^^^^^^^^^^^^
```
> Rubocop jekyll.rb

- site/_docs/configuration.md
Custom WEBrick headers default settings documentation is incorrect.
“We only provide one default and that’s a _Content-Type_ header that disables caching in development […]”
should read:
“We only provide one default and that’s a _Cache-Control_ header that disables caching in development […]”
> Cf. https://github.com/jekyll/jekyll/blob/master/lib/jekyll/commands/serve/servlet.rb#L8-9
> Fix inaccurate HTTP response header field name

- site/_docs/contributing.md
> Link to the HTML page instead of Markdown

- .rubocop.yml
- lib/jekyll/collection.rb
- lib/jekyll/command.rb
- lib/jekyll/configuration.rb
- lib/jekyll/deprecator.rb
- lib/jekyll/page.rb
#4885
Ruby noob here.
There are still some warning left, I don't know how to fix. 
Hope it helps though.
> Cleanup and make misc files compliant with Rubocop.

- .rubocop.yml
- lib/jekyll/site.rb
#4885 
Code style fixes in `site.rb`
> Rubocop: jekyll/lib/site.rb

- site/_docs/plugins.md
Documentation: Introduce a new plugin to _docs/plugins.md
> Add jekyll-tags-list-plugin to list of third-party plugins

- site/_docs/windows.md
unless targeting the blog local repository root, command will throw: 
> Could not locate Gemfile or .bundle/ directory
> Windows docs: Command needs to be called from blog path

- site/_docs/configuration.md
Commit 60c29561f270b15e861fb4b7b2ccb37442fd99f6 [removed](https://github.com/jekyll/jekyll/commit/60c29561f270b15e861fb4b7b2ccb37442fd99f6#diff-2c385c61f976b2a88b5821af3bdf5217L332) `category: "project"` from the example. 
This update makes the text consistent with the example.
An alternative is to update the example and put `category: "project"` back.
> Update text to be consitent with example

- .rubocop.yml
- lib/jekyll/filters.rb
> rubocop: jekyll/lib/filters.rb

- site/_docs/templates.md
This updates the links at the top of the Templates page to point to the new shopify.github.io/liquid website, including the index pages for tags and filters added in https://github.com/Shopify/liquid/pull/765.
> Update template links to point to core Liquid site

- lib/jekyll/filters.rb
- site/_docs/templates.md
- test/test_filters.rb
> Add normalize_whitepace filter

- features/hooks.feature
- lib/jekyll/renderer.rb
Note that this prevents the workaround from working anymore.
> Prevent reset of page in Liquid payload right before rendering layouts

- .rubocop.yml
- exe/jekyll
> Fix rubocop offenses in exe/jekyll

- .rubocop.yml
#4885 
No offenses detected on `/lib/jekyll/command.rb`, it can be excluded from `.rubocop.yml`
> Rubocop: lib/jekyll/command.rb 

- .rubocop.yml
- lib/jekyll/static_file.rb
- test/test_site.rb
> rubocop: lib/jekyll/static_file.rb

- .rubocop.yml
- lib/jekyll/utils.rb
> rubocop: lib/jekyll/utils.rb

- .rubocop.yml
- lib/jekyll/regenerator.rb
> rubocop: lib/jekyll/regenerator.rb

- lib/jekyll/renderer.rb
#4885
As discussed with @parkr I moved out code style fixes from bigger PR (#4961).
In this PR I fixed all the style issues in `renderer.rb`
I did not remove `renderer.rb` from `.rubocop.yml` because there are still a couple of "ABC too high"/"method too long" errors.
> rubocop: lib/jekyll/renderer.rb style fixes

- lib/jekyll/convertible.rb
#4885 
As discussed with @parkr I moved out code style fixes from bigger PR (#4961).
In this PR I fixed all the style issues in `convertible.rb`
I did not remove `convertible.rb` from `.rubocop.yml` because there are still a couple of "ABC too high"/"method too long" errors.
> rubocop: lib/jekyll/convertible.rb style fixes

- lib/jekyll/document.rb
#4885 
As discussed with @parkr I moved out code style fixes from bigger PR (#4961).
In this PR I fixed all the style issues in `document.rb`
I did not remove `document.rb` from `.rubocop.yml` because there are still a couple of "ABC too high"/"method too long" errors.
I will fix those in a separate PR by refactoring complex methods into smaller methods when this PR is merged.
> rubocop: lib/jekyll/document.rb style fixes

- site/_docs/resources.md
Formingo (https://www.formingo.co) is a new service I'm working on that handles form processing for static websites, such as those generated through Jekyll. Adding it to the list of form services because I believe it'd be a helpful resource and alternative to some of the other listed services.
> Add Formingo to the list of Jekyll form SaaS

- lib/jekyll/drops/drop.rb
- test/test_drop.rb
Fixes #4615 
As pointed out by @parkr - added `fetch` method to `Drops::Drop` class.
> Add fetch method to Drops

- test/test_configuration.rb
IMO the removed line doesn't do anything useful.
> Remove useless statement from Configuration test

- lib/jekyll/tags/link.rb
@envygeeks , @parkr is this what you meant in #4878 ?
> Extract tag name to class method

- lib/jekyll/drops/drop.rb
- lib/jekyll/excerpt.rb
- test/test_excerpt_drop.rb
Fix! I noticed that if you tried inspecting an `ExcerptDrop`, it threw an error because of missing fields, e.g. `previous` and `next`'s dependencies `previous_doc` and `next_doc`.
This PR adds the missing elements of the Excerpt so the ExcerptDrop functions properly.
> Add missing fields to ExcerptDrop

- lib/jekyll/errors.rb
- lib/jekyll/url.rb
- test/test_url.rb
> check if relative URL contains a colon

- Gemfile
ActiveSupport 5.0.x depends on [Ruby >= 2.2.2](https://github.com/rails/rails/blob/48512d790680a4fbfc20026f3c976f8fa759b2e5/activesupport/activesupport.gemspec#L10).
I only added it to the `test_legacy` and `site` group because activesupport is an indirect dependency of `shoulda` (via `shoulda-matchers`) and an indirect dependency of `jekyll-mentions` and `jemoji` (both via `html-pipeline`.)
> use activesupport < 5 if we are on a Ruby < 2.2.2

- docs/avoiding-burnout.md
- docs/becoming-a-maintainer.md
- docs/merging-a-pull-request.md
- docs/readme.md
- docs/reviewing-a-pull-request.md
- docs/special-labels.md
- docs/triaging-an-issue.md
One thing I have not done well is write about how to maintain Jekyll. Historically, I have sort of been a "benevolent dictator" in dealing with issues and pull requests, basically making myself a blocker for moving the project forward at all. It's time to change that.
The purpose of this pull request is to empower _all_ maintainers of Jekyll-owned projects to fulfill _all_ duties, such that no one maintainer makes all the decisions or does the lion share of the work. It's a team effort.
Here is the beginning of some documentation for maintainers on @jekyll/core, @jekyll/plugin-core, or any team which grants **write access** to any repository on https://github.com/jekyll. It talks about handling issues, reviewing pull requests, and merging pull requests. Anyone who is looking for guidance …
> Internal documentation for working on Jekyll

- features/theme.feature
- lib/jekyll/commands/new_theme.rb
- lib/jekyll/theme_builder.rb
- lib/theme_template/theme.gemspec.erb
Based on @benbalter's feedback at https://github.com/jekyll/jekyll/pull/4848#issuecomment-220862806
> > `spec.files = %x{git ls-files -z}.split("\x0").reject { |f| f.match(%r{^(exe|_layouts|_includes|_sass|example|example/_posts)/}) }`
>
> Unless I'm misreading, we want to include layouts/includes/sass, the gemspec and exclude everything else (including exe). (A) I don't think this line accomplishes what we want right now, and (B) I'm wondering if we should default to a whitelist to encourage stronger defaults.
@benbalter Yeah, we just want `_layouts`, `_includes`, and `_sass` to be shipped with the gem. The purpose of the line is to package up the theme for release.
> > Rakefile... `example` dir
>
> This feels super heavyweight to me, and given that we have no way to e.g., distribute bug …
> Fix more theme things

- lib/jekyll/configuration.rb
- lib/jekyll/liquid_renderer.rb
Insert
```
liquid:
error_mode: strict # or lax or warn
```
in `_config.yml` to change the error mode. #4372
> Enable strict (or lax) liquid parsing via a config variable.

- lib/jekyll.rb
- test/test_configuration.rb
This fixes a regression with configuration override options where the keys are not stringified before the first use (namely `config` and `skip_initial_build`).
The regression was introduced with version 3.1.4, commit d01f7943debf08dee645990ddb0e00d59cf846bb.
See the example below (with 3.1.5, since requiring of 3.1.4 fails for me):
```
$ cat _my_config.yml
exclude:
- file
$ cat test-3.1.3.rb
gem "jekyll", "3.1.3"
require "jekyll"
p Jekyll.configuration(:config  => "_my_config.yml")["exclude"]
p Jekyll.configuration("config" => "_my_config.yml")["exclude"]
$ cat test-3.1.5.rb
gem "jekyll", "3.1.5"
require "jekyll"
p Jekyll.configuration(:config  => "_my_config.yml")["exclude"]
p Jekyll.configuration("config" => "_my_config.yml")["exclude"]
```
Running the example with 3.1.5 produces:
``` …
```
> Stringify configuration overrides before first use

- lib/jekyll/site.rb
Fix #4861
as discussed in the comments, moved after_init hook at the end of `Site` initialization
> hooks: move after_init hook call at the end of Site.initialize

- .rubocop.yml
- lib/jekyll/collection.rb
> rubocop: lib/jekyll/collection.rb

- site/_docs/templates.md
I noticed a misspelling in `templates.md`: "occurance" should be "occurrence".
> Typo in documentation file templates.md

- README.markdown
- appveyor.yml
This is the second attempt after a long time. Now AppVeyor is 10x faster so there shouldn't be a problem there.
Someone from the repo owners (/CC @parkr) should enable AppVeyor for the whole repo when the errors are fixed.
I tried to mimic the Travis config as close as possible.
BTW, if you want to see what is currently failing, check https://ci.appveyor.com/project/XhmikosR/jekyll until someone enables AppVeyor for this repo.
> Add AppVeyor support.

- benchmark/capture-assign.rb
A minor code style fix in ```benchmark/capture-assign.rb```, which indents 4 space.
I've changed it to 2 spaces.
> Fix indentation in benchmark

- site/_docs/plugins.md
I've recently released a Jekyll plugin I use to create maps in my blog, wanted to share it :smile:
> docs: add jekyll-maps plugin reference

- .github/CONTRIBUTING.markdown
- site/_docs/contributing.md
The link to plugins source page is broken in the docs and leads to 404 error page.
I've changed it from relative URL to absolute URL.
> docs: fix link to plugins page source

- site/_includes/footer.html
- site/_includes/header.html
Only issue left is
>Error: A document must not include both a meta element with an http-equiv attribute whose value is content-type, and a meta element with a charset attribute.
Does anyone know where `http-equiv` comes from?
> site: fix validation errors.

- lib/jekyll/commands/build.rb
- prevents the watch plugin from creating a new site instance
This change won't take effect until https://github.com/jekyll/jekyll-watch/pull/40 is incorporated into a release of the jekyll-watch gem.
> watcher: pass site instance to watch plugin

- site/_docs/configuration.md
The current documentation of the default options is wrong. I've tried to make them agree. The major things
- coderay is no longer in the defaults
- kramdown's `input: GFM` is already the default so I removed the section talking about adding it
- I added documentation for liquid's `error_mode`
> Update the configuration docs to match the code

- lib/jekyll/convertible.rb
- lib/jekyll/liquid_renderer.rb
- lib/jekyll/liquid_renderer/file.rb
- lib/jekyll/renderer.rb
Liquid warnings are not shown (unless liquid's `error_mode` is set to `strict` in which case they are errors). This change causes the warnings to be printed as warnings, but does not stop the build.
For example, given the erroneous code
{% for a in b | c %}{% endfor %}
in `index.md`, the following warning message is displayed
<pre>    Liquid Warning: Liquid syntax error (line 13): Expected end_of_string but found pipe in "a in b | c" in index.md</pre>
This is identical to the `strict` case except it says "Liquid Warning" rather than "Liquid Exception".
The line numbers displayed do not count any front matter lines, but this is already true of the exceptions.
> Show liquid warnings.

- lib/jekyll/filters.rb
- test/test_filters.rb
> filters: raise error if no input given to date filters

- lib/jekyll/filters.rb
- test/test_filters.rb
```liquid
{{ site.posts | where_exp: "posts", "posts.title == 'My Title'" }}
```
This just returns `site.posts`, it does not filter posts by title.
> where_exp filter should filter posts

- lib/jekyll/command.rb
- lib/jekyll/commands/serve.rb
I had this rebased and ready to go yesterday, but ran into [this][] issue - which explains the Travis failures I had been seeing. I've since updated and I think this is ready to go.
[this]: https://github.com/jekyll/jekyll/commit/83a72606b3a0bb89696ce69bcf6f6de971137fb4#commitcomment-18372995
> Add `--baseurl` to `build` subcommand

- site/_config.yml
It looks like excerpts were disabled about three years ago via https://github.com/jekyll/jekyll/pull/1386. At that time, there were all sorts of bugs with excerpts, all of which, appear to have been fixed.
I'd like to enable excerpts for the site so that Jekyll SEO Tag can generate less generic descriptions for posts and docs.
```html
<meta name="description" content="Transform your plain text into static websites and blogs">
```
```html
<meta name="description" content="Happy Day! Jekyll v3.2.0 is out, and packed full of goodies.">
```
Of course, we can always manually set the description via front matter, but this will at least give us a more descriptive default.
Reverts https://github.com/jekyll/jekyll/pull/1386.
> Enable site excerpts

- site/404.html
- site/_layouts/error.html
This is a first go at addressing https://github.com/jekyll/jekyll/issues/5039. Not sure exactly what we're looking for here so I figured I'd open a PR and use the feedback to help this take shape.
> Initial 404 page

- site/_docs/themes.md
> Remove the "this feature is unreleased" warning from the theme docs

- lib/theme_template/theme.gemspec.erb
See https://github.com/jekyll/minima/pull/6.
We need to *include* the theme directories, not *exclude* them.
> Include theme directories in default gemspec

- site/_docs/upgrading/2-to-3.md
Added a note to the future posts section regarding GitHub pages having a different default than regular Jekyll.
> Future True on GitHub Pages note

- site/_docs/windows.md
- Corrected highlighting on multi-line sections
- Replace `cinst` with `choco install` for consistency
> Minor updates and corrections

- lib/jekyll/theme.rb
If a user uses Rbenv, their theme is going to be symlinked. We run `File.realpath` on the path before we grab things like the includes folder, but not on the theme root, meaning when the two are passed to `Jekyll.sanitized_path`, Jekyll will think the unresolved root is the real root, and that the path (with resolved root already prepended) is an unsafe path outside the directory, thus prepending the unresolved theme path.
This PR resolves that by resolving the theme root path before passing things to sanitized path, ensuring the string comparison happens on both resolved paths, not one symlink and one resolved path.
Fixes https://github.com/jekyll/jekyll/issues/5145.
> Fix for symlinked themes

- .travis.yml
- script/cibuild
- script/default-site
Motivated by https://github.com/jekyll/jekyll/issues/5153, and inspired by our tests on the Pages Gem, this PR adds a purposely (for now) failing test to generate and build Jekyll's default site.
The test is quick to run (2.3s, including Ruby's boot on my machine), and would provide a good smoke test / sanity check that the default Jekyll action works out of the box.
> Add test to build the default site

- site/index.html
In addition to #5168 we also need to update quickstart instructions on the homepage.
> index.html: update instructions to require bundler 

- lib/jekyll/layout.rb
Presently, on a Windows machine, you get an ArgumentError on Windows:
```text
Generating...
C:/Ruby23-x64/lib/ruby/2.3.0/pathname.rb:520:in `relative_path_from':
different prefix: "/" and "C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/minima-1.0.1" (ArgumentError)
from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/jekyll-3.2.0/lib/jekyll/layout.rb:61:in `relative_path'
from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/jekyll-3.2.0/lib/jekyll/renderer.rb:161:in `place_in_layouts'
from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/jekyll-3.2.0/lib/jekyll/renderer.rb:71:in `run'
```
This patch attempts to fix that. Creating a PR so I can use AppVeyor.
This doesn't affect filesystems which do not use drive names.
> Layout: set relative_path without using Pathname

- site/_docs/quickstart.md
- site/index.html
With gem-based themes being bundled in the new site via the `Gemfile`, we
should ask folks to use Bundler wherever possible. This should lead to more
successful installations and getting the base site setup properly.
The only trouble this introduces is it puts a dependency on Bundler. That
said, I'm totally fine with requiring everyone use Bundler for this site.
How could we best install bundler in these instructions?
> docs/quickstart: update instructions to require bundler

- script/default-site
It seems this is still failing.
/cc #5154
> script/default-site: specify BUNDLE_GEMFILE for new site

- script/default-site
If you bump the version in the repo, then it all goes haywire.
Fixes build failures in #5187.
> script/default-site: read Jekyll source from local clone

- site/_docs/templates.md
`to_integer` and `inspect` filters have no documentation in /docs/templates/
> Document for to_integer and inspect filters

- Gemfile
- appveyor.yml
* rename variables
* add `default-site` target
* remove `fast_finish` in order to match Travis CI behavior
A side note, @parkr, should we do something with a .gemrc to skip docs on `bundle install`?
> Update appveyor.yml and fix optional deps for Ruby x64

- site/_docs/deployment-methods.md
simply run the `jekyll` shows
```
A subcommand is required. 
jekyll 3.2.1 -- Jekyll is a blog-aware, static site generator in Ruby
``` 
need subcommand build
> need subcommand build

- site/_docs/themes.md
Fix  #5204
Show an output example of the `new-theme` command  to get a theme started.
I see that the command also initialize the theme folder as a Git repository, should we add also a `Version your theme` section to help theme authors?
> Documentation : `new-theme` command

- site/_docs/templates.md
Following #4624 
Documentation for new `link` tag introduced in v3.2.0  
cc @jekyll/documentation
> [site] Document `link` Liquid tag

- test/test_plugin_manager.rb
Hi,
this tries to improve the tests for the `Jekyll::PluginManager` by doing two things:
- migrate the existing tests to `should` syntax (those were the last in the `test` dir with `def test_*` syntax
- add missing tests
When running `script/test test/test_plugin_manager.rb`:
**Before**
**After**
> Improve tests for Jekyll::PluginManager

- site/_posts/2016-07-26-jekyll-3-2-0-released.markdown
> Remove mention of page for link tag in release post

- .travis.yml
Add Ruby v2.3.1 to travis.yml. Leaving everything else as is.
> Update Ruby versions in travis.yml

- lib/jekyll/commands/new.rb
- lib/jekyll/commands/new_theme.rb
- test/test_new_command.rb
Colorize interpolated output in Jekyll.logger.info as a way of highlighting relevant text.
> Colorize interpolated output in logger.info

- site/_sass/_gridism.scss
This PR fixes the Jekyll logo that was stretching when the browser was being resized:
> Maintain aspect ratio with height: auto;

- site/_docs/deployment-methods.md
The link to the scp deploy script was broken - it appears someone changed the link text and did not update the matching link text in the markdown footer. To prevent this problem from happening again, and for consistency with the rest of this markdown file, I changed both links to inline style links.
> Fix a link in deployment-methods.md

- site/_docs/themes.md
The words 'for' and 'in' of ```is ready for you in /path/to/my-awesome-theme!``` was interpreted as Shell keywords. However, it is the output of a shell command and should not be highlighted. And `jekyll new-theme` has no syntax highlighting as Shell command.
So I change the tag into ```plaintext``` instead.
> Documentation: improve highlight in `Creating a theme`

- site/_docs/quickstart.md
The bundle command requires the bundler gem to have been installed before it's run.
> Bundler isn't installed by default

- site/_docs/troubleshooting.md
update to include an error for a jekyll build related to issues ...
https://github.com/jekyll/jekyll/issues/5267
https://github.com/jekyll/jekyll/issues/2938
> Update troubleshooting documentation to include fix for issue with vendored gems

- site/_docs/variables.md
Fix #5033 by providing a link to latent semantic indexing on Wikipedia.
> Link --lsi option's description to Wikipedia docs on LSI

- site/README.md
Many of the gems installed by just running `bundle install` are not necessary to test the Jekyll site. Currently 33 unnecessary gems are installed on my system.
This change comes with the cost of a longer command that users must copy/paste or type.
> Avoid installing unecessary gems for site testing

- site/_docs/configuration.md
> Document --profile option on the configuration page

- .github/ISSUE_TEMPLATE.md
- docs/affinity-team-captain.md
Hey, Jekyll community!
I had a neat chat with @benbalter recently about our affinity teams and all the work the @jekyll/core team has in handling the issues and PR's that come through. He proposed that we ask certain members from affinity teams to become **"Team Captains"** which would:
- triage issues and help find solutions
- review PR's, then pass along to the core team for merge
- determine correct affinity team if not theirs
@jekyllbot would automatically assign an issue to a random team captain for the mentioned affinity team and it would be their responsibility to ensure the issue is handled [according to our guidelines on "Triaging an Issue"](https://github.com/jekyll/jekyll/blob/master/docs/triaging-an-issue.md). @jekyllbot would politely nudge the user to mention an affinity …
> Proposal: Affinity teams and their captains

- .github/ISSUE_TEMPLATE.md
> Replace duplicate with postive local test in issue template

- site/_posts/2016-08-24-jekyll-admin-initial-release.markdown
@jekyll/gsoc, anything you'd like to add ? 😄
> Add post about Jekyll Admin initial release

- site/_docs/assets.md
- site/_docs/collections.md
- site/_docs/configuration.md
- site/_docs/continuous-integration.md
- site/_docs/datafiles.md
- site/_docs/deployment-methods.md
- site/_docs/drafts.md
- site/_docs/extras.md
- site/_docs/frontmatter.md
- site/_docs/github-pages.md
- site/_docs/installation.md
- site/_docs/pages.md
- site/_docs/pagination.md
- site/_docs/plugins.md
- site/_docs/posts.md
- site/_docs/quickstart.md
- site/_docs/structure.md
- site/_docs/templates.md
- site/_docs/themes.md
- site/_docs/troubleshooting.md
- site/_docs/upgrading/0-to-2.md
- site/_docs/upgrading/2-to-3.md
- site/_docs/usage.md
- site/_docs/windows.md
- site/_sass/_style.scss
Replace {% highlight ---- %} and {% endhighlight %} with backticks to keep markdown syntax highlight intact for .md docs within site/_docs folder.
{% highlight --- %} is kept intact for lines code blocks involving optional `linenos` arg and those args not supported in GFM.
> Replace liquid highlight tag with backticks

- site/_docs/continuous-integration.md
Just a little update - I guess Travis has changed its icon a bit. It's not a wrench icon, but a gear one. Adding screenshot as a proof. 
Cheers!
> Word update

- site/_includes/docs_option.html
- site/_includes/docs_ul.html
On the site documentation section, links to documentation sections always point to the `jekyllrb.com` website, this means that users testing changes might get confused because they will see the official external website page instead of their local website upon clicking those links.
**Please check if this change doesn't break the links on the official website on `https://jekyllrb.com` before accepting the pull request.**
----------
> Site documentation section links always point to https://jekyllrb.com

- lib/site_template/_config.yml
`Gemfile` and `Gemfile.lock` is generated after `jekyll new`, both of which should exclude in `_config.yml`. Otherwise, they can be downloaded from site.
> Site template: exclude Gemfile and Gemfile.lock in site config

- appveyor.yml
- script/default-site
Install gems in vendor and cache those only.
> Update AppVeyor config.

- site/_docs/plugins.md
The hook `:site, :post_render` provides a `payload`, but the plugins documentation section of the official Jekyll website doesn't inform this.
> Missing ":site, :post_render" payload documentation on site

- site/_config.yml
> Site: exclude README.md and .gitignore [ci skip]

- script/default-site
While working on #5241, I noticed that its not required to run `jekyll new` from **exe/jekyll** binary and rather works well with Jekyll _cloned with the build_. 
I opened this PR to have all discussions and updates separate from the other PR.
> Execute jekyll from clone instead of defined binary when running 'script/default-site'

- .rubocop.yml
- lib/jekyll/document.rb
#4885 
This PR is extracted from #4961 
Here I reduced `merge_data!` and `read` methods' ABC size and now there are no rubocop errors in `document.rb`
I also moved helper methods like `categories_from_path`, `populate_categories` etc to private.
There are still a couple of methods duplicated with `convertible.rb` (e.g. `yaml_file?`, `asset_file?`, `sass_file?`, `coffeescript_file?`, `published?`, `write`). I plan to extract those duplicated code to some common place after finishing with rubocop fixes in `convertible.rb`
> rubocop: lib/jekyll/document.rb complexity fixes

- lib/jekyll/site.rb
- test/test_site.rb
Some previous ad-hoc 'themes' used this configuration option to store a hash of values.
In that case, we should simply pretend we have no theme.
Fixes #5163.
/cc @benbalter @emico7 @getaaron @wreichard
> Site#configure_theme: do not set theme unless it's a string

- site/_docs/resources.md
This PR adds a link to [Staticman](https://staticman.net), a free and open source platform to insert user-generated into a Jekyll site by converting entries to data files and pushing them to the repository where the site lives.
> Add link to Staticman

- .rubocop.yml
- lib/jekyll/convertible.rb
- lib/jekyll/renderer.rb
This simplifies the code a bit -- much less duplication.
We might consider providing a way to set the layouts for a Renderer so we can override it if necessary. It seems a bit aggressive to want/have to change `site.layouts` in order for this to work.
#4885
> Proxy a number of Convertible methods to Renderer

- site/_docs/troubleshooting.md
Hi,
as described in #5144 somehow on Heroku a `bin/erb` file couldn't be found during build. This was a symlinked file and it couldn't be copied because of the reasons @parkr pointed out in https://github.com/jekyll/jekyll/pull/4640#discussion_r57260002 .
I wasn't sure if i should also rescue the exception in the `static_file.rb` and provide a better error message in the log, so for now there is only a new section in the troubleshooting doc.
I would be glad if @xuanxu and / or @stomar could confirm if their site is building again after they set their jekyll environment to `production`.
cc: @jekyll/documentation
> [docs] add help for missing static_file e.g. on heroku

- site/_docs/themes.md
Update documentation to add a line about publishing a new version of theme gems to help those who may not know how.
@DirtyF
> Add a line about updating theme-gems in the docs

- lib/jekyll/commands/build.rb
- lib/jekyll/utils/platforms.rb
This increases our ability to detect Windows, and to detect Windows+Bash.  It also adds a message to Windows for users who try to "--watch", also noting to to them to check out the Windows ticket so eventually somebody pings us if this issue is fixed. /cc @TAGraves
/cc @jekyll/windows @jekyll/core @parkr @benbalter @jekyll/build
> Fix #5233: Increase our ability to detect Windows.

- lib/jekyll/utils.rb
- test/test_utils.rb
After careful thinking to solve problem when using web-servers which don't support Unicode characters in directory and file names, I came up with solution. We can use a new "urlsafe" mode for slugification, which just allows characters A-Z, a-z and 0-9 on the slug. Everything else is changed to "-".
The accompanying patch to use "urlsafe" on our case is here:
https://github.com/jussikinnula/jekyll-contentful/commit/24d1c854d27701a4e70649fc6802e6585108da3b
If we can get this first part accepted, I'll create secondary pull request.
More specifically the web-server problem on our case is when using Google Firebase or Amazon S3 to host the Jekyll static site, produced with the content from Contentful CMS service.
This would also mitigate the problem described on "Slugify a string doesn't seem …
> Add "ascii" mode to Utils.slugify

- site/_docs/posts.md
- site/_docs/structure.md
With GitHub Pages having removed support for Textile, I figured out it was less confusing to use only .md files in examples.
cc/ @jekyll/documentation
> [docs] .md as default extension in examples

- lib/jekyll/convertible.rb
In #5308, I modified `Convertible` to essentially delegate to the `Renderer`. This removed a lot of duplicated code (😸) but introduced a slight difference: the `Renderer` doesn't really modify the document it's rendering–it's meant only to render and return the result. Sadly, then, the methods aren't *entirely* equivalent. This PR sets `self.output` in two places to ensure the old functionality is preserved.
Without this, the `jekyll-sitemap` gem barfed when rendering the source of `jekyllrb.com`. It [uses the `Page` API's rather than the `Renderer`](https://github.com/jekyll/jekyll-sitemap/blob/bc9f90e032c2bad2f72b451f9ccc3dc8523c6af4/lib/jekyll/jekyll-sitemap.rb#L56-L57). Without these changes the `site_map.output` value is `nil` on the latest `jekyll/jekyll` master.
/cc …
> Convertible: set self.output in #render_all_layouts and #do_layout

- site/_docs/templates.md
It's "normalize_whitespace".
https://github.com/jekyll/jekyll/blob/master/lib/jekyll/filters.rb#L158
> Fix small typo in docs

- lib/jekyll/tags/link.rb
- test/source/info.md
- test/test_filters.rb
- test/test_site.rb
- test/test_tags.rb
Fixes request made in #4624 and bug found in #5182
> Adds ability to link to all files

- lib/jekyll/configuration.rb
- site/_docs/configuration.md
> Exclude vendor by default

- lib/jekyll/filters.rb
Hi,
this fixes the failing tests in #4362 for the liquid 4 update. The reason for the failing tests is that liquid changed the evaluation of the expressions in `Liquid::Condition`
```diff
-      left = context[left]
-      right = context[right]
+      left = context.evaluate(left)
+      right = context.evaluate(right)
```
While the former worked, `context.evaluate(x)` is internally trying to call `evaluate` on the argument `x`.  In our case `x` was still a `String` which doesn't have an `evaluate` method so we need to [parse](https://github.com/Shopify/liquid/blob/64fca66ef5dfd7cf1acef0a7b8cdd825756eb681/lib/liquid/expression.rb#L24-L42) these expressions first.
cc: @parkr
> [liquid 4] parse expressions before passing it to Liquid::Condition

- features/support/helpers.rb
Since Windows does not recognize `exe/jekyll` as an executable, let ruby run it instead of having shell do it. This moves us a step closer to fixing cucumber test scenarios on Windows.
Ref: #5241 
--
Earlier, every cucumber scenario would fail prematurely with following:
```
Exec format error - C:/projects/jekyll/exe/jekyll (Errno::ENOEXEC)
C:/projects/jekyll/features/support/helpers.rb:101:in `run_in_shell'
C:/projects/jekyll/features/support/helpers.rb:93:in `run_jekyll'
C:/projects/jekyll/features/step_definitions.rb:141:in `/^I run jekyll(.*)$/'
<features/*.feature:LN#>:in `When I run jekyll build'
```
--
> Run executable for Cucumber via Ruby instead of Shell

- exe/jekyll
- lib/jekyll/hooks.rb
- test/test_related_posts.rb
Rubocop 0.43.0 seems to have some new expectations.
`rubocop -a`
> Appease Rubocop

- lib/jekyll/commands/new.rb
- test/test_new_command.rb
This PR proposes to extend the `jekyll new` command with following:
- Automatically `cd my_blog` and initiate `bundle install` 
> After you run `jekyll new my_blog` the command shell automatically `cd` into the new directory and runs `bundle install`.
> If bundler is not installed, an exception is raised gracefully.
> The user may choose to skip 'bundle install' if they plan to edit their new gemfile and change the theme gem, or if they want to inspect the new directory before running the `bundle install` command by using the new switch `--skip-bundle`
ref: #5225
> Add bundle install to jekyll new command

- lib/jekyll/converters/markdown/kramdown_parser.rb
After upgrading to jekyll 3, I wanted to continue using coderay as my highlighter.  So I updated my configuration to:
```
kramdown:
syntax_highlighter: coderay
syntax_highlighter_opts:
line_numbers: inline
css: class
```
And I was surprised when jekyll complained:
```
Deprecation: You are using 'kramdown.coderay' in your configuration, please use 'syntax_highlighter_opts' instead.
```
It seems that jekyll is raising this notice whenever `highlighter == "coderay"`, even when the `kramdown.coderay` configuration setting is nonexistent.
Switching this to check for a non-empty `kramdown.coderay` hash keeps this warning when the user has `kramdown.coderay` settings, but suppresses this warning when the configuration has switched to the new style `kramdown.syntax_highlighter_opts`.
> Only complain about `kramdown.coderay` if it is actually in the config

- lib/theme_template/README.md.erb
This clarification is subtle, but may prove greatly useful to Jekyll newbies who can't piece together the line of YAML with the instructions above.
I weighed between the solution I proposed and this alternative line of instruction:
> And add this line to your Jekyll site's configuration file:
Either works sufficiently.
> Clarify documentation in theme gem's README template

- lib/jekyll/tags/highlight.rb
- test/test_tags.rb
This allows the use of the `shell_session` language in Rouge for instance.
> Allow underscore in highlighter language

- features/step_definitions.rb
Feature directories generated during cucumber tests currently throw a `Errno::EACCES` exception after every scenario runs on windows.
This Pull resolves this issue.
--
> remove features' directories on windows with proper access

- lib/jekyll/drops/site_drop.rb
- test/test_site_drop.rb
Hi,
in Liquid 3 when you parsed a Liquid::Template like `{% for method in site.thanksgiving %}{{ method.title }} {% endfor %}` the term `thanksgiving` was recognized as a `String`, in Liquid 4 though `thanksgiving` is a `Liquid::VariableLookup`.
This `Liquid::VariableLookup` was not properly evaluated because the [key was not found within the Jekyll::Drops::SiteDrop instance] (https://github.com/Shopify/liquid/blob/64fca66ef5dfd7cf1acef0a7b8cdd825756eb681/lib/liquid/variable_lookup.rb#L44).
This should fix all the remaining failures with Liquid 4 🎉
> [liquid 4] find keys also in assigned collections

- lib/site_template/_config.yml
Addresses [minima/#34](https://github.com/jekyll/minima/issues/34) at the upstream.
This bug occurs due a recent change shipped with minima-1.1.0
/cc @pathawks
> Site template: set empty url in config file by default

- lib/jekyll/filters.rb
- lib/jekyll/filters/url_filters.rb
- test/helper.rb
- test/test_filters.rb
When creating sites and themes, there's a lot of confusion around `site.url` and `site.baseurl`. These new filters attempt to unify the way we calculate relative and absolute URL's. The new filters are:
- `relative_url` - takes a URL and returns a url with `site.baseurl` properly prepended. This is useful when you want to be host-agnostic.
- `absolute_url` - takes a URL and returns a url with `site.baseurl` and `site.url` properly appended.
Examples, assuming `site.baseurl = "/project"` and `site.url = "http://example.com"`:
```liquid
{{ "/css/main.scss" | relative_url }}
{{ "/css/main.scss" | absolute_url }}
```
If your `site.baseurl` or `site.url` values aren't set, it will just append what it can dependeing on the desired output of the filter. Read the tests in the diff for more on …
> Add absolute_url and relative_url filters.

- lib/theme_template/theme.gemspec.erb
Ref: #5323 
Modify gemspec template to include all non-empty directories within the theme gem.
Currently, trying to build with the generated theme.gemspec results in an empty gem (at least on Windows 7 + Ruby 2.3.1 + RubyGems 2.6.6)
> update gemspec template to include only required theme files

- features/site_configuration.feature
switch to date/time in POSIX format as value to `timezone:` key in `features/site_configuration.feature` since Windows does not seem to understand tz-name specified currently.
Ref: #5414 
--
> site_configuration.feature: use UTC format in timezone

- site/_docs/continuous-integration.md
You can [see](https://travis-ci.org/tf2manu994/tf2manu994.github.io/builds/162424169) that without this fix, it crashes and burns.
`Gem::InstallError: activesupport requires Ruby version >= 2.2.2.`
Which is a dependency.
> Fix Travis.ci documentation

- lib/jekyll/commands/new.rb
patches `commands/new.rb` to swallow outputs by `bundle install` when running in a CI environment.
This removes unnecessary clogging of CI logs.
--
> swallow bundle output from `jekyll new` while in CI

- lib/jekyll/configuration.rb
- site/_docs/configuration.md
- test/test_configuration.rb
If no 'exclude' directive is specified, exclude node_modules by default.
https://twitter.com/mxstbr/status/761856359579185153
> Exclude node_modules by default

- features/hooks.feature
- lib/jekyll/hooks.rb
Low priority hooks are being run before higher priority hooks. This is easy to
demonstrate with the following plugin:
1.upto(10).each do |n|
Jekyll::Hooks.register :site, :after_reset, priority: Jekyll::Hooks::PRIORITY_MAP[:low] do
puts "Low #{n}"
end
Jekyll::Hooks.register :site, :after_reset, priority: Jekyll::Hooks::PRIORITY_MAP[:normal] do
puts "Normal #{n}"
end
Jekyll::Hooks.register :site, :after_reset, priority: Jekyll::Hooks::PRIORITY_MAP[:high] do
puts "High #{n}"
end
end
Sorting by the negative of the priority and then by the order the hook was
added does the right thing.
> Run hooks in priority order.

- site/_docs/quickstart.md
- site/index.html
Update the docs to mention that `jekyll new` now runs `bundle install` automatically for every new site and that they may choose to skip that with the `--skip-bundle` switch.
Ref: #5237
--
> [docs] Update documentation regarding `bundle install` after `jekyll new`

- lib/site_template/_config.yml
Best not to send mixed messages and jekyllrb's quickstart message is "bundle exec jekyll serve"
> Site template config: prepend 'jekyll serve' with 'bundle exec'

- lib/jekyll/static_file.rb
- test/test_static_file.rb
> Don't call `File.utime` for StaticFiles if it's a symlink

- jekyll.gemspec
- lib/jekyll/filters/url_filters.rb
- test/test_filters.rb
How/where should normalization be handled? I would love if the filters could also be responsible for normalization.
> Fix handling of non-ASCII characters in new `*_url` filters

- lib/jekyll/static_file.rb
- site/_docs/static_files.md
- test/test_static_file.rb
_Disclaimer: These are my first ruby lines_ 😅 
A proposal to fix #5263
> Add `static_file.name` and `.basename` Liquid attributes

- lib/jekyll.rb
Referencing Jekyll::Draft raises 'LoadError: cannot load such file -- jekyll/draft'
> Remove autoload of Draft which no longer exists.

- lib/jekyll/excerpt.rb
- test/source/_posts/2016-08-16-indented-link-references.markdown
- test/test_excerpt.rb
- test/test_generated_site.rb
Excerpt link reference extraction is missing all the indented references
at the bottom of the page. Markdown specify that those can be indented up
to three spaces.
I've also added a title to the link in the test.
> Add support for indented link references on excerpt

- lib/jekyll/tags/post_url.rb
- test/test_tags.rb
Instead of matching the the value provided to `post_url` against the base name, test against the relative path.
Updated the regexp to match both `_posts/#{path}/#{date}-#{slug}` as well as `#{path}/_posts/#{date}-#{slug}`
This is a very rough draft, and it's entirely possible that I missed something. But I wanted to get feedback on this approach and check if I should pursue further and work on tests.
This will break the build for anybody who worked around #3926 by removing the path from the calls to `post_url`, but it would be easy to adapt the regexp to match based on date and slug only.
> Fix bug where `post_url` tag matched incorrect post with subdirectory

- site/_docs/frontmatter.md
List no longer exists on that page as an id.  Basic_components holds the lists now, and at the top conveniently :v:
I also added a second link under the tags heading.
> Update Wikipedia YAML list link

- lib/jekyll/readers/data_reader.rb
- test/source/_data/categories.01/dairy.yaml
- test/test_site.rb
Fix #5429
If we're processing a directory - use it's name as a key.
> Fix loading data from subdir with a period in name

- lib/jekyll/commands/serve.rb
This reverts a tiny part of #5431, which introduced a backwards-incompatible change that JekyllAdmin was relying on. It's never fun to break things and jekyll-admin must have a stunning reputation for not breaking. 😄 
This is also necessary because `launch_browser` also used `server_address` and wasn't updated. So we have to handle that anyway.
> Revert Commands::Serve#server_address signature change.

- site/_posts/2016-10-03-jekyll-3-3-0-released.markdown
@jekyll/core @jekyll/documentation @benbalter – for review.
/cc #5400
> Add Jekyll 3.3 release post

- site/_docs/templates.md
Updated templates documentation now that `{% link %}` tag can link to pages and files.
> Documentation: {% link %} tag 

- docs/_docs/windows.md
The excellent guide by Julian Thilo (http://jekyll-windows.juthilo.com) does not cover Ruby 2.2 and newer nor installing Jekyll 3. 
I decided to create a separate installation guide based on this earlier work and bring it up to speed with the latest developments for both Ruby and Jekyll 3 (and discuss issues specific to these versions on Windows).  Modified the Jekyll windows page to include a link to this updated guide.
> Updating install instruction link for Jekyll 3 on Windows

- lib/theme_template/README.md.erb
Jekyll was spelled "Jelyll" on line 41
> Fix typo in theme_template README

- site/_docs/plugins.md
While the basic functionality is the same as that I proposed in #5470, the plugin further adds a `theme` (equivalent to `site.data[theme-name]`) namespace to the `UnifiedPayloadDrop` class and outputs the data read into an easily readable format in `jekyll build --verbose`
--
> Add jekyll-data to the list of plugins

- .rubocop.yml
Rubocop 0.44 introduced a new cop called `Metrics/BlockLength` that excludes spec files and rakefiles by default. This PR excludes our minitest files as well.
Also excludes 2 other files that got caught in [this job](https://travis-ci.org/jekyll/jekyll/jobs/168120013).
- have the new `Metrics/BlockLength` cop ignore test files and
`jekyll/configuration.rb`
- have `AllCops` ignore Jekyll Executable which is not going to be
altered in the near future.
> fix rubocop errors on testing with Rubocop 0.44

- script/test
add missing whitespace between `-I` and `test` in `bundle exec ruby -I test `
> script/test: add missing whitespace

- lib/jekyll/frontmatter_defaults.rb
- lib/jekyll/readers/data_reader.rb
I found a couple places where I could combine two `gsub`s into one :+1:
> Collapse `gsub`

- site/_docs/installation.md
In regards to #5484. I added a section to `/docs/installation/` to show how to check your version of Jekyll, find the latest version and update it. 
Open to feedback.
> Add info about checking version + updating

- Gemfile
Sometimes Rubocop will add cops in a minor version and all of a sudden CI starts breaking for reasons unrelated to any recent changes. This locks Rubocop to the current minor version so that we can start using new cops on _our_ schedule :+1:
/cc: @jekyll/core @ashmaroli
> Restrict Rubocop version

- lib/jekyll/site.rb
> Do not swallow all exceptions on render

- lib/site_template/_config.yml
Found a typo when going through a tutorial. Replaced `these this` with `this`
> Site template: fixed `_config.yml` comment typo

- lib/theme_template/theme.gemspec.erb
Themes created with Jekyll 3.3.x will run with only Jekyll 3.3.x
--
> `jekyll new-theme` should specify Jekyll as a runtime dependency for the theme

- site/_docs/troubleshooting.md
`sudo apt-get install ruby2.0.0-dev` reports _Unable to locate package ruby2.0.0-dev_ (Using Lubuntu 16.04)
> Ubuntu users should install ruby2.3-dev

- site/_docs/deployment-methods.md
Remove Glynn as deployment option since that gem is no longer actively maintained. See notes in readme in repository: https://github.com/dmathieu/glynn and https://github.com/dmathieu/glynn/issues/67
> Remove Glynn as deployment option

- docs/becoming-a-maintainer.md
https://help.jekyllrb.com has been replaced with https://talk.jekyllrb.com :boom:
> Fix broken forum link

- docs/_docs/datafiles.md
Previously the YAML example would contains the string 'yaml' at the top of the file. Very confusing for newcomers.
> Fix HTML rendering

- lib/jekyll/drops/url_drop.rb
- lib/jekyll/url.rb
- test/test_url.rb
fixes #5332 
the tests only cover not throwing a `NoMethodError` because i can't figure out how to capture the logged message to check if it logged the correct message (minitest's `capture_io` only works with kernel `puts`, weirdly enough)
> URL: warn if key doesn't exist in url drop

- lib/jekyll/configuration.rb
- lib/jekyll/entry_filter.rb
- test/test_configuration.rb
An alternative to https://github.com/github/pages-gem/pull/352, but it probably won't work.
~~The way exclusion works in Jekyll is really pretty naïve. In `EntryFilter#filter`, it iterates through an array of pathnames and checks to see if each pathname is included, excluded, etc. The way reading works in Jekyll, this list of pathnames is just the basename, so `vendor/cache` becomes first `vendor`, then (if not excluded), we get the array of files and directories inside of `vendor` as basenames, e.g. `cache` instead of `vendor/cache`.~~
~~I'd love to rethink the way we do reading so we get the full pathname from the site source, or allow `EntryFilter`'s `base_directory` path to be included in exclusion testing.~~
I checked and the code for exclusion already does this! 🎉 
```ruby
def …
```
> Be much more specific about ignoring specific vendored directories.

- features/collections.feature
- features/step_definitions.rb
- features/support/helpers.rb
This pull allows the sole failing cucumber feature to pass on AppVeyor.
Ref: [#5241](https://github.com/jekyll/jekyll/pull/5241#issuecomment-249404210),  63146e6
> Collections.feature: conditional steps to have it pass on Windows

- test/helper.rb
- test/test_collections.rb
- test/test_entry_filter.rb
- test/test_filters.rb
- test/test_generated_site.rb
- test/test_site.rb
- test/test_theme.rb
> Fix tests to get script/test to pass on Windows

- site/_sass/_gridism.scss
Avoiding errors on `jekyll serve`
```
Configuration file: /jekyll-offline-docs/site/_config.yml
Configuration file: /jekyll-offline-docs/site/_config.yml
Source: /jekyll-offline-docs/site
Destination: /jekyll-offline-docs/site/_site
Generating...
Conversion error: Jekyll::Converters::Scss encountered an error while converting 'css/screen.scss':
Invalid US-ASCII character "\xE2" on line 30
jekyll 3.3.0 | Error:  Invalid US-ASCII character "\xE2" on line 30
```
And line 97 when 30 is adjusted...
---
Will be super usefull to have the doc offline while travelling, thank you for that guys 👍
> no more invalid US-ASCII on lines 30 and 97

- site/_docs/plugins.md
Added link to my Jekyll plugin: https://github.com/snaptortoise/jekyll-pinboard-plugin. Interfaces with the Pinboard API to make data for specified tags available to the template, sort of similar to the built-in Data Files support.
> Add jekyll-pinboard to list of third-party plugins

- site/_docs/upgrading/2-to-3.md
I was reading through the "Upgrading from 2.x to 3.x" page in the docs and noticed some of the markdown was janky. I made these small edits to fix the formatting and conform with how it's done elsewhere.
> Fix formatting in 2-to-3.md

- site/_docs/plugins.md
I wrote a couple plugins that help with inlining CSS and JS. I'd like to have them added to the plugins page.
> Add two plugins to the plugins page

- docs/_docs/templates.md
This PR updates the documentation to show that `{{ site.baseurl }}` must be used before the `{% link %}` and `{% post_url %}` tags.
> Use site.baseurl before link and post_url tags

- lib/jekyll/url.rb
- test/helper.rb
- test/test_url.rb
> Allow permalink template to have underscores

- docs/_docs/templates.md
- lib/jekyll/filters.rb
- test/test_filters.rb
When building a sentence based off an array, the default connector is "and". This will allow other terms to be used such as "or".
> Add connector param to array_to_sentence_string filter

- lib/jekyll/tags/post_url.rb
- test/source/_posts/2016-11-26-special-chars-(+).markdown
- test/test_generated_site.rb
- test/test_tags.rb
Previously, the post_url function would give error messages when the post being listed contained special characters for use in regular expressions.  These special characters are now escaped using
`Regexp.escape`.
This is in reference to issue #3486.
> Escaped regular expressions when using post_url.

- test/test_tags.rb
replace **`double-quotes`** inside **unit-test names** with **`single-quotes`** to give them a cleaner look..
> clean unit-test names in `test/test_tags.rb`

- docs/_docs/configuration.md
If you add the previous version to your config file, you'd get an error on build/serve.
> Fix bad config YAML in collections example

- docs/_docs/structure.md
The documentation on 'Directory Structure' contains a few dated information and errors that can confuse a new Jekyll user. This pull fixes those errors.
--
--
> Bring documentation on 'Directory Structure' up-to-date

- features/step_definitions.rb
- features/support/helpers.rb
- features/theme_gem.feature
Adds a cucumber feature to follow the steps a user would take to build a theme gem and check if it is ready for distribution using theme generated by `jekyll new-theme`
Ref: #5362 
/cc @parkr
> Add cucumber feature to test for bonafide theme gems

- docs/_docs/templates.md
- lib/jekyll/filters.rb
- lib/jekyll/filters/grouping_filters.rb
- test/test_filters.rb
> Adds group_by_exp filter

- docs/_docs/permalinks.md
Add special note: built-in permalink styles are not recognized in the YAML Front Matter.
https://github.com/jekyll/jekyll/issues/2691#issuecomment-52406242
https://github.com/jekyll/jekyll/issues/2691#issuecomment-52579505
> Improve Permalinks documentation.

- docs/_docs/variables.md
> Fix typo in Variables doc page

- .github/CONTRIBUTING.markdown
- docs/_docs/contributing.md
Addresses #5650 
Adds a comprehensive section to `contributing.md`
Leaves `docs/readme.md` as is..
--
> Update documentation on updating FontAwesome Iconset

- lib/jekyll/collection.rb
- lib/jekyll/excerpt.rb
> Rubocop -a on lib/jekyll

- docs/_docs/permalinks.md
- docs/_docs/quickstart.md
See https://github.com/jekyll/jekyll/pull/5630 for more details on the update. 
> Improve quickstart docs

- docs/_docs/plugins.md
I have added a link to my pre-render hook plugin to add ordered number to headings.
[jekyll-numbered-headings](https://github.com/muratayusuke/jekyll-numbered-headings)
Following syntax
```markdown
##1. At first
###1. One thing
###1. Another thing
##1. Second
##1. Third
```
will be replaced to:
```markdown
```
> Add jekyll-numbered-headings

- docs/_docs/extras.md
[This link](http://gastonsanchez.com/opinion/2014/02/16/Mathjax-with-jekyll/) is unavailable anymore (Error 404), this PR simply replaces it with [a web-archived one](https://web.archive.org/web/20160522225559/http://gastonsanchez.com/opinion/2014/02/16/Mathjax-with-jekyll).
> Replace a dead link with a web-archived one

- lib/jekyll/tags/include.rb
This is when either 'dir' or 'file' is `nil` and passed `File.join`.
<details>
<summary>Backtrace</summary>
<pre>
<a href="https://github.com/jekyll/jekyll/blob/v3.3.1/lib/jekyll/tags/include.rb#L115" target="_blank">.bundle/ruby/2.3.0/gems/jekyll-3.3.1/lib/jekyll/tags/include.rb:115:in `join&#39;</a>
<a href="https://github.com/jekyll/jekyll/blob/v3.3.1/lib/jekyll/tags/include.rb#L115" target="_blank">.bundle/ruby/2.3.0/gems/jekyll-3.3.1/lib/jekyll/tags/include.rb:115:in `block in locate_include_file&#39;</a>
<a href="https://github.com/jekyll/jekyll/blob/v3.3.1/lib/jekyll/tags/include.rb#L114" target="_blank">.bundle/ruby/2.3.0/gems/jekyll-3.3.1/lib/jekyll/tags/include.rb:114:in `each&#39;</a>
<a href="https://github.com/jekyll/jekyll/blob/v3.3.1/lib/jekyll/tags/include.rb#L114" …
> include: fix 'no implicit conversion of nil to String'

- .rubocop.yml
- Gemfile
Rubocop 47 adds new security cops that trigger warnings to Jekyll's code: 
1. Avoid using of `Marshal.load` or `Marshal.restore` due to [potential security issues](http://ruby-doc.org/core-2.3.3/Marshal.html#module-Marshal-label-Security+considerations).
Q: There is no autocorrect for this cop. Should we ignore this for now or use `Marshal.dump` or another method?
2. Prefer usage of `YAML.safe_load` over `YAML.load` due to [potential security issues](https://ruby-doc.org/stdlib-2.3.3/libdoc/yaml/rdoc/YAML.html#module-YAML-label-Security).
```ruby
features/step_definitions.rb:103:22: C: Security/YAMLLoad: Prefer using YAML.safe_load over YAML.load.
config[key] = YAML.load(value)
^^^^
test/test_configuration.rb:320:31: C: Security/YAMLLoad: Prefer using YAML.safe_load over YAML.load. …
```
> New rubocop security checks

- test/helper.rb
- test/test_static_file.rb
If we do a `Dir.chdir` before `Configuration::DEFAULTS` is initialized, then its `source` and `destination` values will not be what we expect. We expect that `Dir.pwd` should stay as the root of the repo but there are some errant calls to `Dir.chdir` without a block that are still not yet cleaned up. Remove all bare `Dir.chdir` calls.
Failing test this fixes:
```text
Failure:
TestSite#test_: configuring sites should have an array for plugins by default.  [/home/travis/build/jekyll/jekyll/test/test_site.rb:7]
Minitest::Assertion: --- expected
+++ actual
@@ -1 +1 @@
-["/home/travis/build/jekyll/jekyll/_plugins"]
+["/home/travis/build/jekyll/jekyll/test/source/_plugins"]
```
Example: https://travis-ci.org/jekyll/jekyll/jobs/192169603
> test/helper: fix flaky plugin path test by removing calls to Dir.chdir without a block

- features/rendering.feature
- lib/jekyll/tags/include.rb
Hi,
at first i thought about using the new [Liquid::Error#template_name](https://github.com/Shopify/liquid/blob/ffb0ace30315bbcf3548a0383fab531452060ae8/lib/liquid/errors.rb#L4) field but it's only available in Liquid 4 and we already have `Jekyll::Tags::IncludeTagError` which wasn't used anywhere.
**Before:**
**After:**
fixes #5756
> throw IncludeTagError if error occurs in included file

- docs/_docs/collections.md
See https://github.com/jekyll/jekyll/pull/5630 for more details on the update. 
> Improve collections docs

- docs/_docs/installation.md
I am just unsure should we provide the link to the GNU make page, as it's dull and its installation instructions are nothing less dull. Also, make can be installed via the `build-essentials` package.
> Fix #5730: add gcc and make to the list of requirements

- lib/jekyll/site.rb
- test/helper.rb
- test/test_site.rb
- test/test_theme.rb
> Don't include the theme's includes_path if it is nil.

- docs/_docs/maintaining/merging-a-pull-request.md
`doc` and `port-forward` were missing.
source: https://github.com/parkr/auto-reply/blob/e5c55feb1811aad9f2426fbe49891c50a3376e8f/chlog/merge_and_label.go#L30-L70
> Add missing merge labels for jekyllbot

- features/support/helpers.rb
- lib/jekyll/commands/new.rb
- lib/jekyll/utils.rb
- lib/jekyll/utils/exec.rb
- test/helper.rb
- test/test_new_command.rb
This fixes #5463 by taking @envygeeks's `run_in_shell` command and port it directly into the Jekyll codebase.
Any commands Jekyll has to run should be run with this method.
/cc @jekyll/core @ashmaroli
> Write Jekyll::Utils::Exec.run for running shell commands.

- docs/_docs/templates.md
See https://github.com/jekyll/jekyll/pull/5630 for more details on the update. 
> Improve template docs

- docs/_docs/plugins.md
Just came across the [`jekyll-ga`](https://github.com/developmentseed/jekyll-ga) generator plugin from the team that built [http://www.healthcare.gov](https://www.healthcare.gov/) and am adding it for posterity.
> Sort content by popularity using Google Analytics

- docs/_docs/themes.md
See https://github.com/jekyll/jekyll/pull/5630 for more details on the update. 
> Improve theme docs

- docs/_docs/configuration.md
classifier-reborn is mandatory for LSI since Jekyll 3.0
> Add mention of classifier-reborn for LSI

- docs/_docs/quickstart.md
Added instructions about installing Jekyll with a blank slate using the --blank flag.
> Added note about --blank flag

- docs/_docs/permalinks.md
Must be either:
> Rather than typing `permalink: /:categories/:year/:month/:day/:title/`, you can just type `permalink: pretty`.
or:
> Rather than typing `permalink: /:categories/:year/:month/:day/:title.html`, you can just type `permalink: date`.
I guess the former was meant to write because the latter was already mentioned in "Where to configure permalinks" section.
> Fixed inaccuracy in "Built-in permalink styles" docs

- lib/jekyll/related_posts.rb
Imo running `--lsi` should use `Jekyll.logger.info`, so it can be made `--quiet`.
> use logger.info for related posts

- .codeclimate.yml
- .travis.yml
- Gemfile
- test/helper.rb
Fix #5796 
V1.0 changes: https://github.com/codeclimate/ruby-test-reporter/blob/master/CHANGELOG.md#v100-2016-11-03
> Bump codeclimate-test-reporter to v1.0.5

- History.markdown
- jekyll.gemspec
- lib/jekyll/drops/site_drop.rb
- lib/jekyll/filters.rb
- lib/jekyll/filters/grouping_filters.rb
- test/test_site_drop.rb
- test/test_tags.rb
RC1 for now.
@fw42 @dylanahsmith, know what's going on here? `.parse` isn't working like before.
``` text
Error:
TestTags#test_: highlight tag in unsafe mode should recognize the hl_linenos option and its value. :
NoMethodError: undefined method `line_number' for {}:Hash
/Users/parkr/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/liquid-4.0.0.rc1/lib/liquid/tag.rb:21:in `initialize'
/Users/parkr/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/liquid-4.0.0.rc1/lib/liquid/block.rb:4:in `initialize'
/Users/parkr/jekyll/jekyll/lib/jekyll/tags/highlight.rb:14:in `initialize'
/Users/parkr/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/liquid-4.0.0.rc1/lib/liquid/tag.rb:9:in `new'
/Users/parkr/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/liquid-4.0.0.rc1/lib/liquid/tag.rb:9:in `parse' …
```
> Upgrade to Liquid v4

- docs/_docs/installation.md
- docs/_docs/troubleshooting.md
closes #5759 
- The link to the troubleshooting page is more obvious on installation page
- Ubuntu troubleshooting is on troubleshooting page with other Linux specific instructions
/cc @BlueberryFoxtrot
> Install troubleshooting on Ubuntu

- docs/_posts/2017-01-18-jekyll-3-4-0-released.markdown
`/docs/filters/` -> `/docs/templates/#filters`
/cc @nhoizey
> Fix broken links in 3.4.0 release post

- test/test_site_drop.rb
Kinda irritating when tests fail because of the absence of an unexpected comma.
This is to appease Rubocop `0.47`
> [Rubocop] add missing comma

- History.markdown
Year should probably be 2017 instead of 2016
> Corrected date for version 3.4.0

- docs/_docs/troubleshooting.md
Someone recently ran into problems installing the requirements on Android (see termux/termux-packages#713).
This PR documents the solution found in that issue.
> Add Termux section on troubleshooting

- docs/_docs/themes.md
Classes are not being generated in IALs <https://jekyllrb.com/docs/themes/>
> fix ial css classes in theme doc

- lib/jekyll/drops/static_file_drop.rb
- lib/jekyll/static_file.rb
- test/test_static_file.rb
Per https://github.com/jekyll/jekyll-sitemap/pull/157#issuecomment-278429052, this PR implements a new StaticFileDrop such that static files can inherit front matter defaults.
I believe this is implemented as a non-breaking change. The resulting hash should be identical, with a new `collection` field added (to more closely mimic the DocumentDrop).
I also tried to obtain as much parity with how Documents implement front matter defaults, by spiking out a new `data` method, rather than simply delegating to the existing `defaults` method for fallback data (which we could do if we don't want static files to have user-modifiable metadata beyond defaults).
> Convert StaticFile liquid representation to a Drop & add front matter defaults support to StaticFiles

- features/site_configuration.feature
- lib/jekyll/configuration.rb
- lib/site_template/_config.yml
- test/test_configuration.rb
Exclude `Gemfile` and `Gemfile.lock` by default. I can't think of any situation where they may be needed to be processed.
Additionally, comment out existing `exclude:` array in the generated `_config.yml` and explain what to do with it
Addresses #5859 
--
> Exclude Gemfile by default

- docs/_tutorials/orderofinterpretation.md
This tutorial defines Jekyll's "order of interpretation," as @swizca called it in [#5808](https://github.com/jekyll/jekyll/pull/5698). This tutorial makes it clear how Jekyll processes files as it renders the static HTML output.
This order-of-interpretation info is important for troubleshooting and generally understanding Jekyll. It's important to know how Jekyll generates out the files, what rules it uses, what order it processes things, and so forth.
(Note: Please process #5698 before this request, because #5698 includes the tutorial collection/navigation that this tutorial fits into. I also need to update this commit to add a link in the Tutorials nav to this topic, but I'm waiting for #5698 to be merged so that menu becomes available.)
@jekyll/core
> Add documentation about order of interpretation

- lib/jekyll/convertible.rb
> Convertible#validate_permalink!: ensure the return value of data["permalink"] is a string before asking if it is empty

- docs/_docs/deployment-methods.md
Aerobatic has changed the service from a Bitbucket plugin into a command line tool that is usable with any repository host (such as Github!). This means that the old instructions are out of date. This PR fixes that with new instructions.
> Update Aerobatic docs

- docs/_docs/collections.md
As noted in a few Issues including #5064, `posts` is a hard-coded collection that will come up when iterating over `site.collections`. This was a source of confusion for me. I didn't see any mention of this in the docs.
This PR adds a note to http://jekyllrb.com/docs/collections/ that `posts` is a hard-coded collection.
> Add note to collections doc on hard-coded collections.

- docs/_docs/templates.md
I didn't know the difference between `cgi_escape` and `uri_escape` until it bit me when I had a colon in a title I used `uri_escape` on. Addressable::URI.encode (from addressable 2.4.0 and later) thought it was a URI and raised an error. I should have been using `cgi_escape`, which is for strings that will be added to URIs and not `uri_escape`, which is for encoding strings that are already in a URI.
This commit [borrows from the addressable docs](https://github.com/sporkmonger/addressable/blob/master/lib/addressable/uri.rb#L551) to make the `uri_escape` explanation more specific so that readers choose `uri_escape` when they already have a URI and `cgi_escape` when they are just escaping a plain string.
> Makes uri_escape template docs more specific.

- docs/_docs/configuration.md
The configuration page lists the footnote_nr kramdown configuration option twice. That seemed a bit much, so I removed one of the two lines.
> Remove duplicate footnote_nr from default config

- docs/_docs/themes.md
gem build lists files by git, so it is needed to have them commited.
> Fixed tutorial for publishing gem to include repo.

- docs/_docs/templates.md
where once there was a working url, there's now a broken redirect
> update broken links

- lib/jekyll/document.rb
- test/source/_posts/2017-2-5-i-dont-like-zeroes.md
- test/test_generated_site.rb
In https://github.com/jekyll/jekyll/pull/5609, we made the date matching much stricter: it had to be in `YYYY-MM-DD`. In a brief test on GitHub Pages, we noticed this issue.
This PR loosens this to allow 2-digit years, and 1-digit months and days. That makes this a valid filename:
```text
_posts/12-2-5-my-post.md
```
I'm iffy on allowing 2-digit years, but the previous regexp allowed it (just three instances of `\d+`).
Fixes #5879 as well, @andrewbanchich. Would you please test this out?
I'm hoping to get this out as a v3.4.1 and include this patch in v3.5 as well.
> Allow abbreviated post dates

- docs/_data/docs.yml
Change introduced in a05e64c9d360e8357dc9c23a76656d231f0665dd has broken the bottom navigation as the page no longer exists, so I removed it from docs.yml
> Navigation has been moved out from docs

- docs/_sass/_style.scss
When viewing a page, it's kind of hard to see what page you're viewing. The little triangle graphic pointing to the page is too subtle. Making the link to the current page orange (the same as the hover color) would make it visually more apparent where you are in the navigation. Here's a screenshot showing the change: [https://www.screencast.com/t/e6NKerSAUL](https://www.screencast.com/t/e6NKerSAUL). The link to the current page is orange even when I'm not hovering over the link with my mouse.
> Make links in sidebar for current page more prominent

- test/source/_posts/2010-01-16-override-data.markdown
- test/source/_posts/2011-04-12-text-extension.text
- test/source/_posts/2013-08-01-mkdn-extension.mkdn
- test/source/_posts/2014-11-24-Rmd-extension.Rmd
- test/source/_posts/2015-12-27-extra-spaces.markdown
Addresses #5721
`classifier-reborn` is not very happy about empty posts in our test suite. This pull adds dummy content to those posts to appease `classifier-reborn`
/cc @pathawks
> Appease classifier-reborn

- .travis.yml
- appveyor.yml
- rake/release.rake
This should make backporting easier as we'll have CI running on those PR's and allow releasing from the *-stable branches.
> Allow releases & development on *-stable branches

- script/backport-pr
This is a script I pulled from the git-lfs/git-lfs repo which makes it crazy easy to backport a PR.
Example: https://github.com/jekyll/jekyll/pull/5924
/cc @jekyll/affinity-team-captains @jekyll/core
> Add script/backport-pr

- lib/site_template/about.md
This ensures better portability, allowing to switch and preview themes without having to delete the code block.
(Jekyll aborts build if the include is not found when switching themes)
--
> Remove dependency on include from default about.md

- docs/_docs/configuration.md
Follow up to #5860
`Gemfile` and `Gemfile.lock` is excluded by default, circa [`4e40593`](https://github.com/jekyll/jekyll/pull/5860/commits/4e40593a53e51c9f1e2ce567677bc1803bbd4829)
--
> Update exclude array in configuration.md

- docs/_layouts/tutorials.html
The path in the "Improve this page" link that is auto-generated in the Tutorials section had an incorrect parameter. This PR fixes it.
> Fixed path in "Improve this page" link in Tutorials section

- lib/jekyll/configuration.rb
YAML is mature and already works with Jekyll. This PR recommends YAML as first choice and TOML as second in error messages.
TOML is v0.4.0 and is "changing a lot" [according to its author](https://github.com/toml-lang/toml).
And for the love of god, will somebody please read XKCD 927.
> Prefer .yaml over .toml

- docs/_posts/2017-03-21-jekyll-3-4-3-released.markdown
Feel free to make any changes you think necessary.
Our theme does not seem to expect using monospace text as a link:
Should I use `<code class="filter">` for my example Liquid, so that it is green like our filter documentation?
> Release post for v3.4.3

- docs/_docs/static_files.md
Based on the functionality released in [3.4.2](http://jekyllrb.com/news/2017/03/09/jekyll-3-4-2-released/) re adding defaults to static files, I thought this page needed some more detail.
> Included more details about adding defaults to static files

- docs/_docs/continuous-integration/index.md
This can only be approved once https://github.com/jekyll/jekyll/pull/5962 has been merged.
> added (buddyworks) to ci list

- docs/_tutorials/custom-404-page.md
> Add a tutorial on serving custom Error 404 page

- docs/philosophy.md
Here are 5 points to start with.
Fixes #5342.
/cc @benbalter @pathawks @mattr- for :eyes: especially. :heart:
> Document Jekyll's Philosophy

- docs/_docs/troubleshooting.md
- docs/_docs/upgrading/2-to-3.md
Support for Ruby 2.0 has been dropped since https://github.com/jekyll/jekyll/issues/4381
This PR aims to state the current Ruby depency in the docs and on Rubygems.
~~Some core plugins could be impacted, for example[ jekyll/import still requires Ruby 1.9.x ](https://github.com/jekyll/jekyll-import/blob/master/jekyll-import.gemspec#L10
)~~~
/cc @jekyll/plugin-core
> Require Ruby > 2.1.0

- features/site_configuration.feature
- features/step_definitions.rb
- features/support/helpers.rb
Fix recent failures in AppVeyor that occurred due to `ENV["TZ"]` being set on Windows with `tzinfo` gem  with DST-aware cucumber steps.
> Fix Appveyor with DST-aware cucumber steps

- Gemfile
Fixes #5987 
Once this is in, we should bump Rubocop via a new Pull Request.
/cc @parkr
> Use Rubocop v0.47.1 till we're ready for v0.48

- docs/_docs/posts.md
- docs/_docs/quickstart.md
- docs/_docs/themes.md
- docs/_tutorials/navigation.md
- script/proof
- As http://jekyllrb.com/tutorials/navigation/ uses `<a href="#">` links, `allow-hash-href` is now set to true by default
- Set `disable-external-url` by default to avoid checking more than 2500 external URLs **everytime** 
- remove the lasting 404 errors
```shell
$ script/proof
Running ["ScriptCheck", "ImageCheck", "LinkCheck"] on ["./_site"] on *.html...
Ran on 122 files!
HTML-Proofer finished successfully.
```
> Default options for script/proof

- lib/jekyll/document.rb
Numerous `public` methods for an instance of `Jekyll::Document` got removed (converted to `private` methods) in [`158e026`](https://github.com/jekyll/jekyll/pull/5045/commits/158e02623a4b0207878dfd01fda7a9bd666937fc) which should've been put off till `v4.0`
This came to my attention via [this thread](https://talk.jekyllrb.com/t/serve-error-undefined-method-post-read-for-class-jekyll-document/353/3) at Jekyll Talk, which reported a broken plugin `jekyll-multiple-languages`
Now that we have a system to easily release backport-hotfixes, this should probably be released as `v3.3.2` (IMO).
--
/cc @ayastreb, @parkr
> Re-surface missing public methods in `Jekyll::Document`

- exe/jekyll
- lib/jekyll/external.rb
This clarifies the following error message:
You must install the 'jekyll-docs' gem to use the 'jekyll docs' command.
by including the required version
You must install the 'jekyll-docs' gem version = 3.4.0 to use the 'jekyll docs' command.
This removes ambiguity.
The technical solution is no fun (makes "magical" assumptions) but I
couldn't get the RubyGems `Gem` API to play nice and tell me what
constraint is required. Does anyone else know how to do that?
> Specify version constraint in subcommand error message.

- docs/_docs/windows.md
With Bash on Ubuntu on Windows, jekyll can run as with normal Ubuntu.
> Mention Bash on Ubuntu on Windows

- lib/site_template/404.html
Ref: #5944 
Provide a Custom 404 Error Page with `jekyll new`
Personally, not very happy about including internal CSS. However, this is preferable until Minima decides to ship a layout dedicated to this page.
/cc @pathawks @benbalter
> Add a template for custom 404 page

- Gemfile
- docs/_docs/themes.md
- features/theme.feature
- lib/jekyll/plugin_manager.rb
- lib/jekyll/theme.rb
- test/fixtures/test-dependency-theme/test-dependency-theme.gemspec
- test/test_plugin_manager.rb
Have Jekyll require the `runtime_dependencies` of a theme-gem from its `.gemspec` file so that the theme's consumers need not have to edit their `gems` array to include plugins required by their theme.
--
> Require `runtime_dependencies` of a Gem-based theme from its `.gemspec` file

- lib/jekyll/errors.rb
- lib/jekyll/url.rb
- test/test_url.rb
> Don't raise an error if URL contains a colon

- docs/_docs/upgrading.md
I've added the case for a simple Jekyll updates so beginners do not need to google for it, or ask.
> Update upgrading.md to mention usage of `bundle update`

- lib/jekyll/filters.rb
Failure noticed on `master`: https://travis-ci.org/jekyll/jekyll/jobs/217231764
In Ruby 2.4, Time#localtime modifies the Time instance.
In Ruby 2.3, Time#localtime appears to leave them alone.
Either that, or `#to_time` used to duplicate and now it doesn't.
> Filters#time helper: Duplicate time before calling #localtime.

- docs/_docs/configuration.md
I was reading the docs tonight and noticed this quotation mark was missing, which also threw off the highlighting in this block.
> Fix missing quotation mark

- docs/_docs/collections.md
The previous version contained errors regarding the definition and usage of the `:path` permalink template variable (see Issue #5901). This version corrects those errors, removes redundant language where possible, and restructures the section to place examples before template variable definitions.
The reasoning behind the third change is that it's generally easier for learners to understand a generalized or abstracted definition after having seen concrete examples in action first.
> Revamp Permalink section

- Gemfile
@brianmario graciously merged https://github.com/brianmario/yajl-ruby/pull/173 and shipped a new version of yajl-ruby in the 1.2 series to support Ruby 2.4.
This allows us to continue to use pygments.rb < 1.x so Windows users can still use Pygments if so desired.
> Use yajl-ruby 1.2.2 (now with 2.4 support)

- docs/_docs/assets.md
- docs/_docs/configuration.md
- docs/_docs/plugins.md
- lib/jekyll/configuration.rb
- lib/jekyll/errors.rb
- lib/jekyll/plugin_manager.rb
- lib/jekyll/site.rb
- test/test_configuration.rb
- test/test_plugin_manager.rb
- test/test_site.rb
`gems` won't be deprecated. This fixes #4509 .
> add `plugins` config key as replacement for `gems`

- docs/_tutorials/convert-existing-site-to-jekyll.md
The file index.md referenced the layout "default.html" in its frontmatter. As far as I know and according to my tests, a layout has to be referenced without its file extension.
This is my first proposal for a file change in github - sorry, if I did something wrong. Your tutorial was very helpful to me for starting my first Jekyll-blog.
> corrected reference to layout in index.md

- lib/site_template/_config.yml
unless you're explicitly trying to advertise for domain.com
then you should use the official example domain setup by IETF
https://tools.ietf.org/html/rfc2606
https://tools.ietf.org/html/rfc6761
> doc use example.com

- docs/_docs/extras.md
Hi there!
The MathJax CDN is [shutting down at the end of the month](https://www.mathjax.org/cdn-shutting-down/) -- I just updated the documentation to suggest using the cdnjs one instead.
> (Minor) Update MathJax CDN

- docs/_docs/sites.md
We have recently build a Jekyll website for the MvvmCross open source project(https://github.com/MvvmCross/MvvmCross) which we are really proud of. It will make maintaining documentation a lot easier. I've put it in the samples area on the website in the hope that it can inspire other open source projects.
> Add MvvmCross to samples

- lib/jekyll/command.rb
- lib/jekyll/commands/build.rb
- lib/jekyll/commands/serve.rb
- test/test_commands_serve.rb
Hi,
before, `Jekyll.configuration` was called 3 times during  the `serve` command as described in #5467 . With this patch it is called only once:
I also [made sure](https://github.com/jekyll/jekyll/blob/a6580f978e6f826c9c4a369c183a47ce5c222d0a/lib/jekyll/commands/serve.rb#L53-L57) that `jekyll-admin` still works with this, to avoid the disaster from last time 😊 .
@jekyll/build
> create configuration from options only once in the boot process

- docs/_docs/continuous-integration/travis-ci.md
- Use "Flick the repository switch on" which is matched in Travis CI guide
> Update travis-ci.md to correct procedure

- docs/_config.yml
- docs/_sass/_normalize.scss
- rake/site.rake
Suggested by @pathawks in #6008
> Compress Website Sass output

- docs/_tutorials/orderofinterpretation.md
modify Liguid to Liquid in docs/_tutorials/orderofinterpretation.md
> doc correct spelling error

- docs/_tutorials/convert-existing-site-to-jekyll.md
According to the linked specification https://www.sitemaps.org/protocol.html the date-format is https://www.w3.org/TR/NOTE-datetime, e. g. "2017-04-27". The current sitemap produces dates like "2017-April-27" and fails the Google test for sitemaps in the Google Search Console.
> adjusted date-format in sitemap

- docs/_tutorials/navigation.md
The result showed a different title than the yaml example
> Fixed documentation inconsistency

- .rubocop.yml
- docs/_docs/configuration.md
- lib/jekyll/command.rb
- lib/jekyll/configuration.rb
- lib/jekyll/convertible.rb
- lib/jekyll/document.rb
- test/source/_broken/bad_post.md
- test/test_convertible.rb
- test/test_site.rb
This is a feature request by way of a PR for a problem I've had with Jekyll in past.
I have a number of sites that are deployed from a CI. The setup is functionally equivalent to the results of following [Jekyll's own documentation on using a CI](http://jekyllrb.com/docs/continuous-integration/travis-ci/):
> The simplest test script simply runs jekyll build and ensures that Jekyll doesn’t fail to build the site. It doesn’t check the resulting site, but it does ensure things are built properly.
The issue I run into is that `jekyll build` is not sufficient to verify that a site is building as expected. If there is a syntax error in a page's front matter, Jekyll will print a warning, ignore the page, and continue.
This repeatedly causes problems for me when people add a page and add …
> Add option to fail a build with front matter syntax errors

- lib/jekyll/commands/new.rb
I've had `ruby RUBY_VERSION` in all my Gemfiles generated by `jekyll new` on Windows. Ignored it because it never seemed to cause any issue.
Proposing interpolating the variable based on this [comment](https://github.com/jekyll/jekyll/issues/5719#issuecomment-274227923) to trigger a Travis build and check if this is a fix..
> Remove `ruby RUBY_VERSION` from generated Gemfile

- features/rendering.feature
- lib/jekyll/document.rb
Inspired by discussion in #5929 
While `layout: null` will still continue to be overridden by the `defaults`, with this pull in place, the user will be able to process and output a `Jekyll::Document` object without being placed into a layout by 
simply declaring `layout: none` in the Front Matter
/cc @jekyll/ecosystem 
Let me know if this results in any unintended behavior..  I'll update as required.
> Disable default layouts for documents with a `layout: none` declaration

- docs/_config.yml
When I run the docs locally, Jekyll said:
```
Deprecation: The 'gems' configuration option has been renamed to 'plugins'. Please update your config file accordingly.
```
> Docs: rename `gems` to `plugins`

- docs/_docs/templates.md
The original wording implies that the links *is* `page_a.md`. Instead, the link is *in* or *from* that page.
> Use more precise language when explaining links

- docs/_docs/windows.md
Hey guys! I got jekyll running flawlessly on my copy of windows 10 creators update with some pretty basic steps taken. I was curious if I could contribute this guide to the docs. Thanks for your time, let me know if you want me to edit anything / reformat the markdown.
/cc @parkr  @jekyllbot
> windows 10 tutorial

- docs/_docs/themes.md
#5704 
#5690 https://github.com/jekyll/jekyll/pull/5690#issuecomment-269599039
The theme documentation is frustratingly incomplete when it comes to overriding theme styles. This, or something similar, seems long overdue.
> Explain how to override theme styles

- docs/_config.yml
Revert #6082 to prevent GitHub Pages automatic build from failing.
> plugins -> gems

- docs/_docs/windows.md
Changed the link to Microsoft's install guide for Bash on Ubuntu on Windows to go directly to the tutorial instead of a different page. (pull #6100)
Also, we are considering moving the windows guide from its own page to the Installation directions.(Pull #6109).
> updated Bash on Ubuntu on Windows link in tutorial

- docs/_docs/templates.md
Remove unnecessary word in "Linking to posts" section
> Fix wording in _docs/templates.md links section

- docs/_data/docs.yml
Added windows to list of docs in docs.yml after adding updated tutorial to the windows page (#6100)
> Added windows to docs.yml

- docs/_docs/deployment-methods.md
> Be more specific on what to upload

- docs/_docs/windows.md
I was following the new instructions introduced by #6100 
Some of the bash commands have an extra newline, so they look like this:
This pull request removes them.
> Remove Blank Newlines from "Jekyll on Windows" Page

- docs/_docs/quickstart.md
This is a follow up to pull request #6128. The original problem is said to be fixed on master and there is no point in explaining and solving the same bug twice. A link for those who have problems should be nice, though.
> Link the troubleshooting page in the quickstart page

- lib/jekyll/commands/new.rb
This one-liner resolves #5932. Users on most platforms don't
experience the problem, but on NixOS ruby gems are installed in the
Nix store, where their permissions are set to 444 (`r--r--r--`).
Thus when `jekyll new` does `cp_r` from the `site_template`, the
permissions remain read-only and the end user cannot immediately edit
`_config.yml` and friends like the tutorials suggest.
Our packaging for NixOS patches in this change, but if you'll accept
it upstream we can eliminate that patch. It could be helpful for other
platforms where installed gems have read-only permissions.
> In `jekyll new`, make copied site template user-writable

- lib/jekyll/renderer.rb
- test/source/_layouts/default.html
- test/source/index.html
- test/test_generated_site.rb
Fixes #6071 
we add "layout" key to payload when we place doc into layout (see `def render_layout`), so when first doc is rendered - layout data is not present in payload and only added there after, so it is available for next documents.
In this PR I add layout data to payload before rendering the document.
> Add top-level `layout` liquid variable to Documents

- lib/jekyll/filters/url_filters.rb
- test/test_filters.rb
Fix #6057 
/cc @jekyll/ecosystem 
requesting additional review from @parkr as well.
> patch URLFilters to prevent `//`

- features/collections.feature
- features/step_definitions.rb
> Test if hidden collections output a document with a future date

- test/test_filters.rb
#6081 docs the difference between `uri_escape` and `cgi_escape` on reserved characters. This PR is to add test which covers all the reserved characters.
> Add test for uri_escape on reserved characters

- docs/_docs/templates.md
> Document difference between cgi_escape and uri_escape #5970

- .travis.yml
- jekyll.gemspec
Should address @pathawks's comment here: https://github.com/jekyll/jekyll/pull/5230#issuecomment-308261578
In a PR which bumps Rouge, you'd update the default to 2 and voila.
> Allow you to specify the rouge version via an environment variable for testing

- .rubocop.yml
- Gemfile
- features/support/helpers.rb
- lib/jekyll/collection.rb
- lib/jekyll/commands/serve.rb
- lib/jekyll/converter.rb
- lib/jekyll/convertible.rb
- lib/jekyll/document.rb
- lib/jekyll/hooks.rb
- lib/jekyll/liquid_renderer/table.rb
- lib/jekyll/plugin.rb
- lib/jekyll/utils/win_tz.rb
- test/test_document.rb
- test/test_filters.rb
Upgrade Rubocop to 0.49.0 
Fix #6089
Fix #6101
> Bump Rubocop to 0.49.1

- lib/jekyll/filters/url_filters.rb
- test/test_filters.rb
https://github.com/jekyll/jekyll-sitemap/pull/170 made me realize that in several of Jekyll's core plugins we use the pattern `{{ file.path | replace:'/index.html','/' }}`.
That filter works, but is (A) easy to forget, and (B) is a blind replace, not a replace of the a trailing `/index.html`. 
This PR adds a quick `strip_index` filter (very up for a better name, maybe `pretty_permalink`?), to implement the above logic as a native URL filter.
Thoughts?
> Add strip_index filter

- lib/jekyll/commands/serve.rb
- lib/jekyll/configuration.rb
- lib/jekyll/filters/url_filters.rb
Using an empty string as the default value causes all sorts of problems where you don't know if this is user-specified or not. Using an explicitly "illegal" value, like `nil`, resolves this issue.
See https://github.com/jekyll/github-metadata/pull/97 for more info.
/cc @jekyll/build @benbalter
> Default `baseurl` to `nil` instead of empty string

- docs/_docs/maintaining/special-labels.md
- docs/_docs/maintaining/triaging-an-issue.md
i noticed that documentation about this label was missing. are there any other undocumented special labels?
> add documentation about the "pinned" label

- docs/_docs/windows.md
Installation via RubyInstaller
> docs(JekyllOnWindows): Add a new Installation way

- docs/_docs/windows.md
fixed some grammar issues, formatting, etc.
continued from pull(#6148).
/cc @jekyll/documentation @jekyll/windows
> corrected windows.md

- Gemfile
- appveyor.yml
Fails our AppVeyor tests: https://ci.appveyor.com/project/jekyll/jekyll/build/1722/job/3vlp2o2i69uw6n2p
> Lock nokogiri to 1.7.x for Ruby 2.1

- docs/_docs/windows.md
Caution: Editing galore. The `diff` can get confusing.. My apologies
I suggest a read-through of the rendered GFM version first and then finalize by viewing the `diff`
/cc @jekyll/documentation 
P.S. Is the section on Installing **Github-Pages** via Chocolatey relevant in our documentation?
> Refine documentation for Windows

- jekyll.gemspec
- lib/jekyll/utils/rouge.rb
- test/test_kramdown.rb
- test/test_tags.rb
Hey,
i changed `Formatters::HTML` for `Formatters::HTMLLegacy` based on @jneen 's suggestion (https://github.com/jekyll/jekyll/pull/5919#issuecomment-308536849) and because `Formatters::HTML` (the rouge 2 version) doesn't print line numbers (unless i missed something).
**Note**: This targets #5919 instead of `master`. Will close #5230 in favor of this.
> [Rouge 2] use `Rouge::Formatters::HTMLLegacy` and fix tests

- .travis.yml
- test/test_tags.rb
- make sure rouge 1.11 tests are executed with ruby 2.4 (travis is still defaulting to 1.9.2)
- remove additional newline from test
Failing tests can be seen here: https://travis-ci.org/jekyll/jekyll/builds/244774309
cc: @parkr #5919
> fix travis for rouge 1.11

- docs/_docs/installation.md
Version 2.0.x of Ruby is no longer supported
---
Ref #4381 , 8e81dd69ec375
Related: #5983
> Update minimum Ruby version in installation.md

- docs/_docs/collections.md
Add information about finding a collection in `site.collections`.  Information taken from the "Upgrading from 2.x to 3.x" page which was discovered by reading issue #4392.
> [docs] Add information about finding a collection in `site.collections`

- lib/jekyll/filters/url_filters.rb
#6058 introduced a private method `:site` to `Jekyll::Filters::URLFilters` that created unforeseen bugs when the module got extended. This PR reverts that private_method to oblivion.
/cc @jekyll/ecosystem @benbalter
> Backward compatiblize URLFilters module

- docs/_docs/collections.md
Fix for https://github.com/jekyll/jekyll/pull/6165#issuecomment-310865627
Discussion: https://github.com/jekyll/jekyll/pull/6165#issuecomment-310906562
I can change it to escaping the braces if that is what is ultimately wanted.
/cc @DirtyF @ashmaroli @jekyll/documentation
> Add {%raw%} to Liquid example on site

- docs/_docs/plugins.md
I replaced the current Pug plugin, which had major flaws, with my new plugin that fixes those flaws and more. The previous Pug plugin didn't support Pug includes, Jekyll layouts, and at times was buggy with Jekyll includes. 
I also removed the Jade plugin, as it was a 404 link.
> Added improved Pug plugin - removed 404 Jade plugin

- Gemfile
Since jekyll/jekyll#6137 `baseurl` can be `nil`. Until jekyll-feed 0.8
the `baseurl` has been used as argument to `URI.join`. When `baseurl`
is `nil` this throws an exeption:
> URI.join('http://example.com', nil)
> ArgumentError: bad argument (expected URI object or URI string)
The usage of `baseurl` within jekyll-feed has been removed in
jekyll/jekyll-feed@bf728c321d715f8bb1673e43fb3c848fe736fa6d
> set minimum requirement for jekyll-feed

- lib/jekyll/static_file.rb
- test/test_document.rb
- test/test_static_file.rb
Trying to track down https://github.com/jekyll/jekyll-sitemap/issues/176, it seems in 3.5, when you call `to_liquid` on a convertible (page, static_file), the resulting hash doesn't contain front matter default keys, although calling a specific key returns the expected value. This means that things like `to_json` or anything that looks for `.key?` will not act as expected.
This PR currently contains a failing test in hopes of finding the root cause (and adding tests for front matter defaults going forward).
/cc @parkr
> Static files contain front matter default keys when to_liquid'd 

- lib/jekyll/filters/url_filters.rb
- test/test_filters.rb
Since https://github.com/jekyll/jekyll/pull/6137, `baseurl` defaults to `nil`.
That means, for the first time, [this code path](https://github.com/jekyll/jekyll/blob/4f4d42444ac73174d857ad0a630e23d4ba8f41be/lib/jekyll/filters/url_filters.rb#L26) is excercised (since we weren't checking `to_s.empty?` before. This has two implications.
First, URL's aren't normalized, which is an inconsistent behavior.
Second, if `baseurl` isn't set, in Jekyll >= 3.4.4, the `relative_url` filter will return the result of the page's `url` method by reference, which is `@url`, rather than a new string. This continue to be true even if you call `to_s` on the input or output (I suspect because `@url` is already a string, `to_s` has some sort of `return thing if thing.is_a? String` check).
Imagine the following …
> Always normalize the result of the relative_url filter

- lib/jekyll/filters/url_filters.rb
- test/test_filters.rb
Backport of https://github.com/jekyll/jekyll/pull/6185 for the 3.4.x branch since https://github.com/jekyll/jekyll/pull/6137 was backported and introduced the bug.
> Always normalize the result of the relative_url filter (3.4.x backport)

- lib/jekyll/deprecator.rb
Following discussion in #5130  
@crunch09 and @envygeeks suggested to use `warn` instead of `error` for deprecation message.
> Use Warn for deprecation messages

- docs/_docs/includes.md
When passing references to YAML files as parameter values the references shouldn't be added as an object, i.e. it shouldn't be wrapped in double curly brackets.
> Small correction in documentation for includes

- Gemfile
- jekyll.gemspec
- test/test_tags.rb
see https://kramdown.gettalong.org/news.html
cc: @parkr
> bump kramdown to 1.14.0 for rouge 2 support

- docs/_sass/_style.scss
Having not looked at this site in a while, I noticed it looks like the page `body` has lost its margin reset. Note the space around the gold line at the top of the page in the screenshots below:
This PR resets the `margin` of the `body` element to zero, and also adds a little bit of horizontal padding for the mobile version of the site-nav, which otherwise wouldn’t have much space—especially when the leftmost item is the currently selected menu item:
/cc @parkr @mattr-
> Fix docs site page margin

- lib/site_template/_config.yml
Since #5130 we are encouraged to use `plugins` key rather than `gems` in `config.yml`
This should be merged only when GitHub Pages has updated to next release.
> site template: Use plugins key instead of gems 

- lib/site_template/_config.yml
- test/source/_config_folded.yml
- test/test_configuration.rb
**before:** `{{ site.description }}` =>
```
"Write an awesome description for your new site here. You can edit this line in _config.yml. It
will appear in your document head meta (for Google search results) and in your feed.xml site
description./n"
```
**after:** `{{ site.description }}` =>
```
"Write an awesome description for your new site here. You can edit this line in _config.yml. It
will appear in your document head meta (for Google search results) and in your feed.xml site
description."
```
> Ignore final newline in folded YAML string

- lib/jekyll/commands/doctor.rb
If a site does not provide an absolute URL in `site.url`, all sorts of wonky behavior can creep up, especially as sites rely more heavily on themes plugins that assume standard behavior.
To this end, I would like to add some simple URL checks to `jekyll doctor` to make sure that things are in good working order.
> Add URL checks to Doctor

- lib/jekyll/deprecator.rb
Mostly a personal preference, not sure how it affects overall performance
/cc @pathawks
> deprecator.rb: fix typo for --serve command

- lib/jekyll/commands/new.rb
Setting Jekyll to only explicitly install the latest version at runtime is bad form.
> Users should be installing patch versions.

- lib/jekyll/commands/serve/servlet.rb
To avoid having to re-implement the entire set_filename method, I instead extended `search_index_file` and temporarily mutate `res.filename`. Kinda hacky, so I tried to leave plenty of inline comments. (Also first time using ruby, so beware!)
For reference, here's the base class `search_index_file` [implementation](https://github.com/ruby/webrick/blob/3fb6a011/lib/webrick/httpservlet/filehandler.rb#L356-L363).
Feel free to checkout the commit message too.
> Fix serving files that clash with directories (#6222)

- lib/jekyll/reader.rb
Fixes the following error:
```text
Not a directory @ dir_chdir - /home/jekyll/src/_posts
```
> Reader#read_directories: guard against an entry not being a directory

- jekyll.gemspec
I realized from #6216 that our `runtime_dependency` `Liquid 4.0` has already [dropped support](https://rubygems.org/gems/liquid/versions/4.0.0) for Ruby Versions older than `2.1.0`. So there's no point in not following suit ourselves.
> Bump supported Ruby version to >= 2.1.0

- Gemfile
- Rakefile
- exe/jekyll
- jekyll.gemspec
- lib/jekyll.rb
- lib/jekyll/commands/new.rb
- lib/jekyll/commands/serve.rb
- script/console
- script/stackprof
- script/vendor-mimes
- test/helper.rb
- test/test_convertible.rb
- test/test_new_command.rb
> ".. with \_\_dir\_\_ we can restore order in the Universe."
> Define path with __dir__

- lib/jekyll/site.rb
```ruby
def print_stats
if @config["profile"]
puts @liquid_renderer.stats_table
end
end
```
Since `site.print_stats` *further runs* only if `@config["profile"]`, *I feel* it'd be better if the method is **called only in the special scenario.**
The drawback here is the duplicate `if` guard unchanged to prevent breaking downstream use of `site.print_stats` if any
> exit site.process sooner

- lib/jekyll/converters/markdown/kramdown_parser.rb
- test/test_kramdown.rb
Currently-released version of Jekyll uses default_proc to assign values for the kramdown config. `Kramdown::Document#initialize` calls `Options.merge` which does `Hash#each` over our hash which doesn't have symbolized keys. To fix this, we need to add the symbolized keys into the hash itself.
Fixes https://github.com/jekyll/jekyll/issues/5980.
> kramdown: symbolize keys in-place

- History.markdown
> Docs: fix links to issues in History.markdown

- lib/jekyll/filters/url_filters.rb
- test/test_filters.rb
We call `to_s` before we call `site.baseurl`, but we don't call `to_s` before we call `site.url`, meaning if `site.url` is something other than a string, things blow up.
The specific use case for the `to_s` here, other than users that set `url` to something else, is the ability to stub `site.url` with a Proc that would lazily calculate the URL when called.
> Call to_s on site.url before attempting to concatenate strings

- docs/_docs/pagination.md
The 'gems' configuration option has been renamed to 'plugins'. Reflect that in the documentation.
> Update deprecated gems key to plugins.

- features/rendering.feature
- lib/jekyll/liquid_renderer.rb
- lib/jekyll/tags/include.rb
Since Liquid 4 we can set the [`template_name` of a `Liquid::Error`](https://github.com/Shopify/liquid/blob/c582b86f16b64f5df890807603f57914099f3868/lib/liquid/errors.rb#L4). In addition to that we also specify in the `markup_context` that this error occured in an `included` file.
This removes the need for a custom `IncludeTagError`
fixes #6203 
Before (1):
```
Liquid Exception: Liquid syntax error (line 1): Unknown tag 'INVALID' in /Users/crunch/Code/jekyll/tmp/jekyll/_includes/invalid.html, included in index.html
```
After (1):
```
Liquid Exception: Liquid syntax error (/Users/crunch/Code/jekyll/tmp/jekyll/_includes/invalid.html line 1): Unknown tag 'INVALID' included in index.html
```
Before (2):
```
Liquid Exception: Liquid error (line 1): wrong number of arguments (given 1, expected …
```
> set `LiquidError#template_name` for errors in included file

- lib/theme_template/README.md.erb
Updating the README template for `jekyll new-theme`
> Update theme-template README to note 'assets' directory

- lib/jekyll/document.rb
Running `bundle exec rake site:generate` locally, this brings generation time from 16 seconds down to 8 seconds.
```text
done in 16.421 seconds.
```
```text
done in 8.685 seconds.
```
> Memoize the return value of Document#url

- lib/jekyll/static_file.rb
- test/test_static_file.rb
fixes https://github.com/jekyll/jekyll/issues/6259.
In order to make the output prettier and more expressive, it seems better to jsonify `StaticFileDrop` instead of `StaticFile` for the extra information. Delegation feels more natural to me in this situation. 
Open to suggestions and feedbacks is welcome, especially on ways to improve the test. Cheers!
---
`site | jsonify`
**Before:**
```
...
"static_files": [
"#Jekyll::StaticFile:0x005570s01cd1d0"
],
...
```
**After:**
```
...
"static_files": [
{
"name": "base.js",
"path": "/assets/base.js",
"basename": "base",
"extname": ".js",
...
}
],
...
```
> delegate `StaticFile#to_json` to `StaticFile#to_liquid`

- test/test_static_file.rb
Sometimes `Time.new` is not the same time as the creation of `@static_file` anymore. See #6232 for more information. Thanks to @MattSturgeon for noticing it!
cc: @jekyll/build
> make flakey test more robust

- lib/jekyll/configuration.rb
- lib/jekyll/drops/site_drop.rb
- test/test_configuration.rb
Resolves #6180 
Instead of having the array of custom configs removed, let it be available throughout current session.
Allow Jekyll Admin to determine which config file to re-read if not the default `_config.yml` or `_config.yaml`
/cc @jekyll/ecosystem @parkr
> Access custom config array throughout session

- lib/jekyll/drops/drop.rb
- test/test_drop.rb
In Liquid 4.0, `Liquid::VariableLookup#evaulate` [checks `input.key?` when it's evaluating](https://github.com/Shopify/liquid/blob/v4.0.0/lib/liquid/variable_lookup.rb#L44). If the `key` is `nil`, it throws the following error:
```text
Liquid Exception: nil is not a symbol nor a string in <template>
```
We should simply return `false` for `Drop#key?(nil)`.
> Fix Drop#key? so it can handle a nil argument

- docs/_docs/collections.md
I was unable to use custom links in collections until i dug up [this bit](https://github.com/jekyll/jekyll/blob/master/lib/jekyll/drops/url_drop.rb#L27) in the source code, and this a PR demonstrating a more clear explanation of the linked behavior in the source code. great project guys! lemme know what yall think of the contribution.
> Customizing url in collection elements clarified

- lib/jekyll/readers/data_reader.rb
- test/test_data_reader.rb
In #6256, I noticed that we had no tests whatsoever for DataReader.
We should definitely go back and ensure all our classes/modules are tested. Perhaps we can reorganize the test directory too, so the paths/filenames are predictable.
> Add a quick test for DataReader

- lib/jekyll/drops/drop.rb
- test/test_drop.rb
This backports #6281.
Conflicting files:
> Backport #6281 for v3.5.x: Fix Drop#key? so it can handle a nil argument

- script/backport-pr
Merge commit messages used to look like this:
```
Merge pull request #5983 from DirtyF/ruby-2.1
Merge pull request 5983
```
Now they look like this (since we started using squash):
```
Guard against type error in absolute url (#6280)
Merge pull request 6280
```
Looking for `Merge pull request #$pr` only gets the first. We need to look without the hash.
> script/backport-pr: commit message no longer includes the #

- lib/jekyll/filters/url_filters.rb
- test/test_filters.rb
> Backport to 3.5: Guard against type error in absolute url (#6280)

- docs/_docs/deployment-methods.md
Hi,
I just created my first automatic deployment using Jekyll and Git post-receive hook.
Thereby I spotted an error, which leads to situation like described [on StackOverflow](https://stackoverflow.com/q/44836330) (I had the same situation on a CentOS box).
Luckily the fix is quite easy, so I wrote a PR to save others research of an evening ^^
> Execute build command using bundle.

- lib/jekyll/document.rb
> Backport #6266 for v3.5.x: Memoize the return value of Document#url

- lib/jekyll/static_file.rb
- test/test_static_file.rb
> Backport #6273 for v3.5.x: delegate `StaticFile#to_json` to `StaticFile#to_liquid`

- lib/jekyll/reader.rb
> Backport #6226 for v3.5.x: Reader#read_directories: guard against an entry not being a directory

- lib/jekyll/converters/markdown/kramdown_parser.rb
- test/test_kramdown.rb
> Backport #6247 for v3.5.x: kramdown: symbolize keys in-place

- docs/_docs/continuous-integration/buddyworks.md
> name unification - buddy details

- .github/CODEOWNERS
- .github/ISSUE_TEMPLATE.md
- CODEOWNERS
Documentation from GitHub: https://help.github.com/articles/about-codeowners/
I'd like to see GitHub help us keep organized. This [new-ish feature](https://github.com/blog/2392-introducing-code-owners) will automatically request review from a given team if the files touched match anything declared in the CODEOWNERS file. Instead of a user having to /cc an affinity team, we should declaratively state who owns what and have GitHub require our review.
This is also an exercise in logically splitting up the codebase. The build team is pretty overloaded it looks like -- can we split anything out? 🤷‍♂️
> Add CODEOWNERS file to help automate reviews.

- lib/jekyll/log_adapter.rb
- test/helper.rb
- test/test_log_adapter.rb
- test/test_new_command.rb
- test/test_site.rb
This subsumes #6306 and fixes the bugs with that PR.
It also bails early for `debug`, `info`, `warn`, and `error` if the logger's log level is higher than the message's log level. In this case the logging writer will skip it, so it's best to skip it here. It reduces the number of strings we create and greatly reduces the size of the `messages` array. This fixes #6313.
> Allow `yield` to logger methods & bail early on no-op messages

- docs/_docs/plugins.md
- docs/_docs/resources.md
- docs/_docs/templates.md
> trim and relocate plugin info across docs

- docs/_config.yml
We can now use this by default.
> Plugins is the new gems

- docs/_docs/permalinks.md
From https://github.com/jekyll/jekyll/issues/6177#issuecomment-325160280 
Here's the updated version:
> VARIABLE | DESCRIPTION
> -- | --
> year | Year from the post's filename. May be overridden via the document’s date YAML front matter
> month | Month from the post's filename. May be overridden via the document’s date YAML front matter
> i_month | Month without leading zeros from the post's filename. May be overridden via the document’s date YAML front matter
> day | Day from the post's filename. May be overridden via the document’s date YAML front matter
> i_day | Day without leading zeros from the post's filename. May be overridden via the document’s date YAML front matter
> short_year | Year without the century from the post's filename. May be overridden via the document’s date YAML …
> Docs: post's date can be overriden in YAML front matter

- docs/_docs/variables.md
Add some more information regarding the special behavior of `site.url` when using `jekyll serve` in the `site.[CONFIGURATION_DATA]` section. See also: https://jekyllrb.com/news/#3-siteurl-is-set-by-the-development-server.
This brought up some confusion: https://github.com/mmistakes/hpstr-jekyll-theme/issues/167 and https://github.com/white-gecko/jekyll-rdf/issues/102
> Docs: `site.url` behavior on development and production environments

- docs/_docs/variables.md
I've found a typo introduced in #6270 
> Fix typo in site.url section of variables.md :-[

- .codeclimate.yml
Builds currently fail on codeclmate: https://codeclimate.com/github/jekyll/jekyll/builds
It's because default rubocop engine is 0.46 and we use 0.49 with new cops.
With default channel:
```sh
~/code/jekyll/jekyll
$ codeclimate analyze -e rubocop:rubocop-0-46
Starting analysis
Running rubocop: Done!
error: (CC::Analyzer::Engine::EngineFailure) engine rubocop:rubocop-0-46 failed with status 1 and stderr
...
```
When using corresponding channel:
```sh
~/code/jekyll/jekyll
$ codeclimate analyze -e rubocop:rubocop-0-49
Starting analysis
Running rubocop: Done!
Analysis complete! Found 0 issues.
```
> Fix builds on codeclimate

- benchmark/schwartzian_transform.rb
- lib/jekyll/filters.rb
Hey!
I was reading through the [`Enumerable#sort_by` documentation](https://ruby-doc.org/core-2.4.1/Enumerable.html#method-i-sort_by) and came across an interesting passage about how it gets its speed-up:
> A more efficient technique is to cache the sort keys (modification times in this case)
> before the sort. Perl users often call this approach a Schwartzian transform, after
> Randal Schwartz. We construct a temporary array, where each element is an array
> containing our sort key along with the filename. We sort this array, and then extract
> the filename from the result.
>
> This is exactly what sort_by does internally.
Whoa! A hidden gem: a recommendation about getting the most out of `#sort` by reducing object allocations. I'm in!
I tested it on the `_docs` collection in our …
> Use a Schwartzian transform with custom sorting

- docs/_docs/configuration.md
Before the fix no precedence took place because one configuration was for pages and the other was for posts
> Fix precedence docs

- lib/jekyll/drops/drop.rb
- test/test_drop.rb
A follow up to https://github.com/jekyll/jekyll/pull/6338 and discovered via https://github.com/jekyll/github-metadata/pull/112, the current logic for `Jekyll::Drops::Drop#key?` for mutable drops is to look for a mutated key, but then not to look for a native method or fallback data. Instead, Drops should look for a key in the mutated data, in native methods, AND in fallback data.
This PR updates the logic of `Drop#key?` and includes tests to ensure the method does what we expect it to going forward.
> Mutable drops should fallback to their own methods when a mutation isn't present

- lib/jekyll/readers/post_reader.rb
- test/test_site.rb
Instead of letting Liquid crash later in the build process IMHO we should just skip these files and inform the user.
**Before**:
**After**:
This fixes #5181
> skip adding binary files as posts

- docs/_docs/permalinks.md
The permalink documentation references `:y_day` in the `ordinal` built-in permalink style, but does not document it. This change adds documentation for `y_day`.
> Doc y_day in docs/permalinks

- .rubocop.yml
- Gemfile
- jekyll.gemspec
- lib/jekyll.rb
- lib/jekyll/commands/doctor.rb
- lib/jekyll/commands/serve/servlet.rb
- lib/jekyll/configuration.rb
- lib/jekyll/converters/markdown.rb
- lib/jekyll/converters/markdown/kramdown_parser.rb
- lib/jekyll/convertible.rb
- lib/jekyll/document.rb
- lib/jekyll/drops/collection_drop.rb
- lib/jekyll/drops/document_drop.rb
- lib/jekyll/drops/drop.rb
- lib/jekyll/drops/excerpt_drop.rb
- lib/jekyll/drops/jekyll_drop.rb
- lib/jekyll/drops/site_drop.rb
- lib/jekyll/drops/unified_payload_drop.rb
- lib/jekyll/drops/url_drop.rb
- lib/jekyll/reader.rb
- lib/jekyll/readers/collection_reader.rb
- lib/jekyll/renderer.rb
- lib/jekyll/site.rb
- lib/jekyll/tags/highlight.rb
- lib/jekyll/tags/include.rb
- lib/jekyll/tags/link.rb
- lib/jekyll/tags/post_url.rb
- test/test_ansi.rb
- test/test_utils.rb
> Bump rubocop to use `v0.50.x`

- docs/_sass/_style.scss
Fix an edge case when a list is used in a table:
> Docs: Style lists in tables

- features/rendering.feature
- lib/jekyll/convertible.rb
- lib/jekyll/renderer.rb
Continuing from #6172 
Resolves confusion reported in PR #6170 where-in users thought the feature added in #5933 applied to regular `Jekyll::Page` objects as well.
> Disable default layouts for Pages with a `layout: none` declaration

- jekyll.gemspec
Rouge got [recently updated to v3.0](https://github.com/jneen/rouge/pull/783).
The major version bump is due to https://github.com/jneen/rouge/pull/763 but doesn't impact our test suite.
> Upgrade to Rouge 3

- docs/_docs/collections.md
- docs/_docs/configuration.md
- lib/jekyll/collection.rb
- lib/jekyll/configuration.rb
Replaces https://github.com/jekyll/jekyll/pull/3723 for Jekyll v3.6 if we want.
User configures as:
```yaml
collections_dir: my_collections
```
Then we look in `my_collections/_pizza` for the `pizza` collection, and `my_collections/_lasagna` for the `lasagna` collection.
> Allow the user to set collections_dir to put all collections under one subdirectory

- docs/_docs/themes.md
Ref: Question at [Jekyll Talk](http://talk.jekyllrb.com/t/gem-jekyll-theme-awesome-instead-of-gem-install-jekyll-theme-awesome/1000) and another at [StackOverflow](https://stackoverflow.com/questions/46380722/jekyll-theme-could-not-be-found)
> Improve documentation for theme-gem installation

- docs/_sass/_pygments.scss
Since this is subjective, its going to take some inputs from multiple perspective..
Current:
> Fix diff syntax-highlighting

- Gemfile
- features/support/formatter.rb
- script/cucumber
Tests are passing but the `print_stats` method is now undefined.
```sh
undefined method `print_stats' for #<Jekyll::Cucumber::Formatter:0x007fa12cbeba48> (NoMethodError)
/Users/frank/code/jekyll/jekyll/features/support/formatter.rb:210:in `print_summary'
/Users/frank/code/jekyll/jekyll/features/support/formatter.rb:49:in `after_features'
```
Breaking change introduced in https://github.com/cucumber/cucumber-ruby/pull/999
> Upgrade to Cucumber 3.0

- docs/_docs/installation.md
- docs/_docs/upgrading.md
Promoting `bundler update` and adding the upgrade to minor versions.
> Docs: Update instructions

- docs/_sass/_style.scss
Proposing to add additional styling to indicate code-blocks with `sh` syntax-highlighting for added discernibility..
Additional benefits:
- This will allow us to easily detect which of the blocks have incorrectly highlighted as shell-syntax
- consistently use `sh` for shell-highlighting..
> Add special styling for code-blocks run in shell

- docs/_docs/installation.md
- docs/_docs/pages.md
- docs/_docs/permalinks.md
- docs/_docs/plugins.md
- docs/_docs/posts.md
- docs/_docs/quickstart.md
- docs/_docs/themes.md
- Remove `$` from code-blocks for easier copy-pasting
- Add correct syntax-highlighting where previously not present
- Correct erroneous syntax-highlighting markers based on context
> Fix code-block highlighting in docs

- docs/_docs/posts.md
I swear there is an archived issue that I found last week about this, but for the life of me, I can't find it now. However, I still think this is valuable. I put this together to show what's possible with just basic Jekyll.
Ninja edit:
This solves issue #6003
> Docs: Filtering Posts with categories, tags, or other variables

- docs/_docs/posts.md
Pre-formatted text was marked as html, and so the important example was left out.
> Fixes formatting on pre-formatted text.

- .github/CONTRIBUTING.markdown
- docs/_config.yml
- docs/_docs/collections.md
- docs/_docs/continuous-integration/circleci.md
- docs/_docs/continuous-integration/travis-ci.md
- docs/_docs/contributing.md
- docs/_docs/datafiles.md
- docs/_docs/frontmatter.md
- docs/_docs/github-pages.md
- docs/_docs/includes.md
- docs/_docs/index.md
- docs/_docs/pagination.md
- docs/_docs/plugins.md
- docs/_docs/posts.md
- docs/_docs/static_files.md
- docs/_docs/templates.md
- docs/_docs/themes.md
- docs/_docs/troubleshooting.md
- docs/_docs/upgrading/0-to-2.md
- docs/_docs/upgrading/2-to-3.md
- docs/_docs/usage.md
- docs/_docs/windows.md
- docs/_posts/2014-12-22-jekyll-2-5-3-released.markdown
- docs/_sass/_pygments.scss
- docs/_tutorials/convert-existing-site-to-jekyll.md
- docs/_tutorials/custom-404-page.md
- docs/_tutorials/navigation.md
- docs/_tutorials/orderofinterpretation.md
- docs/community/index.md
A mass review of the documentation addressing:
- Code blocks / raw tags uniformisation for better source readability
- highlight liquid rather than html in code blocks
- Tip: `jekyll-paginate-v2` for pagination
- Tip: `jekyll-livereload` for serve
- update Shopify Liquid Help URL
- remove obsolete `site.help_url`
> Docs: updates

- docs/_docs/collections.md
- `collections_dir` is a top-level config key
- use example collections referred to just immediately
Thanks to @lsrdg and @hnaseri for trying the unreleased feature out and consequently opening tickets at Jekyll Talk:
- Ticket 1: http://talk.jekyllrb.com/t/solved-listing-pages-of-a-collection/1011
- Ticket 2: http://talk.jekyllrb.com/t/how-all-collections-inside-one-subdirectory-works/1034
> Docs: Fix `collections_dir` example

- docs/_tutorials/navigation.md
In the "Navigation" tutorial page, numbering of Scenarios was messed up : There were two "Scenario 6". This PR renames the second "Scenario 6" to "Scenario 7" and the old "Scenario 7" to "Scenario 8".
> Docs: Renaming duplicate of "Scenario 6" to "Scenario 7"

- docs/_docs/collections.md
Following #6408 
Our Style Guide provide has a specific note type for unreleased features, let us make use of it.
Unreleased notes are not meant to embed entire code snippets, but that's OK the feature is still understandable.
> Docs: Mark `collection_dir` as unreleased

- lib/jekyll/liquid_renderer.rb
This avoids doing the `||=` check for an existing value when setting values for the per-file stats hash in the liquid renderer. It also gives us the flexibility to add new numerical values to this hash later without having to do the same `||=` check as we can just know that the starting value will be zero.
Discovered while I was investigating #6241
> Provide a better default hash for tracking liquid stats

- docs/_docs/configuration.md
- lib/jekyll/frontmatter_defaults.rb
- test/test_front_matter_defaults.rb
Same as #5854 
When this may be useful: when you have two different set of files (e.g. *.doc & *.pdf) in the same folder that requires different values used by Jekyll plugins or Jekyll itself.
Examples:
```
defaults:
-
scope:
path: "content/*.pdf"
values:
sitemap: false
-
scope:
path: "content/*.html"
values:
sitemap: true
```
or
```
defaults:
-
scope:
path: "offers/*/index.html"
values:
layout: offer
-
scope:
path: "offers/*/thank-you.html"
values:
sitemap: false
```
> Scope path glob
