script/test
test/loader.rb

Fix test script to be platform-independent

---

features/permalinks.feature
lib/jekyll/post.rb
test/test_post.rb

Reimplements #2921. It's a breaking change so punting until 3.0.
/cc @alfredxing

Make permalink parsing consistent with pages

---

lib/jekyll/frontmatter_defaults.rb

Fixed typo [ci skip]

---

site/_posts/2015-01-20-jekyll-meet-and-greet.markdown

@gjtorikian rocks.
/cc @benbalter @jglovier @jekyll/core 
Let me know if this looks good. :heart:

Add blog post about the meet up.

---

site/_posts/2015-01-24-jekyll-3-0-0-beta1-released.markdown

Add Jekyll 3.0.0.beta1 release post

---

lib/site_template/_sass/_layout.scss

See pull request #3329
(Unfortunately I [cannot reopen](http://stackoverflow.com/a/12838195/990356) the existing merged and closed pull request)

CSS refactoring - see pull request #3329

---

lib/jekyll/commands/build.rb

#3377
Thanks to https://github.com/jekyll/jekyll-watch/blob/master/lib/jekyll/watcher.rb and @parkr

Show time after initial generation

---

site/_docs/troubleshooting.md
site/_includes/primary-nav-items.html
site/_layouts/page.html
site/help/index.md

Add a jekyllrb.com/help page which elucidates places from which to get help

---

site/_docs/plugins.md

Deletion of a dash - between last entry of Tags and beginning of Collections.

Formatting adjustment

---

LICENSE

Update LICENSE to 2015.

---

benchmark/flat-map
lib/jekyll/commands/new.rb
site/_docs/usage.md
site/_posts/2013-10-28-jekyll-1-3-0-rc1-released.markdown
site/_posts/2013-12-09-jekyll-1-4-1-released.markdown
test/fixtures/broken_front_matter3.erb
test/source/+/%# +.md
test/source/_posts/2008-02-02-published.textile
test/source/deal.with.dots.html

Remove trailing whitespace

---

site/_layouts/docs.html
site/_sass/_font-awesome.scss
site/_sass/_style.scss

Created an "Improve this page" link for all the documentation headers. The
feature uses the fa-pencil icon of font awesome. Improvement over #3504(closed).
See issue #3495 for more information.

Implemented the "Improve this page" feature. #3495

---

site/_docs/plugins.md

Three plugin strategies are listed, but then only two were referenced in the following note. I've updated this doc so that all three are referenced.

Improve consistency in site/_docs/plugins.md

---

site/_docs/collections.md

Feel free to disregard if you prefer different phrasing.
Thanks for all your work on jekyll. :heart:

Fix grammar on collections docs warning

---

site/_docs/plugins.md

I wasn&rsquo;t sure where to add it, so I just added it to the bottom of the list.

Add Jekyll-Smartify plugin

---

lib/jekyll/configuration.rb
lib/jekyll/plugin_manager.rb

Fixes #3393 
Could you please try this out, @paulrobertlloyd?

Perform jekyll-paginate deprecation warning correctly.

---

site/_docs/plugins.md

Added a link to my **[liquid-md5](https://github.com/pathawks/liquid-md5)** filter plugin.

Added "liquid-md5" plugin

---

site/_docs/contributing.md

Shouldn't this reference the local subpath?

Update the subpath

---

site/_docs/plugins.md

Add a new "Tag": jekyll-files.

Add new "Tag" - jekyll-files.

---

bin/jekyll

bin/jekyll: with no args, exit with exit code 1

---

site/_docs/pagination.md

IRC question of confusion re: wording and meaning.

Clarify pagination works from within HTML files

---

Gemfile

Force minitest version

---

lib/jekyll/static_file.rb
site/_data/docs.yml
site/_docs/collections.md
site/_docs/static_files.md
site/_docs/variables.md
test/source/static_files.html
test/test_generated_site.rb
test/test_static_file.rb

also adds some documentation for them.

static files mtime liquid should return a Time obj

---

site/_docs/continuous-integration.md

travis relies on a Gemfile to be present.
see jekyll#3660 for the discussion.

added a mention on the Gemfile to complete the instructions

---

features/step_definitions/jekyll_steps.rb
features/support/env.rb

Per https://github.com/cucumber/cucumber/wiki/Using-MiniTest.
Handles the piece of #3670 that was unrelated.

features: Update the way we access Minitest assertions

---

features/collections.feature
lib/jekyll/site.rb

Not sure if this is going to break a lot of sites, but we've talk about it for a while.
Replaces #3349, fixes #2346.

Change access of collection in iteration.

---

site/_docs/troubleshooting.md

To me, it's still Mac OS X. Old habits die hard...

Use the proper names

---

site/_docs/plugins.md

New plugin to fetch content of remote files and include it right in your markdown file

Added remote_file_content tag plugin

---

site/_docs/sites.md

Added the Ozon website in the list of sites made by jekyll

Added new website in sites made by jekyll

---

site/_docs/resources.md

I moved my blog with an article about Jekyll to a new location and updated the resources page to reflect the change. Shouldn't need to change that again. Thanks again, @parkr, you're the bestest :heart:

New website again woo

---

site/_docs/pagination.md

- `pagination_path` to `paginate_path`

fixing typo on line 19 of pagination.md

---

test/test_front_matter_defaults.rb

fixing typo on line 31

---

lib/site_template/css/main.scss

There is a line that has an unclear code comment. I'm not entirely sure what the line is really supposed to imply but I made my best guess.
If that's not accurate please let me know and I can reword! :+1:

Fixed an unclear code comment

---

CONTRIBUTING.markdown
site/_docs/contributing.md

update contributing documentation to reflect workflow updates

---

CONDUCT.md
README.markdown

Add a Code of Conduct.

---

site/_docs/plugins.md

Jekyll views router plugin

---

lib/jekyll/commands/clean.rb

Add build options (fixes #3744)

---

site/_docs/sites.md

A week ago, I asked @parkr via email if he could add my site here (mostly because I thought it's too cheeky to just propose a pull request). But now he told me that it's better to just do it here:
I'm asking because I spend a huge amount of time and effort on making it great and usefully structured for people who're just getting started with Jekyll. Therefore it's also great as a forked starting-point, if you ask me. Besides keeping the code clean, I also spend much time on making the site as fast as possible. There's not much CSS in use, the HTML is clearly structured and I've did a lot for the performance.
There's also a lot of "include"-thinking happening for things like embedded Tweets, images or iFrames - which most people just inline in each post. When making a significant change, I …

Added another site for learning purposes

---

lib/jekyll/deprecator.rb

Abort if no subcommand.

---

lib/jekyll/collection.rb
lib/jekyll/document.rb
lib/jekyll/reader.rb
lib/jekyll/related_posts.rb
lib/jekyll/site.rb

Proxies calls to either #data or #docs, respectively. Deprecation warning is printed.
_Don't break, deprecate._

Add Document#method_missing and Collection#method_missing

---

lib/jekyll/tags/post_url.rb

post_url: fix access deprecation warning & fix deprecation msg

---

lib/jekyll/document.rb

Document: Only auto-generate the excerpt if it's not overridden

---

site/_posts/2015-10-26-jekyll-3-0-released.markdown

Add 3.0 release post.

---

site/_docs/assets.md

@perlun had some more ideas for how this should read...

updated to reflect further feedback on #4129

---

Gemfile
features/include_tag.feature
features/support/overview.rb

Allow use of Cucumber 2.1 or greater

---

site/_docs/sites.md

Page not found for this demo site

Removed example Roger Chapman site

---

site/_docs/configuration.md

Added configuration options for draft_posts to configuration docs.

Updated configuration docs

---

site/_docs/configuration.md
site/_docs/contributing.md
site/_docs/deployment-methods.md

I missed this one in #4046. I am ashamed 😐.

Typos and line wrapping

---

site/_docs/upgrading/2-to-3.md

I think @parkr wanted to link to the projects, just forgot to add the URLs.

Upgrading 2-3: Added missing links to Pygments.rb and Rouge

---

site/_docs/pages.md

Adding markdown examples to Pages

---

site/_docs/plugins.md

Add [jekyll-paginate-category](https://github.com/midnightSuyama/jekyll-paginate-category) plugin.

Add jekyll-paginate-category to plugins.md

---

lib/jekyll/drops/drop.rb

drops: provide #to_h to allow for hash introspection

---

lib/jekyll/drops/drop.rb
lib/jekyll/drops/unified_payload_drop.rb
lib/jekyll/utils.rb
test/test_utils.rb

Fixes #4287.
Thanks for finding this bug, @pathawks!

utils/drops: update Drop to support Utils.deep_merge_hashes

---

site/_docs/upgrading/2-to-3.md

Could not find documentation on issues with relative permalinks. Added what fixed it for me.

Added content on relative permalinks

---

History.markdown

Use `permalink` Front Matter variable for clean URLs

Add pro Tip to use front matter variable to create clean URLs

---

.travis.yml
Gemfile

Revert "Reorganize and cleanup the Gemfile, shorten required depends."

---

lib/jekyll/convertible.rb
lib/jekyll/errors.rb
test/fixtures/empty_permalink.erb
test/test_convertible.rb

Raise error on empty permalink

---

lib/jekyll/commands/build.rb

Disable auto-regeneration when running server detached

---

History.markdown
site/_docs/history.md
site/_posts/2016-01-20-jekyll-3-0-2-released.markdown

Adds release notes and such for v3.0.2.

Release :gem: v3.0.2

---

features/post_data.feature
lib/jekyll/document.rb
lib/jekyll/site.rb

This cherry-picks #4378 for `master`. It fixes #4375 on `master`.

Document: throw a useful error when an invalid date is given

---

site/_docs/plugins.md

Corrected the spelling of **building** in the description of the **generator-jekyllrb** plugin.

Minor spelling error

---

lib/jekyll/liquid_renderer/file.rb

LiquidRenderer#parse: parse with line numbers.

---

site/_docs/upgrading/2-to-3.md

upgrade notes: mention trailing slash in permalink; fixes #4440

---

lib/jekyll/document.rb

Document#<=>: protect against nil comparison in dates.

---

site/_docs/plugins.md

Remove broken link

---

site/help/index.md

Add note about upgrading documentation on jekyllrb.com/help/

---

site/_docs/upgrading/2-to-3.md

Add note about dates without timezones

---

lib/jekyll/document.rb
lib/jekyll/page.rb
test/source/_with.dots/mit.txt
test/source/contacts/humans.txt
test/test_collections.rb
test/test_document.rb
test/test_filters.rb
test/test_page.rb
test/test_site.rb

Fixes #4466. Targets v3.0.3. Needs a test.
/cc @jekyll/gh-pages

Fix extension weirdness with folders

---

site/_docs/plugins.md

https://github.com/juusaw/amp-jekyll

Added amp-jekyll plugin to plugins docs

---

ISSUE_TEMPLATE.md

What do you think of these questions? Based on https://github.com/benbalter/problem_child/issues/14
/cc @jekyll/core @benbalter

Add an issue template for new issues

---

site/_config.yml

@parkr @mojombo 
HTTPS is better! :smile:

Set url in _config.yml to https://

---

site/index.html

@parkr @mojombo 
HTTPS is better! :smile:

Set protocol of markdown website link to https://

---

README.markdown

Add fork link in README.markdown

---

README.markdown

Set all jekyllrb.com links and GitHub Pages link to https://

---

README.markdown

@parkr @mojombo 
(PS: Sorry about the spelling/typing mistake in the title.)

Add project maintainer profile links

---

site/help/index.md

Add Google search query to /docs/help/

---

CONTRIBUTING.markdown

Add fork link in CONTRIBUTING.markdown

---

lib/site_template/_sass/_base.scss

Site Template: Removed unnecessary nesting from `_base.scss`

---

lib/site_template/_includes/header.html

Added role="banner" to <header>

---

lib/site_template/_layouts/default.html

Changed main <div> to <main> and added aria-label="Content"

---

site/_docs/upgrading/2-to-3.md

Subdirectories of _posts are no longer categories

---

test/test_theme.rb

Fix invalid theme test

---

test/test_theme.rb

Apparently I didn't commit? o_O (#4654, #4595)
/cc @benbalter

Fix invalid theme test, really

---

.github/CONTRIBUTING.markdown

@parkr 
----
Because it's **`HTTPS`**! :smile: 
----
Yours,
[**Suriyaa Kudo**](https://github.com/SuriyaaKudoIsc) :octocat:

Set protocol of jekyllrb.com to HTTPS

---

site/help/index.md

@parkr 
----
**`HTTPS`** is for everybody better than *`HTTP`*!
----
Yours,
[**Suriyaa Kudo**](https://github.com/SuriyaaKudoIsc) :octocat:

Set protocol of Stack Overflow to HTTPS

---

README.markdown

@parkr 
----
Make the content in `License` section in the **`README.markdown`** file a little bit better. :smiley: 
----
Yours,
[**Suriyaa Kudo**](https://github.com/SuriyaaKudoIsc) :octocat:

Improved content in "License" section in README.markdown

---

site/_docs/configuration.md

Following the discussion on #4676
cc/ @jekyll/documentation

Documentation: future option also works for collections

---

site/_docs/resources.md

Thanks to @arturogh for pointing this out.

Use the correct URL, Fixes #4698

---

.github/CONTRIBUTING.markdown
site/_docs/contributing.md

Highlight the `script/` calls in the Contributing documentation

---

.github/CONTRIBUTING.markdown

Adding some full stop / period.

Small edits in .github/CONTRIBUTING.markdown

---

site/index.html

Switch second GitHub Pages link to HTTPS

---

site/_config.yml
site/_docs/continuous-integration.md
site/_docs/deployment-methods.md
site/_docs/installation.md
site/_docs/pages.md
site/_docs/posts.md
site/_docs/quickstart.md
site/_docs/structure.md
site/_docs/templates.md
site/_docs/troubleshooting.md
site/_docs/upgrading/0-to-2.md
site/_docs/upgrading/2-to-3.md
site/_docs/usage.md
site/_docs/windows.md
site/_includes/docs_option.html
site/_includes/docs_ul.html
site/_posts/2015-01-24-jekyll-3-0-0-beta1-released.markdown

site: use liquid & reduce some whitespace noise

---

jekyll.gemspec

```
Finished tests in 62.257612s, 9.9907 tests/s, 16.6887 assertions/s.
622 tests, 1039 assertions, 0 failures, 0 errors, 0 skips
```
```
196 scenarios (196 passed)
1606 steps (1606 passed)
2m15.323s
```
```
hulk@ci.envygeeks.io ~/projects/jekyll/jekyll/site (upgrade/update-colorator-to-1.0 *) % bundle exec jekyll b
Configuration file: /home/hulk/projects/jekyll/jekyll/site/_config.yml
Source: /home/hulk/projects/jekyll/jekyll/site
Destination: /home/hulk/projects/jekyll/jekyll/site/_site
Generating... done in 4.634 seconds.
Auto-regeneration: disabled. Use --watch to enable.
```

Update colorator dependency to v1.x

---

features/support/formatter.rb

Fixed a typo from indend to indent. Just making the code more readable.

Fixed a typo

---

lib/jekyll/drops/drop.rb
lib/jekyll/drops/excerpt_drop.rb
lib/jekyll/excerpt.rb
test/helper.rb
test/test_excerpt_drop.rb

Merge #4907 into **master**
#4911

Forward-port: Add ExcerptDrop and remove excerpt's ability to refer to itself in Liquid

---

features/layout_data.feature
lib/jekyll/convertible.rb
lib/jekyll/renderer.rb

Merge #4909 into **master**
#4911

From v3.1.4: Fix `{{ layout }}` oddities (proper inheritance & fixing overflow of old data)

---

.rubocop.yml
lib/jekyll/layout.rb
lib/jekyll/page.rb
lib/jekyll/plugin_manager.rb

Cherry picked commits from #4935 :+1:

Rubocop: cleanup for misc files

---

.rubocop.yml
lib/jekyll/entry_filter.rb

Rubocop: lib/jekyll/entry_filter.rb

---

.rubocop.yml
lib/jekyll/liquid_renderer.rb
lib/jekyll/liquid_renderer/table.rb

Rubocop: Liquid renderer

---

site/_docs/github-pages.md

I added a line to a blog post I wrote because it took me 3 days to figure it out.

Instructions on how to install github-gem on Windows

---

site/_docs/github-pages.md
site/_docs/windows.md

I already created a [pull request](https://github.com/jekyll/jekyll/pull/4975) for this topic but it was asked to include the instructions instead of linking them so I did that in this pull request. I also included the instructions for the installation of Jekyll.

Instructions on how to install github-gem on Windows (v2)

---

Gemfile
site/_config.yml
site/_posts/2016-06-03-update-on-jekyll-s-google-summer-of-code-projects.markdown

Two wonderful students are working on Jekyll as a part of Google Summer of Code! I thought we should tell people about it in this intro & teaser.
@jekyll/gsoc, what do you think? 😄

Add post about GSoC project

---

lib/jekyll/commands/doctor.rb

Fixes https://github.com/jekyll/jekyll-redirect-from/issues/50
/cc @akoeplinger @jekyll/ecosystem

Run Site#generate for 'jekyll doctor' to catch plugin issues

---

features/support/formatter.rb

This should help us understand where we can improve.
I think it takes around half a second just to boot the VM and load Jekyll :(

Add timings for each scenario in cucumber & print worst offenders

---

.rubocop.yml
lib/jekyll/configuration.rb

rubocop: lib/jekyll/configuration.rb

---

site/_docs/continuous-integration.md

As in html-proofer docs: https://github.com/gjtorikian/html-proofer

Updates html-proofer code

---

.codeclimate.yml
.rubocop.yml

Just for consistency.
https://github.com/jekyll/jekyll/pull/5116/files?w=1

Normalize yml files.

---

site/_docs/deployment-methods.md

Deleted both instances of "yourself" in the first sentence under "Self-managed web server".

Removed confusing word repetition.

---

site/_docs/windows.md

fixed typo

---

site/index.html

Minor edit:
Update homepage to sync with merge of #5258
\cc @jekyll/documentation

Update homepage to sync with merge of #5258

---

site/_docs/deployment-methods.md

Update url for Github repository with cartridge

Update url for OpenShift

---

site/_docs/themes.md

Fix https://github.com/jekyll/minima/issues/30
cc/ @jekyll/documentation

Explain how to copy a theme's files

---

lib/theme_template/gitignore.erb

add *.gem to have git ignore theme gems built by the user.

update gitignore template to ignore theme gems built by user

---

site/_docs/installation.md

Added a period to the end of the last sentence in the first paragraph, which was missing.

Add missing period to sentence in first paragraph.

---

site/_docs/templates.md

@benbalter @pathawks I can't *believe* I forgot this! Follow-up to #5399 for documentation.

Add documentation for relative_url and absolute_url

---

site/_config.yml

Fix `logo`: `https://jekyllrb.com/img/logo-2x.png`

Bugfix on logo in JSON-LD

---

site/_sass/_style.scss

Reference: https://css-tricks.com/inheriting-box-sizing-probably-slightly-better-best-practice/

Replace classic box-sizing reset with inheritance reset

---

site/_docs/deployment-methods.md

Remove jekyll-hook from deployment methods

---

script/proof

Update source in script/proof

---

.github/CONTRIBUTING.markdown

Fix broken links in CONTRIBUTING

---

docs/_docs/continuous-integration.md
docs/_docs/contributing.md
docs/_docs/github-pages.md
docs/_docs/maintaining/avoiding-burnout.md
docs/_docs/maintaining/becoming-a-maintainer.md
docs/_docs/maintaining/merging-a-pull-request.md
docs/_docs/maintaining/reviewing-a-pull-request.md
docs/_docs/maintaining/special-labels.md
docs/_docs/plugins.md

continuing #5544 
```
==> Proofing...
Running ["ImageCheck", "LinkCheck", "ScriptCheck"] on ./_site on *.html...
Checking 2257 external links...
Ran on 107 files!
HTML-Proofer finished successfully.
real	0m59.789s
user	0m34.478s
sys	0m4.103s
```

appease script/proof --disable-external

---

README.markdown

Update Core team list in the README file

---

Gemfile

Bump to rake 12.0

---

Gemfile

:robot:
- Reorder gems
- use double quotes

Rubocop Gemfile

---

lib/jekyll/filters.rb

As long as we are upgrading to Liquid 4, let's take advantage of some of the utility methods provided by Liquid.
In the long run, this should help our behavior and code more closely match that of Liquid core.
Note that this PR is against `liquid-4` rather than `master`.
#4362
* [`to_integer `](https://github.com/Shopify/liquid/blob/v4.0.0/lib/liquid/utils.rb#L36-L44)
* [`to_date`](https://github.com/Shopify/liquid/blob/v4.0.0/lib/liquid/utils.rb#L63-L81)
/cc @parkr

[liquid 4] Utils

---

docs/_docs/github-pages.md

The paragraph was repeated.  I picked the one with the formatting that I feel reads best.

Remove duplicate paragraph.

---

docs/_docs/themes.md

I've corrected a minor grammatical mistake which I happened to find when I was reading a document.

Fix a minor grammatical mistake on themes' document

---

.travis.yml

Bump ruby versions in travis.yml

Bump rubies we test against

---

Gemfile

Bump rdoc to v5.0

---

docs/_docs/plugins.md

A Jekyll plugin for dealing with money. Published as a RubyGem. Provides filter for formatting of money with I18n support. Intends to grow into something bigger.
https://github.com/jhabdas/jekyll-money

Got that diaper money?

---

docs/_docs/contributing.md

Minor subject/verb agreement: use plural “pull request**s**” to agree with verb form

Fix typo in contribution information

---

.travis.yml
lib/jekyll/document.rb
test/source/_posts/2017-2-5-i-dont-like-zeroes.md
test/test_generated_site.rb

Backport #5920 for v3.4.x: Allow abbreviated post dates

---

docs/_posts/2017-03-09-jekyll-3-4-2-released.markdown

This is the release post for v3.4.2. Thoughts?

Add v3.4.2 release post

---

docs/_data/tutorials.yml

following #5946 
/cc @jekyll/documentation @ashmaroli

add custom 404 to tutorial navigation

---

docs/_tutorials/index.md

Fix broken link

---

docs/_docs/continuous-integration/travis-ci.md

fix sentence in documentation

---

docs/_docs/posts.md

This is admittedly ambiguous--it would be grammatical either way--but a quick corpus search confirmed my intuition that "welcome change" is the normal wording (by about 40:1).

Typo fix (welcomed change -> welcome change).

---

lib/jekyll/collection.rb
lib/jekyll/entry_filter.rb
test/source/_methods/with.dots/.gitignore
test/source/_methods/with.dots/.htaccess
test/test_collections.rb

This PR fixes #6091
Before this dot-files were ignored when reading collection dir.

Read explicitly included dot-files in collections.

---

README.markdown

Make generic the reference to trouble with OSX/MacOS and update link from non-existent destination to generic destination.

Update reference to trouble with OS X/macOS

---

History.markdown

@parkr Is it a human error or a script to update somewhere?

Fix release date in History

---

.github/ISSUE_TEMPLATE.md

Ask to run `jekyll doctor` to check the config before posting an issue.
props @pathawks

Add jekyll doctor to GitHub Issue Template

---

docs/_docs/continuous-integration/buddyworks.md

Helpful if people don't like copying and pasting URLs :)

Linking the link

---

lib/jekyll/commands/new.rb

Strip unnecessary leading whitespace in template

---

docs/_posts/2017-06-14-jekyll-3-5-0-released.markdown

Fixes a small typo on the "Jekyll turns 3.5, oh my!" post text.

Fixes minor typo in post text

---

lib/jekyll/filters/url_filters.rb
test/test_filters.rb

This backports #6266.
Conflicting files:

Backport #6266 for v3.5.x: Memoize the return value of Document#url

---

docs/_docs/continuous-integration/index.md

name unification - application index

---

README.markdown

some minor changes: 
* link to Jekyll's philosophy
* contact a team captain in case of CoC enforcement

update Jekyll's README

---

.github/CONTRIBUTING.markdown
.github/SUPPORT.md

add SUPPORT file for GitHub

---

History.markdown

Some of the latest PRs weren't affected to the good category. My bad.
Note to self: Space matters for @jekyllbot.

Fix History

---

docs/_docs/deployment-methods.md
docs/_docs/resources.md

- Add  some integrations (Contentul, Snipcart, Algolia) to resources
- Add some more recent useful blog posts
- Start with modern continuous deployment methods 
- Add Netlify

Docs: updates

---

.travis.yml

Bump rubies on Travis

---

.github/CONTRIBUTING.markdown
docs/_docs/contributing.md

Thanks to @parkr for mentioning this!

add note to contributing docs about `script/console`

---

docs/_docs/permalinks.md

fix #6354 #6355 
props @Crunch09

Docs: Fix permalink example

---

lib/jekyll/commands/new.rb

ref: #5660 [comment by @pathawks ](https://github.com/jekyll/jekyll/pull/5660#issuecomment-331191402)
/cc @pathawks

Don't break if bundler is not installed

---

docs/_posts/2017-09-21-jekyll-3-6-0-released.markdown

Hey y'all! Let's get 3.6.0 out the door.
I'd like to also ask that this be my last minor release for a while. I'd like to give y'all the power to merge contributions you think are worthy and make releases without me. I have been at this for 4+ years and want to ensure the project outlives my involvement in it! I'd also like to give y'all the ability to add new committers by giving you the ability to add new people to various teams on the org. What do you think?
Thanks ❤️

Add Jekyll 3.6.0 release post

---

docs/_data/tutorials.yml
docs/_tutorials/video-walkthroughs.md

See https://github.com/jekyll/jekyll/pull/6385
Added a new tutorial on the [Tutorials Page](http://jekyllrb.com/tutorials/home/). Its a series of videos that walks the user through some of the core features of Jekyll.

Docs: Added new tutorial to tutorials section on docs

---

docs/_config.yml

Update list of files excluded from Docs site

---

docs/_docs/templates.md

Docs: Add a note about Liquid and syntax highlighting

---

docs/_docs/continuous-integration/buddyworks.md
docs/_docs/continuous-integration/circleci.md
docs/_docs/deployment-methods.md

- Correct a couple syntax highlighting declarations
- Change “our” to “their” in the docs for deploying with Aerobatic

Fix a few minor issues in the docs

---

lib/jekyll/site.rb

Remove parentheses around arguments to raise

---

docs/_docs/configuration.md

Here's the discussion about the time zone: https://talk.jekyllrb.com/t/post-doesnt-show-up-according-to-theirs-date

Default time zone depends upon server

---

docs/_docs/plugins.md

Added Premonition plugin to list of plugins

Added Premonition plugin to liste of plugins

---

docs/_posts/2018-02-12-meet-jekyll-s-new-lead-developer.markdown
docs/_posts/2018-02-19-meet-jekyll-s-new-lead-developer.markdown
docs/team/index.md

:tada: Welcome @oe as our new lead developer! :tada:

Say hello to Jekyll's New Lead Developer

---

docs/_docs/plugins.md

Add reference to Liquid to plugin docs

---

lib/jekyll/cleaner.rb
lib/jekyll/site.rb

Memoize helper methods in site-cleaner

---

docs/_docs/installation.md

This adds the missing 'and' between major updates ... detailed instructions.

Fixed Minor Grammar Issue

---

lib/jekyll/excerpt.rb
test/source/_posts/2018-01-28-closed-liquid-block-excerpt.markdown

Resolves: https://github.com/jekyll/jekyll/pull/6724#issuecomment-377794855
/cc @DirtyF

Handle liquid tags in excerpts robustly

---

docs/_docs/troubleshooting.md

Show how to fix extentions build error

add Arch Linux instalation troubleshoot

---

docs/_posts/2018-03-15-jekyll-3-8-0-released.markdown

Release post for v3.8.0

---

docs/_posts/2018-03-14-development-update.md

This should be merged after 3.8 is released and all neccessary requirements have been done. Feel free to suggest improvements!

Add 4.0 development post

---

lib/site_template/.gitignore

Add vendor folder to a newly installed site's .gitignore

---

History.markdown
features/collections.feature
lib/jekyll/collection.rb

Backport #6959

---

Gemfile

Resolves #6965
Tested on High Sierra, Ruby 2.5.1, all works fine

yajl-ruby update to v1.4.0

---

docs/_docs/configuration.md

Remove documentation for using Redcarpet

---

docs/_tutorials/custom-404-page.md

The "default" nginx configuration file is the file which has almost all of the server related configurations such as which port will the nginx server listens to, etc.

Updated nginx configuration for custom-404-page documentation

---

docs/_docs/pagination.md
docs/_docs/structure.md
docs/_docs/upgrading/2-to-3.md
docs/index.html

Textile is only supported through a converter plugin

---

docs/_docs/contributing.md

Made a change in a sentence from a passive to active voice.

proposed change for passive voice.

---

docs/_docs/plugins.md

CAT behaves like Unix' cat and includes the contents of any file into a post/page, see https://github.com/binfalse/jekyll-cat

added the CAT plugin to the plugin list

---

Gemfile

Update rubocop version

---

docs/_docs/drafts.md

Made it more clear that there shouldn't be a date in the filename. This was confusing to me as I thought it meant that there shouldn't be a date in the front matter. It took me awhile to figure out that I just needed to not put a date on the filename.

Clarify definition of 'draft'

---

docs/_docs/plugins.md

Listed the jekyll-target-blank plugin in plugins list.

---

CODE_OF_CONDUCT.markdown

REF: https://www.contributor-covenant.org/version/1/4/code-of-conduct

Updates to CODE OF CONDUCT  (v1.4.0)

---

docs/_docs/themes.md

Added instructions to view theme’s files under Linux

Instructions to view theme’s files under Linux

---

docs/_docs/deployment-methods.md

Add to  docs/_docs/deployment-methods.md info how to deploy using git pre-push hook.

Add info how to deploy using pre-push git hook

---

features/include_relative_tag.feature

Closes #7212 
Demonstrates that `include_relative` tag works fine with nested files

Add cucumber feature to test include_relative tag

---

docs/_docs/step-by-step/09-collections.md

Fix minor grammatical error in "Front matter defaults" section.

Fix minor grammatical error

---

docs/_docs/step-by-step/02-liquid.md

Made changes per suggestions from @DirtyF

clarified front matter requirement

---

docs/_docs/upgrading/3-to-4.md
lib/jekyll/liquid_renderer.rb
lib/jekyll/liquid_renderer/file.rb
lib/jekyll/tags/include.rb
lib/jekyll/tags/link.rb

Fixes #7135 
by caching parsed templates and then rendering those templates non-destructively

Optimize rendering Liquid templates

---

docs/_data/showcase.yml

**Add Isomer - Singapore Government Static Websites to showcase**
Hi friends!
I work for the Singapore Government Technology Agency, and we're powering our government informational websites with Jekyll + GitHub Pages. We call our project Isomer; our main site is at https://isomer.gov.sg/ and one of the sites on Isomer is https://www.hlb.gov.sg/. We thought it'd be cool to submit our site to the showcase! 😃

Add Isomer to showcase

---

docs/_docs/step-by-step/07-assets.md

It wouldn't work for me without one, I am new to Sass so I could be missing something :)

Added missing semicolon

---

README.markdown

Add a link to Giraffe Academy's tutorial

---

docs/_docs/step-by-step/07-assets.md

"straight forward" -> "straightforward"

grammar correction

---

docs/_docs/liquid/filters.md

Co-Authored-By: Pat Hawks <pat@pathawks.com>
Following https://github.com/jekyll/jekyll/issues/7331#issuecomment-432442333

docs: list all standard liquid filters

---

lib/jekyll/excerpt.rb
test/source/_posts/2018-01-28-closed-liquid-block-excerpt.markdown
test/source/_posts/2018-01-28-open-liquid-block-excerpt.markdown
test/test_excerpt.rb

Backport #7250 to 3.8.x

---

Gemfile

Upgrade liquid-c to v4.0

---

docs/pages/resources.md

Updated Siteleaf to match it's official name.
Remove Contentful because the link is broken and they no longer list Jekyll under their ecosystem page.

Fix content management section

---

docs/_docs/installation/ubuntu.md

I've adjusted the documentation (if it's a feature or enhancement)
Apply Official Guide Documents
https://www.ruby-lang.org/en/documentation/installation/#apt

Apply ruby official guide documents

---

docs/pages/team.md

Add @ashmaroli to Core Team listing

---

Gemfile
test/test_configuration.rb
test/test_document.rb
test/test_front_matter_defaults.rb
test/test_static_file.rb

Just some very minor corrections required in test-files

Bump RuboCop to v0.61.x

---

docs/_docs/permalinks.md

Fix grammatical error in permalinks.md

---

docs/_data/jekyll_variables.yml

adds something to the tags table for `{{ page.collection }}`.
https://github.com/jekyll/jekyll/issues/7415
none.

Include docs for `{{ page.collection }}`

---

Gemfile

https://github.com/rubocop-hq/rubocop/releases/tag/v0.62.0
Resolves #7447

Bump RuboCop to v0.62.x

---

docs/_docs/step-by-step/01-setup.md

there's ➡️ there are.
Fixed a minor grammatical error in the docs.

Fixed grammar

---

Gemfile

Update rubocop to ~> 0.63.0
Fixes #7480
Fixes #7490

Update rubocop to ~> 0.63.1

---

docs/_docs/step-by-step/04-layouts.md
docs/_docs/step-by-step/05-includes.md

Minor typo and punctuation fixes.
Minor typo and punctuation fixes.

Minor doc fixes

---

docs/_docs/deployment/third-party.md

Added hosting with AWS Amplify to the docs.

Hosting with AWS Amplify

---

docs/_tutorials/convert-existing-site-to-jekyll.md

Fix typo in tutorial for converting existing site

---

docs/pages/resources.md

Added formX to list of form-backend service providers

Added formX to form-backend resources

---

README.markdown

Fix Wiki link in README.markdown

---

docs/_docs/installation/macos.md

These are just three very minor edits to the [Jekyll on macOS](https://jekyllrb.com/docs/installation/macos/) page (with at least one of them being necessary!).

Minor typographical suggestions

---

features/post_url_tag.feature

Cucumber feature will let us (and future devs) easily track the various behavior surrounding the tag
Is there any other known usage I've not listed here?

Add a Cucumber feature for post_url tag

---

docs/pages/resources.md

I added [Statictastic](https://www.statictastic.com) to the list of resources in the documentation.

Adds Statictastic to the list of resources

---

docs/_docs/pagination.md

Current code produces wrong link space.
This patch fixes the issue.

Fix link space

---

docs/pages/resources.md

Added Formspark to the form resources.

Added Formspark to form resources

---

lib/jekyll/liquid_renderer/table.rb

This is an 🙋 enhancement.
Generate a footer row showing the "sum total" of the values in a column of the table output by running `jekyll build --profile`
```
Filename                                                    | Count |     Bytes |   Time
------------------------------------------------------------+-------+-----------+-------
_layouts/default.html                                       |   177 |  4521.18K |  4.568
_includes/top.html                                          |   178 |   571.12K |  2.828
_layouts/docs.html                                          |    74 |  1346.96K |  2.530
_includes/docs_contents_mobile.html                         |    84 |   248.80K |  2.031
_includes/header.html                                       |   177 |   247.20K |  0.782
_layouts/news.html …
```

Generate a "TOTAL" row for build-profile table

---

docs/_docs/datafiles.md

Add TSV in data file doc, which is actually already supported.

Doc: Data file section adds TSV

---

docs/_docs/contributing.md

In line 96, changed "Interesting" to "Interested"
I was reading the contributing guidance and noticed a small grammar typo. I am updating the first word in the following sentence from "Interesting" to "Interested in submitting a pull request? Awesome. Read on. There's a few common gotchas that we'd love to help you avoid."
I looked at other issues/PRs and didn't see anything related. Apologies if I missed something (my first contribution...ever). Let me know if any other info is needed. Thanks!

Update small typo in contributing.md

---

lib/jekyll/site.rb

Backport #7684 for v3.8.x: Revert memoizing Site#docs_to_write and refactor #documents

---

docs/_docs/ruby-101.md

Github -> GitHub
Just a tiny little typo fix.
This is not related to any GitHub issues.

Fix typo from 'Github' to 'GitHub'

---

docs/_posts/2019-03-18-jekyll-4-0-0-pre-alpha1-released.markdown

Just a tiny little typo fix in a blog post.
This is not related to any GitHub issues.

Typo fix in a blog post

---

.rubocop.yml
lib/jekyll/excerpt.rb
lib/jekyll/filters.rb
lib/jekyll/readers/post_reader.rb

[Fix current CI errors](https://travis-ci.org/jekyll/jekyll/jobs/567204636#L465)

Fix: rubocop offenses

---

docs/pages/resources.md

Added Bonsai.io to search options
☑️
The team at Bonsai.io created [Searchyll][https://github.com/omc/searchyll], which makes it possible to use Elasticsearch with Jekyll. Bonsai Search is a fully managed Elasticsearch host. I've added Bonsai Search under "Resources" on your website, and linked to the Jekyll Quickstart Guide. If you have any questions about this integration, I can connect you to the developers who built this.

Added Bonsai Search

---

docs/pages/resources.md

Added another Form backend as a service platform.

Adding SmartForms as Forms service

---

lib/jekyll/filters.rb

Test number_like regex on stringified property

---

docs/_data/jekyllconf-talks.yml

Update JekyllConf page with 2019 talks

---

docs/pages/resources.md

Adding link to memberspace.com in the /resources > E-commerce section. MemberSpace is a 3rd party tool which allows Jekyll sites to have membership & paywall functionality. E.g. subscriptions, gated content, user accounts, etc. without forcing visitors to leave the website. MemberSpace is actually a Jekyll site itself :)

link for memberships

---

docs/_docs/deployment/third-party.md

Fix broken link in 3rd Party section.
> Read this [step-by-step guide](https://medium.com/@jameshamann/deploy-your-jekyll-site-using-aws-amplify-with-only-a-few-clicks-8f3dd8f26112) to deploy and host your Jekyll site on AWS Amplify.
The link now correctly points to an article that explains how to deploy and host a Jekyll site on AWS Amplify.
Resolves #7855

Update third-party.md - Fix broken link

---

docs/_data/jekyll_variables.yml

> https://jekyllrb.com/docs/variables/

Replace `` with html tag

---

docs/_docs/datafiles.md

Update link to the "Liquid templating system"

---

Gemfile

Update dependency constraint to allow RuboCop v0.76

---

script/travis

Use bash executable consistently

---

docs/_docs/step-by-step/09-collections.md

Change `affect` to `effect` in the collections docs

---

.rubocop.yml
Gemfile
lib/jekyll/excerpt.rb
test/test_liquid_renderer.rb

Closes #7963 
Closes #7939 
Closes #7911

Bump RuboCop to v0.79.x

---

docs/_docs/index.md

Corrected typo 

---

docs/_docs/installation/macos.md

Correct a sentence in the documentation

---

docs/_docs/plugins/filters.md

Correct documentation of filters

---

docs/_docs/index.md

I fixed a sentence that had a grammar error in it.
Not related to an issue number.

Fix English grammar error.

---

test/test_kramdown.rb

This is an attempt to reduce the flakiness of our `test/test_kramdown.rb`

Update unit tests for Kramdown-based converter

---

docs/_config.yml
docs/_tutorials/cache-api.md
docs/_tutorials/convert-site-to-jekyll.md
docs/_tutorials/custom-404-page.md
docs/_tutorials/index.md
docs/_tutorials/navigation.md
docs/_tutorials/orderofinterpretation.md
docs/_tutorials/using-jekyll-with-bundler.md
docs/_tutorials/video-walkthroughs.md

Replace repetition with front matter defaults

Add default front matter for tutorials collection

---

.travis.yml

Use the latest available versions.

Bump Ruby versions on Travis builds

---

docs/_data/tutorials.yml
docs/_tutorials/csv-to-table.md

Added tutorial and updated tutorial navigation list.
Resolves #8086

Create CSV to table tutorial

---

docs/_docs/installation/other-linux.md

Add help about Gentoo/Linux

---

docs/_docs/deployment/third-party.md

KeyCDN added to third party site (documentation).
The newly added documentation links to the tutorial from KeyCDN on how to run a Jekyll website with a CDN.

Update documentation on third party site

---

docs/_docs/index.md

Added note about OS specific installation instructions.

---

features/collections.feature
lib/jekyll/static_file.rb
test/source/_methods/extensionless_static_file

Add static file's basename to its url_placeholder
This backports be70c3e to 4.0-stable

Backport #7908 for v4.0.x

---

lib/jekyll/entry_filter.rb
test/test_entry_filter.rb

`include` in the configuration file should include directory when trailing slash is present, e.g.  
```
include:
- _pages/
```
should include the directory `_pages/` if exists.   
The current behavior in the `master` is that including `_pages` will include the directory while `_pages/` does not.  
This PR check that `_pages/` matches a directory named `_pages` but not file.
Resolves #7951

Config include trailing slash

---

docs/_docs/plugins/your-first-plugin.md

🔦Add an example for hooks section.

docs: update your-first-plugin.md

---

lib/jekyll/filters.rb
test/test_filters.rb

Update item_property to recognize integers
This backports eb81dc0 to 4.0-stable

Backport #7878 for v4.0.x

---

docs/_docs/continuous-integration/github-actions.md

Fix typo in documentation on GitHub Actions

---

.github/workflows/ci.yml

Test caching bundler dependencies to speed up GitHub Actions builds.

chore(ci): cache dependencies

---

docs/_docs/usage.md

After spending hours trying to figure out a solution to my issue, I stumbled upon [a SO answer](https://stackoverflow.com/a/48292461/205696) that mentions the `--config` flag, which is paramount to solving my use-case.
Then I found it is hidden away in the documentation, as the second section under *Configuration Options*, that starts out with explaining options in `_config.yml`.
I expected all CLI commands, options and arguments to be documented under *Command Line Usage* or via `jekyll --help`, like most other terminal programs. In lieu of that I have tried my best to ease the discovery of the CLI commands (in their entirety).
It is unfortunate that CLI usage is split in the documentation between CLI usage and `_config.yml` options but to fix that, I …

Ease discovery of CLI commands (in their entirety)

---

docs/_docs/configuration/markdown.md

Currrently no examples on how to use kramdown options.
Added an example to show how to add options. 
Related to this [issue](https://github.com/jekyll/jekyll-docs/issues/25)

Added example usage of options.

---

docs/_docs/deployment/third-party.md

This is a 🔦 documentation change
- The test suite passes locally (run `script/cibuild` to verify this)
add 21YunBox for deployment.

docs: add 21yunbox for deployment

---

docs/_data/showcase.yml

I changed the name that was SketchApp to Sketch.
:)

Including correct Sketch website

---

docs/_docs/configuration/liquid.md

Fix missing yaml front matter colon and adjust/add clarifying language.

Fix missing yaml front matter colon and adjust/add clarifying language.

---

docs/_docs/step-by-step/10-deployment.md

Corrected typo / grammatical error in the docs. "There's three" (short for "There is three") is bad English, it should be "There are three".

correct typo

---

docs/_docs/deployment/third-party.md

Netlify has posted a newer version of their getting started with Jekyll guide.
The new guide uses Jekyll 4.0.0 and has simper/less text in the guide.
This pull-request changes the link, so that it points to the newer guide.

Update link to Netlify step-by-step guide

---

docs/_docs/collections.md

Update pointer to special permalink variables for collections

Update pointer to special permalink variables for collections

---

Gemfile

This is a project maintenance.
Update cucumber gem from version 3.0 to 4.1.0
Closes #8276
Closes #8263
Closes #8226

Update cucumber gem to version 4.1

---

docs/pages/resources.md

Thanks!
Adds Formcake to the form section

Add Formcake to forms section

---

docs/_docs/ruby-101.md

add punctuation

---

jekyll.gemspec

https://github.com/advisories/GHSA-mqm2-cgpr-p4m6
Fix #8348

fix: security bump

---

docs/_docs/configuration/default.md

- Added a `note info` div to clarify CWD vs site source for dir keys.
- Added an inline comment to plugins_dir key to clarify load order in array of strings.
Resolves #8314

Update default.md with info requested in #8314

---

docs/_docs/configuration/options.md
docs/_docs/plugins.md

Change `Safe` option description to improve clarity and specificity. 
Resolves #8321

Clarify description of `safe` option

---

docs/_data/docs_nav.yml
docs/_docs/community/community.md
docs/_docs/index.md
docs/_docs/installation.md
docs/_docs/installation/macos.md
docs/_docs/installation/other-linux.md
docs/_docs/installation/ubuntu.md
docs/_docs/installation/windows.md
docs/_docs/ruby-101.md

Reviewed the docs in Getting Started including OS-specific instructions and made updates to content.
Does not update the Step By Step Tutorial yet. 
Includes the following: 
- Add CentOS/RHEL instructions for installing Ruby/GCC/Make
- Update content for consistency and clarity
- Add notes where appropriate

Docs Review: Getting Started

---

Gemfile

This is a project maintenance.
Update cucumber gem from version 4.1 to 5.1.2.
Closes #8402
Closes #8370

Update cucumber gem version to 5.1.2

---

docs/_docs/plugins/your-first-plugin.md

Fix typo in documentation

---

docs/_tutorials/convert-site-to-jekyll.md

Easy navigation and easy reading for others.

Fix broken url in docs

---

docs/_docs/step-by-step/10-deployment.md

Document update based on my experience using the tutorial.
Document update based on my experience using the tutorial.
I also recommend adding the attached screen capture directly where I updated the text.

docs: init project

---

features/site_configuration.feature
lib/jekyll/reader.rb

Before reading explicitly included files, Jekyll should check if the file has been read-in already.
Resolves #8461

Generate items from `site.include` list only once

---

features/rendering.feature

This is to test and confirm that Liquid expressions are only evaluated superficially.

Test that Liquid expressions are not deeply evaled

---

docs/_docs/plugins/hooks.md
docs/_sass/_style.scss

Improve documentation on Hooks in Jekyll

---

docs/pages/resources.md

Add Arengu to form services list documentation

Add Arengu to form services list documentation

---

docs/_docs/deployment/third-party.md

- Update the URL for 21yunbox documentation. 
- Sort the deployment list in alphabetical number so number rank first then a thru z.

docs: update deployment docs for 21yunbox

---

docs/_docs/installation/windows.md

typo - do instead of don't

---

docs/_docs/datafiles.md

Add .tsv to the list of supported file extensions

Document support for TSV files consistently

---

docs/_docs/collections.md

Fix i.e. typos in collections.md

---

docs/_docs/upgrading/3-to-4.md

Fix typo in migrating from 3.0 to 4.0 page

---

docs/_data/jekyll_filters.yml

Hi :-)
This is my first PR
I've done my best to make it useful and easy to review
and i may have missed something
i'm happy to rework my PR if necessary
Clarify documentation for relative_url and absolute_url filters
While learning Jekyll, it took me a long time to figure out that the input of relative_url and absolute_url were file paths (and the filter names refer to the output of the filter), so i'm trying to clarify that in the docs for others

docs: Clarify relative_url and absolute_url filters

---

docs/_docs/installation/macos.md

Updated the macOS install documentation for Big Sur.
Just a minor update :smile:
PS - Thank you for this fantastic project!

Update macOS install docs for Big Sur

---

docs/_docs/community/community.md

Update community.md to fix up IRC reference link

---

docs/_docs/contributing.md

Fixed typo.
specfic -> specific

Fix typo in contributing.md

---

docs/_docs/continuous-integration/razorops.md
docs/_docs/deployment/automated.md

Razorops cicd added

---

docs/_docs/deployment/third-party.md

Just corrected a typo word: Jekull to Jekyll.

Correct a typo for a word

---

docs/_docs/community/community.md

Adjust by adding Libera, and continue Freenode availability.

IRC networks - Libera, Freenode

---

README.markdown

- Change HTML tag to Markdown
- Change Spaces Warning

Linting README.markdown

---

.github/actions/spelling/expect.txt
docs/_docs/deployment/third-party.md

docs: add Layer0 deployment guide

---

lib/theme_template/README.md.erb

In **Contributing** section:
1. The code of conduct link generated by `jekyll new-theme` looks outdated, so I updated the [link](https://www.contributor-covenant.org/).
2. Set proper repo name.

docs: Update REAMDE generated by `jekyll new-theme`

---

docs/_docs/plugins/installation.md

- This is a 🔦 documentation change. 
Rewrite to reduce gotchas for a novice user working with plugins in their site
Closes #8917 
/cc @EmilySeville7cfg to provide feedback.
[Preview URL](https://deploy-preview-8921--jekyllrb.netlify.app/docs/plugins/installation/)

Rewrite documentation on installing plugins

---

.github/ISSUE_TEMPLATE/bug_report.yml

Minor: fix typo in `github-pages` command
(kind of 😄 )
Fixed minor typo in bug report template
Just stumbled on this.

Fix typo in Bug Report template

---

README.markdown

It appears that hakiri is [shutting down](https://hakiri.io/sunsetting-hakiri) next month. Switch to @Dependabot.
Closes #8945

Remove references to EOL hakiri.io service

---

docs/_data/config_options/build.yml
docs/_data/config_options/global.yml
docs/_data/config_options/serve.yml

Change `Word Word` to `word word` in `_data/config_options/`.

Enhance option's case for Jekyll configuration

---

docs/_data/config_options/build.yml

Provide `quiet`/`verbose` from default config.

Add quiet/verbose options

---

docs/_docs/permalinks.md

I added the phrase "Preserves case from the source." to the description of "title" (in 2 places) to make this behaviour more clear.
Related to #4100

Update permalinks.md 

---

docs/_docs/installation/windows.md

I propose to install everything as I have no idea what shall be installed.
You have these options:
- MSYS2
- MSYS2 and MINGW development toolchain
By proposing to install everything, I hope to create a discussion in case people know what to choose at this step.
I chose the development toolchain so that compilation can take place.
Is that correct?

Windows: describe which option to choose

---

.rubocop.yml
Gemfile

This is a 🔨 code refactoring. 
Updated rubocop to 1.32.
Closes #9082
Closes #9085
Closes #9088
Closes #9090

Bump rubocop to 1.32

---

lib/jekyll/liquid_renderer/table.rb
lib/jekyll/profiler.rb

This backports 82bb271 to 4.3-stable

Backport #9186 for v4.3.x: Remove totals in profile table properly

---

lib/jekyll/site.rb

This backports b2891a4 to 4.3-stable

Backport #9187 for v4.3.x: Optimize `Site#each_site_file`

---

Gemfile

Updated the Gemfile to bump the version of Rubocop to 1.50.x
Closes  #9332
Closes #9343
Closes #9345
Closes #9349 
Closes #9365
Closes #9378

Bump rubocop version to 1.52.x

---

docs/_docs/deployment/third-party.md
docs/_docs/plugins/hooks.md
docs/pages/resources.md

- In hooks article, change (After converting the post content, but before rendering the post layout) to (... post layout.).
- In 3rd party deployment article, change (More documentation can here found here.) to (... be found here.).
- In resources article, (is essentially an added "build"step between you and the browser...) to (... "build" step...).
This pull request fixes three typo in documentations.

Typo fix - update to hooks and 3rd party deployment and one other article

---

docs/_docs/pages.md

Specify that markdown files should have front matter, for them to be processed as pages, in case someone is confused why their page isn't showing properly.
A user just wanting to host a folder of markdown files with a static site may think that 'pages' is the simplest option. Without the docs mentioning front matter, they might not realise that front matter is necessary for those pages to turn into html.

Mention the front matter requirement in pages.md

---

docs/_docs/liquid/tags.md
docs/_docs/upgrading/2-to-3.md

Updated links to Rouge to point to the GitHub Repo rather than the website which has been down since January.
Closes #9340 
Works around https://github.com/rouge-ruby/rouge/issues/1917

Point to the Rouge GitHub repo rather than broken website

---

docs/pages/resources.md

Add builtatlightspeed.com to themes resources. 
This resource lists over 700 Jekyll themes. It is definitely the largest and most up-to-date directory of Jekyll themes available. I believe it is a useful resource for the community and is appropriate to add to this section of the Jekyll docs.

Add new theme directory to themes resources

---

docs/_docs/deployment/third-party.md

It adds an additional 3rd party provider to the deployment documentation.

Adds Kinsta to 3rd party deployments

---

Gemfile
lib/jekyll/drops/drop.rb

Bumping Rubocop
There are several open issues related to this bump.
Fixes https://github.com/jekyll/jekyll/issues/9454
Fixes https://github.com/jekyll/jekyll/issues/9444
Fixes https://github.com/jekyll/jekyll/issues/9436
Fixes https://github.com/jekyll/jekyll/issues/9429
Fixes https://github.com/jekyll/jekyll/issues/9421

Bump Rubocop to 1.56.4

---

docs/_data/showcase.yml

When browsing the showcase, there was a broken link. While I was at it, I figured it was worth checking some other links too:
* Replace links to where they redirect if a redirect occurs. (Excluding localization.)
* Remove locale from the URL, so it uses the preferred language of the user.
* Add a trailing slash on base URLs for consistency.
* Remove dead links.

chore: update showcases

---

docs/pages/resources.md

Fix broken links for several Jekyll integrations

---

jekyll.gemspec

We haven't really supported Ruby 2.5 in quite some time so let's codify that in our gemspec.
Closes #9160
Closes #9524

Bump the minimum ruby version to 2.7

---

docs/_includes/search/script.html

deferring the docsearch script is important. add it back. should make site search work again.
Closes #9528

Make site search work again

---

test/test_collections.rb
test/test_configuration.rb
test/test_document.rb
test/test_excerpt.rb
test/test_excerpt_drop.rb
test/test_filters.rb
test/test_utils.rb

Fix the style check actions run being red all the time.

Correct rubocop lint errors

---

.github/workflows/ci.yml

This is maintenance PR to keep CI green 💚 .
This change keeps us using the same JRuby release series, 9.4.
Release blog post:
https://www.jruby.org/2024/07/02/jruby-9-4-8-0.html
Extracted from another PR. #9614
Details:
<details>
<summary>Error output in JRuby 9.4.0.0, what CI looked like before this change</summary>
```
+ ruby -S bundle exec rake TESTOPTS=--profile test
rake aborted!
LoadError: load error: /home/runner/work/jekyll/jekyll/vendor/bundle/jruby/3.1.0/gems/csv-3.3.0/lib/csv/parser -- java.lang.NoSuchMethodError: 'org.joni.Region org.joni.Region.newRegion(int, int)'
/home/runner/work/jekyll/jekyll/vendor/bundle/jruby/3.1.0/gems/csv-3.3.0/lib/csv.rb:98:in `require_relative'
/home/runner/work/jekyll/jekyll/vendor/bundle/jruby/3.1.0/gems/csv-3.3.0/lib/csv.rb:98:in `<main>' …
```

CI: Use JRuby 9.4.8.0

---

docs/_data/jekyll_variables.yml
docs/_docs/variables.md

Document available keys of the global Liquid variable `{{ jekyll }}`
Resolves #9652

Document keys of global variable `{{ jekyll }}`

---

docs/_config.yml
docs/_includes/improve_doc_link.html
docs/_layouts/docs.html
docs/_layouts/page.html
docs/_layouts/step.html
docs/_layouts/tutorials.html
docs/_sass/_style.scss

Extract repeating HTML for `Improve this page` link into an include_file / inclusion.

Extract markup for `Improve this page` into an inclusion

---

docs/_docs/continuous-integration/github-actions.md
docs/_docs/plugins/installation.md

Migration from standard flow can be fraught with surprises if one keeps using a GitHub-hosted theme. This PR smooths the way by pointing out the necessary configurations.

Improve docs around using GitHub Actions to build and deploy Jekyll sites

---

docs/_docs/deployment/third-party.md

Fix "Get started with Jekyll" URL on [GitLab Pages section](https://jekyllrb.com/docs/deployment/third-party/#gitlab-pages).

Fix broken link on third-party.md

---

.github/workflows/ci.yml
Gemfile
features/support/formatter.rb
script/cucumber

This backports 2db7db7 to 4.3-stable

Backport #9747 for v4.3.x: Bump cucumber to v9
