docs/_docs/collections.md

This information was originally given by @mmistakes in https://github.com/jekyll/jekyll/issues/5023#issuecomment-227150225

Explain how to override output collection index page

---

docs/_docs/plugins.md

Adds my personal plugin, github-cards, on the list.
Github-cards allow you to create Repo cards to quick-link your viewers to the repo in a nice graphical way.

Added github-cards to the list of plugins

---

README.markdown

fix #6428
@pup you seem to be the right person to handle this, maybe we should add another team mate to second you?

Docs: CoC violation correspondants

---

.github/first-timers-issue-template.md
.github/first-timers.yml

From the discussion at https://github.com/jekyll/community/issues/6, we have decided to add [First Timers bot](https://github.com/apps/first-timers) to this repository. The reason we are doing this is to help on-board new contributors to the project.
The way this works is that maintainers create special branches prefixed with `first-timers-` and commit needed changes to that branch. When the branch is pushed to **jekyll/jekyll**, the bot will create an issue template with step-by-step instructions to walk a first-timer through committing those changes to their own branch and then creating a PR.
This is a very hand-holding process, and will certainly slow things down a bit: rather than a maintainer merging their own changes, they will go through all the steps of committing the changes and …

Add configuration for first-timers bot

---

lib/jekyll/site.rb
lib/jekyll/utils.rb
test/test_utils.rb

Utils.merged_file_read_opts was attempting to shim in `bom|<encoding>` to a Hash key that didn't exist...
/cc @jekyll/build https://github.com/jekyll/jekyll/pull/6322

Fix BOM-related read problems

---

lib/jekyll/renderer.rb

Added 'to_s' method to line 146. 
Can you review my code change?

Always treat `data.layout` as a string

---

features/layout_data.feature

Add missing test for layout as string.
Related issue: #6443

Add test for layout as string

---

docs/_posts/2017-10-19-diversity-open-source.markdown

this plays into what we discussed at #6431. here's a post detailing what we've done to increase new contributors, and diversity overall so far.
this is the first draft, so i'd be happy for anyone willing to point out my spelling mistakes or logical inconsistencies
/cc @parkr

add post about diversity

---

docs/_docs/plugins.md

Ref: https://github.com/jekyll/jekyll/issues/6358#issuecomment-339859914

Add a note on `:jekyll_plugins` group in the docs

---

docs/_tutorials/custom-404-page.md

I'm not sure if I was doing something wrong or the docs are incorrect. 
But the only way I managed to serve a custom 404 page was by adding an equality sign (`=`) to the location directive.
Please correct me if I'm wrong.

Updated custom-404-page.md

---

docs/_docs/troubleshooting.md

It should be made very clear that `sudo` is not recommended on macOS, so the examples should show the commands without `sudo`. If the user knows what they're doing, they can prepend `sudo` themselves as the note suggests.

Remove `sudo` from macOS troubleshooting instructions

---

.rubocop.yml
Rakefile
lib/jekyll/commands/doctor.rb
lib/jekyll/convertible.rb
lib/jekyll/document.rb
lib/jekyll/renderer.rb
lib/jekyll/tags/include.rb
lib/jekyll/tags/post_url.rb

RuboCop sez it's not a good practice to `rescue` an `Exception` without specifying an `::Exception` subclass.
So lets specify the classes, then.
In many of the offenses encountered, the `rescue` covers a broad range and a particular class is not readily discernible. Hence, correct such offenses by `rescue`-ing the default class for `rescue` &mdash; `StandardError`
The remaining offenses have been corrected by *assuming the most likely* by manually interpreting the code context.
/cc @pathawks

Enable `Lint/RescueWithoutErrorClass` Cop

---

lib/jekyll/theme.rb
test/test_theme.rb

Fixes #5575 by raising `RuntimeError` with a meaningful message when the directory to which a theme was installed is removed:
```
$ bundle exec jekyll serve
Configuration file: /Users/angelika/Documents/jekyll-test/_config.yml
jekyll 3.6.0 | Error:  Path /Users/angelika/.rvm/gems/ruby-2.3.1/gems/minima-2.1.1 does not exist, is not accessible or includes a symbolic link loop
```
I concluded from the test suite that returning `nil` in this method is desired: https://github.com/jekyll/jekyll/blob/d79ca534e40d4d6ae4deb998b9f418f8ba5e3db4/lib/jekyll/theme.rb#L49-L53 because loading files from `_includes`, `_layouts`, `_sass` and `assets` is supposed to be skipped if their path is `nil`.
What is more, when the root directory exists (but has no contents), Jekyll does not raise, but provides …

Raise when theme root directory is not available

---

features/collections.feature

Added direct collection access to future collection item feature test

---

features/collections.feature

Reverts jekyll/jekyll#6151
Collection handling output doesn't take `future` into account for non output files.

Revert "Added direct collection access to future collection item feature test"

---

.rubocop.yml

- enabling `Style/Attr` cop doesn't throw any offense on current codebase
- `Layout/SpaceAroundOperators` and `Style/FrozenStringLiteralComment` cops are enabled by default
/cc @pathawks

Clean up Rubocop config

---

lib/jekyll/commands/clean.rb

https://github.com/sass/sass/blob/f31605339b4f4dd3098b010186db481b7563a634/lib/sass/plugin/configuration.rb#L18

.sass-cache doesn't *always* land in options['source']

---

Gemfile
docs/_docs/templates.md
jekyll.gemspec
lib/jekyll.rb
lib/jekyll/utils.rb
test/test_utils.rb

This is in response to #4623 
To summarize the discussion in the above issue, trying to slugify strings with Swedish letters in them (accented characters in general) produced unexpected output. `ascii` mode does the job but drops accented characters, which is probably undesirable to some users. So we add `latin` mode, which will transliterate accented characters to the ASCII equivalent.
```
{{ 'kvalité, då, äta, öl' | slugify: 'ascii' }} # -> kvalit-d-ta-l
{{ 'kvalité, då, äta, öl' | slugify: 'latin' }} # -> kvalite-da-ata-ol
```
* Add a new `latin` mode to be used as an option for `#slugify`
* Add runtime dependency on `i18n` gem to perform the transliteration
* Update the documentation to demonstrate `latin` mode, and also `ascii` mode, which existed but was not documented

Add latin mode to slugify

---

lib/jekyll/converters/markdown/kramdown_parser.rb
lib/jekyll/utils/ansi.rb

Rubocop did not catch this superfluous magic comment because it was on the second line which was not preceded by a line with a comment starting with a shebang

Remove unnecessary encoding comment

---

script/fmt

Suggest using Rubocop to automatically fix errors

---

lib/jekyll/filters/url_filters.rb
test/test_filters.rb

Currently, `relative_url` converts all uris to an absolute path even absolute uris with authority.
This can lead to unexpected results. For example `{{ "https://example.com/" | relative_url }}` becomes `/https://example.com/` (with `baseurl = "/"`).
This is an issue when you want to define for example a navigation structure with internal and external links.
```liquid
{% for link in nav %}
<a href="{{ link.url | relative_url }}">{{ link.label }}</a>
{% endfor %}
```
The `relative_url` converts all links to absolute paths, even external links. Leaving it out would mean that internal links don't get the baseurl prepended.
This PR adds a simple check if the input is an absolute url with authority and doesn't modify it (except normalization).
As a minor issue, `https://example.com/` *could* …

filter relative_url should keep absolute urls with scheme/authority

---

lib/jekyll/document.rb
test/test_convertible.rb
test/test_site.rb

Assert raising Psych::SyntaxError when `"strict_front_matter"=>true`

---

.rubocop.yml
lib/jekyll/commands/serve.rb
lib/jekyll/converters/markdown.rb

```
Do not use %W unless interpolation is needed. If not, use %w.
```

[RuboCop] Enable `Style/UnneededCapitalW` cop

---

lib/jekyll/configuration.rb

Ref: [bbatsov/ruby-style-guide](https://github.com/bbatsov/ruby-style-guide#array-coercion)
I don't think there's a cop for this yet.
Also, I guess its better handling such lines one-at-a-time..

Use Kernel#Array instead of explicit Array check

---

lib/jekyll/commands/serve.rb

Assignment Branch Condition Size for the method on repo branches (as reported by RuboCop) :
- `master` : **29.7**
- `PR-branch`: ~~20.1~~ **13.64**

Refactor method to reduce ABC Metric size

---

lib/jekyll/converters/markdown/kramdown_parser.rb
lib/jekyll/converters/smartypants.rb
test/test_kramdown.rb

This fixes #6516 . Thank you @gettalong for making us aware of this option! 👍 
cc: @jekyll/build

Log kramdown warnings if log level is WARN

---

lib/jekyll/commands/new.rb

Use double-quotes around gem name

---

lib/jekyll/filters/url_filters.rb
test/test_filters.rb

I may have proposed this before, but I'm curious if anybody else would be interested in URL filters that work directly with documents.
Instead of `{{ page.url | absolute_url }}` this would allow `{{ page | absolute_url }}` which feels just a little nicer to me.  Curious to hear other's thoughts.
/cc: @jekyll/build @jekyll/ecosystem

Allow URL filters to work directly with documents

---

Gemfile

Cucumber 3.0.2 has dropped support for Ruby 2.1

Lock to cucumber 3.0.1 on Ruby 2.1

---

docs/_sass/_style.scss

Style mobile-docs select element

---

docs/_docs/plugins.md

The official website includes user-friendly instructions, easy for a Jekyll beginner. Soon, there will even be a section for Jekyll-Pug themes.
I also improved the description. Jekyll-Pug is no longer a basic converter plugin. It now supports Jekyll includes, layouts, a custom caching engine, and much more.
An upcoming feature is full Pug support, where you can use native Pug variables, for loops, and if statements, rather than using the Liquid equivalent.

Updated Jekyll-Pug listing to include official website

---

lib/jekyll/commands/serve.rb

Add json extension to list of directory indices

---

.travis.yml

JRuby `v 9.1.14.0` released on Nov 09 2017

Bump JRuby version in Travis config

---

docs/_includes/header.html
docs/_includes/mobile-nav-items.html
docs/_sass/_docsearch.scss
docs/_sass/_style.scss

- render site header at full-width using Flexbox
- use site color scheme for search input

Site header redesign

---

docs/_includes/header.html
docs/_sass/_style.scss

Move logo above site navigation on small screens

---

lib/jekyll/theme.rb

Closes #6423 
Print our custom error message and let the user know they need to install "sass" gem instead of showing them the backtrace.

Fail gracefully if "sass" gem cannot be loaded

---

lib/jekyll/commands/serve/servlet.rb
test/fixtures/webrick/bar.html
test/fixtures/webrick/bar/baz.html
test/helper.rb
test/test_commands_serve_servlet.rb

- bar.html
- bar
|- baz.html
_GET /bar/_
_Before:_ Returns bar.html
_After:_  Returns bar.html
_GET /bar/baz_
_Before:_ Returns bar.html
_After:_  Returns bar/baz.html
_GET /bar/whatever_
_Before:_ Returns bar.html
_After:_  Returns 404
This fixes #6475. Thanks @janpio for the great reproduction script! 👍 
cc: @jekyll/build

return correct file in dir if dir has same name as file

---

docs/_docs/themes.md

I'm opting to showcase this feature with the version-badge instead of editing the `From 'v3.5'..` part out entirely, just in case end-users / developers would need a quick reference as to what version introduced the concerned feature.

Use version-badge on an existing feature intro

---

lib/jekyll/theme_builder.rb

Fixes #6382 
Redefine `private` methods as `public` methods to prevent warning messages from the Ruby Interpreter since forwarding to private methods have been deprecated from Ruby 2.4

Drop forwarding to private methods by exposing those methods as public

---

test/test_redcarpet.rb

- replace multiple calls to creating heredocs containing the same content, with an instance variable
- use `%()` to wrap strings containing double quotes to avoid having to escape internal double-quotes, thereby improving readability at the minor expense of multiple string concatenation.

Cleanup test_redcarpet.rb

---

lib/jekyll.rb
lib/jekyll/page.rb
lib/jekyll/page_without_a_file.rb
test/fixtures/physical.html
test/test_page_without_a_file.rb

Official plugins `jekyll-sitemap`, `jekyll-feed` and a couple more add a `Page` subclass to generate a file (usually from Liquid templates not present in the user's source directory).
Advantages
- Users adding both plugins need not allocate memory for the twin subclasses.
- Also allows other third-party plugins that follows the above implementation.
---
Plugins known to implement this subclass or similar:
- [`jekyll-sitemap`](https://github.com/jekyll/jekyll-sitemap/blob/7c944d0cfd151a51f210ac4eb0ceeb56f3a74031/lib/jekyll/page_without_a_file.rb#L3-L9)
- [`jekyll-feed`](https://github.com/jekyll/jekyll-feed/blob/2ff6fdcb77cea99ed67b6be0378ccc3ae60417d8/lib/jekyll-feed/page-without-a-file.rb#L3-L9)
- [`jekyll-admin`](https://github.com/jekyll/jekyll-admin/blob/3415b5a15d4b98d0b41211f00a6a9ae …

Add PageWithoutAFile class from jekyll plugins

---

lib/jekyll/version.rb

I wonder how this remained unchanged. Fortunately, the last released gem has the correct version specified..

Update Jekyll::VERSION to the latest released version

---

jekyll.gemspec

See https://github.com/jekyll/jekyll-watch/releases/tag/v2.0.0

Dependency: Bump jekyll-watch to 2.0

---

docs/_docs/configuration.md
lib/jekyll/configuration.rb
lib/jekyll/converters/markdown/kramdown_parser.rb
lib/jekyll/converters/smartypants.rb
test/test_kramdown.rb

With this, warnings from kramdown are swallowed by default.
Add `log_warnings: true` under `kramdown:` options to enable them

Add an option to configure kramdown warning output

---

docs/_docs/installation.md

When I tried to install Jekyll into my local environment using the `gem install jekyll bundler` command, the error was shown and the install failed:
```
ERROR:  Error installing jekyll:
ruby_dep requires Ruby version >= 2.2.5, ~> 2.2.
```
So the requirement for the Ruby version is 2.2.5 or above.

Update "Requirements" for Ruby version

---

lib/jekyll/commands/serve/live_reload_reactor.rb

some changes to the livereload reactor I withheld requesting to made before this class was merged to avoid noise in that PR..

Cleanup LiveReloadReactor

---

lib/jekyll/commands/serve.rb

Resolves issue mention in https://github.com/jekyll/jekyll/pull/5142#issuecomment-349786108
Calling `:register_reload_hooks` in `#process` after the site starts to `generate...` instead of much earlier in the build-process..
/cc @awood

Register reload hooks in Server#process

---

lib/jekyll/regenerator.rb

The path to *metadata_file* need not be generated each time the file is referenced..

Memoize path to metadata file

---

lib/jekyll/liquid_renderer.rb

Motivation: https://travis-ci.org/benbalter/jekyll-remote-theme/builds/312202423#L591-L638

Use `require_relative` to load Jekyll classes

---

docs/_docs/plugins.md

This PR
💁‍♂️ Since `i18n_filter.rb` has been removed with https://github.com/gacha/gacha.id.lv/commit/004bffd97c3a38d835aca39acafe794ce8c8cc65, the current link is broken.

Fix: Update link to i18n_filter plugin

---

docs/_sass/_pygments.scss
docs/_sass/_style.scss

Improve docs styling for code to be run in shell

---

docs/_docs/plugins.md

This adds my plugins to the list:
1. Tweetsert - Import tweets as posts
2. Stickyposts - Pin `sticky` posts to the top
3. Jekyll::Paginate::Content - Automatic page/post/collection item splitter

Add Tweetsert, Stickyposts, Paginate::Content

---

lib/jekyll/collection.rb

Jekyll's logger likes the first parameter to be of 20 chars or lesser.
```
Reading: _docs/future-dated-doc.md
Skipped From Publishing: _docs/future-dated-doc.md
Reading: _docs/past-dated-doc.md
```
```
Reading: _docs/future-dated-doc.md
Skipped Publishing: _docs/future-dated-doc.md
Reading: _docs/past-dated-doc.md
```

Use a shorter topic label for readability

---

lib/jekyll/page.rb

Scope Resolution Operator should be `::` instead of `:` which is for Symbols..

Correct custom inspect string for Jekyll::Page

---

Gemfile
lib/jekyll/configuration.rb
test/test_configuration.rb

We have an ancient version of the `toml` gem which appears to have been abandoned for years and isn't compliant with TOML 0.4.0, the current state of the art.
The `tomlrb` and `toml-rb` gems are both (more) actively maintained and kept up-to-date; switching to either gives us TOML 0.4.0 support.  This patch switches us to `tomlrb`.
(See also: #6540 #6541)

Switch to an actively-maintained TOML parser.

---

docs/_layouts/news_item.html

Fix permalink icon markup in news-item layout

---

docs/_config.yml
rake/site.rake

As discussed in #6676 , I've already ran the command once, so we can see what changes in the `config.yml` file when running this command (as it normalizes the YAML output)

Update version in `config.yml` via YAML load / dump

---

docs/_docs/collections.md

This PR
Follows #6331.
Related to #6678.
Follows https://github.com/jekyll/jekyll/pull/6679#issuecomment-355803114.

Fix: Add note about posts in context of collections_dir

---

lib/jekyll/tags/include.rb
test/test_tags.rb

If the file given to `include` / `include_relative` can't be found in safe mode it might be because it is a symlink which are not allowed in safe mode. We should make the user aware of this.
This closes #6480.
There was a [note added to the symlink check two years ago](https://github.com/jekyll/jekyll/blob/401f8fef5b969387b55730d74c660e2a6aa69887/lib/jekyll/entry_filter.rb#L67-L69) which says that the symlinks could now be allowed in safe mode. Can someone confirm this as i'm not familiar with the security implications (especially for github pages)? Maybe @parkr or @envygeeks as he has written that note?

inform that symlinks are not allowed in safe mode

---

lib/jekyll/converters/markdown/kramdown_parser.rb
lib/jekyll/converters/markdown/rdiscount_parser.rb
lib/jekyll/converters/markdown/redcarpet_parser.rb
lib/jekyll/converters/smartypants.rb
lib/jekyll/theme.rb
lib/jekyll/utils/rouge.rb
lib/jekyll/utils/win_tz.rb

Even though the Ruby interpreter does not require a library more than once, there's scope for optimization by not initiating `Jekyll::External.require_with_graceful_fail` unless necessary within current build session

Require external library only if necessary

---

docs/_docs/deployment-methods.md

Update documented deploy script to correctly use the Gemfile present in the configured source directory.
Ref: http://talk.jekyllrb.com/t/deploy-with-jekyll-paginate-v2-fails/1320

Update deploy-script in documentation

---

lib/theme_template/theme.gemspec.erb

Default `new-theme` `.gemspec` should inherit Jekyll's Ruby Style Guide.

Lint file and bump theme dependencies

---

docs/_docs/collections.md

Clarifying situation in follow up to #6702. /cc @ashmaroli

Add note about naming of collections_dir

---

docs/_docs/configuration.md
lib/jekyll/frontmatter_defaults.rb
test/test_front_matter_defaults.rb

Resolves #6691
Take the less expensive route unless the user configures the `scope["path"]` with a glob pattern. e.g. include
- `"content/*.pdf"`
- `"content/**/*"`
- `"content/config.?"`
- `"content/config.[^a]"`
- `"content/config.{yaml, yml}"`

Glob scope path only if configured with a pattern

---

lib/jekyll/commands/new.rb

I recently found out that adding `gem "wdm"` to the Gemfile actually [boosts performance](https://github.com/jekyll/jekyll/pull/6692#issuecomment-359865460) on Windows while `watch: true`..
So its better we have it included in the newly generated `Gemfile` by default..

Add gem "wdm" to all newly generated Gemfiles

---

Gemfile

This is a reflect of #204, 093a5ef.
About redgreen:
- https://rubygems.org/gems/redgreen/versions/1.2.2
- http://on-ruby.blogspot.kr/2006/05/red-and-green-for-ruby.html
I found that redgreen is installed by running `rg` command. It stands for ripgrep now, at least for me.

Remove redgreen gem

---

features/collections_dir.feature
features/step_definitions.rb
lib/jekyll/collection.rb
lib/jekyll/document.rb
lib/jekyll/reader.rb
lib/jekyll/site.rb
lib/jekyll/static_file.rb

I believe this removes bugs with the recently released `collection_dir` feature reported via jekyll/jekyll-feed#202 and confirmed via #6679 
Basically with this patch,
- Site runs as usual if the `collections_dir` setting is not customized.
- When the `collections_dir` setting is customized, Jekyll looks for all collections *within* that directory only:
- Posts and drafts at the root will no longer be read / processed &mdash; you need to move them inside the `collections_dir`
- Relative path of all "documents" will be with-respect-to that directory. e.g. If the directory is named `my_collections`, then the relative_path for `./my_collections/_puppies/rover.md` is simply `_puppies/rover.md`
- Ergo, **relative_path for a document does not change whether the collection is at the site-root or …

Refactor collections_dir feature for consistency

---

lib/jekyll/site.rb

move duplicate code to a single private method

---

lib/jekyll/document.rb
lib/jekyll/drops/site_drop.rb
lib/jekyll/related_posts.rb
lib/jekyll/renderer.rb

1. Don't calculate `site.related_posts` unless we request it.
2. Calculate `site.related_posts` without LSI much more efficiently.
I've been using `@jvns`'s new `rbspy` program. I generated a random site of 10,000 posts (no layouts) to test this. When I got back the flamegraph, it was obvious that `most_recent_posts` was the culprit for a significant amount of time. After I applied this patch, regeneration went from 150s to 50s. We saved about 100s (1m40s) of time just by not generating related posts unless we needed it!

Two massive performance improvements for large sites

---

docs/_docs/plugins.md

I've added the [jekyll-algolia](https://community.algolia.com/jekyll-algolia/) to the list of plugins that can be used with Jekyll. I added them to the "Other" category as this is the one that seemed the more appropriate (the plugin index content to make it available through search).

Adding the jekyll-algolia plugin to the list of plugins

---

docs/_docs/maintaining/avoiding-burnout.md
docs/_docs/maintaining/index.md
docs/_docs/maintaining/merging-a-pull-request.md
docs/_docs/maintaining/releasing-a-new-version.md

Closes https://github.com/jekyll/jekyll/issues/6721 ✨

Add document on releasing a new version

---

docs/_docs/plugins.md

Added a small plugin I made to download a webfont from [Fontello](https://github.com/fontello/fontello) to the list of plugins, generators. Update from #6744, now a Ruby gem instead of a GitHub Gist.

Add 'jekyll-fontello' to plugins

---

.codeclimate.yml

An asset we do not maintain shouldn't affect our Code Climate score.

Codeclimate: exclude livereload.js

---

docs/_docs/posts.md
docs/_docs/variables.md

`{{ page.excerpt }}` is *currently* meant for `Jekyll::Document` objects only, and has nothing to do with `Jekyll::Page` objects, much like `{{ page.id }}` is meant to be used for documents alone.

Fix documentation for `{{ page.excerpt }}`

---

docs/_docs/permalinks.md

Documents change made in https://github.com/jekyll/jekyll/commit/b6c283a4aee531a06ba6b3c9cde5e972889c7471
Other references:
- https://github.com/jekyll/jekyll-sitemap/issues/206

Update docs on permalink configuration

---

features/link_tag.feature
features/step_definitions.rb

Mainly to act as a control element for #6727 which passes other existing tests in spite of containing a breaking change.

Add a cucumber feature to test link tag

---

lib/jekyll/site.rb

To avoid multiple traversal of the `Site#documents` array using `Array#select` and `Document#write?`
https://github.com/jekyll/jekyll/blob/0f2c27bcb0a491a1eca0c2f801139992377bd6e2/lib/jekyll/site.rb#L317-L324
https://github.com/jekyll/jekyll/blob/0f2c27bcb0a491a1eca0c2f801139992377bd6e2/lib/jekyll/site.rb#L310-L315

Cache the list of documents to be written

---

features/step_definitions.rb
features/theme_gem.feature

theme gem feature failed with Rubygem 2.7.6 because we have TODO strings and an invalid URL in the default theme gemspec
`--force` option will skip the validation, it's OK here because we want to keep this TODO comments to show theme developers that they need to update those fields.

Fix theme gem feature

---

docs/_includes/top.html

Always load Google Fonts over HTTPS

---

benchmark/sanitize-url.rb
lib/jekyll/document.rb
lib/jekyll/static_file.rb
lib/jekyll/theme_builder.rb
lib/jekyll/url.rb

Prefer built-in functions over using simple regular expressions to produce same result

Replace simple regex with equivalent Ruby methods

---

lib/jekyll/commands/doctor.rb

If one defines a custom location for their collections, `_posts` directory should not exist at the root of the source directory

Allow Jekyll Doctor to detect stray posts dir

---

lib/jekyll/excerpt.rb
test/source/_posts/2018-01-28-closed-liquid-block-excerpt.markdown
test/source/_posts/2018-01-28-open-liquid-block-excerpt.markdown
test/test_excerpt.rb
test/test_generated_site.rb

Resolves #5596 
If a `Liquid::Block` tag subclass gets caught between the `excerpt_separator`, then append the concerned block delimiter to the excerpt to avoid a `Liquid Exception due to invalid syntax`

Append appropriate closing tag to Liquid block in an excerpt

---

lib/jekyll/excerpt.rb
test/test_excerpt.rb

Currently a document's excerpt's relative path equals the doc's relative path instead of the excerpt-path relative to the site's source.
```
doc.path: my_blog/_posts/2017-12-04-some-doc.md
excerpt.path: my_blog/_posts/2017-12-04-some-doc.md/#excerpt
doc.relative_path: _posts/2017-12-04-some-doc.md
excerpt.relative_path: _posts/2017-12-04-some-doc.md
```
```
doc.path: my_blog/_posts/2017-12-04-some-doc.md
excerpt.path: my_blog/_posts/2017-12-04-some-doc.md/#excerpt
doc.relative_path: _posts/2017-12-04-some-doc.md
excerpt.relative_path: _posts/2017-12-04-some-doc.md/#excerpt
```

Excerpt relative-path should match its path

---

lib/jekyll.rb
lib/jekyll/utils.rb

Fixes #6669 
We shouldn't be hardcoding locales unnecessarily

Do not hardcode locale unless certainly necessary

---

docs/_posts/2018-02-25-jekyll-3-7-3-released.markdown

Release post for a patch release that fixes a bug introduced in `v3.7.0`
(Other bug-fixes should be released as part of `v3.8.0` IMHO)

Draft a release post for v3.7.3

---

docs/_includes/analytics.html

safer, faster and recommended way by Google
REF: https://developers.google.com/analytics/devguides/collection/analyticsjs/

always load analytics.js over HTTPS

---

docs/_docs/themes.md

Theme documentation steps for converting a gem-based theme into 'intrinsic' site files are missing explanation about plugins.
First brought up in jekyll/minima#157
h/t @ashmaroli 

add missing step for gem-based theme conversion

---

lib/jekyll/commands/new.rb

Ref: https://github.com/jekyll/jekyll/issues/6797#issuecomment-368088913 by @pathawks 
/cc @chrisfinazzo

Remind user to resolve conflict in `jekyll new` with `--force`

---

benchmark/conditional_liquid.rb
lib/jekyll/convertible.rb
lib/jekyll/document.rb
lib/jekyll/renderer.rb
lib/jekyll/utils.rb

Currently, all `Page` objects and certain `Document` objects are always *parsed* and *rendered* via `Liquid` before being passed onto the concerned `Converter`.
With this patch, a simple check is performed after `:pre-render` hooks to determine if the `content` contains any `Liquid Tags / Variables` and then handled accordingly:
- if the content is simply 100% plaintext (or Markdown), then `Liquid`'s parse-render phase is skipped and directly passed onto the associated `Converter`
- otherwise, follow current behavior

Bypass rendering via Liquid unless required

---

benchmark/native-vs-pathutil-relative
lib/jekyll/document.rb

Use `String#sub` instead of `Pathutil#relative_path_from` which uses regexes [internally](https://github.com/envygeeks/pathutil/blob/08cadda52af0971b58b64987fb089d83e12c9e38/lib/pathutil.rb#L425-L434)
```ruby
#!/usr/bin/env ruby
require 'benchmark/ips'
require 'pathutil'
DOC_PATH = File.join(File.expand_path(__dir__), "_puppies", "rover.md")
COL_PATH = File.join(File.expand_path(__dir__), "_puppies")
def pathutil_relative
Pathutil.new(DOC_PATH).relative_path_from(COL_PATH).to_s
end
def native_relative
DOC_PATH.sub("#{COL_PATH}/", "")
end
if pathutil_relative == native_relative
Benchmark.ips do |x|
x.report("pathutil") { pathutil_relative }
x.report("native")   { native_relative }
x.compare!
end
else
print "PATHUTIL: "
puts pathutil_relative
print "NATIVE:   "
puts native_relative
end
``` …

Compute document's relative_path faster

---

lib/jekyll/reader.rb

Currently, for every valid directory (based on the `EntryFilter`) traversed by `Reader`, a new instance of `PostReader` is created (with the same site instance) to retrieve posts and drafts from that directory.
This PR proposes to use just one `PostReader` instance to retrieve posts and drafts from all valid directories.

Create a single instance of PostReader per site

---

Gemfile
script/rubyprof

The original script seemed to be unused as it has been left broken for a long time..
(The script was testing `Jekyll::Commands::Build.process({'source' => 'site'})`)
..and there were issues while trying to get it to run on Windows , even after the `source` was corrected to the current docs site at `./docs` (`NameError: uninitialized constant CallTreePrinter`)
So, I rewrote it as a Ruby script.
---
1. Invocation:
```diff
- $ bash script/rubyprof
+ $ bundle exec ruby script/rubyprof
```
2. The generated result is now a simpler text output via `RubyProf::FlatPrinter` instead of `RubyProf::CallTreePrinter` earlier.
3. The generated filename now has a time-stamp as against a random integer earlier

Rewrite `script/rubyprof` as a Ruby script

---

docs/_docs/templates.md
lib/jekyll/filters.rb
lib/jekyll/filters/date_filters.rb
test/test_filters.rb

It is normal to write things like _posted on 12th February 2018" in the blog post. Currently to achieve this, a code similar to this one is needed:
```
{% assign d = page.date | date: "%-d" %}
{% case d %}
{% when '1' or '21' or '31' %}
{{ d }}st
{% when '2' or '22' %}
{{ d }}nd
{% when '3' or '23' %}
{{ d }}rd
{% else %}{{ d }}th
{% endcase %}
{{ page.date | date: "%B" }}
{{ page.date | date: "%Y" }}
```
I think the case is common enough to introduce it in Jekyll, by adding some parameters to the `date_to_string` and `date_to_long_string` methods.
It supports both UK and US styles. UK is the default.
I also changed @sample_date in one of the tests to cover more cases.

Allow date filters to output ordinal days

---

lib/jekyll/drops/collection_drop.rb
lib/jekyll/drops/document_drop.rb
lib/jekyll/drops/site_drop.rb
lib/jekyll/drops/static_file_drop.rb

Methods defined via `def_delegator` are `public` even if there is a preceding `private` keyword
https://github.com/jekyll/jekyll/blob/93e16428d8a27f20b16f77e466e0873692a9cb7f/lib/jekyll/drops/document_drop.rb#L65-L66
```bash
$ irb
require 'jekyll'
Jekyll::Drops::DocumentDrop.private_instance_methods.include?(:fallback_data)
Jekyll::Drops::DocumentDrop.public_instance_methods.include?(:fallback_data)
```

Delegated methods after `private` keyword are meant to be private

---

lib/jekyll/liquid_renderer.rb
script/default-site

Currently, the resulting table from building with `--profile` has **`relative_path`** for files at the source dir but an **`absolute_path`** for files within a theme-gem (which can be a long string depending on the user's Ruby Installation location.)
- all filenames are normalized to be relative to the source-directory or theme-root.
- if a path starts with a non-alphanumeric char, (e.g. `../../` or `~foo`), those characters are ignored.
- no discernible effect on performance.
---
- prepend relative paths from theme-gem with the gem's dirname
(e.g. `minima-2.3.0/_includes/head.html`)

Change regex to sanitize and normalize filenames passed to LiquidRenderer

---

docs/_docs/collections.md
features/collections.feature
lib/jekyll/collection.rb
lib/jekyll/document.rb
test/test_document.rb

Resolves #5953 
Replaces #6506

Improve handling non-default collection documents rendering and writing

---

test/test_site.rb

```
Use assert_nil if expecting nil from test/test_site.rb:65:in `block (2 levels) in <class:TestSite>'. This will fail in MT6.
```
cc: @jekyll/stability

fix minitest deprecation warning in test

---

docs/_docs/configuration.md
features/rendering.feature
lib/jekyll/configuration.rb
lib/jekyll/renderer.rb

Resolves #6725 
Allow users to enable detecting non-existent variables and filters specified in a template by setting `["liquid"]["strict_variables"]` and `["liquid"]["strict_filters"]` to `true` respectively in their config file.
/cc @begincalendar, @iddan, @ianhinder

Allow passing :strict_variables and :strict_filters options to Liquid's renderer

---

lib/jekyll/site.rb

- `Site#site_data` is called [*twice*](https://github.com/jekyll/jekyll-seo-tag/blob/f19b29ea0a20c08b32e3018800da83d9da69ace5/lib/jekyll-seo-tag/author_drop.rb#L63-L64) per page / document when the popular plugin `jekyll-seo-tag` is used
- `jekyll-seo-tag` is loaded by default via recent releases of Minima
- IMO, its better addressing this here instead of patching per plugin(s)

Memoize `Site#site_data`

---

lib/jekyll/document.rb

This is to avoid creating new instances of `Jekyll::Renderer` each time `Document#output_ext` is called

Memoize document output extension

---

lib/jekyll/convertible.rb
lib/jekyll/document.rb
lib/jekyll/regenerator.rb
lib/jekyll/site.rb

We have log outputs for the `Reading` phase upto `Rendering`.. but no outputs when a generated file is being written to the disk.
This prints the destination path of each file being written to disk and the write-path to the metadata file. (all relative to `site.source`)

Debug writing files during the build process

---

lib/jekyll/renderer.rb

Currently `Renderer#permalink_ext` calls `document.permalink` 3 times per document instance which results in accessing a *non-memoized method* involving conditional traversing,,
https://github.com/jekyll/jekyll/blob/0f2c27bcb0a491a1eca0c2f801139992377bd6e2/lib/jekyll/document.rb#L195-L201
While a better approach would be to additionally cache the `permalink` value within the `Document` instance itself, I'm deferring that for cases that may be altering the permalink via a `:post_render` hook using plugins..

Access document permalink attribute efficiently

---

features/include_tag.feature
lib/jekyll/tags/include.rb

Summary of changes:
- moved locally initialized regexps in frequently called methods to class constants
- `INVALID_SEQUENCES` now flag sequences of *multiple adjacent periods* `(..)` and *multiple adjacent forward slashes* `(//)` along with original sequences of *dot-slash* `(./)` and *slash-dot* `(/.)`
- `:validate_file_name` now first checks for `INVALID_SEQUENCES` and then proceeds to check for `VALID_FILENAME_CHARS` to `raise` sooner
- use `String#=~` over slower `String#match`

Improve regex usage in `Tags::IncludeTag`

---

lib/jekyll/tags/include.rb
test/test_tags.rb

Fix passing multiline params to include tag when using the variable syntax 

---

lib/jekyll/filters.rb

Since `Kernel#Array` creates an array out of the returned `item_property`, calling `map!` here only modifies elements of the said array which is already being done currently (albeit by creating more copies of the array..)
This reduces a lot a Array allocations especially when a large *`Collection`* is piped to the `where` filter multiple times in Liquid..

Minimize array allocations in the `where` filter

---

docs/_docs/plugins.md

Hi!
I've created a Jekyll plugin to generate a large amount of random data. The data is generated based on `forloop.index`, so that every time when you run `jekyll build` the generated data is the same.
It would be nice to list it on plugins page. 
Thanks!

Add `jekyll-random` plugin to docs

---

docs/_docs/posts.md

I came across this when I read your documentation. I think mentioning the same page twice doesn't make sense, so I assumed you meant the respective pages for the two tags.

Fixed typo in description of categories and tags

---

docs/_tutorials/navigation.md

In scenario 5, the result list is surrounded by `<ul>` tags. In scenario 6 they are missing, causing the list to move to the left and causing a rendering issue at https://jekyllrb.com/tutorials/navigation/#scenario-6-applying-the-active-class-for-the-current-page under "Result".

Add missing ul-tag

---

test/test_collections.rb

Adding a test that wasn't added in 530e049d2dfa1cad05d828cfa71bbec74a1a8e27.

Assert existence of <collection>.files

---

lib/jekyll/regenerator.rb

When its not an incremental build, exit early instead of walking the `case` tree and arriving at the same conclusion..

Regenerate unconditionally unless its an incremental build

---

benchmark/local-require
lib/jekyll.rb
lib/jekyll/cleaner.rb
lib/jekyll/commands/doctor.rb
lib/jekyll/commands/serve/live_reload_reactor.rb
lib/jekyll/converters/markdown/kramdown_parser.rb
lib/jekyll/convertible.rb
lib/jekyll/drops/drop.rb
lib/jekyll/drops/jekyll_drop.rb
lib/jekyll/filters.rb
lib/jekyll/filters/url_filters.rb
lib/jekyll/reader.rb
lib/jekyll/site.rb
lib/jekyll/url.rb
lib/jekyll/utils/rouge.rb

With every call to `require`, Ruby has to check through the `$LOADED_FEATURES` array to see if the requested file has already been loaded beforehand. Therefore, multiple `require` calls to the same file have an overall negative effect on performance.
This patch removes the multiple `require` calls (esp. from within frequently called instance methods) and adds them to `lib/jekyll.rb`
Also includes a benchmark script to compare `require` calls per file-load and per method-call.

Centralize require statements

---

features/collections_dir.feature
lib/jekyll/tags/include.rb

`include_relative` tag should find related documents in collections gathered within custom `collections_dir`

---

lib/jekyll/filters.rb
lib/jekyll/site.rb

Store converter instances into, and retrieve from a hash.
Since the associated filters *may* be called frequently within single Liquid template for various inputs, and the template itself *may* be called for a ton of documents / pages in a large site, its better to opt for hash-lookups over multiple `Array#find`
- Move to using multiple hash lookups against multiple `Array#find`
- Existing local variables have been dropped since they serve no bigger purpose than to be created, used once and immediately *garbage-collected* away
- `@converter_instances` remains defined for the duration of current `Site` instance since initialized converters don't change when the site regenerates

Store and retrieve converter instances for Jekyll::Filters via a hash

---

lib/jekyll/filters.rb

This is improve build times in sites that use *multiple calls to the `where` filter* with the same *`input` and `property` parameter.*
The official docs site for Jekyll contains multiple uses of `where` filter with `input: site.docs, property: url`
The cache implementation resulted in reduced calls to `Jekyll::Filters#item_property`.
( *via `method_profiler` gem on Windows 7 with Ruby 2.3* ):
```
MethodProfiler results for: Jekyll::Filters
+---------------------------+----------+----------+--------------+------------+-------------+
| Method                    | Min Time | Max Time | Average Time | Total Time | Total Calls |
+---------------------------+----------+----------+--------------+------------+-------------+
| #xml_escape               | 0.000s   | 0.012s   | 0.000s       | 0.030s …
```

Implement a cache within the `where` filter

---

lib/jekyll/liquid_renderer.rb

I should've made these corrections *before* #6610 got merged..
Oh well.."*Better late than never..*"

Optimize computing filename in LiquidRenderer

---

lib/jekyll/tags/highlight.rb

- return early if argument is empty
- skip checking if key `linenos` exist in the 'options' hash => if it doesn't exist, the hash will return `nil` anyways..
- guard clause makes the method more appealing.. :stuck_out_tongue:

Refactor private method `HighlightBlock#parse_options`

---

docs/_docs/installation.md

This commit adds installation instructions for Ubuntu Linux to the docs.
The instructions have been tested against the ubuntu:16.04 Docker image
to ensure they work on a fresh install.
Specifically, this commit should address issue #6800.

Add Installation Instructions for Ubuntu

---

docs/_docs/plugins.md

I added to the overview of all available jekyll plugins to the section jekyll tags my latest package: `jekyll-flickr`
It is a Liquid tag for responsive Flickr images using HTML5 srcset.

add liquid tag jekyll-flickr

---

docs/_docs/resources.md

Updated "saas" to "SaaS" as that is customarily how Software as a service is abbreviated.

Updated copy - fixed casing of SaaS on resources page.

---

features/post_excerpts.feature
lib/jekyll/excerpt.rb

Fixes #6944 
The bug occurred due to a miscalculation while implementing #6735 
While `Excerpt#render_with_liquid?` called the method correctly on *its container `doc`*, `doc.content` *by that time* had already been rendered by Liquid and therefore returned `false` to query `Utils.has_liquid_construct?(content)`
The patch addresses the bug by implementing the `Excerpt#render_with_liquid?` directly to ensure `Utils.has_liquid_construct?(content)` is called on the excerpt's contents..

Fix rendering Liquid constructs in excerpts

---

docs/_docs/quickstart.md
docs/index.html

This probably should have been in #6881. It seems reasonable to me that Jekyll should be under Bundler's purview. This is consistent w/ instructions [here][] and is useful if you don't run `jekyll new` (which calls `bundle install` internally). The wording is a bit repetitive, so that might need to be tweaked.
[here]: https://jekyllrb.com/docs/installation/

WIP: Do not advise users to install Jekyll outside of Bundler

---

lib/jekyll/page.rb

Once we drop support for Ruby 2.2 in Jekyll 4.0, having the magic comment `# frozen string literal: true` is all that's needed to avoid creating multiple copies of the same string.
In that event, the constant `Jekyll::Page::FORWARD_SLASH` will be unnecessary.

Remove unnecessary Jekyll::Page constant

---

lib/jekyll/excerpt.rb

because `relative_path` is called multiple times (at least *3 times per post)*..
(This *definition* was introduced in `3.8.0`)

Memoize computing excerpt's relative_path

---

features/post_excerpts.feature
lib/jekyll/excerpt.rb

This backports #6945 to `3.8-stable`

Backport #6945

---

features/collections.feature
lib/jekyll/collection.rb

Resolves #6958 
- `data["published"] == false` decides if the concerned `doc` should be accessible via Liquid or if it should be processed and ultimately written to disk..
- future-dated documents in both *visible* (`output: true`) and *hidden* (`output: false`) collections **continue** to be accessible via Liquid, but will be written only if `site.future == true` and document is part of a *visible* collection.

Liquify documents unless published == false

---

docs/_docs/collections.md

This PR
Follows #6680.
💁‍♂️ Tripped over this, apparently tests for it exist, see https://github.com/jekyll/jekyll/blob/41fa9cda369c01f6ac4da44bba9924e8bdd61ad4/features/collections_dir.feature#L67-L161

Document that _drafts need to be contained within the custom collection directory

---

test/test_kramdown.rb

Closes #7006 
Because TestKramdown calls for `Rouge::Formatters::HTMLLegacy` and the `rouge` library hasn't been loaded yet as a consequence of loading the test-helper

Load Rouge for TestKramdown

---

Gemfile
History.markdown
lib/jekyll/excerpt.rb
test/source/_posts/2018-05-15-closed-liquid-block-excerpt-whitespace-control.md
test/source/_posts/2018-05-15-excerpt-whitespace-control-variable.md
test/source/_posts/2018-05-15-open-liquid-block-excerpt-whitespace-control.md
test/test_excerpt.rb
test/test_generated_site.rb

Backport #7015 for 3.8-stable: Add whitespace control to LIQUID_TAG_REGEX

---

features/collections.feature
lib/jekyll/collection.rb

Fixes #7026 
Note that the changes to `collection.rb` different slightly to what was suggested — the `fmt` linter gave me a warning against using parens with `unless`. Please let me know if any further modifications are needed.
As a sidenote thanks for the very quick and friendly prompts for how to add this PR. Getting a chance to learn about Cucumber was great!

Fix --unpublished not affecting collection documents

---

History.markdown
features/collections.feature
lib/jekyll/collection.rb

This backports #7027 for `3.8`

Backport #7027

---

jekyll.gemspec

The `acceptance` build on Travis has been failing for a while, erroring on the `bundle install` step. This is due to: 
```text
Resolving dependencies...
Bundler could not find compatible versions for gem "activesupport":
In Gemfile:
jekyll-mentions (= 1.3.0) was resolved to 1.3.0, which depends on
activesupport (~> 4.0)
Could not find gem 'activesupport (~> 4.0)', which is required by gem 'jekyll-mentions (= 1.3.0)', in any of
the sources.
Bundler could not find compatible versions for gem "i18n":
In Gemfile:
jekyll-mentions (= 1.3.0) was resolved to 1.3.0, which depends on
activesupport (~> 4.0) was resolved to 4.0.3, which depends on
i18n (>= 0.6.4, ~> 0.6)
jekyll was resolved to 3.8.2, which depends on
i18n (~> 1.0)
```
This patch maintains compatibility with activesupport 4.2.10, …

Allow i18n v0.9.5 and higher

---

docs/_docs/continuous-integration/travis-ci.md

Adds hint about caching, notifications and uses ruby which is present in trusty dockers on Travis.

Add Hints for some Improved Travis Config in Doc

---

.rubocop.yml
Gemfile
lib/jekyll/drops/drop.rb

Update Rubocop to `0.57.2`
Closes #7062, and closes #7075

Update rubocop version to 0.57.x

---

docs/_docs/continuous-integration/circleci.md

New CircleCI projects use the v2 docker based system and the config files are very different.
It may be wise to remove v1 example - but we should def include a v2 example like the one proposed.

Example of CircleCI deployment through CircleCI v2

---

docs/_docs/themes.md

Although GitHub pages do not support pulling in themes from Gems it does support pulling in themes from other repositories and thus can be used in a similar way.

GitHub enables you to use themes from other repos

---

test/test_document.rb
test/test_excerpt_drop.rb
test/test_filters.rb
test/test_front_matter_defaults.rb
test/test_page_without_a_file.rb

The expected value needs to come _before_ the actual. Otherwise, the test results are confusing.
From [the docs](https://apidock.com/ruby/Test/Unit/Assertions/assert_equal):
```ruby
assert_equal(exp, act, msg = nil)
```

Fix tests to have "expected value" as the first argument passed to `assert_equal`

---

docs/_docs/plugins.md

Add Jekyll XML Source to the Plugins list. 
Signed-off-by: Derek Smart <derek@grindaga.com>

add jekyll-xml-source

---

lib/jekyll/commands/serve.rb

The actual call to validate_options got lost during a rebase, I believe.
This patch fixes the problem.

Add call to unused method `validate_options` in `commands/serve.rb`

---

.rubocop.yml
test/helper.rb
test/test_coffeescript.rb
test/test_collections.rb
test/test_command.rb
test/test_commands_serve.rb
test/test_configuration.rb
test/test_convertible.rb
test/test_doctor_command.rb
test/test_document.rb
test/test_drop.rb
test/test_entry_filter.rb
test/test_excerpt.rb
test/test_filters.rb
test/test_front_matter_defaults.rb
test/test_generated_site.rb
test/test_kramdown.rb
test/test_layout_reader.rb
test/test_liquid_extensions.rb
test/test_page.rb
test/test_page_without_a_file.rb
test/test_plugin_manager.rb
test/test_regenerator.rb
test/test_related_posts.rb
test/test_sass.rb
test/test_site.rb
test/test_site_drop.rb
test/test_static_file.rb
test/test_tags.rb
test/test_utils.rb

Re-enable Rubocop on our Test suite.
(All changes to the test files are the result of `rubocop -a`)

Fix Rubocop offences in test files

---

lib/site_template/404.html

Github Pages was not using the custom 404 page on my site.
I implemented the attached fix per [Github](https://help.github.com/articles/creating-a-custom-404-page-for-your-github-pages-site/) and now all is as it should be.

Fix custom 404 page for GitHub pages

---

test/test_collections.rb

Some of the `assert_equal` calls have been fixed in othe PRs but this is a `refute_equal` that was sending the actual first and then the expected, which is against the expected pattern and might as well be cleaned up.

fix up refute_equal call

---

test/test_ansi.rb
test/test_collections.rb
test/test_commands_serve.rb
test/test_configuration.rb
test/test_kramdown.rb
test/test_liquid_extensions.rb
test/test_regenerator.rb

Abstracts just the *autocorrected* changes from #7130 (without the custom RuboCop cop that is entirely outside Jekyll's scope).

Fix incorrectly passed arguments to assert_equal

---

docs/help/index.md

[DEV Community](https://dev.to/) is a burgeoning source of guidance and discussion on software topics, especially web dev. This will be a useful link to point to the official place to discuss Jekyll matters on the platform.
A few additional links pertaining to dev.to
Traffic stats: https://www.similarweb.com/website/dev.to
Twitter: https://twitter.com/thepracticaldev
Jekyll tag (as included in PR): https://dev.to/t/jekyll
Some example Jekyll posts:
https://dev.to/evantypanski/the-art-of-a-personal-website-15h1
https://dev.to/adrienjoly/how-to-maintain-a-collection-of-music-albums-online-using-jekyll-and-github-pages-3hd6
https://dev.to/jaybeekeeper/getting-started-with-jekyll-3nf9
Happy coding :heart:

Add DEV Community's Jekyll tag to community page

---

docs/help/index.md

it looks like I forgot to include the dev.to link in the previous PR (I added only the jekyll tag link), I'm sorry for this issue but I think it's  important to add it for the UI consistency ( all links are yellow which is not the case for "The DEV Community" as I didn't includethe link ).
This should be a quick  easy merge, Thanks :)

Add dev.to link

---

docs/_docs/upgrading/3-to-4.md

So that we can document breaking changes and their solutions in the same PR that introduces the breaking-change.
This document is hidden from the unwitting general public until we add a link to this document via the navigation. However, it can be accessed for preview purposes by pointing the browser to the `permalink`

Initialize upgrading doc for v4.0

---

.travis.yml

Some weird bug in `Bundler-1.16.3` is breaking our test-suite on Ruby 2.4 and 2.5 on Travis CI. Attempting to resolve by locking Bundler to `v1.16.2`.

Lock Travis to Bundler-1.16.2

---

features/post_excerpts.feature
lib/jekyll/excerpt.rb

As noted in #6824 the latest feature to disable liquid rendering did not extend to excerpts. This is a bit of a simple copy and past of logic. I do not exactly understand  how to add the updated tests for it but figured someone might be able to help me move it along.

Do not process Liquid in post excerpt when disabled in front matter

---

.travis.yml

This doesn't gain us much, since most of our builds are not explicitly defined, but hopefully it adds a bit of clarity for somebody who is not used to looking at our Travis builds.

Name some of our Travis builds

---

docs/_docs/templates.md

I was getting errors when trying to use the new `date_to_long_string: "ordinal"` parameter on my Jekyll website. I found out that this feature was introduced in Jekyll 3.8.0 (jekyll/jekyll#6773) and realised that the reason why I couldn't use it was because I had installed Jekyll through the `github_pages` gem, which only supports version 3.7.3 still today.
This adds a version badge to the two filters documented here, so that it may help others if they get the same error.
(cc @jekyll/documentation)

Add version badge for date filters with ordinal

---

lib/jekyll/commands/clean.rb
lib/jekyll/configuration.rb

Remove 'cache_dir' during `jekyll clean`

---

README.markdown

Hi, I'm making updates for Open Collective. Either you or a supporter signed this repo up for Open Collective. This pull request adds backers and sponsors from your Open Collective https://opencollective.com/jekyll❤️
It adds two badges at the top to show the latest number of backers and sponsors. It also adds placeholders so that the avatar/logo of new backers/sponsors can automatically be shown without having to update your README.md. [more info](https://github.com/opencollective/opencollective/wiki/Github-banner). See how it looks on this [repo](https://github.com/apex/apex#backers).
You can also add a postinstall script to let people know after npm|yarn install that you are welcoming donations (optional). [More info](https://github.com/OpenCollective/opencollective-cli)
You can also …

Display Open Collective backers and sponsors

---

README.markdown

The badges currently point to `https://github.com/jekyll/jekyll/blob/master/codeclimate` and `https://github.com/jekyll/jekyll/blob/master/coverage` erroneously

Fix links in Code Climate badges

---

lib/jekyll/log_adapter.rb

To allow one to deduce what version of Jekyll was used to build the site by simply reading through the complete `--verbose` output

Output Jekyll Version while debugging

---

lib/site_template/.gitignore
lib/theme_template/gitignore.erb

Following #7169 
When creating a new site or a new theme, make sure we don't version the default cache directory.

Ignore cache directory

---

docs/_tutorials/cache_api.md
lib/jekyll.rb
lib/jekyll/cache.rb
lib/jekyll/site.rb
lib/site_template/.gitignore
lib/theme_template/gitignore.erb
test/test_site.rb

This adds a basic caching mechanism to Jekyll.
Any internal Jekyll class, or any Jekyll plugin, can create its own cache. That cache will be shared among all instances of that class or plugin. The cache is essentially a key-value store.
The following operations can be performed on a cache:
* Get the `value` associated with a `key`
* Set the `value` associated with a `key`
* Delete the `value` associated with a `key`
* Check if a `key` exists in the cache
* Clear the cache
Additionally, all caches can be cleared at once.
The cache as implemented here is not persistent at all. The idea is that most users would use a custom cache plugin to provide a persistent backend (if that is desired). This is not being done out of the box because of security concerns, and because there are many times …

Add Cache class

---

lib/jekyll/tags/include.rb

Because, `:gsub` with string arguments are faster..

Replace regex arg to :gsub with a string arg

---

docs/_docs/windows.md

I user Windows Subsystem for Linux with Ubuntu 18.04 distribution.
Follow this page, I got an error bellow. And change 2.4 to 2.5 can resolve it.
```
E: Unable to locate package ruby2.4
E: Couldn't find any package by glob 'ruby2.4'
E: Couldn't find any package by regex 'ruby2.4'
E: Unable to locate package ruby2.4-dev
E: Couldn't find any package by glob 'ruby2.4-dev'
E: Couldn't find any package by regex 'ruby2.4-dev'
```

Resolve "Unable to locate package ruby2.4" error

---

docs/_docs/step-by-step/07-assets.md

In [step 7](https://jekyllrb.com/docs/step-by-step/07-assets/) of the step-by-step tutorial, the reader is instructed to create `/assets/css/styles.scss`, and then add the stylesheet to their default layout using `<link rel="stylesheet" href="/assets/styles.css">`.  However, Jekyll places the processed stylesheet at `/assets/css/styles.css`.  This causes the stylesheet not to be applied.
This pull request corrects the link tag to `<link rel="stylesheet" href="/assets/css/styles.css">`, so as to reduce confusion among readers of the tutorial.

Correct stylesheet url in tutorial step 7

---

benchmark/schwartzian_transform.rb

Refactoring of some duplicated lines in the `benchmark/schwartzian_transform.rb`

Small benchmark refactoring

---

docs/_data/showcase.yml

Hey folks!
I work at Spotify and my team recently launched a new version of our developer site over at <https://developer.spotify.com> with Jekyll.
Thought we'd submit it to the showcase! Let me know if this isn't the right place to submit it. Thank you! :)

Add developer.spotify.com to the Jekyll Showcase

---

docs/_docs/posts.md

Having quotes in the markdown was breaking the references to images and other assets

removes quotes from markdown for assets

---

lib/jekyll/entry_filter.rb
test/source/symlink-test/symlinked-file-outside-source
test/test_entry_filter.rb
test/test_layout_reader.rb

In `EntryFilter#filter`, we check for `include?` before we check for `symlink?`, which allows symlinks to be read in a build when they shouldn't be by just including them.
/cc https://github.com/jekyll/jekyll/pull/7224

Security: fix `include` bypass of `EntryFilter#filter` symlink check

---

docs/_docs/step-by-step/08-blogging.md

I initially saved my blog.html file to the wrong directory. Making it explicit on row 65 may help other beginners avoid confusion.

explicit location of where to create blog.html

---

lib/jekyll/entry_filter.rb
test/source/symlink-test/symlinked-file-outside-source
test/test_entry_filter.rb
test/test_layout_reader.rb

Backports #7226 for the 3.6.x series of releases.

3.6.x: security: fix `include` bypass of `EntryFilter#filter` symlink check

---

docs/_docs/collections.md

I was just re-reading through the docs and found this small blip, thought I'd correct it.

Fix a small grammar error/typo in the docs

---

lib/jekyll/frontmatter_defaults.rb

Since `#applies?` requires both conditions to be `true`, let us run the more expensive method only if required

Check if scope applies to type before given path

---

docs/_docs/configuration/environments.md

This is a new take on https://github.com/jekyll/jekyll/pull/7193 after the docs where restructured recently. 
I reference the build command options as a valid solutions to handle environments.
Why is this change important: It took me more than a year an several github issues/comments to understand this feature / learn of its existence. I think the main reason is, I always searched for a solution for multiple environments and only found this page which does not reference the build command that allows multiple config files.

environments.md: reference the build command options that allows multiple config files

---

lib/jekyll/utils/platforms.rb

I want to use jekyll in my android phone.
But the android doesn't allow accessing to /proc/version.
Currently jekyll uses information from /proc/version to determinate it's windows or not.
I think it's safe to ignore this error.

Ignore permission error of /proc/version

---

lib/jekyll/document.rb

Very simple PR. Documented two methods and slightly changed one of them.
Reasons:
- Undocumented public methods.
- Memoization of `source_file_mtime` dropped since it was used only once.

Document two methods, simplify one of the methods

---

lib/jekyll.rb
test/test_path_sanitization.rb

Depending on whether the asserted scenario is outside the scope of `Jekyll.sanitized_path`, this PR can be seen as a bug-report-cum-resolution combo or just an edge-case noise.
/cc @benbalter for his opinion on the relevance of the asserted scenario

Strip extra slashes via `Jekyll.sanitized_path`

---

README.markdown

Fix broken Contributors link in README.markdown

Fix broken Contributors link in README.markdown

---

lib/jekyll/drops/site_drop.rb

- **This is a :roll_eyes: micro-optimization.**
Check if keys of hash `site.collections` includes given drop-key only if the drop-key isn't `"posts"`

Check key in collections only if it isn't "posts"

---

docs/_posts/2018-09-19-security-fixes-for-3-6-3-7-3-8.markdown

Release Post for `v3.6.3`, `v3.7.4` and `v3.8.4`
@parkr Feel free to push changes to the branch as you see fit.

Add Release Post for v3.6.3, v3.7.4 and v3.8.4

---

docs/_tutorials/convert-existing-site-to-jekyll.md

It adds a `<title>` tag to the `items` section of the rss example feed. The existing title tag is for the site title, but each item entry should also have a title.

Docs: Add title tag to item in RSS template

---

lib/jekyll/commands/build.rb

- This is a 🐛 bug fix. 
This check was introduced as a bridge between [`jekyll-watcher-1.4.0`](https://github.com/jekyll/jekyll-watch/blob/v1.4.0/lib/jekyll/watcher.rb) and [`jekyll-watcher-1.5.0`](https://github.com/jekyll/jekyll-watch/blob/v1.5.0/lib/jekyll/watcher.rb) which is no longer necessary because Jekyll requires at least `jekyll-watcher-2.0.0` by default
See: https://github.com/jekyll/jekyll-watch/pull/40
https://github.com/jekyll/jekyll/blob/a70ed3713f9189bd8497dddb5cc94434d206a017/jekyll.gemspec#L38

Drop support for `jekyll-watch-1.4.0` and older

---

lib/jekyll/converters/identity.rb
lib/jekyll/converters/markdown.rb
lib/jekyll/converters/smartypants.rb

Added documentation for Identity, Markdown and SmartyPants converters.
Add some links to the Converter usage examples.
---
- Documented method for converters and pointed to the appropriate usage guide.

Document converter methods

---

docs/_tutorials/convert-existing-site-to-jekyll.md

If this is missing, the feed validator at https://validator.w3.org/feed/
will output the message ```This feed does not validate.
line 28, column 4: Missing channel element: link [help]
</channel>```

Docs: Add link tag to item in RSS template

---

lib/jekyll/converters/markdown.rb
test/test_kramdown.rb

**Problem:** Much of a site's generation time is spent converting Markdown.
**Assumption:** Markdown converters are trivially deterministic.
**Proposed solution:** Cache rendered Markdown.
Given a blob of raw Markdown, we hash the blob and see if this blob as already been converted. If it has been, we can return the cached HTML. If it has not, we will convert it like normal, and then save the output to our cache.
~~This is simply using the filesystem as a cache. The hash of the raw Markdown is the filename, and the file contains the converted Markdown.~~
Since Markdown converters are trivially deterministic, none of this depends on the state of the site, and can be totally separate from incremental regeneration.
~~This is absolutely related to #7158, which will clear the cache on `jekyll …

Cache converted markdown

---

lib/jekyll.rb
lib/jekyll/reporting_context.rb
lib/jekyll/tags/include.rb

Many sites use includes for things like headers or footers that are identical on all pages.
Instead of rendering these includes for each page that includes them, it would be nice to detect when an include does not rely on anything page specific and cache the rendered include.
For starters, we can cache any includes that do not have any Liquid (which is not a very common case). Next, we could cache includes that only access `{{ site.* }}` (which is a more common case) by creating a special Liquid context which is capable of reporting if anything that hasn't been whitelisted has been accessed.
This PR is in a very early stage, and feedback is appreciated.

WIP: Cache rendered includes

---

lib/jekyll/cache.rb

If a `Hash` has a default proc, it cannot be Marshalled. It can be used to create a new `Hash` without any defaults, which can then be dumped.
Either way, if an object cannot be dumped, we may still want to "cache" it in memory. This change makes our `Cache` compatible with such objects, and it will simply avoid dumping objects that cannot be dumped.

Cache: Do not dump undumpable objects

---

docs/_docs/configuration.md
lib/jekyll/configuration.rb
test/test_configuration.rb

When looking for a `_config.*` file to load, also look for `_config.toml`.
Currently, Jekyll can load a TOML configuration file, but will only do so if explicitly told to with a command line option. With this PR, Jekyll will automatically look for a `_config.toml` file as well.
Default behavior remains the same: `_config.yml` and `_config.yaml` are tried first. If those don't exist, and `_config.toml` does exist, then that will be used instead.

Automatically load _config.toml

---

lib/jekyll/readers/post_reader.rb
test/source/_posts/2008-02-03-wrong-extension.yml
test/test_post_reader.rb
test/test_site.rb

Adresses #7255 
Issue #7255 suggests to skip processing posts that can not be read due to wrong (?) file extension and log/print the exception. 
The fix will also catch 
```
'undefined method `valid_encoding?' for nil:NilClass'
```
during startup of `jekyll serve`.
If anyone can help me pointing to the right place/approach to add a corresponding test, I'd love to do that.

Skip processing posts that can not be read

---

History.markdown
lib/jekyll/renderer.rb

This reverts b8dfc9a and 1512841
Ref: https://github.com/jekyll/jekyll/issues/7320#issuecomment-431398028
Resolves #7320 
*May additionally resolve* #7323

Revert "Cache converter in renderer"

---

docs/_docs/liquid/filters.md

Utilize the power of Liquid Templating and the fact that Markdown is rendered by Jekyll after an initial Liquid Rendering, to DRY content and improve maintainability.
- The Shopify Filter URL is now defined at just one place &mdash; any future change to this *external URL* need be changed here at just one place.
- Adding a link to a filter that is introduced upstream in the future is as simple as adding the name to the `shopify_filters:` array in the front matter.

Liquid templating to DRY content

---

docs/_data/jekyll_variables.yml
docs/_docs/variables.md

Move page API to YAML files. (following #7335)
What if Jekyll API was available as JSON output, could IDE plugins use it to implement autocompletion for instance?

docs: Page variables as YAML data

---

Gemfile
lib/jekyll/cleaner.rb
lib/jekyll/commands/serve/servlet.rb
lib/jekyll/document.rb
lib/jekyll/excerpt.rb
lib/jekyll/frontmatter_defaults.rb
lib/jekyll/tags/highlight.rb
lib/jekyll/tags/include.rb
lib/jekyll/tags/post_url.rb
lib/jekyll/utils/ansi.rb

RuboCop [v0.60.0](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md#0600-2018-10-26) has been released

Bump RuboCop to v0.60.x

---

.github/ISSUE_TEMPLATE/documentation.md

This is a change to an :octocat: issue template.
N/A
None, because this doesn't affect the codebase.

Remove redundant instruction comment

---

lib/jekyll/site.rb

- The test suite passes (run `script/cibuild` to verify this)
Two common *callers*, `Site#tags` and `Site#categories`, are frequently called in Liquid Templates via the `SiteDrop` class
https://github.com/jekyll/jekyll/blob/44a8035d135b9f2a5b0102fcec84d3c9a87a79af/lib/jekyll/drops/site_drop.rb#L11
https://github.com/jekyll/jekyll/blob/44a8035d135b9f2a5b0102fcec84d3c9a87a79af/lib/jekyll/site.rb#L243-L249

Memoize Site#post_attr_hash

---

lib/jekyll/liquid_renderer.rb
lib/jekyll/liquid_renderer/file.rb

As a direct consequence of #7136, the `count` field in the `--profile` output table returns `1` for includes rendered for each "page" / "document", which doesn't provide the user with valuable information.
This PR restores the "profile data"

Measure the no. of times a template gets rendered

---

docs/_docs/themes.md
features/theme_configuration.feature
lib/jekyll/site.rb
test/fixtures/test-theme/_config.yml
test/test_site.rb

- The test suite passes
Loading config files from within a theme-gem is beneficial because users need not:
- manually adjust their local config file to use theme-specific settings (or)
- have to copy a config file from the theme repo to use theme-specific settings
- can easily *test* various complex themes with *extensive settings* before settling on one.
The proposed changes ensure minimal side-effects:
- Default config keys set by Jekyll cannot be overridden by a theme config. That *ball is still in the user's court.* A theme expecting its user to change Jekyll defaults is a sign of design smell.
- The theme config should be a Hash. Otherwise, its simply …

Load config file from within current theme-gem

---

lib/jekyll/site.rb

- This is a :bug: fix 
Memoize the return value of Site#documents as it is a potentially expensive method that involves `Enumerable#reduce` and multiple array allocations.
This issue was discovered while building the *"Official Docs Site"*
Source of *"performance drain"*:
https://github.com/jekyll/jekyll/blob/1e9cd27dc40c26624abb34ad947b314c9571ccc7/lib/jekyll/drops/site_drop.rb#L11
Use of drain in the *"Official Docs Site"*
https://github.com/jekyll/jekyll/blob/1e9cd27dc40c26624abb34ad947b314c9571ccc7/docs/_includes/docs_option.html#L2
https://github.com/jekyll/jekyll/blob/1e9cd27dc40c26624abb34ad947b314c9571ccc7/docs/_includes/docs_ul.html#L3

Memoize the return value of Site#documents

---

docs/_docs/plugins/tags.md

I have tried adding some relevant documentation on adding custom liquid tag blocks using a Jekyll Plugin. On my local machine, I have run the Jekyll server using the [instructions](https://github.com/jekyll/jekyll/tree/master/docs#running-locally) in the readme file and everything seems to be working just fine.
Fix  #7358.

Add documentation for custom tag blocks

---

docs/pages/resources.md

I added 99Inbound to the list of services offering a form endpoint integration for Jekyll.
In terms of adding 99Inbound to the top of the list -- I'm not trying to trump existing integration listings -- It looks like you guys sort these sections in alphabetical order

Added 99inbound's Jekyll post to form resources

---

docs/_includes/footer.html

On the footer of https://jekyllrb.com/, there was a missing closing tag `</a>` for the Tidelift link. The `<a>` element now has a closing tag `</a>`.

Fix link to Tidelift in site's footer

---

docs/_includes/footer.html

On https://jekyllrb.com/, there was no link in the footer to the OpenCollective Jekyll page.
Now there is one on "Sponsored by".

:sparkles: Add a link to OpenCollective backing

---

docs/_docs/installation/macos.md

The `ruby` formula was changed to [keg-only], which means the `ruby(1)` executable is no longer linked and the installation instructions no longer work—the system Ruby continues to be used.
[keg-only]: https://github.com/Homebrew/homebrew-core/pull/33503

Remove installation instructions with Homebrew

---

docs/_docs/installation/macos.md

https://github.com/jekyll/jekyll/pull/7381 left a few problems behind: a dead link to the section that was removed, and prose that can be confusing to the newcomer.

Fix dead link and misleading prose

---

.codeclimate.yml

Exclude superfluous files that do not affect our CodeClimate Score
(Any file that isn't `lib/**/*.rb`)

Update excludes for CodeClimate Analyses

---

docs/_docs/assets.md

If I am understanding this right, my re-wording helps me clearly visualize what's going on in plainer English.

Proposed re-wording of Sass note. :)

---

docs/_data/jekyll_filters.yml

* Add missing colon to truncate filter
* In example output remove '...' since the truncate
filter is used with the optional argument (string
to append) which in this case is an empty string

docs: Fix group_by_exp filter example

---

docs/pages/team.md

- Removed ordered lists, and replaces them with unordered lists
- Remove myself as project lead
- Sort all person lists by name

adjust team page listings

---

.travis.yml

This is a 🔧  CI config change. 
Given we don't use any new features from Ruby > 2.3, we can speed up our CI builds a bit and save some resources 🌱  by not testing the intermediary Ruby version.

dev: test oldest and latest Ruby only

---

docs/_docs/installation/ubuntu.md

The exports in .bashrc should include quotes to handle spaces in `$HOME` and/or `$PATH`.
The exports in .bashrc should include quotes to handle spaces in `$HOME` and/or `$PATH`.
None.
None

[Docs] Fix BASH code-block in ubuntu.md

---

Gemfile
lib/jekyll/theme.rb
test/fixtures/test-theme-symlink/test-theme-symlink.gemspec
test/test_theme_assets_reader.rb

This PR fixes an issue where symlinks could be used by themes to bypass security protections. In this specific case, theme _directories_ could be symlinks (e.g. `theme_dir/assets -> /etc`) that break out of our very carefully-constructed cage. In this case, we want to re-apply the theme root (e.g. `theme_dir/assets -> /etc -> theme_dir/etc`).
This fix & test was written by @dbussink.
I'd like to backport this to 3.8 and 3.7.

Theme gems: ensure directories aren't symlinks

---

lib/jekyll/drops/document_drop.rb
lib/jekyll/drops/excerpt_drop.rb
test/test_document.rb

Documents should be able to relay their `date` attribute when queried for via `{{ page.date }}`
Fixes #7244

Documents should be able to render their date

---

lib/jekyll/static_file.rb
test/test_static_file.rb

Since a `StaticFile` object is initialized with the `site` instance, the object's default debug string contains the entire config data of the site.
Providing a custom string ensures that we get a simple result allowing faster debugging.
Additionally, this maintains consistency with core classes `Jekyll::Page` and `Jekyll::Document`
A direct response to the output in [test log](https://travis-ci.org/jekyll/jekyll/jobs/467560220#L738)

Add a custom inspect string for StaticFile objects

---

lib/jekyll/reader.rb

This proposal is mainly to replace the following steps with optimized alternatives and see what Utterson feels about it.
```ruby
dot_dirs  = dot.select { |file| File.directory?(@site.in_source_dir(base, file)) }
dot_pages = dot_files.select { |file| Utils.has_yaml_header?(@site.in_source_dir(base, file)) }
```
Also `dot_files = (dot - dot_dirs)` simply exists to create another array `dot_static_files` ...

Reduce array traversal in Jekyll::Reader

---

test/helper.rb
test/test_layout_reader.rb

- Introduce a test-helper to generate symlinks only if the test environment has access to the target file. If access is denied, skip creating symlink (and therefore the test itself) with a terminal output
- Delete with `{ force: true }` so that the test doesn't abort if symlink wasn't created
Would like to backport this to stable branches which include the changed tests: `3.6-stable`, `3.7-stable` and `3.8-stable`

Create symlink only if target is accessible

---

Gemfile

Until JRuby is able to handle refinements introduced in [`i18n-1.3.0`](https://github.com/svenfuchs/i18n/compare/v1.2.0...v1.3.0)

Lock JRuby builds on Travis CI to i18n-1.2.x

---

.travis.yml

- https://www.ruby-lang.org/en/news/2018/12/25/ruby-2-6-0-released/
- https://github.com/rvm/rvm/pull/4542

Test with the new Ruby v2.6

---

lib/jekyll/renderer.rb

Change OR operator to a lazy assignment in Jekyll::Renderer#layouts
When warnings are enabled, Jekyll emits a rather insidious warning message (inidious because of how many times it occurs).
> warning: instance variable @layouts not initialized
This patch fixes the problem.
Based on other methods in the Jekyll::Renderer class, I believe the intention is to use a lazy assignment operator here instead of an OR operation.
If that's not the case, then I can update the patch to allow the OR operator to be used without emitting a warning.
Patch.

Fix Interpreter warning from Jekyll::Renderer

---

features/collections.feature
lib/jekyll/static_file.rb

- This is a 🐛 bug fix/
Collections other than `posts` can contain static assets along with Markdown files.
If a collection is initialized with metadata `output: false`, then neither its "documents" nor its "files" should be *output* to the destination directory.
Resolves #7389

Dont write static files from unrendered collection

---

lib/jekyll/excerpt.rb
test/source/_plugins/custom_block.rb
test/source/_posts/2018-11-15-excerpt-liquid-block.md
test/test_excerpt.rb
test/test_generated_site.rb

Resolves #7380. This updates `lib/jekyll/excerpts.rb` to improve handling of Liquid blocks which are not properly closed in the excerpt. User-defined custom blocks can now be auto-closed and intermediate logic in blocks (e.g. `else`, `elsif`, `break`, and `continue`) no longer generate issues.

Excerpt handling of custom and intermediate tags

---

docs/_docs/permalinks.md

- Fixes grammar by removing improper `'` in `lets you`
- Fixes typo `in` by replacing with `it`, in the sentence "Luckily, Jekyll lets you set it globally in your `_config.yml`."
- Clarifies unclear antecedent `it` in the sentence "Luckily, Jekyll lets you set it globally in your `_config.yml`." by replacing `it`  with `the permalink structure`
This is not related to an existing issue.
This does not require a semver change.

Permalink docs typo fixes

---

docs/_docs/community/community.md

Excluded aticles and pronouns "the" and "an" from the anchor link tags and moved them outside of the anchor link on `line 18` and `line 19` respectively.
Edited the anchor link on `line 11` and formatted the grammar on `line 17`.
Removed unnecessary aticles and pronouns on the anchor links in `line 18` and `line 19` and added them outside the anchor link.
Is this related to any GitHub issue(s)? No
None

Fixed unnecessary aticles and pronouns

---

docs/_docs/contributing.md

Excluded [aticles/articles](http://www.studyandexam.com/english-aticles.html) like **"the"** and **"an"** from the anchor link tags and moved them outside of the anchor link on `line 11`, `line 19`, `line 20`, `line 21` and `line 56` respectively.
I have removed the [aticles/articles](http://www.studyandexam.com/english-aticles.html) like **"the"** and **"an"** from the anchor link tags and added them outside of the anchor link on `line 11`, `line 19`, `line 20`, `line 21` and `line 56` respectively.
Is this related to any GitHub issue(s)? No
None

Grammatical correction

---

Gemfile

To allow testing and building with latest version available

Relax version constraint on classifier-reborn gem

---

docs/_docs/configuration/options.md

This adds a small note that the SSL key and certificate must be stored in or symlinked from the site source when using `--ssl-cert` and `--ssl-key`.
Users (like me and in #4056) may assume that keys and certs can be stored anywhere. I have not found documentation that notes that they should be in the site source.
However, I am concerned that we should also note that keys and certs should never be added to source control. I have not added this because the Jekyll docs may not be the appropriate place to be giving security advice.

Docs: store SSL key and cert in site source

---

lib/jekyll/external.rb

Novice users don't know that running with `bundle exec` requires their plugin-gems to be listed in their Gemfile as well.
Related: #7475

Remind user to include gem in the Gemfile on error

---

lib/jekyll/page.rb

So that it's consistent with `Document` objects, `StaticFile` objects and also with `Convertible#to_liquid`
https://github.com/jekyll/jekyll/blob/4271495fcaad4073b2375b76089041acd16ffb49/lib/jekyll/document.rb#L39
https://github.com/jekyll/jekyll/blob/4271495fcaad4073b2375b76089041acd16ffb49/lib/jekyll/static_file.rb#L37
https://github.com/jekyll/jekyll/blob/4271495fcaad4073b2375b76089041acd16ffb49/lib/jekyll/convertible.rb#L119
(This will have a *minor* performance gain in sites with numerous `pages` and uses `front matter defaults` since the paths are cached internally now..)

Search Front matter defaults for Page objects with relative_path

---

docs/_docs/continuous-integration/circleci.md

When setting up CircleCI for my Jekyll site I needed to have the site built first before running HTMLProofer. So I switched their order to reflect that. Other than that this guide works like a charm!

Changed order of steps

---

jekyll.gemspec

Before we start to release, pre versions for v4, I thought some cleaning wouldn't hurt:
- list every lead developers in authors (currently Matt)
- use generic email 
- add metadata for issues, changelog, source code and homepage
- require Rubygems > 2.5

dev: update gemspec

---

appveyor.yml

AppVeyor has added support for Ruby 2.6.1 : https://www.appveyor.com/updates/2019/02/11/

Test with Ruby 2.6 on AppVeyor [skip travis]

---

docs/_docs/installation/windows.md

[TZInfo-2.0 introduced changes](https://github.com/tzinfo/tzinfo/releases/tag/v2.0.0) that will silently affect users on Windows.
Document that they need to lock to the older series for Jekyll 3.x
Discovered while investigating #7516

Notify users on Windows to use tzinfo-1.x series

---

docs/_docs/resources.md

Add a link to CloudSh search in the Integrations section of the Resources page.

Add CloudSh to resource page.

---

features/cache.feature
lib/jekyll/cache.rb
lib/jekyll/site.rb
test/test_site.rb

Resolves #7220 
Additionally, this **ensures** that the cache is always "within the source_dir" and also sanitizes the `cache_dir` configuration..

Configure cache_dir

---

docs/_docs/includes.md

Otherwise it will result in 
Liquid Exception: Invalid syntax for include tag. File contains invalid characters or sequences: Valid syntax: {% include file.ext param='value' param2='value' %} in FILE.html

Docs: check if var exists before include tag

---

lib/jekyll/readers/post_reader.rb

- This is a 🐛 bug fix
This pull request changes the log level used from `debug` to `warn` when reading posts that are dated in the future.
Resolves #7493

changed future post loglevel to warn to help user narrow down issues

---

docs/_docs/collections.md
features/collections.feature
features/collections_dir.feature
features/step_definitions.rb
lib/jekyll/collection.rb
test/source/_tutorials/dive-in-and-publish-already.md
test/source/_tutorials/extending-with-plugins.md
test/source/_tutorials/getting-started.md
test/source/_tutorials/graduation-day.md
test/source/_tutorials/lets-roll.md
test/source/_tutorials/tip-of-the-iceberg.md
test/test_collections.rb

- I've added tests (if it's a bug, feature or enhancement)
Allow custom sorting of Document objects in collections by via the collection's metadata.
The two routes available are by either setting a `sort_by` metadata string or by setting an `order` array, with the latter route having a greater precedence.
Resolves #5754 
This is also a fresh take on #5904 
/cc @gvwilson

Allow custom sorting of collection documents

---

features/collections.feature
lib/jekyll/document.rb
lib/jekyll/page.rb
lib/jekyll/static_file.rb
test/source/_methods/trailing-dots...md
test/source/_posts/2018-10-12-trailing-dots...markdown
test/source/trailing-dots...md
test/test_collections.rb
test/test_document.rb
test/test_filters.rb
test/test_generated_site.rb
test/test_page.rb
test/test_site.rb

Render files with trailing dots in their "basename" (filename w/o extension) into correct url instead of generating incorrect URLs or aborting the build entirely
Resolves #7246

Handle files with trailing dots in their basename

---

docs/_docs/collections.md

The document on Collections states that collection documents without front matter will not be generated, but this is not true. Those documents without front matter will be regarded as [static-files](https://jekyllrb.com/docs/static-files/) and copied over to the destination (e.g., `_site`).
You need to always add front matter to collections documents (especially .md files). If `output: true` is set in collections metadata, then collections documents with front matter will get generated (i.e., converted to .html and copied to `_site`). If `output: false` (the default value) is set in collections metadata, then …

Clarify docs on collections regarding the need for front matter

---

.travis.yml
appveyor.yml
script/profile-docs

Build Jekyll's Documentation site in 'debug' mode and outputs the site's profile stats.
Helps detecting *hard* breaking-changes (`jekyll build` aborts) and optimizations in the `build` process.
*Also, a basic stand-in for Utterson who's A.W.O.L.*

Add a script to profile docs with CI

---

docs/_docs/themes.md

Fix incorrect Windows path in themes.md

---

Gemfile
docs/_docs/upgrading/3-to-4.md
lib/jekyll/commands/new.rb
lib/jekyll/utils/win_tz.rb

- This is an 🙋 enhancement.
- TZInfo-2.0 returns local time with the correct UTC Offset.
- WinTZ utility will now generate inaccurate results with TZInfo-1.x
Discovered while investigating #7516

Upgrade WinTZ utility to use TZInfo-2.0

---

Gemfile
History.markdown
docs/_docs/upgrading/3-to-4.md
lib/jekyll/commands/new.rb
lib/jekyll/utils/win_tz.rb

Revert commit d8c745ca30c91c3d8678c694b724bd6eac288cad.
Revert commit 7ee2e26d6c9eb9523195521e8bece7908cf83eac.
Revert commit 13cbef42219fc3821f0a0a63d46923c9ce4b25cf.
Lock use of `tzinfo` gem (Windows n JRuby only) to `v1.x` to avoid conflicts with [`activesupport` gem](https://rubygems.org/gems/activesupport) which is typically present in a site's *gemset* via some plugins and also bundled with the [`github-pages` gem](https://rubygems.org/gems/github-pages)
Because ActiveSupport locks `tzinfo` to `v1.x`, Bundler will resolve to the last available version for `tzinfo-1.x`. Forcing the use of `v2.0` results in Bundler resolving to a much *older version of ActiveSupport* (on master):

Lock use of TZInfo gem to v1.x

---

Gemfile
lib/jekyll/theme.rb
test/fixtures/test-theme-symlink/test-theme-symlink.gemspec
test/test_theme_assets_reader.rb

Backport #7419 for v3.8.x: Theme gems: ensure directories aren't symlinks

---

lib/jekyll/excerpt.rb
test/source/_plugins/custom_block.rb
test/source/_posts/2018-11-15-excerpt-liquid-block.md
test/test_excerpt.rb
test/test_generated_site.rb

Backport #7382 for v3.8.x: Excerpt handling of custom and intermediate tags

---

.travis.yml
Gemfile

This is a PR to **`3.8-stable`** branch
CI Builds are currently failing on **`3.8-stable`** branch because of testing on EOL Ruby 2.2.
This PR is to attempt fixing those builds on Travis and AppVeyor

Fix CI builds on older Ruby versions

---

lib/jekyll/readers/static_file_reader.rb

`Array#map` returns a new array derived from the given array after the iteration.
`Array#each` returns self after the iteration.
In `StaticFileReader#read`, `@unfiltered_content` is being returned instead of the array created by `Array#map`

Fix unnecessary allocations via StaticFileReader

---

lib/jekyll/commands/build.rb
lib/jekyll/configuration.rb
test/test_configuration.rb

Currently user-provided paths (to `jekyll build` or `jekyll serve`) are output as is. This results in a very minor visual mismatch:
```bash
$ jekyll build --source example
Configuration file: example/_config.yml
Source: example
Destination: /usr/projects/demo/_site
```
```bash
$ jekyll build --config _config_dev.yml
Configuration file: _config_dev.yml
Source: /usr/projects/demo
Destination: /usr/projects/demo/_site
```
With the proposed change, the output becomes:
```bash
$ jekyll build --source example
Configuration file: /usr/projects/demo/example/_config.yml
Source: /usr/projects/demo/example
Destination: /usr/projects/demo/_site
Incremental build: …
```

Utilize absolute paths of user-provided file paths

---

lib/jekyll/filters.rb

- This is an `optimization` change.
Cache output of `private` method `Jekyll::Filters#item_property`
The official Documentation site at `docs` uses this method heavily via the `where` and `sort` Liquid Filters.

Cache computed item property

---

lib/jekyll/commands/doctor.rb

Resolves the following scenario:
```ruby
url = nil
Addressable::URI.parse(url).absolute?
```

Don't check if site URL is absolute if it is nil

---

.rubocop.yml
lib/jekyll/configuration.rb
lib/jekyll/converters/smartypants.rb

Communicative parameter names improve readability.
Changing method signature of `Configuration#renamed_key` because the *"unused parameter"* was never used even [at the time of its inception](https://github.com/jekyll/jekyll/commit/399606c54447b5c4853981ae52cf40c30195c3be).

Use communicative method parameters

---

lib/jekyll/site.rb

`site.pages` is already a flat array of `pages`. Calling `flatten` on it and creating a new Array instance is unnecessary.

Avoid unnecessary duplication of pages array

---

features/rendering.feature
lib/jekyll/liquid_renderer.rb

**Fixes a regression** introduced in **`v3.8`** via commit https://github.com/jekyll/jekyll/commit/e1b64f9afd8391b9aeaea6a3b00700a8851585d1
Fixes #7547 
Though the issue ticket has misinterpreted the error, the issue is relevant to a path of any length containing parentheses, on any platform
Recommend backport to **`3.8-stable`**

Escape valid special chars in a site's path name

---

lib/jekyll/document.rb

- This is a minor :zap: optimization change
For a given `Document` instance, `#excerpt_separator` is called at following places in Jekyll Core in a site with default configuration:
https://github.com/jekyll/jekyll/blob/bdbf35136ebd7b9f193568bd2728721ef5d020d2/lib/jekyll/document.rb#L346-L348
https://github.com/jekyll/jekyll/blob/bdbf35136ebd7b9f193568bd2728721ef5d020d2/lib/jekyll/excerpt.rb#L137-L138
*Since this is a minor optimization, the perf gain is very minimal and can also be achieved at client-side by disabling excerpt generation.*

Memoize Document#excerpt_separator

---

lib/jekyll/converters/markdown.rb

- Reduced noise in error message output for an invalid processor.
```
Jekyll Feed: Generating feed for posts
Invalid Markdown processor given: cmark
Available processors are: kramdown, CommonMark
Conversion error: Jekyll::Converters::Markdown encountered an error while converting '_posts/2013-05-06-jekyll-1-0-0-released.markdown':
Bailing out; invalid Markdown processor.
ERROR: YOUR SITE COULD NOT BE BUILT:
------------------------------------
Bailing out; invalid Markdown processor.
------------------------------------------------
Jekyll 3.8.5   Please append `--trace` to the `build` command
for any additional information or backtrace.
------------------------------------------------
```
```
Jekyll Feed: Generating feed for posts
Markdown processor: "cmark" is not a valid Markdown …
```

Cleanup Markdown converter

---

lib/jekyll/page.rb
test/test_page_without_a_file.rb

- This is a 🐛 bug fix
Pagination pages (from `jekyll-paginate`) have the same `name` attribute value : `index.html`.
Therefore, every pagination page will output the same `inspect` string.
Apart from pagination pages, the output would be the same for pages at paths `./index.md` and `./about/index.md`

Replace `name` in Page#inspect with relative_path

---

docs/_docs/configuration/markdown.md

Following #7417 
This PR mentions the possibility to use gem plugins to switch to a CommonMark parser in Jekyll.
Preview: https://deploy-preview-7418--jekyllrb.netlify.com/docs/configuration/markdown/#commonmark
/cc @pathawks @kivikakk authors of CommonMark plugins

docs: mention CommonMark plugins

---

lib/jekyll/utils.rb
test/test_utils.rb

When slugifying an emoji character an empty string is returned unless you use a slug mode of `:pretty`.
```irb
irb(main):002:0> x = "💎"
=> "💎"
irb(main):003:0> Jekyll::Utils.slugify(x)
=> ""
irb(main):004:0> Jekyll::Utils.slugify(x, mode: nil)
=> ""
irb(main):005:0> Jekyll::Utils.slugify(x, mode: :pretty)
=> "💎"
```
The proposed change in this pull request will raise an error instead of returning an empty string. 
I have marked this PR as WIP as I am not sure if this change warrants a documentation update or not. Please advise.
This PR is based on a proposal described in https://github.com/jekyll/jekyll-archives/pull/129. 
I recommend a patch version increment. This `shouldn't'` change any existing behaviour except in cases where slugs are getting returned as a blank …

Log a warning when the slug is empty

---

docs/_docs/deployment/automated.md

Adds code so the ```bundle: command not found``` error that results from not having the gems location define on the server does not happen and allows gems to be installed when running a ```$ git push origin```.

Addresses bundle not found.

---

features/rendering.feature
lib/jekyll/liquid_renderer.rb

Backport #7568 for v3.8.x: Escape valid special chars in a site's path name

---

features/post_excerpts.feature
lib/jekyll/excerpt.rb

Currently if Markdown reference-style links are present anywhere in a document's body, the reference definition(s) are included into the document's excerpt which results in kramdown throwing a warning (when configured to log warnings) for those reference definitions that are *not used* in the excerpt.
This PR proposes to push only those link definitions that are necessary during the excerpt's rendering.
*The additional changes are simply to reduce complexity scores as flagged by RuboCop*.
Resolves #7576

Push Markdown link refs to excerpt only as required

---

docs/_docs/liquid/filters.md
features/embed_filters.feature
features/step_definitions.rb
lib/jekyll/filters.rb
test/test_filters.rb

- This is an 🙋 enhancement.
- I've added tests 
- I've adjusted the documentation
With this, one can pass `nil`, Liquid literals `empty` or `blank` to detect `nil` and empty values in the given array of objects.
*Additionally, this also slightly optimizes current operation by avoiding unnecessary array iteration due to chaining `#map` with `#include` (especially with an array property containing numerous elements)*
Resolves #6038
Closes #6039

Detect `nil` and empty values in objects with `where` filter

---

features/step_definitions.rb
lib/jekyll/commands/serve/servlet.rb
lib/jekyll/utils.rb
test/test_kramdown.rb

Since Jekyll 4.0 requires at least Ruby 2.4, `Jekyll::Utils.strip_heredoc` is redundant as we may as well use the native operator `<<~`
This is a `breaking change` because we'll be removing `Jekyll::Utils.strip_heredoc` with this.

Remove Jekyll::Utils#strip_heredoc in favor of a Ruby > 2.3 built in

---

docs/_docs/upgrading/3-to-4.md
docs/_sass/_style.scss
features/post_url_tag.feature
jekyll.gemspec
lib/jekyll/tags/post_url.rb

- I've adjusted the documentation (via `spec.post_intall_message`)
With this, `{% post_url 2019-03-27-hello %}` will return `/blog/2019/03/27/hello.html` for a site configured with `baseurl: blog`
**`BREAKING-CHANGE`**
Resolves #7353

Incorporate `relative_url` within `post_url` tag

---

docs/_includes/docs_contents.html
docs/_includes/docs_contents_mobile.html
docs/_includes/step-index.html

Standard Liquid Filter `default` can be used to handle conditional rendering of two variables

Simplify couple of includes in the docs site

---

.travis.yml
Gemfile

JRuby 9.2.7.0 got shipped [a day ago](https://github.com/jruby/jruby/releases/tag/9.2.7.0). Let us test with that version and see if Travis reports any failures..

Bump tested version of JRuby to 9.2.7.0

---

docs/_includes/mobile-nav-items.html
docs/_includes/news_contents.html
docs/_includes/primary-nav-items.html
docs/_includes/tutorials_ul.html

This change is to avoid generating empty classnames (e.g. `<li class="">...</li>` when the associated Liquid condition evaluates to `false`.
`<li class="current">...</li>` => `<li class="current">...</li>` (no change)
`<li class="">...</li>` => `<li>...</li>`

Avoid generating empty classnames

---

docs/_docs/installation/macos.md

When following the current documentation on MacOS 10.14 you recieve the following error because of SIP Protections:
```
ERROR: While executing gem ... (Gem::FilePermissionError)
You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory.
```
This PR updates the instructions so that on Mojave you do not run into that error. It also improves the overall clarity of the page by organizing it clearer subsections.
Resolves #3984
Resolves #7608

Install Docs that Work on MacOS 10.14

---

.github/CONTRIBUTING.markdown

The WIP probot app has been removed, since draft pull requests can be used in its place. Update the contribution docs to point out the new functionality.

Update the contribution docs for draft pull requests

---

.rubocop.yml
lib/jekyll/commands/serve/servlet.rb
lib/jekyll/commands/serve/websockets.rb
lib/jekyll/tags/include.rb

Now that `master` requires at least Ruby 2.4.0, let RuboCop suggest using Ruby 2.4 syntax over legacy syntax.

Target Ruby 2.4 syntax in RuboCop scans

---

.rubocop.yml
Gemfile
lib/jekyll/configuration.rb
test/helper.rb

- Update development environment to allow linting with RuboCop 0.68.x
- RuboCop 0.68.x has extracted `Performance` cops into a new gem: [`rubocop-performance`](https://github.com/rubocop-hq/rubocop-performance)
- The `Layout/IndentArray` cop has been renamed to `Layout/IndentFirstArrayElement`.
- The `Layout/IndentHash` cop has been renamed to `Layout/IndentFirstHashElement`.
- Enforce naming Rescued Exceptions Variables as `e` (since its RuboCop default **and** we use that style the most
Closes #7605

Bump RuboCop to v0.68.x

---

features/include_relative_tag.feature
lib/jekyll/tags/include.rb

- This is a 🐛 bug fix. 
Excerpt resources have payload paths as `<doc.relative_path>/#excerpt`. This isn't taken under consideration in the `include_relative` Liquid tag in `v3.8.x`.
Resolves #7629

Fix broken include_relative usage in excerpt

---

lib/jekyll/convertible.rb
lib/jekyll/document.rb

This is a :zap: micro-optimization fix.
Storing an invariable set of extensions in a class constant to avoid allocating memory (exactly 40bytes per array) for every *document* or *page* rendered.

Store list of expected extnames in a constant

---

docs/_docs/step-by-step/07-assets.md

To keep it consistent with rest of the documents where a file or directory is created at root level.

Indicate where the _sass folder is by default

---

docs/_docs/permalinks.md

I've added version tags to permalink placeholders that are already documented, but will be in version 4.0.0. 
Also a small documentation error was fixed.
See #5981

Docs: add version tags to new placeholders (#5981) for permalinks

---

docs/_docs/step-by-step/10-deployment.md

I followed the "Step by Step Tutorial" (https://jekyllrb.com/docs/step-by-step/01-setup/) and it worked fine locally on my computer. 
But after pushing the repository I received an email about "Page build failure" from GitHub. 
It said "The tag `feed_meta` on line 7 in `/_layouts/default.html` is not a recognized Liquid tag.".
After checking Jekyll Feed plugin (https://github.com/jekyll/jekyll-feed), I followed the instruction to add a line to the site's _config.yml (see the file change for details) and pushed again.
Finally the Pages were successfully built. 
So I propose this file change to help others who may have the same problems as me.

Solve "GitHub Page build failure" in 10-deployment.md

---

lib/jekyll/drops/drop.rb

- This is a **micro-optimization** change.
Since `@mutations` are *technically* not required for *immutable* Drops (has `mutable: false`), its better to move its initialization outside the Drop's constructor.
MemoryProfiler reports the following for this change: (run against the `docs/` site)
```
Total allocated: 9.96 MB (54896 objects)
Total retained:  743.62 kB (1998 objects)
```
```
Total allocated: 9.95 MB (54555 objects)
Total retained:  730.02 kB (1658 objects)
```

Initialize mutations for Drops only if necessary

---

Gemfile

https://github.com/rubocop-hq/rubocop/releases/tag/v0.69.0
Closes #7660

Bump RuboCop to v0.69.x

---

lib/jekyll/cleaner.rb

- This is a **micro-optimization** change.
MemoryProfiler report for this change by profiling the `docs/` site:
```
Total allocated: 20.06 MB (369854 objects)
Total retained:  702.98 kB (13089 objects)
```
```
Total allocated: 20.02 MB (368470 objects)
Total retained:  702.98 kB (13089 objects)
```

Reduce Array allocations via Jekyll::Cleaner

---

lib/jekyll/frontmatter_defaults.rb

`@glob_cache` shouldn't be initialized nor reset if `scope["path"]` doesn't contain glob patterns.
Improves change implemented by #7345

Initialize and reset glob_cache only as necessary

---

lib/jekyll/url.rb

This is an :zap: optimization change.
Avoid wasting resources on encoding simple alphanumeric urls that additionally contain just a slash or a period or a dash.

Encode and unencode urls only as required

---

.travis.yml
Gemfile
appveyor.yml
rake/profile.rake
script/memprof

Rake task and shell script to provide additional information for pull requests concerned with refactoring / optimizing memory allocation existing code in Core.
- *Currently, the task is wired to run with CI build's branch only. To compare 2 branches, run `script/memprof` locally and compare. ( TODO: Automate with an app.. :thinking: )*
Would help with demonstrating benefits from #7641 #7643 #7653 #7654

Profile allocations from a build session

---

Gemfile

https://github.com/rubocop-hq/rubocop/releases/tag/v0.70.0
Closes #7677

Bump RuboCop to v0.70.x

---

docs/_docs/step-by-step/09-collections.md

Added:
> To (re)load the configuration, restart the jekyll server. Press `Ctrl`+`C` in your terminal to stop the server, and then `jekyll serve` to restart it.
These steps were missing in the Step-by-Step instructions on [jekyllrb.com/docs](https://jekyllrb.com/docs/step-by-step/01-setup/).

docs: `jekyll serve` restart after changing config

---

docs/_docs/configuration/options.md

Live Reloading was was added in 3.7.0 (see https://jekyllrb.com/news/2018/01/02/jekyll-3-7-0-released/) but it's not mentioned anywhere in the docs. This PR does something about it.

Added documentation for Live Reload feature

---

lib/jekyll/site.rb

Memoizing `Site#docs_to_write` in Jekyll 3.8 caused plugin `jekyll-redirect-from` to break.
Therefore, reverting that and associated memoization of `Site.documents` made for Jekyll 4.0
https://github.com/jekyll/jekyll-redirect-from/issues/199

Revert memoizing Site#docs_to_write and #documents

---

features/include_relative_tag.feature
lib/jekyll/tags/include.rb

Backports the following for v3.8.x:
* Add cucumber feature to test include_relative tag (#7213)
* Fix broken include_relative usage in excerpt (#7633)

Backport #7213 and #7633 for v3.8.x: Fix broken include_relative usage in excerpt

---

lib/jekyll/document.rb

Overriding of `#respond_to?` is unnecessary when `#method_missing` and `#respond_to_missing?` has been overridden.
Based on the Ruby [docs](https://ruby-doc.org/core-2.4.5/Object.html#method-i-respond_to-3F)
> Returns `true` if *obj* responds to the given method.
> If the method is not defined, `respond_to_missing?` method is called and the result is returned.
`Document#repond_to_missing?` has the same logic as `Document#respond_to?`;
https://github.com/jekyll/jekyll/blob/c914e8628beb7a3ec9fb563238905f27943298ae/lib/jekyll/document.rb#L413-L415
https://github.com/jekyll/jekyll/blob/c914e8628beb7a3ec9fb563238905f27943298ae/lib/jekyll/document.rb#L397-L399
`:respond_to?` is a popular method that is *almost always* called with a **Symbol** argument.
But because we **coerce the argument to …

Remove override to Jekyll::Document#respond_to?

---

.travis.yml

Travis builds can be made *faster* by avoiding wasting time on installing and parsing documentation for Rubygems update on all jobs. For example, the following can be seen in
https://travis-ci.org/jekyll/jekyll/jobs/543313989#L501-L514 :
```
$ gem update --system
Updating rubygems-update
Fetching rubygems-update-3.0.3.gem
Successfully installed rubygems-update-3.0.3
Parsing documentation for rubygems-update-3.0.3
Installing ri documentation for rubygems-update-3.0.3
Installing darkfish documentation for rubygems-update-3.0.3
Done installing documentation for rubygems-update after 47 seconds
Parsing documentation for rubygems-update-3.0.3
Done installing documentation for rubygems-update after 0 seconds
Installing RubyGems 3.0.3
Bundler 1.17.3 installed
RubyGems 3.0.3 installed …
```

Do not install docs on updating gems on Travis

---

docs/_docs/github-pages.md

Link HTML was missing an end quote on the `href` attribute, and so was showing as plain text.

fix link to Site Source config

---

test/test_tags.rb

Rouge 3.4 released [recently](https://rubygems.org/gems/rouge/versions/3.4.1) and it is causing our CI builds to fail.
It includes a *minor change* in [the output from HTMLTable formatter](https://github.com/rouge-ruby/rouge/commit/a050f9e6155326f11b6ca73fa3a66bc16fafde65). According to the author of the change:
> The rationale is that it's important for the end of the lines stay clean to allow postprocessing to operate on all lines in the same way. When the closing `</pre>` bumps up against the last line, it requires special processing.

Update TestTags in sync with Rouge v3.4

---

Gemfile

https://github.com/rubocop-hq/rubocop/releases/tag/v0.71.0
Closes #7688

Bump RuboCop to v0.71.0

---

lib/jekyll/entry_filter.rb
test/test_entry_filter.rb

- We really don't need `Pathutil` or `Pathname` to be used in `EntryFilter#glob_include?`.
- The array of patterns should ideally be just strings and regexps.
- Handle the most common use-case of *string* patterns and then handle regex patterns and non-string patterns.
- Use `Regexp#match?` from Ruby 2.4 with regex patterns

Refactor `EntryFilter#glob_include?`

---

lib/jekyll/entry_filter.rb

Globbing a directory can result in the inclusion of `.` and `..` in the array returned if dots are allowed to be matched, e.g. in https://github.com/jekyll/jekyll/blob/13d31c4c8be13ab1536a0139a48952b142e81682/lib/jekyll/collection.rb#L80
Collection directory or not, such entries serve no purpose in a Jekyll Build and should be filtered away at all times. Moreover, doing so allows us to avoid wasting memory and time on checking if such entries qualify to be passed through for rendering.

Reject entries that are just dots in a directory

---

lib/jekyll/entry_filter.rb

Using an anchored regular expression with `Regexp#match?` is more optimal than checking if the *first character* of given `entry` exists in an array (because):
- No need for array traversal.
- No need to allocate memory for the `entry[0..0]` substring.
- `Regexp#match?` doesn't allocate `MatchData` objects.

Use regexp to filter special entries

---

lib/jekyll/reader.rb

- This is a :warning: security fix.
As a result of #7188, any entry in `site.include` that points to a file within the `source_dir` is read-in during a build. That created a **`security`** issue where an entry referring to a symlink is read-in even if it points to an entity outside the `source_dir`.
~~This PR attempts to resolve that by mirroring `EntryFilter#symlink?` without creating a new `EntryFilter` instance.~~

Don't read symlinks in site.include in safe mode

---

lib/jekyll/tags/include.rb

- This is an :zap: optimization change.
Prefer using the faster `String#match?` from Ruby 2.4 where `Matchdata` from the current match context is not used.

Replace `String#=~` with `String#match?`

---

lib/jekyll/drops/site_drop.rb

`Site#documents` cannot be memoized so that `Site#docs_to_write` can access the latest state of the attribute.
Since this `SiteDrop#documents` will be called after the `Site#pre_render` hook, the `Site#documents` shouldn't thereafter change and can therefore be safely memoized.

Memoize SiteDrop#documents to reduce allocations

---

lib/jekyll/drops/site_drop.rb

This backports #7697 as a reaction to #7689 which reverted a memoization in `Site#documents`.
The backport would bring the performance of `3.8-stable` back to similar levels of `jekyll-3.8.5` but without affecting plugins.

Backport #7697 for v3.8.x: Memoize SiteDrop#documents to reduce allocations

---

lib/jekyll/converters/markdown/kramdown_parser.rb
test/test_kramdown.rb

kramdown *expects* to get an `options` hash with Symbol keys. But it is not really necessary because `kramdown` converts string keys as well.
Resolves #6558

Remove patch to modify config for kramdown

---

docs/pages/resources.md

Add a link to Jekpack which is an integration of Jekyll and Webpack to make them work together. Provide this tool for people who want to use both Jekyll and Webpack at the same time.

Add Jekpack to resources page

---

docs/_docs/step-by-step/02-liquid.md

The second step of the step-by-step tutorial introduces liquid and waits on introducing frontmatters until step 3. The result of this can be that users get stuck on step two, not understanding why liquid doesn't work, and not realizing that the solution is on step 3. This tripped me up a bit, and it seems it confused a few other people as well: https://stackoverflow.com/questions/29662793/using-liquid-tags-in-a-jekyll-page-not-working#comment94717164_29666241
This change simply adds an instruction to step 2 to include a frontmatter in the index page.

Introduce frontmatter in step 2

---

Gemfile
features/theme.feature
lib/jekyll/theme.rb
test/fixtures/test-theme-skinny/_layouts/default.html
test/fixtures/test-theme-skinny/_layouts/home.html
test/fixtures/test-theme-skinny/test-theme-skinny.gemspec

This fixes an issue since v3.8 where-in a non-actionable message is output to the terminal regarding a directory within current theme (gem / remote) that could either be missing, or be inaccessible, or includes a symlink loop.
The proposed message is:
```
Theme exception: The '_sass' directory does not exist at theme's root,
is either not accessible or includes a symbolic link loop
```
Fixes #7630
cc: @ashmaroli

Update log output for an invalid theme directory

---

Gemfile
History.markdown
features/theme.feature
lib/jekyll/theme.rb
test/fixtures/test-theme-skinny/_layouts/default.html
test/fixtures/test-theme-skinny/_layouts/home.html
test/fixtures/test-theme-skinny/test-theme-skinny.gemspec

Backport #7679 for v3.8.x: Update log output for an invalid theme directory

---

.github/CONTRIBUTING.markdown
docs/_docs/contributing.md

#7464 and #7671 erroneously made changes to the auto-generated document `docs/_docs/contributing.md` instead of the source file `.github/CONTRIBUTING.markdown`

Move updates from generated file to source file

---

lib/jekyll/document.rb
lib/jekyll/utils.rb

`array.flatten.compact` generates *two copies* of `array` on each call.

Reduce Array objects generated from utility method

---

docs/_tutorials/navigation.md

This adds an example of using a recursive include to generate nested navigation links. I wrote about this on [my blog](http://excid3.com/blog/recursive-layout-with-jekyll-and-liquid) a long time ago and @arkadianriver mentioned we should add this to the docs in case it's helpful for other people. 👍

Add recursive navigation tutorial

---

lib/jekyll/readers/page_reader.rb

- The result of `Array#map` isn't being saved here. Therefore the generated array is just wasteful.
- Corrects the code-comment to better reflect the implementation.

Replace redundant Array#map with Array#each

---

docs/_docs/installation/windows.md

This change fixes a misspelling of "additional" in the Windows installation documentation.

Fix misspelling of "additional"

---

lib/jekyll.rb
lib/jekyll/document.rb
lib/jekyll/entry_filter.rb
lib/jekyll/page.rb
lib/jekyll/path_manager.rb
lib/jekyll/reader.rb
lib/jekyll/tags/include.rb

- This is an :zap: optimization change.
`File.join` allocates an Array and returns a new String on every call using **the same arguments**. Caching the result means reduced memory usage. However, the caches are never flushed so that they can be used even when a site is regenerating.
The results are frozen to deter mutation of the cached string.
Additionally caches result from logic formerly exposed as part of `Jekyll.sanitized_path`
Clubs the changes proposed in #7725 and #7729 and extracts the logic into a new singleton class.
Closes #7725 
Closes #7729

Add PathManager class to cache interim paths

---

docs/_docs/liquid/tags.md

this pull request updates gallery link to urls with option to download a css file and includes basic instructions for including the file in main css. 
Fixes #7713

docs: improve how to include rouge stylesheets

---

docs/_posts/2019-07-20-jekyll-4-0-0-pre-beta1-released.markdown
lib/jekyll/version.rb

This is a :shipit: release preparation change.
Prepare for the release of Jekyll 4.0.0 beta1.
It's, uh, been awhile since I've done a release. I'm happy to have any feedback regarding what else we need to do to this PR before we prep another pre-release.
Fix #7770

Prepare Jekyll 4.0.0 beta1

---

jekyll.gemspec
lib/jekyll/liquid_renderer/table.rb
test/test_liquid_renderer.rb

Delegate to a third-party gem ([`terminal-table`](https://github.com/tj/terminal-table)) instead of maintaining in-house code.
- There is a very slight *change in output* in case anyone is parsing the output via a plugin.
- *If it is of any relevance, [`github-pages`](https://rubygems.org/gems/github-pages/versions/197) gem also uses `terminal-table` to output tables..*

Delegate --profile tabulation to `terminal-table`

---

lib/jekyll/configuration.rb
lib/jekyll/convertible.rb
lib/jekyll/site.rb

The loop within `config.reduce({}) { |hsh, (k, v)| hsh.merge(k.to_s => v) }` is going to run for each
key-value pair in `config` and on each iteration, `hsh.merge` is going to allocate a new Hash object.
Therefore, if a config file has 20 **top-level key-value pairs**, this method would've allocated at least 20 Hash objects (of increasing size)..
This can be bad for sites that have numerous top-level config keys (e.g. forks of [`minimal-mistakes`](https://github.com/mmistakes/minimal-mistakes/blob/master/_config.yml) theme repo)

Reduce allocations by using #each_with_object

---

lib/jekyll/drops/url_drop.rb

To avoid generating a new Hash object on every call

Memoize fallback_data for Drop

---

lib/jekyll/entry_filter.rb

`String#[]` allocates memory for the substring but `String#end_with?` doesn't (and therefore faster as well).

Use String#end_with? to check if entry is a backup

---

Gemfile
jekyll.gemspec

https://github.com/jekyll/jekyll-sass-converter/releases/tag/v2.0.0
Highlights:
- Sass written in C (via sassc-ruby)
- source maps by default

Use jekyll-sass-converter-2.0 by default

---

docs/_docs/continuous-integration/travis-ci.md

Travis environment comes with Ruby 2.4.5 pre-installed.
Using this version saves about 20s of build time since 2.4.1 no longer needs to be downloaded and installed every time.
I guess many people (including me) generally do a copy paste of the scripts, so it makes sense to optimize them.

Update Ruby version used in Travis-CI example

---

docs/_docs/liquid/filters.md

Documents enhancement introduced in #6998

Documentation for binary operators in where_exp

---

lib/jekyll.rb

The gem is named `liquid-c`, but the correct require is `liquid/c`. I'm
fairly certain the conditional require has been wrong since it was
introduced five years ago, and it went unnoticed because there is of
course no error message when the gem is unavailable.

Actually conditionally include liquid-c

---

lib/jekyll/filters/url_filters.rb

These two filters are quite slow, as Addressable::URI.parse is quite
slow. Fortunately, they are pure functions and so can be easily
memoized. This one change shaves 8s off the CockroachDB docs build
(github.com/cockroachdb/docs).

Memoize absolute_url and relative_url filters

---

lib/jekyll/commands/serve.rb

This is ~either a 🐛 bug fix or~ an 🙋 enhancement.
Jekyll, currently does not accept an ECC (Elliptic-Curve) private key via its `--ssl-key` option when running the `serve` command, because the key loading code only assumes an RSA key with no other key types considered. Even though, even the older OpenSSL 1.0.2 supports EC keys. It means that Jekyll will fail to start with this error when an EC key is provided:
```
jekyll 3.8.5 | Error:  Neither PUB key nor PRIV key: nested asn1 error
```
This patch will try to load the provided key file as an ECC key if loading it as an RSA key failed. It also checks if the ECC key load method exists, as some Ruby variants ([JRuby](https://github.com/philr/putty-key/blob/964f9e110160937802d039e5db44048812de7b7e/test/openssl_test.rb#L47-L48)?) may not have …

serve: add support for ECC certificates

---

docs/_docs/step-by-step/09-collections.md

'title: Staff' was part of the page previously, but then dropped. Without it the meta title is incorrect.
A small fix to the code shown. The title part was dropped, so I re-added it. Otherwise it may confuse users learning Jekyll.

Add dropped 'title: Staff' to the code

---

docs/_docs/collections.md
docs/_docs/upgrading/3-to-4.md

Documenting a breaking-change introduced via #7410 which was only seen as a bug-fix at the time.
https://github.com/jekyll/jekyll/pull/7410#issuecomment-527837763 by @dcabo

Clarify docs for static files in collection

---

docs/_docs/continuous-integration/circleci.md

This PR updates the text to make it clearer that the v2 section is just an example of how you might deploy to AWS.

Rephrase the CircleCI v2 section

---

docs/pages/resources.md

-  https://wiki.github.com/rfelix/jekyll_ext/extensions (Old GitHub wiki URL)
+ https://github.com/rfelix/jekyll_ext/wiki/Extensions (New GitHub wiki URL)

Update old GitHub wiki URL with new one

---

test/test_document.rb
test/test_filters.rb

Remove Rubocop offence of Performance/Detect. 
```
test/test_document.rb:178:52: C: Performance/Detect: Use find instead of select.first.
@document = @site.collections["slides"].docs.select { |d| d.is_a?(Document) }.first
test/test_filters.rb:1039:28: C: Performance/Count: Use count instead of select...count.
assert_equal posts.select { |p| p.date > @sample_time }.count, results.length
```
Closes #7840

Fix RuboCop Performance offenses in test files

---

docs/_includes/top.html

This is a 🐛 bug fix. 
The `<meta name="generator" content="Jekyll v3.8.5" />` meta tag is already included as part of the SEO plugin. View source on the site to see.
`view-source:https://jekyllrb.com/`

Remove Generator meta tag

---

docs/_docs/upgrading/3-to-4.md

Minor fix on 3 to 4 migrating guide. It should be `>=` 2.4 (ruby min version) instead of `>`.

Doc: minor fix, should be greater or equal to min version [ci skip]

---

docs/_docs/collections.md

Clarifying the expected type of the `collections` field.
based on comment from: https://github.com/jekyll/jekyll/pull/7872

clarify _config.yml/collections type

---

lib/jekyll/converters/identity.rb

This is an internal change.
Found a typo in documentation comment and a parameter name mismatch.

Fix documentation comment for Jekyll::Converters::Identity

---

docs/_docs/collections.md

Before: When defining a collection as a sequence, it's pages will not be rendered by default.
After: When defining a collection as a sequence, its pages will not be rendered by default.
Justification: "its" is possessive; "it's" is "it is".

fixed grammatical error (it's --> its)

---

.github/workflows/ci.yml

The step currently fails on `master` with the following message:
gem update --system --no-document && gem update bundler --no-document
~~
The token '&&' is not a valid statement separator in this version.
CategoryInfo          : ParserError: (:) [], ParseException
FullyQualifiedErrorId : InvalidEndOfLine

Split action steps to avoid using `&&` on Windows

---

docs/_docs/pages.md

Adding clarification about the structure of pages in sub folders with example
It does not address any open issues but does provide clarification on resulting structure/naming of page files/folders which I was having issues understanding at first.

Docs: Clarify organizing pages into subfolders

---

docs/pages/resources.md

On <https://jekyllrb.com/resources/> page, the item *Contentful* is missing a colon after its name. Just a simple typo fix for the website.

Add back a missing colon to /resources/ page

---

docs/_docs/permalinks.md

Placeholders of pages: https://github.com/jekyll/jekyll/blob/master/lib/jekyll/page.rb#L109-L111

Disambiguate the placeholder of permalink

---

Gemfile

This PR updates the version number for `rake` in the Gemfile to use `~> 13.0` in order to solve issue #7900 
I have not added any tests but running `script/cibuild` passes locally.
Resolves #7900

Upgrade rake to use version 13

---

docs/_docs/configuration/options.md

Added the short command for livereload to the documentation.

docs: add short serve command for livereload

---

docs/_docs/configuration/options.md

Added config options for regeneration (watch) and force polling to the documentation. We use jekyll in a combination with docker, npm and webpack and we like to keep all build (serve) commands in the config instead of the command line. The only command we run is `jekyll serve --config fake_config.dev.yml` and let the config(s) take care of the rest.

docs: add options for watch and force polling

---

docs/_docs/installation/other-linux.md

add install instructions for ArchLinux and openSUSE

add install instructions for ArchLinux and openSUSE

---

docs/_docs/index.md

1. Moved the prerequisites link to the top of the page (instead of the bottom) so it's available right away. 
2. Removed ableist language ('simply') and reworded the introductory paragraph to use less jargon.
I came to the doc site to see how to use Jekyll, but couldn't find the prerequisites easily, either on the Quickstart page or the Installation page.

Improve index page of Jekyll documentation 

---

docs/_docs/usage.md

The command `jekyll new` to create a new jekyll site outputs an error `jekyll 4.0.0 | Error:  You must specify a path.`. The correct command is `jekyll new <path>`, where `<path>` should be specified by the user.
I noticed the issue while reading the docs, from where an *improve this page* link took me here.

Include path in jekyll new commands (Usage docs)

---

lib/jekyll/filters.rb
test/test_filters.rb

This is a 🐛 bug fix
Method `item_property` aggressively parses floats from values. In order to properly render integers I added integer check before float check. I guess better solution would be type check, but I'm afraid it might break other things.
Fixes #7827
--
P.S.
Thanks for wonderful software, glad to bring my 5 cents!

Update item_property to recognize integers

---

docs/_docs/themes.md

When using `bundle show` I got a message saying that `bundle show` has been deprecated and replaced by `bundle info`. Updated the Themes documentation accordingly.

Changed deprecated command in themes documentation

---

docs/_docs/plugins/hooks.md

I recently found that someone had take advantage of the `:clean, :on_obsolete` hook in a PR to a plugin of mine, but I couldn't find it documented anywhere. This PR adds the hook to the [Hooks page](https://jekyllrb.com/docs/plugins/hooks/).
Hope this is ok. Thanks!

Adds some documentation for the :clean, :on_obsolete hook

---

docs/_docs/github-pages.md

Simple update of link. 
Seems the base URL for the Github help pages has changed.

docs: fix broken link

---

jekyll.gemspec

The post-install message meant for Jekyll 4.0.0 is not necessary for the next release.

Remove post-install message from gemspec

---

docs/_docs/configuration/options.md

In PR #7918 I added config options for `watch` and `force_polling` to the docs. However, after running this, it seems that jekyll says that using `watch` from config is deprecated and it should be used from the CLI instead:
```bash
Configuration file: _config.dev.yml
Deprecation: Auto-regeneration can no longer be set from your configuration file(s). Use the --[no-]watch/-w command-line option instead.
```
Perhaps the `watch` part of #7918 shouldn't have been added at all and the preferred way is using `--watch` (?).
This PR removes the `watch` config option.

docs: remove watch option in config

---

docs/_tutorials/navigation.md

There was a small syntax issue in the YAML example block for the `group_by` operator; one of the inner lists wasn't closed with a square bracket. In the interest of accuracy, I am submitting a fix.
No corresponding issues that I was able to find.

Fix YAML representation of `group_by` result

---

docs/_docs/configuration/options.md

It looks like `--baseurl` works on `build` as well as `serve`, possibly since this PR was merged:
https://github.com/jekyll/jekyll/pull/5135
I just tried it myself and sure enough, `jekyll build --baseurl /test` successfully transforms URLs in Jekyll 4.0.0.
As such, this PR moves Base URL to Build Command Options.

Move --baseurl to build command options

---

lib/jekyll/filters/url_filters.rb

Currently, when `site.config["url"]` is an empty string, `:absolute_url` proceeds to prepend the result from `:relative_url` with the empty string and then normalize the result via Addressable.
Instead, this PR proposes to return the result from `:relative_url` (which is already normalized via Addressable) in this scenario.
The expected result is already covered by a test:
https://github.com/jekyll/jekyll/blob/f3b4cad057a9632d4129d0f0529ec5bdbad8abce/test/test_filters.rb#L421-L428

Return relative_url if site.url is an empty string

---

.rubocop.yml
.travis.yml
appveyor.yml
lib/jekyll/convertible.rb
lib/jekyll/document.rb
lib/jekyll/tags/include.rb

So that Ruby 2.7 doesn't issue warnings for deprecated use of keyword arguments
fix #7947

Attain Ruby 3.0 compatibility

---

docs/_docs/collections.md

Collections sort by `date` if both documents have that key, otherwise they sort by `path`. This was giving me problems, so I figured I'd at least correct the documentation.
N/A
I based this change off experienced behavior and code inspection.
- Collections *fall back to* `Document#<=>` if `sort_by` is missing or non-sortable (and call `docs.sort!` if the `sort_by` isn't defined for either):
https://github.com/jekyll/jekyll/blob/dd7d03eccdefd7bc4227e577dd409fde52fc7eb8/lib/jekyll/collection.rb#L240
- `Document#<=>`  tries to compare date, falling back to `path`:
https://github.com/jekyll/jekyll/blob/dd7d03eccdefd7bc4227e577dd409fde52fc7eb8/lib/jekyll/document.rb#L336-L342
Thanks!

Document sorting two documents by their `date`

---

features/step_definitions.rb
features/theme_gem.feature
lib/theme_template/theme.gemspec.erb

#7304 introduced loading the `_config.yml` from a theme, but the gemspec doesn't include this file.
Currently a site will correctly include values from the theme's `_config.yml` locally, but not once the theme is packaged and pulled from a gem repository, as the file doesn't exist.
This PR adds `_config.yml` to the gemspec generated when you run `jekyll new-theme`.
#7304 introduced this feature.
- I haven't added a test for this change as there currently doesn't seem to be a test around gem packaging
- All existing themes will still encounter this problem unless they amend their gemspec files to include `_config.yml`

Include _config.yml in a new theme's gemspec

---

docs/pages/resources.md

Add a link to the integration of Kentico Kontent. It enables the generation of Jekyll content (pages, posts...) modeled in the CMS and backed by its API.

Add Kentico Kontent CMS integration to resources

---

docs/_docs/step-by-step/07-assets.md

The Assets page has some references to the wrong files. Patching these in this PR.

Fix file references in Step by Step Tutorial's Assets step

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
docs/_docs/contributing.md
docs/_docs/installation.md

Add files to create a Visual Studio Code development container which can be used to quickly get new contributors up and building the app. To use this you need to have [Visual Studio Code](https://code.visualstudio.com/) and the [Remote Development Extension Pack](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack) installed.
The development environment includes `gcc`, `ruby`, and `nodejs`. I've verified that `script/cibuild` runs without errors. I've also added a section to the installation page describing how to setup VS Code to use this environment.
From start to finish setting up a new development box is entirely automatic and takes about 5 minutes. Once you're done you can open a new terminal in the development container using the same …

Add Visual Studio Code Development Container

---

docs/_docs/configuration/options.md
features/cache.feature
lib/jekyll/command.rb
lib/jekyll/site.rb

Running in `safe` mode just to disable Jekyll 4.0's disk-caching seems like an overkill.
Plugins would need to be modified to be compatible with `safe` mode, whitelist gems...
With this change one can disable disk-cache in non-*safe* mode via either `--disable-disk-cache` CLI switch or `disable_disk_cache: true` configuration.
Closes #7804 
/cc @Convincible

Add an option to easily disable disk-cache

---

docs/_docs/configuration/default.md
lib/jekyll/configuration.rb

When kramdown is given the option `toc_levels` as a string range (`"1..6"`), kramdown *parses* the string into an Array but in the process, generates *intermediate objects* of `Range`, `MatchData` and `Array`.
Since this process repeats for every *kramdown document* converted by kramdown, Jekyll can help *reduce* the work done by passing an Array *by default.*
*This is a backwards-compatible change.*

Configure kramdown toc_levels as array by default

---

docs/_docs/step-by-step/07-assets.md

After creating posts in the step 8 of the step by step tutorial, Jekyll will look for `/YYYY/MM/DD/assets/css/styles.css` as `_layouts/post.html` requires the `default` layout which references `assets/css/styles.css`. This results in `ERROR '/YYYY/MM/DD/assets/css/styles.css' not found.`. 
This can be solved by this change.
Replacement of the line in the code snippet of the step 7 of the step by step tutorial.

[Docs] Fix asset link ref in step-by-step tutorial

---

lib/jekyll/converters/markdown/kramdown_parser.rb

- Tested by existing coverage.
`Kramdown::Document` is designed to set up the necessary options and a parser (based on the provided options) to initiate conversion of a Markdown content string.
But Jekyll uses the same set of options (and therefore the parser as well) to convert *all of its Markdown documents*. Therefore, having kramdown run the set up tasks for each document is wasteful.
This PR proposes to subclass `Kramdown::Document` and move the set up tasks from the `:initialize` method to a `singleton_menthod`. This approach has the set up tasks run for just the *first Markdown document contents* converted, cache the resulting objects and subsequently provide these objects to consequent conversions.

Optimize markdown parsing with Kramdown by reusing the options and parser objects

---

docs/_docs/installation/macos.md

The existing command to modify the path will not persist after closing and reopening Terminal. This new command should be permanent.

Corrected command to modify PATH

---

docs/_includes/news_item.html
docs/_includes/news_item_archive.html
docs/_layouts/news_item.html
docs/_sass/_style.scss
docs/pages/news.html
docs/pages/releases.html

The older posts are just rendered as references to their respective page where the full content is already rendered:
This has two benefits:
- Jekyll doesn't have to render the full post contents twice &mdash; once on the index page and then again on the post's URL.
- Users need not scroll through the full contents of every post at both `/news/` and `/releases/`

Docs: Render full contents of just the latest post

---

docs/_docs/collections.md
docs/_docs/configuration/environments.md
docs/_docs/installation/macos.md
docs/_docs/installation/windows.md
docs/_docs/liquid/tags.md
docs/_docs/maintaining/affinity-team-captain.md
docs/_docs/maintaining/avoiding-burnout.md
docs/_docs/maintaining/becoming-a-maintainer.md
docs/_docs/maintaining/index.md
docs/_docs/maintaining/merging-a-pull-request.md
docs/_docs/maintaining/releasing-a-new-version.md
docs/_docs/maintaining/reviewing-a-pull-request.md
docs/_docs/maintaining/special-labels.md
docs/_docs/maintaining/triaging-an-issue.md
docs/_docs/pages.md
docs/_docs/plugins/commands.md
docs/_docs/plugins/installation.md
docs/_docs/plugins/tags.md
docs/_docs/posts.md
docs/_docs/step-by-step/07-assets.md
docs/_docs/structure.md
docs/_docs/themes.md
docs/_docs/upgrading/2-to-3.md
docs/_sass/_style.scss
docs/_tutorials/convert-existing-site-to-jekyll.md
docs/_tutorials/index.md
docs/_tutorials/navigation.md

Notes currently are marked up either as a single paragraph with a [Kramdown IAL](https://kramdown.gettalong.org/syntax.html#block-ials) or as straight HTML if the note has a title or multiple paragraphs. I fixed the CSS to make their text styles match and converted the single-paragraph HTML notes to IAL form, and fixed several other inconsistencies. 
Mostly a sequel to #8017.
I also have on hand CSS and markup to allow converting titled or multi-paragraph notes to IAL form, if there's interest.

docs: improvements for note boxes

---

lib/jekyll/hooks.rb

- Use `Hash#dig` to traverse nested hashes and check if the result is `nil`.
- Guard against *empty* object as well so that we need not consequently duplicate it via `:sort_by`.

Simplify Jekyll::Hooks.trigger logic

---

lib/jekyll/filters.rb
test/test_filters.rb

Allow filtering with expressions involving multiple use of `and` or `or`.
Resolves #8046

Allow multiple binary operators in where_exp filter

---

docs/_tutorials/using-jekyll-with-bundler.md

The documented [Bundler configuration](https://jekyllrb.com/tutorials/using-jekyll-with-bundler/#configure-bundler) to install gems under `./vendor/bundle/` refers to a deprecated usage of `bundle install`
```sh
$ bundle install --path vendor/bundle
[DEPRECATED] The `--path` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set path 'vendor/bundle'`, and stop using this flag
```

Non-deprecated `vendor/bundle` path configuration

---

lib/jekyll/collection.rb

Check for `nil` values before checking for zero value since `nil` doesn't respond to `:zero?`
Closes #8024

Fix documents custom-ordering logic

---

jekyll.gemspec

> the `require_relative` method comes handy, It will load a file relative to the current location. — https://piotrmurach.com/articles/writing-a-ruby-gem-specification/

chore: simplify require for Jekyll::VERSION

---

jekyll.gemspec

The relaxation was introduced via https://github.com/jekyll/jekyll/commit/1684905ec793be16ebb3ca4e81406aff5cbdbd10 to allow use of activesupport 4.2.10 on Ruby 2.2.
Since Rubies older than v2.4.0 are not relevant for Jekyll 4.0, the constraint-relaxation can be removed.

Remove version-constraint relaxation for i18n gem

---

jekyll.gemspec

**`"https://jekyllrb.com"`** is already present as value of `spec.homepage`.
Therefore, marking the same value as `spec.metadata["homepage_uri"]` is unnecessary.

Mirror `spec.homepage` as `metadata["homepage_uri"]`

---

docs/_docs/step-by-step/08-blogging.md

I've removed the paragraph tags around `{{ post.excerpt }}`. This tag already outputs paragraph tags, so wrapping it in another set causes invalid HTML output.

Remove extra paragraph tags

---

lib/jekyll/renderer.rb

So that Jekyll's `LiquidRenderer` can correctly differentiate between layout from source vs layout from theme.
The bug can be identified in the `--profile` output:
```
| Filename                                     | Count |  Bytes |  Time |
+----------------------------------------------+-------+--------+-------+
| _posts/2020-03-20-welcome-to-jekyll.markdown |     1 |  1.68K | 0.181 |
| _layouts/default.html                        |     4 | 20.33K | 0.032 |
| minima-2.5.1/_includes/head.html             |     4 |  7.22K | 0.023 |
| feed.xml                                     |     1 |  4.00K | 0.007 |
| minima-2.5.1/_includes/header.html           |     4 |  3.96K | 0.004 |
| minima-2.5.1/_includes/footer.html           |     4 |  4.65K | 0.003 |
| …
```

Use `layout.path` when rendering the Liquid layout

---

lib/jekyll/converters/markdown/kramdown_parser.rb

- This is tested by existing coverage.
By having `:to_html` explicitly defined for the `Kramdown::JekyllDocument` instances, the benefits are following:
- Reduce String allocations from converting `:to_html` to `"to_html"`.
- Reduce MatchData and String allocations from testing and extracting `"html"` from the method name and consequent conversion into `"Html"`.
- Reduce time spent to `require "kramdown/converter/html"` and consequent constant-lookup.
The optimization is to bypass steps above and call `Kramdown::Converter::Html.convert` directly. This is possible because `Kramdown::Converter::Html` is set up to be *autoloaded* if not available already.
Prior, I made an attempt to propose this patch at the upstream kramdown core : …

Optimize `Kramdown::JekyllDocument#to_html` calls

---

lib/jekyll/frontmatter_defaults.rb

Instead use simple String methods as alternative.
*This can be significant improvement for sites with numerous default front matter scopes in their config file.*

Reduce Pathname objects from front matter defaults

---

lib/jekyll/document.rb

When a document's special directory (e.g. `_posts` for a post) is located at the root of the site's `collections_dir`, its `categories_from_path` is always empty.
So it's wasteful to process an empty string to get an empty array eventually.

Quicker categories for documents without superdirs

---

lib/jekyll/static_file.rb

`Jekyll::StaticFile#path` involves duplicating arrays via `Array#Compact`. So multiple calls to the unmemoized method would result in unnecessary Array allocations.

Reduce array allocations from `StaticFile#path`

---

lib/jekyll/renderer.rb

Currently, if a rendering document's layout is valid and not `nil`, `layout_source` is computed even if the build is not running on `debug` log level.
Additionally when building with `--verbose`, `Layout source: ...` is output for every rendered document placed into a layout. That can be considered *noise* because when 10 documents use the same layout, outputting `Layout source: ...` for each of them is repetition.
Finally, when a layout is not from `site.source`, it is currently assumed to be from the theme, when in reality, it could be from a plugin (like [`jekyll-redirect-from`](https://github.com/jekyll/jekyll-redirect-from/blob/52bcaa018c53a37998f7bf09d4f2b0d4ccbd6809/lib/jekyll-redirect-from/generator.rb#L12-L15)).
<br/>
*Therefore, instead of checking if a layout comes from …

Simplify `Jekyll::Renderer#validate_layout`

---

docs/_layouts/tutorials.html
docs/_sass/_style.scss
docs/_tutorials/cache-api.md
docs/_tutorials/convert-site-to-jekyll.md
docs/_tutorials/custom-404-page.md
docs/_tutorials/navigation.md
docs/_tutorials/orderofinterpretation.md
docs/_tutorials/using-jekyll-with-bundler.md
docs/_tutorials/video-walkthroughs.md

Tutorials are mostly written by volunteers from the community. I think it makes sense letting everyone know who is responsible for sharing the idea / tips.
*Retroactively added author information on existing tutorials based on the metadata of the commit that added the tutorial*

Render tutorial metadata in documentation site

---

docs/_docs/collections.md

_Custom Sorting of Documents_ only works from Jekyll 4.0.

Add version badge for Custom Sorting of Documents

---

docs/_docs/front-matter.md

```diff
- be available to you
+ be available for you
```

Docs: Fix grammar in `_docs/front-matter.md`

---

features/collections.feature
lib/jekyll/static_file.rb
test/source/_methods/extensionless_static_file

Jekyll 4.0 introduced a minor change (via #7315) in how URLs for static files were generated whereby the logic for static files in a collection became more responsive to the associated collection's `url_template`. So when a collection's `url_template` is customized at client-side to utilize `:name`, static files should adapt accordingly.
Resolves #7904

Add static file's basename to its url_placeholder

---

lib/jekyll/liquid_renderer/file.rb

- *No unit-tests.*
Since `Liquid::Templates` are now cached, ensure that every render starts with a clean context.
Resolves #7811

Clear cached Liquid template scope before render

---

docs/_docs/permalinks.md
features/post_data.feature
lib/jekyll/drops/url_drop.rb

- I've updated the documentation.
This allows generation of URLs without `%20` when a singular category is a composite of multiple words.
Resolves #8093

Add slugified_categories URL placeholder

---

History.markdown
lib/jekyll/commands/new.rb

Reverts jekyll/jekyll#7618
The original commit is failing our CI builds on Rubies 2.4, 2.5, 2.6 and JRuby consistently.
Perhaps there's another way to resolve the issue addressed by the original commit

Revert "Pass require path to sub-process when running `bundle install`"

---

docs/_sass/_pygments.scss
docs/_sass/_style.scss

Most of the tokens generated by Rouge are colored `#ffffff` in the code-blocks in the documentation site. This pull request attempts to remedy this deficiency to a limited extent.

Improve syntax-highlighting in documentation site

---

.rubocop.yml
.travis.yml
appveyor.yml
lib/jekyll/convertible.rb
lib/jekyll/document.rb
lib/jekyll/tags/include.rb
script/profile-docs

Attain Ruby 3.0 compatibility
This backports 389eb88 to 3.8-stable
Includes additional changes to appease RuboCop
Includes additional changes to CI configs
Additionally backports dev change #7540 to help detecting more Ruby 2.7 warnings.

Backport #7948 for v3.8.x

---

.rubocop.yml
.travis.yml
lib/jekyll/convertible.rb
lib/jekyll/document.rb
lib/jekyll/tags/include.rb
test/test_document.rb
test/test_filters.rb

Attain Ruby 3.0 compatibility
This backports 389eb88 to 4.0-stable
Includes additional changes to appease RuboCop

Backport #7948 for v4.0.x

---

docs/_docs/installation/other-linux.md

I tested this after freshly installing Clear Linux OS (<https://clearlinux.org>) on my laptop and it installed without any error.
The subsequent setting of gem installation path, as well as the installation of the `jekyll` and `bundler` gems as per the documentation (<https://jekyllrb.com/docs/installation/ubuntu/>) worked as expected.
Cloning a Jekyll site and running the usual `bundle install` & `bundle exec jekyll serve` worked as expected, as well as creating a new Jekyll site.
For reference, the contents of the package that Clear Linux OS uses for `ruby-basic`: <https://github.com/clearlinux/clr-bundles/blob/master/bundles/ruby-basic>

Added Clear Linux

---

docs/pages/resources.md

On https://jekyllrb.com/resources/, there's a link to https://jekyllrb.com/docs/github-pages/ (under Guides > Publishing to GitHub Pages), but it is broken. The commit in this pull request fixes the link.

Fix broken URL in the Resources Page on the Documentation Site

---

features/post_excerpts.feature
test/test_kramdown.rb

This backports commits d65a09b and 79be8ab to 4.0-stable to stabilize CI builds on the
`4.0-stable` branch

Fix Kramdown converter based tests for v4.0.x

---

lib/jekyll/liquid_renderer/file.rb

Clear cached Liquid template scope before render
This backports 67380a2 to 4.0-stable

Backport #7967 for v4.0.x

---

docs/_docs/continuous-integration/github-actions.md
docs/_docs/deployment/automated.md

Create a instructions for Github Actions CI and added appropriate item to a list on the CI page.
https://deploy-preview-8119--jekyllrb.netlify.com/docs/continuous-integration/github-actions/
Closes #8095

Docs: Deploy Jekyll site with GitHub Actions

---

test/test_convertible.rb

Our paths contain the + sign, which if not escaped changes the match regex
and the tests fail.
Fixes #8137

Escape regex characters in paths to match

---

Gemfile
lib/jekyll/commands/new.rb

With :install_if bundler will check for the gems even if they are not required
on our platform. To prevent users from having this issue use :platforms
instead: https://lists.debian.org/debian-ruby/2020/04/msg00062.html
fixes #8139

Use platforms instead of install_if

---

docs/_tutorials/using-jekyll-with-bundler.md

* Add `--local` option to the `bundle config set` command in the tutorial.
* Clarify what the config command does and why you might want to use it.
* Clarify the differences between this tutorial and the Quickstart.
I originally wrote this Bundler tutorial back in 2018. At that time, running
`bundle install --path vendor/bundle` was the correct way to install
gems to a custom directory with Bundler. Since then, Bundler released
[version 2.1](https://github.com/rubygems/bundler/blob/master/CHANGELOG.md#210pre1-august-28-2019),
which deprecates breaking changes for Bundler 3. One of these changes is
the deprecation of the `install --path` option, which has been replaced
by `bundle config set path foo`. The tutorial was updated for this in #8048.
This PR …

Clarify `bundle config` in Bundler tutorial

---

lib/theme_template/theme.gemspec.erb

There is no explicit dependency on Bundler or Rake while developing a theme-gem.
As Bundler is now included with Ruby itself, there wouldn't be a need for the mention in the gemspec going forwards.

Remove dev dependencies from new theme-gem gemspec

---

docs/_docs/configuration/options.md
features/theme_configuration.feature
lib/jekyll/site.rb
test/test_site.rb

- I've adjusted the documentation.
So that related bugs are not activated out-of-the-box.. 
Resolves #8114

Allow disabling import of theme configuration

---

lib/jekyll/liquid_renderer.rb
lib/jekyll/theme.rb
test/test_liquid_renderer.rb

- This is a 🐛 bug fix. 
Merging #8069 exposed a bug in `Jekyll::LiquidRenderer`. The table output when building with
`--profile` isn't robust to handle absolute paths of layouts from plugins (like `jekyll-redirect-from`).
So, this PR revamps the path normalization logic into a new private instance method.

Improve path normalization in liquid_renderer

---

docs/_includes/docs_contents.html
docs/_includes/docs_contents_mobile.html

`{{ site.documents }}` returns *all of the documents* in the `site`.
However, include files `_includes/docs_contents.html` and `_includes/docs_contents_mobile.html` are just used to render the navigation for documents in the `docs` collection.
In other words, it is wasteful having to loop through the entire set of *documents* when the current scope requires just a subset.

Site: Filter through just the docs collection

---

lib/jekyll/drops/document_drop.rb
lib/jekyll/drops/page_drop.rb

While playing around with profilers, it noticed that **memory allocations** are greater when a `Drop` queried with a key doesn't have a method defined for the key and is therefore forwarded to query `fallback_data`.
So, this PR provides commonly queried keys as methods defined for the drops.

Provide invokables for common drop query keys

---

lib/jekyll/frontmatter_defaults.rb

`String#gsub` duplicates the given string irrespective of a pattern match.
So, it is better if one checks if a given string will match the pattern beforehand and return the original string if it doesn't match the pattern.
Regarding the pattern, `%r!\A/|(?<=[^/])\z!`, it translates to
*Test if a given string either starts with `/` or just match the `end-of-string` preceded by a character that is not `/`.*
The second option of the regex will always generate a *match* for the major use-cases
(e.g. `scope["path"] == "pages"` or `scope["path"] == "\pages"`)
So we can optimize for the major use-cases by checking if the given string `start_with?` `"/"` prior to the `gsub` call.

Optimize path sanitization of default front matter

---

lib/jekyll/utils.rb
test/test_utils.rb

Modifies the Regex to support a wider range of Unicode character groups. The original issue has more context on why the existing Regex was not working as expected for Tamil (or other Unicode characters), including external references to a possible fix.
This was deemed to be a breaking change in the original issue. There are no failing tests to help guide us in confirming that it would break existing sites, but it does seem possible.
The original issue mentioned making this change opt-in. We're happy to support this but we were not sure how to best implement that.
Possible proposal: add a new slug `mode` option (something like `pretty_unicode` -- open to ideas on the name) that would apply this more advanced regex instead.
Any ideas on how to proceed? We …

Switch slugify regex to support more Unicode character groups

---

lib/jekyll/entry_filter.rb

Because testing `File.directory?(entry)` for every `pattern` in `enumerator` (`site.exclude` and `site.include`) is redundant and can hamper performance.
Therefore, test `entry` once per enumerator and stash the result in a local variable which is tallied against `enumerator`'s items when needed.

Check if entry is a directory once per enumerator

---

docs/_docs/continuous-integration/travis-ci.md

[Sudo is deprecated in Travis CI](https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration). This PR removes the mentions of sudo in the tutorial for Travis CI.

Remove sudo from Travis CI tutorial

---

docs/_docs/deployment/third-party.md

GitLab Pages is a big enough player to be mentioned in the list of 3rd party deploy tools. This PR adds GitLab Pages to the list.

Add Gitlab Pages to 3rd party list

---

docs/_docs/posts.md

- This is a 🔦 documentation change. 
Rewrite the entire section by introducing tags first and then introducing categories as an extended feature-set of tags.
Closes #8195

Improve documentation on tags and categories

---

benchmark/find-filter-vs-where-first-filters.rb
docs/_data/jekyll_filters.yml
lib/jekyll/filters.rb
test/test_filters.rb

- I've adjusted the documentation.
Introducing Liquid filters `find` and `find_exp` to optimize scenarios involving `first` chained to `where` and `where_exp` filter respectively.
`where` (`where_exp`) evaluates given conditions against *all items* in a given array and chaining the `first` filter returns a single object from the pool. This could be wasteful when the array is large with numerous items and the first winner is near the starting end.
i.e. say the array is `["apple", "lemonade", "spade", "sunglasses", "umbrella", "cola"]`
`{{ array | where: "type", "drink" | first }}` and `{{ array | find: "type", "drink" }}` are equivalent and return the same object (`"lemonade"`) but the latter stops processing after two items.

Add find filters to optimize where-first chains

---

lib/jekyll/static_file.rb

Instead of initializing a static file's `data` hash at the time the static file is read-in, initialize the `data` hash at a later time if required.
*This can improve performance of sites with numerous static files and default front matter in the config file.*

Initialize static files' data hash only if needed

---

docs/_tutorials/convert-site-to-jekyll.md

The [W3C validator](https://validator.w3.org/feed/check.cgi) says:
> This feed is valid, but interoperability with the widest range of feed readers could be improved by implementing the following recommendations.
With the added line, this should be fixed.

Add atom:link rel="self" to RSS feed template

---

.rubocop.yml
Gemfile
lib/jekyll/cleaner.rb
lib/jekyll/collection.rb
lib/jekyll/page.rb
lib/jekyll/tags/include.rb
lib/jekyll/utils.rb
test/helper.rb
test/test_convertible.rb
test/test_front_matter_defaults.rb
test/test_kramdown.rb
test/test_tags.rb
test/test_theme.rb

RuboCop v0.85 Release Page:
https://github.com/rubocop-hq/rubocop/releases/tag/v0.85.0

Bump RuboCop to v0.85.x

---

docs/_docs/pages.md
lib/jekyll/page.rb
test/test_page.rb

Jekyll 4.1.0 changed `{{ page.excerpt }}` for `Page` objects from `nil`.
This patch allows to opt-in via a config setting.
Resolves #8216

Disable page excerpts by default

---

test/helper.rb

Bash on Windows expands similar to paths on Linux
Based on discussion in #8220 with @noproblema
Resolves #8220

Expect drive letter only on vanilla windows

---

docs/_docs/structure.md

Suggests using the `info` command, rather than the `show` command when trying to locate the theme.
It's a super minor thing, but when running through the quickstart/first steps, I noticed the suggested command throws a deprecation warning. Did a quick check, and looks like as at bundler 2.1.0.pre.1 `bundler info GEM` has feature parity with `bundle show GEM` so it seems like we should update the docs accordingly.

Replace deprecated 'show' command with 'info'

---

lib/jekyll/page.rb
test/source/assets/test-styles.scss
test/test_filters.rb
test/test_page.rb
test/test_site.rb

- This is a 🐛 bug fix. 
I don't see a major use-case for *generating excerpts* for non-html pages (mainly assets) even with `page_excerpts: true`.
Should there be a need, we'll have to enable it via another config option in a future minor release so that only those willing, gets to bear the performance burden.

Don't generate excerpts for non-html pages

---

docs/_docs/deployment/third-party.md
docs/_tutorials/convert-site-to-jekyll.md
docs/pages/resources.md

Vercel (formerly ZEIT) had a rebranding changed the name as the domain of your site. To avoid confusion, this PR focuses on changing the name and modifying the links that pointed to the [zeit.co](https://zeit.co) to [vercel.com](https://vercel.com) page.
Rebranding from ZEIT to Vercel

Change name to ▲Vercel

---

docs/pages/resources.md

Changes repository name of zeit to vercel
A few hours ago my PR became merged #8247 but I forgot to change the repository name of `now` to `vercel`. I am sorry for the inconvenience for creating a PR "unnecessary" on the same problem 🙏 
Excellent day to the Jekyll team ❤️

Fix typo name of repository Vercel

---

docs/_docs/liquid/filters.md
docs/_posts/2020-05-27-jekyll-4-1-0-released.markdown

Instead of linking to the filter docs page, point to a specific filter.
Edit the release post for v4.1.0 as an example.

Allow hyperlinks to specific filter documentation

---

docs/_docs/usage.md

Change the word 'is' to 'are', because when the subject is plural, we use 'are'.

Fix grammar in documentation section

---

docs/_docs/pagination.md

The example code in the documentation has a section for the corner case of page 1 because Jekyll won't build a pagination URL for page 1. I'm not sure why the cretor used `previous_page_path` for page 1 but this results in wrong hrefs in the pagination. If you are e.g. on page 5 the link behind the 1 would be to page 4. Simply using `href="/"` for page 1 solves this issue afaik.

Fix special treatment for 'page 1' in docs of pagination

---

lib/jekyll/configuration.rb

This is refactoring.
Change case statement to the hash constant. 
It is good practice to separate the data from the code.
It isn't related to any GitHub issue. 
The goal of this PR is to improve readability. 
The functionality is the same.

Move permalink styles data to constant

---

.rubocop.yml
Gemfile

This is a project maintenance.
Update rubocop gem from version 0.86.0 to 0.87.1
Closes #8285 
Closes #8288

Update rubocop gem to 0.87.1

---

docs/_data/docs_nav.yml
docs/_docs/rendering-process.md

The *Order of Interpretation* tutorial touches upon some of the quirks of Jekyll's rendering process.
But since tutorials are authored from a user's point-of-view and because they're not a readily accessible part of the documentation site, I propose to add a dedicated section to the main documentation.
Closes #8286 
Related discussion in #8246

Add a note on the rendering process in the docs

---

.rubocop_todo.yml
lib/jekyll/tags/include.rb

This is refactoring.
I wanted to remove the `lib/jekyll/tags/include.rb` file from the exclusion list in `.rubocop_todo.yml`.
But when I looked there, I did a little refactoring.
Now this code is more readable.
It isn't related to any GitHub issue.
The functionality is the same.

Replace nested conditional with guard clauses

---

.github/PULL_REQUEST_TEMPLATE.md

I assumed that the PR template is a kind of documentation.
I have added to the list of PR types: "This is a 🔨 code refactoring."
It isn't related to any GitHub issue.
The functionality is the same.

Add refactoring type to PULL_REQUEST_TEMPLATE

---

Rakefile

IRB has since dropped the need for `-rubygems` CLI argument and now parses it as `-r ubygems`. It's better to remove this outdated switch from Rakefile.
Fixes #8199

Fix `rake console` generating LoadError

---

docs/_docs/posts.md

Probably related to a habit of writing URLs in CSS ...

Extra apostrophes in an URL

---

docs/_docs/structure.md

The parenthetical clause providing examples ("such as css and images [...] and so forth") applies to "Every other directory and file", not the exceptions ("those listed above").
---
_Very_ minor grammatical correction. When I initially read the original wording, I was like, "Wait, what? That makes no sense / that seems like the opposite of what I'd expect." But then I realized if I mentally shifted the modifier clause to the beginning of the sentence, it made total sense. 
This PR corrects the attachment point of the modifier clause (but more economically than my mental shift).

Clarify target of subordinate clause

---

.travis.yml
Gemfile
features/collections.feature
features/step_definitions.rb
jekyll.gemspec
lib/jekyll/commands/new.rb
lib/jekyll/configuration.rb
lib/jekyll/converters/markdown/kramdown_parser.rb
script/default-site
test/test_kramdown.rb

This PR applies @ashmaroli's kramdown v2 upgrade to the Jekyll 3.x series.
Ultimately I would like to be able to support both versions, but that may not be viable.
Upgrading to kramdown v2 requires bundling extra extension gems, so that is a consideration for GitHub Pages and other hosting sites that curate a list of dependencies.
/cc @jekyll/core 
Fixes #8315

[3.x] kramdown v2 upgrade

---

History.markdown
docs/_posts/2020-08-06-jekyll-3-9-0-released.markdown

This is a release post for the 3.9.0 version which allows kramdown v2.
/cc https://github.com/jekyll/jekyll/issues/8315

[3.x] Add 3.9.0 release post

---

features/collections.feature
lib/jekyll/configuration.rb
lib/jekyll/converters/markdown/kramdown_parser.rb
test/test_kramdown.rb

Default the language to `plaintext`. This prevents errors like `Rouge::Guesser::Ambiguous` like https://github.com/jekyll/jekyll/issues/7858.
/cc https://github.com/jekyll/jekyll/issues/8324

[3.x] Add default language for kramdown syntax highlighting

---

features/permalinks.feature
lib/jekyll/site.rb

This prints a warning for permalink conflict when running `jekyll serve`
Example output:
```
Configuration file: ~/permalink-conflict-test/_config.yml
Source: ~/permalink-conflict-test
Destination: ~/permalink-conflict-test/_site
Generating... 
Jekyll Feed: Generating feed for posts
Conflict: The URL '~/permalink-conflict-test/_site/z.html' is the destination for the following pages: b.markdown, c.markdown
done in 0.324 seconds.
Auto-regeneration: enabled for '~/permalink-conflict-test'
Server address: http://127.0.0.1:4000/
Server running... press ctrl-c to stop.
```
Closes #6207

Warn on command-line with permalink conflict

---

features/permalinks.feature
lib/jekyll/commands/doctor.rb

This updates `lib/jekyll/commands/doctor.rb` to skip redirect pages (from the `jekyll-redirect-from` plugin) when checking for permalink conflicts
Closes #8346

Supress warning issued for redirect pages

---

docs/_docs/index.md

Show how to serve the web with autoreload rightaway:
`bundle exec jekyll s --livereload
`
Described how to add autoreload mode when running the server:
`bundle exec jekyll s --livereload` 
At the quick start guide is not explained how to run in autoreload mode. And this is a must feature always.

Run server with Autoreload

---

.rubocop.yml
test/test_filters.rb
test/test_front_matter_defaults.rb

`rubocop-performance-1.7` and `rubocop-performance-1.8` added some new cops that are not configured by default.
This opinionated PR enables some of them and disables some of them.

Configure Performance cops

---

docs/_docs/deployment/automated.md

In a bare git repo (which is what we dealing with here) the [$GIT_DIR](https://git-scm.com/docs/githooks/)-variable points to what we want to clone here. (It would actually also work with a non-bare repo though `$GIT_DIR` points to the repo-root's `.git` subdirectory in this case.)
So omitting `$GIT_REPO` and using `$GIT_DIR` instead makes one less adjustment necessary.
This is a 🔨 code refactoring of some code-example in the docs.
Just used it and had to do one additional edit before it worked because I overlooked the $GIT_REPO variable. 
I you think it is not worth thinking about it to much or conducting en extended discussion about it. So don't hesitate to just drop this pr without further notice before it creates headaches to anyone. It is meant as a quick improvement but not to waste …

Simplifying the Git post-receive hook-example

---

docs/_docs/configuration/options.md

Several build and serve flags/options are documented in the command line help, but not on the Jekyll website.  This pull request adds the doc to the website. Here are the command-line help flags missing from the doc (v4.1.1):
```
$ jekyll help build
...
-p, --plugins PLUGINS_DIR1[,PLUGINS_DIR2[,...]]  Plugins directory (defaults to ./_plugins)
--layouts DIR  Layouts directory (defaults to ./_layouts)
...
-t, --trace        Show the full backtrace when an error occurs 
$ jekyll help serve
...
-o, --open-url     Launch your site in a browser
...
--show-dir-listing  Show a directory listing instead of loading your index file.
...
--livereload-ignore ignore GLOB1[,GLOB2[,...]]  Files for LiveReload to ignore. Remember to quote the values so your shell won't …
```

Add missing doc for build and serve commands

---

features/post_url_tag.feature
features/support/helpers.rb
lib/jekyll/tags/post_url.rb

The existing path matching regex has a `\x` modifier in order to disregard whitespaces.
This patch fixes the issue by modifying the regex to be whitespace-sensitive.
Resolves #8374
/cc @pekspro

Fix path matching regex in post_url Liquid tag

---

docs/_data/config_options.yml
docs/_docs/configuration/options.md

Currently there are two tables (build options and serve options) at https://jekyllrb.com/docs/configuration/options/ that are rendered by marking up in HTML directly. This hampers new additions to those tables.
Since the markup is consistent for a given table, we can improve the contributability / maintainability by using datafile(s) and iterating through them via Liquid.
For example:
```
<tbody>
{% for entry in site.data.config_options.serve %}
<tr class="setting">
...
</tr>
{% endfor %}
</tbody>
```
and 
```
<tbody>
{% for entry in site.data.config_options.build %}
<tr class="setting">
...
</tr>
{% endfor %}
</tbody>
```
Closes #8373

Docs: Use data file(s) to render table(s) at https://jekyllrb.com/docs/configuration/options/

---

lib/jekyll/tags/link.rb

- This is a 🔨 code refactoring.
Currently with the `link` tag, we have a string interpolation inside an iteration block:
https://github.com/jekyll/jekyll/blob/959fc18db5864f94b4c15c1540a223d5e72b43bb/lib/jekyll/tags/link.rb#L25-L29
In a site with lots of files, the string interpolation on `L#28` *can* result in a lot of unnecessary String allocations especially if the link tag is rendered in multiple pages.
The simplest solution is to stash the interpolated string in a variable outside the iterating block and reference it as necessary.

Reduce string allocations from the `link` tag

---

lib/jekyll/document.rb

- This is an :zap: optimization change.
Instead of checking `collection&.write? && site.publisher.publish?(self)` on every call to the `:write?` method, compute the result once per instance and reuse the result on subsequent calls.
`document.write?` is invoked via various core classes (e.g. `Site`, `Regenerator`) and in-house plugins (e.g. `jekyll-mentions`, `jemoji`)

Stash documents `write?` attribute in a variable

---

.rubocop.yml
Gemfile

Enable some new cops: https://github.com/rubocop-hq/rubocop/releases/tag/v0.91.0
Closes #8390

Bump RuboCop to v0.91.x

---

.github/workflows/actions/memprof.rb
.github/workflows/third-party.yml

A GitHub Actions Workflow to build a third-party repository and profile memory usage of the build as well.
The third-party repository is a slightly modified fork of public repo https://github.com/tomjoht/tomjoht.github.io which was earlier used in the (now retired) Utterson check-runs.
- Using the fork means the contents don't change over time even if the original upstream repository adds new content.
- The memory-profiling script only traces files with the stub `lib/jekyll/` in order to better expose relevant information.

Add workflow to build and profile third-party repo

---

lib/jekyll/url.rb

Generating URLs from a drop (current route for all documents of a collection) results in a lot of string allocations because of use of non-mutating methods to manipulate strings.
This pull request replaces those non-mutating methods that mutate a duplicated version of long-term strings and mutate temporary strings.

Reduce string allocations from generating doc URLs

---

docs/_docs/installation/ubuntu.md

I made clearer that not Ruby itself but RubyGems packages should not be installed as root.
Small change, no issue opened.

Clarify gem installation instructions

---

lib/jekyll/tags/include.rb

`Jekyll::Site#incremental?` takes an optional argument which is an empty Hash by default:
https://github.com/jekyll/jekyll/blob/f8c72089dd9591d1654f10dedd819536d2674c7c/lib/jekyll/site.rb#L367-L369
Since the empty hash is a default parameter, every call to the method allocates an empty Hash.
Therefore, calling the method while rendering an *include file* can allocate numerous Hashes unnecessarily.
The solution is then to access the config value directly.

Check if site is in incremental mode optimally

---

docs/_docs/continuous-integration/circleci.md

Removes CircleCI v1 docs as it was sunset in 2019.
Also removes the `NOKOGIRI_USE_SYSTEM_LIBRARIES` description from the CircleCI docs. That was originally introduced 6 years ago (2014-06-27) (cf. e2de7ab0c7ceacf46ee34ee8b71bd44cfaea2465), but has not been reviewed or revised so far. (cf. #8409)
cf. https://circleci.com/sunset1-0/

Remove CircleCI v1 docs

---

docs/_docs/continuous-integration/travis-ci.md

Remove `NOKOGIRI_USE_SYSTEM_LIBRARIES` from the [Travis CI docs](https://jekyllrb.com/docs/continuous-integration/travis-ci/#3-configuring-your-travis-builds).
Travis CI now makes CI jobs faster enough by automatically caching all rubygems including nokogiri by default.
At least since 2017-05-12, nokogiri team explicitly has stated the their own libxml2/libxslt libraries in the docs.
- https://nokogiri.org/tutorials/installing_nokogiri.html
- https://github.com/sparklemotion/nokogiri.org/commit/780c269f6bf32b0a20ef6459ceddf77e5d242c0f
The description to be removed was originally introduced 6 years ago (2014-06-27) (cf. e2de7ab0c7ceacf46ee34ee8b71bd44cfaea2465), but has not been reviewed or revised so far.
It is confirmed that caching rubygems is valid on …

Remove NOKOGIRI_USE_SYSTEM_LIBRARIES from Travis CI docs

---

lib/jekyll.rb
test/test_path_sanitization.rb

Bail early if the questionable path to be prefixed is `nil`.
Discovered while implementing #8408

Handle nil argument to Jekyll.sanitized_path

---

Gemfile

Lock to an older version of `rubocop-ast` on JRuby since the `v0.7.0` has a dependency on a native extension not compatible with JRuby.

Fix test suite compatibility with JRuby

---

benchmark/path-manager.rb
lib/jekyll/page.rb
test/test_page_without_a_file.rb

`File.join` is sensitive to `nil` arguments. So we need to coerce arguments to String to be safer.
Using `Jekyll::PathManager.join` on the other hand allows optimized execution for same results.
Prior discussions: https://github.com/jekyll/jekyll/pull/8404#discussion_r494402547

Compute relative_path of pages using PathManager

---

.rubocop.yml
lib/jekyll/drops/drop.rb
lib/jekyll/filters/url_filters.rb
lib/jekyll/frontmatter_defaults.rb
lib/jekyll/page.rb
lib/jekyll/readers/post_reader.rb
lib/jekyll/related_posts.rb
lib/jekyll/renderer.rb
lib/jekyll/site.rb

RuboCop Performance has a cop that allows detecting method chains that duplicate starting array with each chain segment.
But the cop is disabled by default.
This pull request enables the cop and fixes offenses reported by it by switching non-mutating methods with mutating counterparts.

Enable `Performance/ChainArrayAllocation` cop

---

lib/jekyll/document.rb
lib/jekyll/static_file.rb

`Site#in_dest_dir` is a flexible method that joins multiple arguments into an absolute path:
https://github.com/jekyll/jekyll/blob/f8c72089dd9591d1654f10dedd819536d2674c7c/lib/jekyll/site.rb#L411-L415
Therefore, it is unnecessary to generate paths beforehand.

Utilize flexibility of Site#in_dest_dir

---

lib/jekyll/filters.rb

- This is a 🔨 code refactoring.
Chaining multiple non-mutating methods result in unnecessary duplication.
The solution is to duplicate input once and mutate the result thereafter.

Reduce allocation from normalize_whitespace filter

---

lib/jekyll.rb
lib/jekyll/path_manager.rb
test/test_path_manager.rb

I was running stackprof over a site with ~600 posts and noticed `Jekyll.sanitize_path` was being called many times over so I tried caching responses. Benchmarks logs for `jekyll-sanitize-path` before and after:
Before:
```
Warming up --------------------------------------
with no questionable path
6.977k i/100ms
with a single-part questionable path
6.620k i/100ms
with a multi-part questionable path
6.350k i/100ms
with a single-part traversal path
6.544k i/100ms
with a multi-part traversal path
6.314k i/100ms
with the exact same paths
402.619k i/100ms
with a single-part absolute path including the base_directory
6.656k i/100ms
with a multi-part absolute path including the base_directory
6.443k i/100ms
with a single-part traversal path including the …
```

Cache Jekyll.sanitized_path

---

lib/jekyll/cleaner.rb

- This is a 🔨 code refactoring.
`Regexp#match?` is the faster alternative from Ruby 2.4 when the `MatchData` object is not consequently utilized.
While the first build after running `jekyll clean` won't have files in the dest-dir, consequent builds will have the directory populated. So this line could get executed numerous times especially in a site with numerous pages and files

Use Regexp#match? when MatchData is not required

---

docs/_data/showcase.yml

This is a 🔦 documentation change. My employer, Lightburn, noticed that the company name was misspelled and would like it corrected.

correcting lightburn company spelling

---

docs/_docs/themes.md
docs/pages/resources.md

I've noticed that many of the best, community-curated, jekyll themes are right on GitHub under the #jekyll-theme tag ([GitHub.com #jekyll-theme repos](https://github.com/topics/jekyll-theme)). So, I've added links to this location on the Jekyllrb site in the two places it has a list of themes to go get.
NA

Add links to all Jekyll themes on GitHub tagged with #jekyll-theme

---

lib/jekyll/convertible.rb

- This is an optimization change.
Classes that mixin the `Jekyll::Convertible` module (primarily `Jekyll::Page`) doesn't have their `to_liquid` method memoized.
Therefore, every call to the `#to_liquid` method (esp. via the Liquid Filters `where`, `find`, `sort`) has their default front matter (which never changes for a given `site.config` hash) freshly computed.

Memoize defaults computed for Convertibles

---

.github/workflows/third-party.yml

So that the profiling results
- can expose any deprecation warning not fixed yet.
- better reflect allocations by using newer Ruby versions.
*(Not using Ruby 2.7.2 just in case the deliberate breaking change in Ruby not abort the workflow prematurely)*

Use Ruby 2.7.1 in GitHub Actions

---

lib/jekyll/document.rb

Call *set union* on `data["categories"]` only if it is an Array instead of defaulting to a temporary empty array.

Reduce array allocations from merging categories

---

docs/_docs/installation/other-linux.md
docs/_docs/troubleshooting.md

On Fedora, add:
- openssl-devel 
- redhat-rpm-config
as default dependecies, there is no reason to not list them in the installation section since the build step depends on them.
Add default build dependency on Fedora.

docs: installation: fedora: add additional dependencies

---

.rubocop.yml
lib/jekyll/path_manager.rb

- Enable `Lint/NoReturnInBeginEndBlocks`
- Split logic in offending `Jekyll::PathManager.sanitized_path` into a private class method.
- Add a new private cache to stash `base_directory` appended with a forward slash.
RuboCop 1.2.0 added `Lint/NoReturnInBeginEndBlocks`. According to its author:
> This cop detects the usage of explicit `return` statements inside a `begin..end` block in the context of assignments.
>
> The issue is that a return inside a `begin..end` block in assignment contexts will not assign the desired value to the variable, but will return the value expected to the caller.
>
> In case you're using memoization, the memoized variable will be always `nil` and the code inside the `begin..end` block will
> execute as many times as you access the …

Enable Lint/NoReturnInBeginEndBlocks Cop

---

lib/jekyll/document.rb
lib/jekyll/page.rb
lib/jekyll/static_file.rb

- This is an optimization change.
Because multiple calls to the `:destination` method with the same dest_dir (generally `@site.dest`) will result in unnecessary computations and allocations.

Memoize destination of pages, documents and staticfiles

---

features/permalinks.feature
lib/jekyll/commands/doctor.rb

Currently on `master`, the build process detects conflicting URLs. But it is limited to just pages and posts.
The proposed change extends the detection to *all documents* and *static files*.
Also, improves the readability of the warning message:
```
URL Conflict: The destination "jekyll/tmp/jekyll/_site/puppies/2009/03/27/rover.html" is the same for the following:
- jekyll/tmp/jekyll/_posts/2009-03-27-rover.markdown
- jekyll/tmp/jekyll/_puppies/rover.md
```

Enhance detection of conflicting destination URLs

---

features/hooks.feature
lib/jekyll/hooks.rb

`Jekyll::Document` instances allows triggering all registered hook events for owner `:documents` as well as an individual collection:
https://github.com/jekyll/jekyll/blob/11ff8aa0dd610fa26689dc8d2d42decd3bba79ee/lib/jekyll/document.rb#L390-L393
But this support was not extended for the `post_convert` hook event on `master` (*hook event to be introduced in v4.2*).
This pull request fixes the above discrepancy.

Allow triggering `:post_convert` events atomically

---

lib/jekyll/filters.rb

Instead of using `#map` recursively, iterate through using `#each_with_object`.

Reduce allocations from rendering item as liquid

---

lib/jekyll/convertible.rb

Currently only `Document` objects are shown to be read when Jekyll builds with `--verbose` switch.
With this change, all classes that include the `Convertible` module (mainly `Page`, `Layout`), except `PageWithoutAFile`, will have their `relative_path` output when building with `--verbose` mode.

Debug reading Page and Layout objects

---

features/rendering.feature

This is to test a hypothesis put forward by @parkr in https://github.com/jekyll/github-metadata/issues/131#issuecomment-446625377 and resolve any confusion surrounding the same.

Test rendering arbitrary Liquid variables by default

---

.github/workflows/docs.yml

This is essentially a rework of #8126.
Key points and notable features:
- Use `GITHUB_TOKEN` provided by GitHub Actions for authentication
- Reference: [GitHub Help article on `GITHUB_TOKEN`][1]
- There used to (before February 2020) be an issue where the above token cannot trigger GitHub Pages builds. This is no longer the case. ([Reference][2])
- Cache installation from Bundler
- The cache depends on both `Gemfile` and `jekyll.gemspec` from the repository root. As Jekyll is always in rapid development, I chose to always run `bundle install`, regardless of whether there's a cache hit.
- Use a global environment variable to specify Ruby version ([Reference][5])
- Generate prettier commit messages. Example:
```text
Deploy docs from 0123456789abcdef0123456789abcdef
iBug: Build docs site …
```

Build docs site with GitHub Actions

---

lib/jekyll/site.rb
test/test_site.rb

The various phases within `site.process` has `Returns nothing.` in the Ruby code documentation.
Yet, those phases when called individually returns something other than nothing.
This pull request fixes above by explicitly returning `nil`.
When toying with the site build process phases via IRB, various phases may output large amount of data in site with numerous pages and documents.

Explicitly return nil after site process phase

---

lib/jekyll/layout.rb
lib/jekyll/site.rb

Most of the objects created under Jekyll namespace already have custom inspect strings.
This pull request extends the behavior to `Jekyll::Site` and `Jekyll::Layout` objects as well.

Add custom debug strings for Jekyll objects

---

lib/jekyll/readers/data_reader.rb

- This is a 🙋 feature or enhancement. 
In sync with the `master` branch outputting relative paths of layouts, pages, documents and static files as they are read in a site under `--verbose` builds, also output similar relative paths for data files.

Debug reading data files in a site

---

docs/_docs/structure.md

On the **Directory Structure** documentation page, in the `_sass` section, add a link to the **Assets** documentation page.
With the existing wording, there's no indication that the `main.scss` file needs to contain front matter in order to be converted into `main.css`. So this pull request adds a link from the `_sass` section of the directory structure to the Assets documentation page to avoid confusion over this.

structure.md: add link to Assets page from `_sass` section

---

docs/_docs/installation/macos.md

Apple switched the default shell to Zsh with Catalina, so adding the ruby PATH in .bash_profile is increasingly now the legacy approach, and will not have effect for newer macOS users, preventing them from continuing with the Jekyll installation instructions.
This commit adds instructions to echo the PATH to .zshenv (the Zsh equivalent of .bash_profile) if the user is on Catalina or newer, as well as to check which version of macOS is running for those who are unsure.
I've updated the macOS installation documentation to make them work for users of Catalina and newer versions of macOS, for whom the default shell is no longer bash but is now zsh, and so for whom adding the ruby PATH to .bash_profile will not have any effect. 
I've added this change to both …

Echo PATH to .zshenv for newer macOS's

---

lib/jekyll/filters.rb

- This is an :zap: optimization change.
The `:to_liquid` method for `Convertible` objects (mainly `Jekyll::Page` and subclasses) is not memoized. Therefore, calling `Jekyll::Page#to_liquid` multiple times results in unnecessary Hash allocations.
This change optimizes iteration through `site.pages` when `item_property` of each page is computed.
Filtering `site.pages` with either of `sort`, `where`, `find` filters multiple times.

Reduce allocations from computing item property

---

lib/jekyll/page.rb

- This is an :zap: optimization change
In the same boat as #8485, because `Jekyll::Page#to_liquid` isn't memoized, `Jekyll::Page#dir` get called for every call to `#to_liquid`.
Unfortunately, `#dir` can't be directly memoized either because `@dir` is already defined in `Jekyll::Page#initialize` and has different semantics in comparison to the result from calling `#dir`. Using a new instance variable name is risky because `Jekyll::Page` is a popular ancestor for Generator based plugins.
Therefore, move the allocating logic into a new private and memoized method.

Optimize Page#dir with a private method

---

docs/_config.yml
docs/_data/showcase.yml
docs/pages/showcase.html

Dynamic screenshots hosted on Cloudfront weren't loading, replaced with static screenshots served by Cloudinary to ensure optimal performance.
👀 [Preview on Netlify](https://deploy-preview-8504--jekyllrb.netlify.app/showcase/)
Fixes #8491

fix: showcase

---

docs/_layouts/tutorials.html
docs/_sass/_style.scss

Tutorials utilizing just Liquid logic is considered safe since Liquid is inherently non-evaling. However, tutorials with Ruby code to be used as plugins cannot be deemed safe without proper review and test-coverage.
Therefore, place a disclaimer to indirectly state that the user discretion is recommended.
The disclaimer is not rendered by default. Tutorials with Ruby code need to explicitly enable it via the front matter:
```
plugin_disclaimer: true
```

Add a disclaimer to tutorials involving Ruby code

---

docs/_docs/plugins/generators.md

- Improve Ruby examples.
- Improve comprehensibility of the article. 
- Normalize line-lengths.

Improve documentation on developing generators

---

docs/_data/config_options/build.yml

There was a typo in the Configuration docs, specifically the 'layouts_dir'.

Fixes typo in layouts_dir documentation

---

.github/workflows/ci.yml
jekyll.gemspec
test/test_generated_site.rb

As of Ruby 3.0, WEBrick is no longer bundled with Ruby, so it needs to be listed as a dependency of Jekyll.
Fixes #8523

Add webrick as a dependency

---

.rubocop.yml
Gemfile
benchmark/schwartzian_transform.rb
test/helper.rb
test/test_ansi.rb
test/test_cleaner.rb
test/test_collections.rb
test/test_commands_serve.rb
test/test_configuration.rb
test/test_doctor_command.rb
test/test_document.rb
test/test_drop.rb
test/test_entry_filter.rb
test/test_excerpt.rb
test/test_filters.rb
test/test_front_matter_defaults.rb
test/test_kramdown.rb
test/test_page.rb
test/test_page_without_a_file.rb
test/test_plugin_manager.rb
test/test_regenerator.rb
test/test_sass.rb
test/test_site.rb
test/test_site_drop.rb
test/test_static_file.rb

This is a 👨🏻‍🎤  style enhancement.
- Bump to [Rubocop 1.8.0](https://github.com/rubocop-hq/rubocop/releases/tag/v1.8.0) 🆙 
- Enable new cops 👮🏻 
- Add extensions for minitest, rake and rspec 💅🏻 
- Lint Robucop config file ✅ 
- Auto-correct ✨

style: enable new cops

---

docs/_docs/github-pages.md

Much of the contents of the Jekyll GitHub Pages guide is duplicated on the GitHub docs page. I imagine they have been considerably updated since the Jekyll GitHub Pages guide was last modified. Given that the GitHub docs seem to be pretty high quality to me, I think it's probably best to link to them rather than duplicating their contents.
I'm not entirely sure how much of the Jekyll GitHub Pages guide needs to be kept:
- The "github-pages gem" section seems to be duplicated [in the GitHub docs](https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/creating-a-github-pages-site-with-jekyll) (see steps 8-9) so I've removed it.
- I can't find the information from the "Project Page URL Structure" section in the GitHub docs (I am not …

Remove GitHub Pages content which is in GitHub docs

---

lib/jekyll/mime.types

Notably, this adds support for `.avif` images.

Regenerate supported mime types

---

Gemfile

This is a CI fix
To fix current CI failures.
[Rubocop 1.9 had a bug][1] which caused rubocop to crash when inspecting one of jekyll's files. Since jekyll had rubocop  `~> 1.0`, CI would automatically pull up latest version.
To fix this, pin minor version too. Upgrade rubocop as and when required.
[1]: https://github.com/rubocop-hq/rubocop/issues/9479

Pin rubocop version

---

.github/workflows/ci.yml
.rubocop.yml
Earthfile
docs/_docs/contributing.md
features/post_excerpts.feature

This is a 🙋 feature or enhancement to the build process.  Jekyll itself is unchanged.
- I've adjusted the contributor documentation to explain how to use the local cross-version feature
Introduce earthly to speed up JRuby tests and allow for running the CI locally across various ruby versions. This build should be about 10 minutes faster than the previous build (40+ minutes -> 27ish minutes). 
I discussed this change with @DirtyF via email. 
The JRuby build in GitHub Actions is the bottleneck for the CI process. By introducing an earthfile, the step can be optimized a bit, and also it allows for running the CI locally, across various ruby versions, by using containers.
You can now run the full CI locally by running:
```
earthly +all
```
GitHub Actions also does a similar process, although …

Cross Version Testing Locally and Faster CI

---

docs/_data/ruby.yml

This updates the current Ruby version to 3.0.0. This is the current stable version per the Ruby [docs](https://www.ruby-lang.org/en/downloads/).
Just a minor doc update!

Update current Ruby version to 3.0.0

---

lib/jekyll/tags/include.rb
test/source/_includes/params@2.0.html
test/test_tags.rb

Our `{% include %}` tag presently isn't permissive enough to handle many valid filenames, include `foo@bar.html`. This `@` symbol is used by systems within the Node ecosystem and the `include` tag is often used to selectively include HTML/JS/CSS from within a Node package in a Jekyll site. 
This does _not_ include any of the reserved characters: https://en.wikipedia.org/wiki/Filename#Reserved_characters_and_words
It adds support for the following characters:
- `@`
- `#`
- `~`
- `+`
- `-`
- `(` and `)`
This PR continues the work that @Convincible did in #7096.
We'd like to be able to use this in GitHub Pages, so I'll plan a back port to Jekyll 3.x as well.

Update include tag to be more permissive

---

docs/_docs/configuration/liquid.md

Perhaps "orthogonal" (they don't affect each other) is slightly better wording than "mutually exclusive" (they can't "exist" at the same time)?
https://en.wikipedia.org/wiki/Mutual_exclusivity
Was a bit confused when I saw "mutually exclusive" regarding `error_mode` and (`strict_variables`, `strict_filters`), then to see both sets turned on.

docs liquid: Replace "mutually exclusive" with "orthogonal"

---

docs/_docs/installation/macos.md

When you install Ruby with Homebrew, and you install a gem the regular
way, without any flags, it gets installed in
`/usr/local/lib/ruby/gems/2.7.0/bin`. If that directory is not in the
`PATH`, you will get "command not found" when trying to use that gem.
This is a common issue people run into when they type
`gem install jekyll` instead of `gem install jekyll --user-install`.
Do a search for "jekyll: command not found" in your favorite search
engine, in GitHub, Stack Overflow, etc.
Updating the documentation to also include the gems directory will
prevent this issue and will make people happier.
Ideally, if this were my project, I would replace pretty much this
entire document with 3 steps:
1. Link to a reliable, repeatable script that can set up a proper
Ruby environment with a Ruby …

Fix for important missing step in macOS Installation Docs: Add the Homebrew gems directory to the PATH

---

docs/_docs/continuous-integration/github-actions.md

The most recent version of the jekyll-action GitHub Action, 2.1.0, has changed the _environment variable_ `JEKYLL_PAT` to a _parameter_ called `token`.
https://github.com/marketplace/actions/jekyll-actions#deprecation
Adding this change should make it easier for anyone setting up the GitHub Action. Using the latest version of the action brings it into line with current documentation.

Use latest Jekyll-action configuration

---

docs/_docs/troubleshooting.md

Docs about failure and troubleshooting on macOS with ARM64 architecture (M1 chip).
Solves #8548

docs: troubleshoot macOS with ARM64 architecture

---

lib/jekyll/tags/include.rb
test/source/_includes/params@2.0.html
test/test_tags.rb

This backports #8618 for Jekyll 3.9.x.

Backport #8618 for v3.9.x: Update include tag to be more permissive

---

docs/_docs/continuous-integration/github-actions.md

This PR replaces the occurrences of `master` as a branch name with `main` in the Github Actions doc. The default branch name on GitHub has been `main` [for a while now](https://github.blog/changelog/2020-10-01-the-default-branch-for-newly-created-repositories-is-now-main/), so I thought I'd swap it out.
😁

Replace references to 'master' branch with 'main' in Github Actions doc

---

docs/_docs/installation/other-linux.md

OpenSUSE requires `ruby-devel`, which is not covered by the existing distro-specific install docs.
Initially raised in https://github.com/jekyll/jekyll/issues/8118, this issue is still outstanding.
This PR is an unqualified improvement over existing docs, but still doesn't present a perfect solution. 
The second half of the OpenSUSE install instructions borrow the Ubuntu install instructions. On OpenSUSE Tumbleweed (in April '21), following these install instructions to the letter will add an executable named `jekyll.ruby2.7*` to PATH, rather than `jekyll`. Users must either use the unwieldy  `jekyll.ruby2.7 serve` (etc),  or consider adding a bash alias or symlink so that `jekyll serve` works as expected.
This could be fixed with either a separate …

DOCS: ruby-devel required for OpenSuse install

---

docs/_docs/step-by-step/02-liquid.md

Simple typo correction on the step-by-step liquid tutorial where a section mistakenly referred to a tag as an object (likely a copy-paste mistake from the previous paragraph).

Fix typo in 02-liquid.md

---

docs/_data/config_options/build.yml

While adding `JEKYLL_LOG_LEVEL`, I also found out that `JEKYLL_NO_BUNDLER_REQUIRE` wasn't mentioned in the docs. 
I am not sure it belong to this exact place in the doc, so I followed the only env variables example I could find in the doc (`JEKYLL_ENV`)
This diff closes #8480

Document JEKYLL_LOG_LEVEL and JEKYLL_NO_BUNDLER_REQUIRE

---

Gemfile

Rubocop 1.13 was released today (2021-04-20) and it has dropped support
for Ruby 2.4[1][2].  This causes rubocop to die on the spot when
trying to run it:
$ bundle exec rubocop --version
1.13.0
$ bundle exec rubocop
Error: RuboCop found unsupported Ruby version 2.4 in `TargetRubyVersion` parameter (in .rubocop.yml). 2.4-compatible analysis was dropped after version 1.12.
Supported versions: 2.5, 2.6, 2.7, 3.0
And thus the "style_check" ci job is currently broken[3].
Rubocop 1.10 and 1.11 don't work either because of a rename:
$ bundle exec rubocop
Error: unrecognized cop Style/StringChars found in .rubocop.yml
Did you mean `Style/StringMethods`?
The latter and arguably the former are breaking changes on minor
versions, which means that rubocop does not follow semantic …

fix: pin rubocop to 1.12 due to error with ruby 2.4

---

docs/_docs/structure.md

It's currently missing from the Directory Structure page:
https://jekyllrb.com/docs/structure/
Kind of relates to #8646.
Feel free to suggest a better explanation; I just want to add the dir there for
completeness and also link to the configuration option.

docs: add overview of .jekyll-cache dir

---

docs/_data/config_options/build.yml
docs/_docs/structure.md

In its overview section, link to the incremental regeneration page and
show how to create the file.  That page is the only one that mentions
both the file by name and also how/when it gets generated (e.g.: with
the `-I` flag):
https://jekyllrb.com/docs/configuration/incremental-regeneration/
I wanted to see if this file is ever generated (or if it was deprecated or
something) and how to do so before adding it to a .gitignore file, as I only
use `jekyll serve` anyway.
It took me a long while to find out how to generate it (I had to clone the repo
and grep around).

docs: clarify where .jekyll-metadata comes from

---

lib/jekyll/cache.rb

$ ./script/fmt --disable-pending-cops
RuboCop 1.12.1
Inspecting 134 files
.W....................................................................................................................................
Offenses:
lib/jekyll/cache.rb:166:5: W: [Correctable] Lint/RedundantCopDisableDirective: Unnecessary disabling of Security/MarshalLoad.
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
134 files inspected, 1 offense detected, 1 offense auto-correctable
Try running `script/fmt -a` to automatically fix errors
Relates to #8651.

style: run rubocop -a

---

docs/_data/config_options/serve.yml

This is a 🐛 bug fix, a 🙋 feature or enhancement, and a 🔦 documentation change. 
This adds the default values of the `--port` and `--host` arguments to their documentation.
This was inspired by discussion on https://github.com/jekyll/jekyll/pull/7253 but is not directly impacted by it, or by any subsequent decisions to keep or remove the changes from that PR.

Specify default port and host for serve commands in docs

---

lib/jekyll/cache.rb

This reverts commit 5631170d443c01f85e5c59198bb0847ffdac4af1.
It fixes a warning when using Ruby 3.0, but brings about another one
when using Ruby 2.5, which is what ci uses.  From the logs of that
commit's workflow run[1]:
+style-check | RUBY=2.5
+style-check | --> RUN script/fmt
+style-check | RuboCop 1.12.1
+style-check | The following cops were added to RuboCop, but are not configured. Please set Enabled to either `true` or `false` in your `.rubocop.yml` file.
+style-check | Please also note that can also opt-in to new cops by default by adding this to your config:
+style-check |   AllCops:
+style-check |     NewCops: enable
+style-check | Minitest/AssertWithExpectedArgument: # (new in 0.11)
+style-check |   Enabled: true
+style-check | Performance/MapCompact: # …

Revert "style: run rubocop -a"

---

lib/jekyll/plugin_manager.rb
test/test_plugin_manager.rb

- ✅ &nbsp;I've added tests 🎉 
- ✅ &nbsp;The test suite passes locally 🎉 
Before telling bundler to load plugins in the `:jekyll_plugins` group, `plugin_manager.rb` checks for the existence of a Gemfile in the current working directory.  
In some setups, the Gemfile may live elsewhere and be referenced using the `BUNDLE_GEMFILE` environment variable. In this case, the Gemfile check will fail and the `:jekyll_plugins` group will not be loaded.  
Bundler is aware of the file (since the gems still resolve), so all we need to do is expand the check for a Gemfile to include the BUNDLE_GEMFILE environment variable.
For a given Jekyll site with plugins referenced in the Gemfile and **not** in the _config.yml, run the following in the parent directory:
```
export …
```

Load Jekyll plugins from BUNDLE_GEMFILE location

---

docs/_docs/installation/macos.md

This solves an issue caused by a change in the location of development headers between macOS 10.14 Mojave and 10.15 Catalina.
on OSX 10.15+, the headers package is no longer available. This extra step fixes this issue by setting SDKROOT in shell configuration to the value provided by xcrun

Add step to set SDKROOT

---

jekyll.gemspec

We should force Kramdown to >=2.3.1 to avoid https://github.com/advisories/GHSA-52p9-v744-mwjj

fix(security):  CVE-2021-28834

---

.github/actions/spelling/expect.txt
docs/_docs/configuration/markdown.md

It seems the Markdown Options docs have become out of date, as noted in
https://github.com/jekyll/jekyll/issues/8593. The docs most likely
became out of date when Kramdown was updated to v2, as described in
these release notes:
https://jekyllrb.com/news/2020/08/05/jekyll-3-9-0-released/.
Initially, I intended to fix the specific issue about `gfm_quirks` noted
in #8593, but after digging a little deeper to figure out the correct
way to use that option, it became apparent that other parts of the
Markdown Options Jekyll docs were also outdated and the whole page
needed to be updated to be more accurate and more useful for modern
versions of Jekyll.
So, with that in mind, here's an overview of the changes I'm proposing:
* Adjust the page headings. `Kramdown` …

Improve the "Markdown Options" Docs

---

benchmark/parse-date
lib/jekyll/utils.rb

Same as #8424, let me know if I should write a benchmark :)

Optimize `Jekyll::Utils.parse_date`

---

docs/_docs/index.md

For Ruby 3.0.0 and higher, `bundle exec jekyll serve` will fail because of a missing dependency: `webrick`.
The documentation doesn't mention this problem, while it states that all Ruby versions above 2.4.0 are supported. This is confusing to new users who will probably install the latest Ruby version and thus will be unable to move past step 5 of the [Quickstart](https://jekyllrb.com/docs/).
This PR aims to put a band-aid in this situation by adding a warning at the end of the instructions, allowing affected users to quickly identify and solve the problem.
I came across this problem when starting a new site and getting a bunch of errors on step 5 of the Quickstart.
A quick search lead me to [this …

Add 'webrick' warning note to "Quickstart" Docs

---

docs/_docs/configuration/markdown.md
docs/_tutorials/convert-site-to-jekyll.md

I recently merged #8681 to improve the Jekyll docs for markdown options.
While researching that, I noted that the `kramdown-parser-gfm` gem is
required by default in Jekyll, but I didn't dig further as to why.
After #8681 merged, I was curious about why `kramdown-parser-gfm` is
required by default, and I followed up on digging into it. As it turns
out, this GFM parser is required by default because Jekyll uses GFM by
default. This is clear from the [default config
docs](https://jekyllrb.com/docs/configuration/default/) and the code:
https://github.com/jekyll/jekyll/blob/76517175e700d80706c9139989053f1c53d9b956/lib/jekyll/configuration.rb#L67-L72
Although this is outlined in the default configuration docs, other parts
of the docs don't do a good job making …

Improve GitHub Flavored Markdown Docs

---

.github/workflows/ci.yml
.rubocop.yml
Gemfile
docs/_data/ruby.yml
jekyll.gemspec
lib/jekyll/converters/markdown/kramdown_parser.rb
lib/jekyll/external.rb
lib/jekyll/page.rb
lib/jekyll/renderer.rb
lib/jekyll/tags/include.rb
test/test_utils.rb

This pull request does 3 related things:
1) Update the version of rubocop from 1.12.0 to 1.18.3.
2) Rubocop 1.18.3 doesnt support ruby 2.4 anymore. To allow rubocop to run this PR also brings the minimum ruby version up to 2.5.
3) Autofix all of the problems reported by the newer version of rubocop.
Locally 'script/cibuild' gives this a clean bill of health.
This will resolve multiple open issues.
Closes #8732
Closes #8726
Closes #8721 
Closes #8720

Update rubocop from 1.12 to 1.18 and min ruby from 2.4 to 2.5

---

lib/jekyll/commands/serve/servlet.rb

If you run `jekyll serve --livereload` behind an ssl-terminating reverse proxy (or, presumably, using jekyll's own ssl options), the livereload script gets loaded over `http`. Browsers like Firefox will reject this mixed content load.
Instead of forcing the injection to use `http`, this change uses `location.protocol` which dynamically chooses `http` or `https` depending on the URL in the browser.
This API is well supported: https://caniuse.com/mdn-api_location_protocol

Inject livereload script using `location.protocol` instead of `http:`

---

.rubocop.yml
lib/jekyll/cache.rb
lib/jekyll/commands/serve/live_reload_reactor.rb
lib/jekyll/drops/unified_payload_drop.rb
lib/jekyll/excerpt.rb
lib/jekyll/layout.rb
lib/jekyll/page.rb
lib/jekyll/site.rb

This is refactoring.
Enables Rubocop `Style/AccessorGrouping` rule.
And fixes existing offenses related to accessor grouping.
Accessors with comments still have them, but in some cases I shortened them to the essential context.
It isn't related to any GitHub issue.
The goal of this PR is to to use more strict rules with Rubocop.
Consequently, this is to ensure greater readability and uniformity of the code.
The functionality is the same.

Enable Rubocop accessor grouping, fix existing offenses

---

docs/_docs/installation/macos.md

- This is a 🔦 documentation change
The rbenv-doctor project has renamed its default branch to `main`, so the link to rbenv-doctor provided in the installation instructions no longer resolves.
Super minor and scoped.
The current `rbenv` instructions in the docs no longer work given the branch rename the rbenv-doctor project made.
Before:
```
curl -fsSL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-doctor | bash
```
After:
```
curl -fsSL https://github.com/rbenv/rbenv-installer/raw/main/bin/rbenv-doctor | bash
```

Fixing URL in MacOS install for rbenv-doctor

---

lib/jekyll/tags/highlight.rb

I've decomposed `HTMLLegacy` formatter to appropriate sequence of formatters in the `highlight` tag.
I was verifying approaches for #8621 and discovered that `render_rouge` was not open for extension. Moved away from `HTMLLegacy` so it becomes extensible. No change in actual functionality.
* https://github.com/rouge-ruby/rouge/blob/master/lib/rouge/formatters/html_legacy.rb#L27-L37

Tags:Highlight: Decomposed HTMLLegacy formatter

---

lib/site_template/_config.yml

This is a 🔦 documentation change
A simple removal of extra white space that I noticed on the template `_config.yml` file
Not related to any context, sorry if this is a bad PR :(

Remove trailing whitespace in _config.yml template

---

features/rendering.feature
lib/jekyll/convertible.rb

Reverts a change intended to optimize allocations of Hash objects from `Convertible#to_liquid` in v4.2.0.
Adds a Cucumber scenario to reproduce the regression with current `master` or Jekyll 4.2.0
Ref: https://github.com/jekyll/jekyll/issues/6467#issuecomment-903819795 by @pdmosses
Backport this to `4.2-stable` and include in v4.2.1 ?

Fix regression in Convertible module from v4.2.0 

---

docs/_docs/troubleshooting.md

Fix adjective in `troubleshooting.md` document

---

docs/_docs/step-by-step/01-setup.md
docs/_docs/step-by-step/10-deployment.md
docs/_docs/usage.md
lib/jekyll/commands/serve.rb
test/test_commands_serve.rb

I have not run the CI suite.
When running with `bundle exec jekyll serve` and no other options, the `absolute_url` filter will now use the local server URL instead of the URL from the config (like `benlk.com`) when that URL is the default `localhost:4000`.
This PR is designed to fix the regression introduced in https://github.com/jekyll/jekyll/pull/7253 and described in my comments there: https://github.com/jekyll/jekyll/pull/7253#issuecomment-776359879
If you don't want to check the links, here's a summary: 
- https://github.com/jekyll/jekyll/pull/7253 changed the behavior of `jekyll serve` to use the site URL from the site's config when serving a local development version of the site, if the localhost host and port were not explicitly specified. This meant that …

Revert #7253: "Don't reset site.url to localhost:4000 by default"

---

features/rendering.feature
lib/jekyll/convertible.rb

Fix regression in Convertible module from v4.2.0
This backports eca4504 to 4.2-stable

Backport #8786 for v4.2.x: Fix regression in Convertible module from v4.2.0

---

docs/_docs/step-by-step/01-setup.md
docs/_docs/step-by-step/10-deployment.md
lib/jekyll/commands/serve.rb
test/test_commands_serve.rb

Revert #7253: "Don't reset site.url to localhost:4000 by default"
This backports faef38b to 4.2-stable

Backport #8620 for v4.2.x: Revert #7253: "Don't reset site.url to localhost:4000 by default"

---

docs/pages/index.html

Grammar fix: Use singular copula when dealing with a proper noun.
No production code has been changed.
Fixed grammar, standard english expects the singular copula in relation to proper nouns.
N/A

Update index.html: Grammar fix.

---

docs/_docs/community/community.md

Freenode kind of imploded back in May and everybody moved to Libera.

Prefer Libera. Remove Freenode.

---

lib/jekyll/site.rb
test/test_site.rb

Cache-dir and its contents shouldn't be tracked by version control even if users do not add the directory to their `.gitignore` file.
Currently, while `jekyll new` generates a new site with `.jekyll-cache` added to the `.gitignore`, existing sites using Jekyll 3 on migrating to Jekyll 4 will have to manually update their `.gitignore` file as well.
Similarly, users on Jekyll 4 but opting to use a custom cache-dir location will also have to manually update their `.gitignore` file.
Additionally, Jekyll contributors switching between `master` (or any recent branch) and `3.9-stable` (and older) will also have to manually handle cache dir contents because the `.gitignore` files in older checkouts do not …

Always hide cache-dir contents from Git

---

docs/_data/showcase.yml

What it says on the tin. :smile:
According to their docs repo, they're using Next.js now.

Remove AWS Amplify from the showcase

---

docs/pages/team.md

What it says on the tin :broken_heart: :cry:

Move Frank to Emeritus Core Team Members

---

lib/jekyll/commands/build.rb

This removes the warning about auto regeneration on Windows potentially having problems. According to the info in #8820, the bug we're calling out is four years old and I don't think that it's in our best interest to continue support installations using WSL that are running software that old. I'd rather remove this warning and handle a few extra questions from folks in these scenarios and encourage them to upgrade instead.
Fixes #8820
Potential 4.2 backport candidate?

Remove the warning about auto-regeneration on Windows

---

.github/actions/spelling/expect.txt
docs/_docs/continuous-integration/circleci.md

The original purpose of my PR was to update the CircleCI images used in this example. We've deprecated the legacy Convenience images (the ones namespaced `circleci/`) and instead use the next-gen images (the ones namespaced `cimg/`). While I was in there though, I saw a bunch of other outdated CircleCI mentions or keys. So I updated all of it.
Quick summary:
1. Updated image names to supported ones.
2. Updated to v2.1 config.
3. Removed references to CircleCI 1.0 nomenclature such as a "dependencies" step.
4. Correct docs link.

Update CircleCI example

---

Gemfile
test/test_collections.rb
test/test_site.rb

Bumps Rubocop to 1.22.0 to fix #8827 and tells Rubocop to ignore a couple bits of code in the tests where our formatting is clearer than Rubocop's suggested replacement
Closes #8765
Closes #8773
Closes #8790
Closes #8805
Closes #8827

Relax Rubocop Dependency

---

.github/workflows/ci.yml
Gemfile
lib/jekyll/commands/new.rb

- Running CI via an Earthfile on GitHub Actions results in extremely noisy log outputs. Therefore, run directly. See https://github.com/jekyll/jekyll/runs/4188128787?check_suite_focus=true for an example of a noisy output. The `Earthfile` however  has not been removed to maintain compatibility with the original intention behind introducing the medium.
-  Rewrote the workflow file to improve readability of CI job names and step names.
- Additionally, lock JRuby builds to `http_parser-0.6.0` because newer versions do not have a Java counterpart.

Improve readability of CI logs

---

test/test_filters.rb

Failures can occur in the `TestExcerpt` `#to_liquid` test when the random seed orders `TestFilters` tests before `TestExcerpt` and the tests are run with a system time zone that's has a non-zero offset on 2013-07-22.
The `TestFilters` setup changes `ENV["TZ"]` to `"UTC"` but doesn't reset it.
The `TestExcerpt` `#to_liquid` test fails because `@excerpt.to_liquid["date"]` returns a UTC time and `Time.parse("2013-07-22")` returns a time in the system time zone:
>  Failure: TestExcerpt#test_: An extracted excerpt #to_liquid should contain the proper page data to mimic the post liquid.
>   [jekyll/test/test_excerpt.rb:103] Minitest::Assertion:
>   Expected: 2013-07-22 00:00:00 +0000
>     Actual: 2013-07-22 00:00:00 +0100
This pull request adds a teardown to `TestFilters` …

Fix random test failures in TestExcerpt #to_liquid

---

.github/workflows/release.yml
History.markdown

Add a workflow to build gems consistently
This backports db3f034 to 4.2-stable

Backport #8830 for v4.2.x: Add a workflow to build gems consistently

---

docs/_docs/continuous-integration/github-actions.md

Remove text on GITHUB_TOKEN which is now built-in

---

jekyll.gemspec

`psych-4.x` default in Ruby 3.1 breaks our Cucumber based tests.
```
(::) failed steps (::)
Tried to load unspecified class: Date (Psych::DisallowedClass)
(eval):2:in `date'
/home/runner/work/jekyll/jekyll/features/step_definitions.rb:166:in `/^I have a configuration file with "(.*)" set to "(.*)"$/'
/home/runner/work/jekyll/jekyll/features/step_definitions.rb:175:in `block (2 levels) in <top (required)>'
/home/runner/work/jekyll/jekyll/features/step_definitions.rb:174:in `each'
/home/runner/work/jekyll/jekyll/features/step_definitions.rb:174:in `/^I have a configuration file with:$/'
features/site_configuration.feature:211:in `I have a configuration file with:'
```

Lock gem `psych` to `v3.x`

---

docs/_docs/maintaining/releasing-a-new-version.md

Make the guide self-explanatory to a novice maintainer yet not too verbose for a veteran maintainer looking for quick refresh.

Improve maintainers guide on releasing a new version

---

Gemfile
lib/jekyll/commands/new.rb

Lock `http_parser.rb` gem to `v0.6.x` on JRuby since newer versions of the gem do not have a Java counterpart
- Needed for dev changes in #8942 to pass.
- This needs explicit mention in our History document so that it gets visibility via `jekyllrb.com`.

Lock `http_parser.rb` gem to `v0.6.x` on JRuby

---

docs/_docs/continuous-integration/github-actions.md

Update the document of Github Actions to add cache action step for reducing the build times. Please refer to the original document of [jekyll-action](https://github.com/helaili/jekyll-action). The cache step is also included for performance improvement.
Therefore, I think this change would benefit all bloggers who are using or begin to use Github Actions to publish thier sites.
There are changes below,
- Update example of workflow .yml code
- Update code description

Recommend using `actions/cache` in GitHub Actions documentation

---

features/post_data.feature
lib/jekyll/document.rb

The deprecation message issued when a key in document's data is called directly currently points to the Jekyll gem.
It should instead point to the offending location in the concerned plugin.

Fix deprecation message for missing doc method

---

docs/_posts/2022-03-03-jekyll-4-2-2-released.markdown

Its about time we shipped v4.2.2.
I set the date for tomorrow (March 3rd, 2022).
There's isn't really much to advertise about this release.
Therefore resorted to some bike-shedding and teased the upcoming v4.3.0.

Release post for v4.2.2

---

docs/_docs/maintaining/index.md
docs/_docs/maintaining/releasing-off-stable-branches.md

Document the various steps maintainers need to follow to ship releases of `*-stable` branches.
Based on latest experience from shipping `v4.2.2`
Closes #8825 (prior art by @parkr)

Document releasing off `*-stable` branches

---

docs/_docs/deployment/manual.md

Most traditional web hosting providers <-- add "s"

Fix typo in `_docs/deployment/manual.md`

---

docs/_docs/deployment/third-party.md

Remove [Aerobatic](https://jekyllrb.com/docs/deployment/third-party/) from the [list of third party hosting services](https://jekyllrb.com/docs/deployment/third-party/), as it appears to no longer being in business.

Remove Aerobatic

---

lib/jekyll/collection.rb
lib/jekyll/site.rb
test/test_site.rb

`Jekyll::Site#static_files` should expose all static files in the site. Even those static files read from within collections.
Resolves #8901

Expose collection static files via `site.static_files`

---

.github/actions/spelling/expect.txt
docs/_data/ruby.yml
docs/_docs/installation/macos.md

Instead of providing various options for installing Ruby, it's better to
stick to a single reliable solution: using a version manager. This
drastically simplifies this doc and makes it more maintainable.
Over the past 10 years, I've maintained detailed tutorials for properly
installing Ruby on a Mac. I've helped thousands of people, and I've seen
the same issues over and over.
Per @ashmaroli's request here:
https://github.com/jekyll/jekyll/issues/8784#issuecomment-1060267860
I've linked to my Jekyll installation guide and I pledge to keep it up
to date, as I have with my other Ruby on Mac guides over the past ten
years.
Here's a collection of tweets from grateful people who have benefited
from my guides and script for setting up a proper Ruby environment …

Simplify macOS installation docs

---

lib/jekyll/utils.rb
test/test_utils.rb

Ruby does not allow the BOM option on non-UTF encodings, warning that it is "nonsense". To remove this warning, we change the BOM option check here to match how Ruby checks for compatible encodings.
Relevant bits from the Ruby source are the [test](https://github.com/ruby/ruby/blob/ruby_2_7/io.c#L5693-L5699) and the [`utf_prefix` string](https://github.com/ruby/ruby/blob/ruby_2_7/io.c#L5454).
Fixes #7972.

Only enable BOM encoding option on UTF encodings

---

.github/actions/spelling/patterns.txt
docs/_docs/datafiles.md
lib/jekyll/readers/data_reader.rb
test/fixtures/sample.csv
test/fixtures/sample.tsv
test/test_data_reader.rb

Lets the user specify which converters to pass to `CSV`, defaulting to `nil` if not present in config. This is specifically so that numeric values in a CSV file can be parsed as something other than strings.

Allow Configurable Converters on CSV

---

lib/jekyll/entry_filter.rb

- This is a 🔨 code refactoring.
`pathutil` gem appears to be unmaintained.
Therefore, emulate its existing use in `lib/jekyll/entry_filter.rb` using Ruby's built-in methods.
Relies on existing test defined as: 
https://github.com/jekyll/jekyll/blob/e695c1e24b298994ecb84daa74fba3d20959cba9/test/test_entry_filter.rb#L89-L93

Check symlink outside site_source without Pathutil

---

lib/jekyll/site.rb
test/test_site.rb

`site.config` merged with theme_config should continue responding to methods defined in `Jekyll::Configuration` class.
Consider backporting to 4.2 series

Ensure theme config is a `Jekyll::Configuration` object

---

lib/jekyll/profiler.rb

The total time printed as part of the build profile table is often *significantly* different from the total time reported in the *Build Summary* table. Therefore, *stop* outputting the info that is more misleading than beneficial.
*(Deferring a "fix" per se, for future)*
Closes #8796

Remove misleading totals row from `--profile` table

---

lib/jekyll/commands/doctor.rb
lib/jekyll/filters.rb

Replace links shortened with git.io with the fully resolved URL.
[Github has deprecated git.io and will be disabling all git.io links in 3 days (April 29th)](https://github.blog/changelog/2022-04-25-git-io-deprecation/)

Remove git.io shortlinks from repo

---

docs/_data/ruby.yml
docs/_docs/installation/macos.md

Following macOS [installation guide](https://jekyllrb.com/docs/installation/macos/) installs ruby 3.1.2 at the moment.
This version is used in instruction for setting up chruby:
---
How it looks like now:

Update ruby version for macos guide

---

.github/actions/spelling/allow.txt
.github/workflows/spelling.yml

* Refreshes the workflow based on
https://github.com/check-spelling/spell-check-this/blob/744c66e2140fd8acaf5388efd0db3727d010d6e9/.github/workflows/spelling.yml
* This splits the workflow into two stages, one stage takes (potentially untrusted) user input w/ reduces permissions and the second stage takes the output and produces a comment.
* Updates check-spelling to v0.0.20
* The previous PR comment will be collapsed when a new PR run is performed.
Closes #9091

Use check-spelling/check-spelling@v0.0.20

---

lib/jekyll/drops/theme_drop.rb
lib/jekyll/drops/unified_payload_drop.rb
test/test_theme_drop.rb

- I've added tests (if it's a bug, feature or enhancement)
Introduce `theme` drop to expose theme details.
The details are sourced from the theme's `*.gemspec` file and therefore only valid for gem-based themes.
To allow theme demo-site or documentation site to easily render information regarding the theme (e.g. on the `[About](/about/)` page).

Introduce `theme` drop to expose theme-gem details

---

jekyll.gemspec

[Rouge 4.0 was released](https://github.com/rouge-ruby/rouge/releases/tag/v4.0.0) that dropped support for Rubies older than 2.7.0
Closes #9123

Relax version constraint to allow Rouge 4.x

---

features/step_definitions.rb
jekyll.gemspec

In https://github.com/jekyll/jekyll/pull/8918 we locked the `psych`
dependency because the new version shipped with ruby 3.1 was breaking
our cucumber-based tests.
This PR allows for us to relax that dependency by making our tests use
`SafeYAML` instead of `YAML`.
We are using `YAML.load`, which works in psych 3.x but raises a
`Psych::DisallowedClass` when trying to parse a date with psych v4.x.
This PR fixes this by making our tests use `SafeYAML` instead of `YAML`,
as we are doing in the rest of the codebase.
Closes #9122.

Unlock Psych dependency

---

Gemfile

RDoc's version dependency doesn't allow for minor version updates. This
PR relaxes this dependency to allow any RDoc 6.x.
This allows installing RDoc 6.4.0, released in December 2021. I have
successfully generated the documentation on this version.
Closes #8916

Relax RDoc version dependency

---

lib/jekyll/site.rb
test/test_doctor_command.rb
test/test_site.rb

This PR fixes some cases of false positive reports of file conflicts
when running `jekyll serve`.
In #8961 we added the static files in collections to
`Jekyll::Site#static_files`. 
Static files in collections were part of the `Site#documents` (they get
added [here][1]), so when we added them to `static_files` they were now
in two places.
As, `Jekyll::Site#each_site_file` traverses both `static_files`
and `documents`, those entries get duplicated. This in turn shows up in
the output of `Jekyll::Commands::Doctor` as a false positive:
```
Conflict: The following destination is shared by multiple files.
The written file may end up with unexpected contents.
[...]_site/books/images/sleep-cycles.png
- [...]_books/images/sleep-cycles.png
- [...]_books/images/sleep-cycles.png …
```

Fix false positive conflicts for static files in a collection

---

jekyll.gemspec

jekyll-sass-converter 3.x release will come soon. This PR relaxes version requirements so that users will be able to choose between 2.x and 3.x. 
On API level there is no change, thus it remains compatible with current jekyll.
However, there are a few behavior changes espeically in regard to how sass import works that may break a small fraction of users if they didn't lock dependency version: https://github.com/jekyll/jekyll-sass-converter#migrate-from-2x-to-3x
https://github.com/jekyll/jekyll-sass-converter/pull/140

Support jekyll-sass-converter 3.x

---

docs/_docs/installation/macos.md

While installing `ruby`, `ruby-install` depends on `xzcat` command. If `xz` is not installed, you get an error when you launch `ruby-install ruby`. This PR fixes that.
N/A

Fixed xz dependency

---

lib/jekyll/drops/document_drop.rb
lib/jekyll/drops/excerpt_drop.rb
test/source/_roles/named.md
test/source/_roles/unnamed.md
test/test_document.rb

Fix break in expected behavior where value of `Document#data["name"]` would translate over to Liquid templates as
`{{ page.name }}`. This was broken in v4.3.0 when `{{ page.name }}` was made to delegate to `Document#basename` for parity with `Page` objects.
Resolves #9164
?? #9165

Respect user-defined name attribute in documents

---

docs/_posts/2022-10-26-jekyll-4-3-1-released.markdown

Release post for v4.3.1

---

docs/_tutorials/navigation.md

The current [Nested tree navigation with recursion](https://jekyllrb.com/tutorials/navigation/#scenario-9-nested-tree-navigation-with-recursion) example results in invalid HTML due to incorrect nesting. This PR fixes that.

Fix Nested tree navigation with recursion example

---

lib/jekyll/tags/highlight.rb

- This is a 🔨 code refactoring proposal.
- Existing tests cover changed lines.
Some internal changes to improve `Jekyll::Tags::HighlightBlock`

Cleanup highlight tag

---

script/test

- I've added tests (if it's a bug, feature or enhancement)
- The test suite passes locally (run `script/cibuild` to verify this)
If on a system where system timezone is not +00,
when tests are launched with 'script/test', test case
"TestFilters#test_: filters jsonify filter should convert drop to json"
fails due to difference in expected and actual value of 'date'.
This difference equals the system timezone offset.
Some other forms of lauching tests do work,
such as 'script/test test/test_filters.rb'.
Make the tests run correctly regardless of system timezone
by setting TZ=UTC.
Not related to a GitHub issue.

Run tests in utc

---

.github/workflows/ci.yml

Our CI appears to break on Ruby 3.1.3 in one of our PRs. Investigate with `master` codebase.
Ruby 3.1.3 was shipped on 2022-11-24.

Lock Ruby in CI to v3.1.2 and bump JRuby to v9.4.0.0

---

lib/jekyll/liquid_renderer/table.rb
lib/jekyll/profiler.rb

In #9039 I proposed to remove the `TOTALS` row but there were remnants that continued to generate and render info.
The current pull request removes all of such remnants.
- Consider backporting this to the `4.3-stable` branch.

Remove totals in profile table properly

---

lib/jekyll/site.rb

`Site#each_site_file` reduced in performance in Jekyll v4.3.0 owing to additional checks to filter duplicate entries of static files from a collection.
This pull request optimizes the regression by avoiding duplicate entries of static files itself thereby removing the need for additional checks and filtering.
Consider backporting to the `4.3-stable` branch.

Optimize `Site#each_site_file`

---

features/rendering.feature
features/theme.feature
test/test_filters.rb
test/test_sass.rb
test/test_theme_assets_reader.rb

jekyll-sass-converter just had 3.0.0 release. While the API is compatible, the output is slightly different due to `compact` output style is no longer supported.
https://github.com/jekyll/jekyll-sass-converter/releases/tag/v3.0.0

Update sass related tests for jekyll-sass-converter 3.x

---

docs/_posts/2022-12-21-jekyll-sass-converter-3.0-released.markdown

`jekyll-sass-converter-3.0.0` was released yesterday and contains major changes warranting a post on the official blog especially since users on Jekyll 4.3 and beyond can use it.

Publish post on major release of sass-converter

---

test/test_filters.rb

ruby 3.2 changes Struct.new behavior so that keyword_init option is enabled by default. This means that keyword argument passed to the initializer of Struct is now treated differently with ruby3.2.
To avoid behavior change in jekyll test code, use hash explicitly.
Fixes #9236 .

test: use hash explicitly for Struct initializer for ruby 3.2

---

docs/_data/ruby.yml
docs/_docs/installation/macos.md

I've updated the current ruby version to 3.1.3 in ruby.yml to update the ruby version referenced in the [Jekyll on macOS](https://jekyllrb.com/docs/installation/macos/) guide.
Ruby version 3.1.3 was released yesterday, November 24, 2022, and step 2 in the [Jekyll on macOS](https://jekyllrb.com/docs/installation/macos/) guide currently references ruby version 3.1.2. The pull request change updates the current ruby version in ruby.yml to 3.1.3 from 3.1.2 to update the guide.
Fixes #9194

Update Jekyll on macOS (macos.md) and current ruby version to 3.1.3 in ruby.yml

---

features/rendering.feature
features/theme.feature
test/test_filters.rb
test/test_sass.rb
test/test_theme_assets_reader.rb

Update sass related tests for jekyll-sass-converter 3.x.
This backports 572c86e to 4.3-stable

Backport #9223 for 4.3.x: Update sass related tests for jekyll-sass-converter 3.x

---

script/default-site

In #9257, @ashmaroli proposed copying `script/default-site` to `script/blank-site` so that we could run `jekyll new --blank` then `jekyll build` the way that `script/default-site` does. I was hesitant to duplicate much of the script into another script, so I was thinking that maybe we could make the common components a single script.
With this, you can `script/default-site --blank` to run `jekyll new --blank`. It still runs the smoke test that says "does a blank site build".
The best outcome would probably be a Cucumber test which is already setup to do roughly this kind of operation (create a site, then run jekyll build, and verify that it built the expected output).

script/default-site: accept flags for `jekyll new`

---

docs/_posts/2023-01-20-jekyll-4-3-2-released.markdown

It's time to release v4.3.2 from our `4.3-stable` branch.

Add release post for v4.3.2

---

test/test_rdiscount.rb

This is a 🐛 dev bug fix.
In recent changes to the `3.9-stable` branch, an rdiscount test started failing. I think it's due to an update. Fix the test so that we can get green CI statuses on the more substantive changes.
/cc #9269 #9272

v3.9.x: fix rdiscount test

---

.github/workflows/ci.yml

This is a 🔨 dev change.
Ruby 3.2 has been a more eventful than many other releases, so I figure it's good to get it in the CI matrix for 3.x changes.
I have https://github.com/jekyll/jekyll/pull/9269 but it's not tested in Ruby 3.2, so I figured I'd add it to the matrix.

v3.9.x: test under Ruby 3.2

---

jekyll.gemspec

The test suite passes locally (run `script/cibuild` to verify this)
The `i18n` plugin was added in https://github.com/jekyll/jekyll/commit/93e3eb06d2 to allow for some extra options to the `slugify` filter. At the time, we locked it to i18n v0.x, not allowing v1.0. This is a reasonable solution since we didn't know what v1 would hold. v1 is out (and has been out a while) and it's now required by the newest version of activesupport, a common library used by/with Jekyll. We should update v3.x to allow compatibility with this newer gem version.
Closes #9268.
/cc https://github.com/github/pages-gem/issues/866

3.9.x: Support i18n 1.x

---

docs/_docs/upgrading/3-to-4.md

The second paragraph of Kramdown v2 had a little grammatical error. I moved the word desired to the correct position in the sentence, and gotten rid of the verb are.

Grammatical reordering in  3-to-4 upgrading docs

---

docs/pages/showcase.html

There was a grammatical mistake on the "showcase" page which this pull request fixes.

fixed grammatical mistake on "showcase" page

---

docs/_docs/liquid/tags.md

The use of `mark_lines` in the `highlight` liquid tag, added in https://github.com/jekyll/jekyll/pull/9138, is merged but not yet released.
The docs on the live site have been updated to reflect this new, but unreleased functionality: https://jekyllrb.com/docs/liquid/tags/#marking-specific-lines. This could be confusing to people... it took me some digging to work out why it wasn't working ;)
I'm not sure if this is the correct approach, but this PR tags the feature in the docs as requiring the upcoming `4.4.0` release...

Mark `highlight` `mark_lines` feature as 4.4 in docs

---

docs/_docs/deployment/manual.md

s3_website has been unmaintained for a while and has issues with more recent JDK versions.
I encountered this issue with my Jekyll site and decided to move to using the AWS CLI client directly.

Update S3 deployment to remove s3_website

---

.rubocop.yml
Gemfile
lib/jekyll/static_file.rb

Latest version of RuboCop: 1.45.1 
Closes #9183
Closes #9210
Closes #9220
Closes #9226
Closes #9242
Closes #9251
Closes #9267
Closes #9276
Closes #9295

Bump RuboCop to v1.45.x

---

lib/jekyll/commands/serve.rb
test/test_commands_serve.rb

This PR fixes the issue that `Process.fork` + `Process.detach` would not detach correctly and may crash ruby when subprocess of sass-embedded (part of jekyll-sass-converter) is still running. The problem is that sass-embedded runs a child process and registers an `at_exit` hook to stop the child process, and the `at_exit` hook ran when main process exits but also get inherited by the forked process and would run again when forked process exits.
This PR changes it so that any `at_exit` hook would not run when main process exits, but then would only run when the forked process exits.
-  Fixes #9234

Fix `jekyll serve --detach` with jekyll-sass-converter 3.x

---

lib/jekyll/filters.rb
test/test_filters.rb

Invoking `Array#[]` with a non-integer argument raises `no implicit conversion of String into Integer (TypeError)` which is too technical and vague for end-users. Therefore, surface a more comprehensive message with additional context.
Fixes #9289
Perhaps in a future pull request:
- Let users know the error occurred via a Liquid filter or tag.

Handle TypeError from `where` filter gracefully

---

.rubocop.yml
Gemfile
lib/jekyll/site.rb

- Upgraded Rubocop to version 1.48.1
- Additionally enabled the minmax comparison cop and linted the detected rubocop issue.
Closes #9319 
Closes #9317 
Closes #9313 
Closes #9310

Bump Rubocop to version 1.48.x

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json

This is a 🐛 bug fix
I've updated the NodeJS version in the devcontainer to the 18.x LTS release branch. This fixes the NodeJS deprecation error that initially broke the devcontainer build.
In addition, I have bumped the ruby Docker image version to 3.0 which fixes a rubygems mismatch that further broke the devcontainer build.
I've confirmed that script/cibuild passes. The results are in a gist here: https://gist.github.com/jmahoney/76e7d3ae3833aacb9138d17671208bc5
Fixes  #9358

Bump versions of ruby & nodejs in devcontainer

---

docs/_data/config_options/global.yml

I've documented the difference between Exclude in Jekyll 3 and Jekyll 4 as well as the fact that Include can override the Exclude entries.
The exclusion list is taken from a `_config.yml` as generated via `jekyll new`.
Closes #9372.

Document Exclude behavior, Include overrides and the default exclusion list

---

Gemfile

Upgrade RuboCop dependency to 1.54
Resolves #9387
Resolves #9395
Resolves #9396
Resolves #9398

Upgrade RuboCop to 1.54

---

lib/jekyll/stevenson.rb

logger 1.4.3 will have ruby/logger#85. It initializes a new instance variable in `Logger#initialize`. `Jekyll::Stevenson < ::Logger` doesn't use `super`. So the new instance variable isn't initialized in `Jekyll::Stevenson`. And it causes an exception:
```text
/tmp/local/lib/ruby/3.3.0+0/logger.rb:385:in `level': undefined method `[]' for nil (NoMethodError)
@level_override[Fiber.current] || @level
^^^^^^^^^^^^^^^
from /tmp/local/lib/ruby/gems/3.3.0+0/gems/jekyll-4.3.2/lib/jekyll/log_adapter.rb:45:in `adjust_verbosity'
from /tmp/local/lib/ruby/gems/3.3.0+0/gems/jekyll-4.3.2/lib/jekyll/configuration.rb:143:in `config_files'
from /tmp/local/lib/ruby/gems/3.3.0+0/gems/jekyll-4.3.2/lib/jekyll.rb:118:in `configuration'
from …
```

Add support for upcoming logger 1.4.3

---

.devcontainer/devcontainer.json

Fixes typo in devcontainer.json allow container to build in Codespaces
Fixes #9363

Fix typo in devcontainer.json

---

docs/_docs/installation/other-linux.md

I am on Fedora 36 and found that the prerequisites listed on this page did not include g++. This lead to this make error
```
make: g++: No such file or directory
```
when building native extensions for Bundler.
I think this is the cause of issue [9218](https://github.com/jekyll/jekyll/issues/9218)

Update Fedora prerequisites to include g++

---

.github/actions/spelling/expect.txt
docs/_docs/continuous-integration/github-actions.md

Update github actions documentation to use the [official Jekyll starter-workflow](https://github.com/actions/starter-workflows/blob/main/pages/jekyll.yml) instead of the deprecated docker based workflow.
-  Closes #9418

Update github-actions documentation

---

Gemfile
test/helper.rb

Replace shoulda by shoulda-context
AFAICT, only shoulda-context is used for Jekyll test suite. Therefore replacing `shoulda` by `shoulda-context` should:
1. Remove unneeded dependency (should, shoulda-matchers)
2. Remove ambiguity (because are shoulda-matchers allowed or no?)
3. Improve run time (less files to install, less libraries to load, smaller memory footprint).
Apart from this, I remember times when `shoulda` gem was not really maintained. The stable version still references to `shoulda-matchers 4`, while `shoulda-matchers 5` were released more then 2 years ago.

Test suite uses shoulda-context only.

---

.github/actions/spelling/allow.txt
Gemfile

Allowing activesupport to be bumped to version 7.1 with cucumber 5.1.2 causes our CI to fail. This PR keeps activesupport at version 7.0.x to prevent this for now.
Related: #9235
Related: #9468

Keep activesupport at version 7.0.x

---

docs/_docs/step-by-step/10-deployment.md

Adds a helpful setup note for people publishing with GitHub Pages.
GitHub Pages will build your project using the `github-pages` gem and without any regard for your repository's `Gemfile.lock` file. This PR adds such a note to documentation and advises how you might work with that.

Add GitHub Pages helpful notes

---

docs/_docs/pagination.md

The docs say that this plugin is required in "Jekyll 3", but doesn't clarify what's needed for Jekyll 4. This is a small change to make it clear that it's needed for both.
This isn't related to any open issues, just something I noticed.

Clarify which version of Jekyll needs 'jekyll-paginate'

---

.github/dependabot.yml

This updates our dependabot config for jekyll to allow it to bump ruby dependencies. It also attempting to configure update grouping so we can potentially avoid large numbers of PRs that bump individual gems in favor of larger group updates

Configure dependabot to handle rubygems dependencies

---

Gemfile

Update dependency constraint to allow for rubocop v1.57.2
https://github.com/jekyll/jekyll/issues/9474

Update rubocop gem

---

docs/_docs/installation.md
docs/_docs/installation/freebsd.md

Added instructions to install Jekyll on FreeBSD.

Add FreeBSD installation instructions

---

.github/workflows/ci.yml
Gemfile
appveyor.yml
lib/jekyll/stevenson.rb

This PR ports #9392 to 4.3 stable branch. This change is backward compatible with older version of logger. We should  fix this as soon as possible, because Jekyll is completely unusable on Ruby 3.3 right now. In my test this is the only patch required for Ruby 3.3.
This also picks #9469 and #9196, but these are test-only fixes for the CI. 
cc @parkr @ashmaroli Can you please help take a look and perhaps cut a patch release? Thank you.

Cherry pick logger fix for Ruby 3.3

---

test/test_filters.rb

Merge request #9237 fixed running tests with Ruby 3.2.
In Fedora, we already use version of Ruby, and want to include the latest Jekyll 4.3.2.
Because of this, I ask to backport #9237 to `4.3-stable`.
This project seems to use extensive automation to manage pull requests.
If you prefer, you can close this pull request and backport the merge request using your preferred method.
No issue, but I can add one if you prefer to have one for the archives.
The title would be _tests from 4.3-stable fail with Ruby 3.2_.

Backport #9237 to 4.3-stable "test: use hash explicitly for Struct initializer for ruby 3.2"

---

.github/workflows/ci.yml

Add newly-released Ruby 3.3 to CI matrix. 
https://www.ruby-lang.org/en/news/2023/12/25/ruby-3-3-0-released/
https://github.com/jekyll/jekyll/pull/9513

Add Ruby 3.3 to Jekyll 3.9.x test matrix

---

lib/jekyll/stevenson.rb

This backports the changes in #9392 to 3.9.x release chain. Fixes compatibility with Ruby 3.3.
Backported to the 4.3.x release chain in https://github.com/jekyll/jekyll/pull/9510.

Backport logger-1.4.3 from #9392 to 3.9-stable

---

Gemfile
lib/jekyll/site.rb

A Performance/StringIdentifierArgument violation snuck in.
Also, AppVeyor tests were failing due to activesupport and tzinfo version conflicts.
I noticed in other PRs that this was failing on code that was unchanged.
This should allow the CI check "Style Check" to pass.

Fix Performance/StringIdentifierArgument violation in site.rb and allow activesupport 6 for windows tests

---

docs/_docs/pages.md

The docs about the `page_excerpts` config option in `_config.yml` only had a [textual indication](https://jekyllrb.com/docs/pages/#excerpts-for-pages), that this feature was added in Jekyll 4.1.1. I removed this part and added a docs version badge instead.

Add docs version badge to page_excerpts feature

---

jekyll.gemspec

This adds csv as a dependency in the gemspec.
As of Ruby 3.3.0 I was seeing this warning print to the console when running `jekyll serve`:
`/Users/username/.gem/ruby/3.3.0/gems/jekyll-4.3.3/lib/jekyll.rb:28: warning: csv was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add csv to your Gemfile or gemspec. Also contact author of jekyll-4.3.3 to add csv into its gemspec.`
Since this was a fairly simple fix, I figured I'd just throw a PR up for it. I wasn't sure what version to require as a dependency so I just used the latest major version of csv.
I didn't think there was any tests needed for this type of change but let me know if I'm wrong on that.
Notably if we wanted, this could be a conditional …

Add csv to runtime dependency list

---

docs/_includes/anchor_links.html
docs/_includes/docs_contents.html
docs/_includes/docs_contents_mobile.html
docs/_includes/mobile-nav-items.html
docs/_includes/news_contents_mobile.html
docs/_includes/news_item.html
docs/_includes/news_item_archive.html
docs/_includes/search/input.html
docs/_includes/search/script.html
docs/_includes/top.html
docs/_includes/tutorials_contents_mobile.html
docs/_layouts/default.html
docs/_layouts/news_item.html

Improvements made to the docs include changing `<!DOCTYPE HTML>` to `<!DOCTYPE html>` and `en-US` to `en`, adding missing accessibility, documentation and aria-labels, implementing structured data to templates, adding `target="_blank"` to some external links, and adding `defer` attribute for faster page load.
Still making improvements, but I realize I should start chunking these updates down so that the team can review them more efficiently, and to reduce their workload.

Improve accessibility of the docs

---

docs/_docs/continuous-integration/circleci.md
docs/_docs/continuous-integration/github-actions.md
docs/_docs/installation/windows.md
docs/_docs/step-by-step/10-deployment.md
docs/_docs/upgrading/2-to-3.md
docs/_posts/2019-08-19-jekyll-4-0-0-released.markdown

Changed all documentation double quotes to single quotes. In some places there already was a use of single quotes and this is what Bundler suggests to use.
Documentation.

Fix gem quote consistency on docs

---

docs/pages/team.md

Olivia (whose handle I can't find) and Pat should be represented as Emeritus Core Team members. Ben Balter should also be included since he was a big reason I worked on Jekyll as long as I did.
[Olivia was Lead Developer](https://jekyllrb.com/news/2018/02/19/meet-jekyll-s-new-lead-developer/).
Pat was responsible for several releases [as early as 3.4.3](https://jekyllrb.com/news/2017/03/21/jekyll-3-4-3-released/).
Ben was a very early advisor and [released 1.4.3](https://jekyllrb.com/news/2014/01/13/jekyll-1-4-3-released/). Ben was Product Manager for GitHub Pages for a couple years as well.

Add a few more emeritus team members

---

docs/_includes/docs_contents.html
docs/_includes/docs_contents_mobile.html

This is a 🐛 bug fix. 
- 1st commit: fixed typo in docs_contents_mobile.html: `page` -> `current_page`
- 2nd commit: renamed `current_page` to `item_page` in  docs_contents_mobile.html and docs_contents.html
I did the two fixes above as separate commits. This will be my very first PR, so I am not sure if you can see that I did two commits and see the description for each of them. 
I would very much appreciate if you let me do if I did things the right way with this PR :)
- Closes #4567

Jekyll docs template typo - All pages show "Deployment"

---

lib/jekyll/page.rb
test/source/page_with_excerpt.md
test/test_excerpt.rb
test/test_filters.rb
test/test_site.rb

This allows Excerpts to be created from Pages, rather than just from Documents.
jekyll-relative-links started expecting Pages to work with excerpts in https://github.com/benbalter/jekyll-relative-links/pull/65. When github-pages upgraded their version of that gem, it started causing anyone using that plugin to fail the build, see https://github.com/jekyll/jekyll/issues/9544.
I figure it's alright to give Pages the ability to have excerpts.
cc @yoannchaudet

3.9-stable: allow Pages to be Excerpted

---

docs/_includes/docs_contents.html
docs/_includes/news_contents.html

Because if clears spaces, li and class are merged into one, so they are not displayed according to the preset CSS style.

Fixed: Wrong navigation style on the right side of news and docs pages

---

rubocop/jekyll/assert_equal_literal_actual.rb
rubocop/jekyll/no_p_allowed.rb
rubocop/jekyll/no_puts_allowed.rb

This PR uses `RuboCop::Cop::Base` for custom cops.
Follow https://github.com/rubocop/rubocop/pull/7868.
The legacy `RuboCop::Cop::Cop` API is soft deprecated and this PR makes custom cop inherit `RuboCop::Cop::Base` API instead.
> maintain any RuboCop extensions, as the legacy API will be removed in RuboCop 2.0.
https://metaredux.com/posts/2020/10/21/rubocop-1-0.html

Make custom cop inherit `RuboCop::Cop::Base`

---

docs/_docs/step-by-step/01-setup.md

This change adds a redirect from /docs/step-by-step/ to the first page in the tutorial (i.e., /docs/step-by-step/01-setup/), simplifying the URL for anyone who wants to link to the tutorial.

Add redirect for step-by-step tutorial

---

jekyll.gemspec

> This adds csv as a dependency in the gemspec.
I added a `3.10-stable` branch since I think this should be a Jekyll 3.10 release (and go out to GitHub Pages).
> As of Ruby 3.3.0 I was seeing this warning print to the console when running `jekyll serve`:
>
>`/Users/username/.gem/ruby/3.3.0/gems/jekyll-4.3.3/lib/jekyll.rb:28: warning: csv was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add csv to your Gemfile or gemspec. Also contact author of jekyll-4.3.3 to add csv into its gemspec.`
>
>Since this was a fairly simple fix, I figured I'd just throw a PR up for it. I wasn't sure what version to require as a dependency so I just used the latest major version of csv.
>
>I didn't think there was any …

Backport add-csv-dependency from #9522 to Jekyll 3

---

jekyll.gemspec

Add `webrick` as a runtime dependency.
It was [removed in Ruby 3.0 by default](https://github.com/ruby/ruby/blob/v3_0_0/NEWS.md#stdlib-compatibility-issues), but it's our web server for 'jekyll serve'.

3.10-stable: Add webrick as a dependency

---

docs/_docs/plugins/hooks.md

A paragraph was erroneously duplicated, this has been fixed.

Fix minor docs error

---

lib/jekyll/commands/new.rb

Relax version constraint on `gem "wdm"` that contains native extension and therefore creating installation issues. Let Bundler install the newer version of the gem.
Closes #9615
Closes #9646
Closes #9660

Relax version constraint on `wdm` in new Gemfile

---

.github/workflows/ci.yml
.github/workflows/docs.yml
.github/workflows/spelling.yml
.github/workflows/third-party.yml

Use the `paths` and `paths-ignore` filters to limit triggering GitHub Action runs to those files that are relevant to given workflow
[GitHub Actions Docs](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#example-including-paths)

Run GitHub Actions only if needed

---

docs/_docs/permalinks.md

One entry in this table and all the entries in the other tables already had the colons prefix.

Fix incorrect and inconsistent variables in the permalinks page

---

docs/_data/jekyll_variables.yml

Addresses lapses found in the documentation of variables exposed via Liquid global object `{{ page }}`.
Resolves #9656
Closes #9665

Fix lapses in documentation of page variables

---

docs/_docs/configuration/sass.md

This PR adds a note to the Sass/SCSS options documentation to inform users about a known issue in VSCode where it warns about `@import "main";` in SCSS files. The note clarifies that this warning does not affect the functionality of the SCSS code in Jekyll.
Resolves #9506
- Added a note to `docs/_sass.md` explaining the VSCode warning and providing references for more information.
- **Improved User Guidance:** The added note helps users understand that the warning in VSCode is known and harmless, reducing confusion and improving the developer experience.
- **Enhanced Documentation:** Providing clear and accurate information about common issues ensures that the documentation is user-friendly and comprehensive.
- [An error in styles.scss which should be …

Add note about VSCode warning for SCSS files

---

docs/_data/config_options/serve.yml
lib/jekyll/commands/serve.rb

- I've adjusted the documentation.
The `livereload_port` option is already supported internally but is hardcoded to `35729`:
https://github.com/jekyll/jekyll/blob/1484c6d6a41196dcaa25daca9ed1f8c32083ff10/lib/jekyll/commands/serve.rb#L55
https://github.com/jekyll/jekyll/blob/1484c6d6a41196dcaa25daca9ed1f8c32083ff10/lib/jekyll/commands/serve.rb#L74
In order to give preference to user defined `livereload_port` instead of the hardcoded value, the above line needed to be moved from the `init_with_program` function to `process`.
Fixes #9605

Acknowledge `livereload_port` from site config too

---

docs/_data/config_options/serve.yml
lib/jekyll/commands/serve.rb

Makes `livereload_ignore` finally work properly.
Fixes #9502

Fix `--livereload-ignore` option

---

docs/_docs/step-by-step/07-assets.md

In the Assets section of the Step by Step Tutorial, parentheses are incorrectly used, leading to ambiguity.
This PR fixes the aforementioned problem in the documentation.

docs: Fix incorrect parentheses

---

docs/_docs/pagination.md

There is a little bug in the laste code snippet in the pageination section. The link for the first page does not work when the `paginate_path` property points to a subfolder. In that case `{{ '/' | relative_url }}` points to the base url and ignores the subfolder.
I made a little demo which you can find [here](https://swagar.github.io/wrong-page1-link/blog/page2/). There you find the link for the first page twice. One with the old link und one with the new and working link.
You can finde the source code [here](https://github.com/swagar/wrong-page1-link/blob/master/blog/index.html#L38)

docs: Fix of a bug in the pagination section

---

docs/_data/ruby.yml
docs/_docs/installation/macos.md

This is a documentation change to update the current version of Ruby to the
latest as of today: 3.3.5
As for the macOS docs, I updated the supported macOS versions to be in line with what Homebrew supports. I also removed `xz` from the  prerequisites that need to be installed with Homebrew since it gets installed automatically when you install ruby-install.

Update current Ruby version renders and macOS docs

---

lib/jekyll/commands/new.rb

This backports 3a8b282 to 4.3-stable

Backport #9662 for v4.3.x: Relax version constraint on `wdm` in new Gemfile

---

docs/_data/jekyll_variables.yml
lib/jekyll/drops/theme_drop.rb
test/test_theme_drop.rb

- I've adjusted the documentation
`{{ theme.root }}` rendering the absolute path to theme-gem has no value outside development builds.
So, render the value only when site is built in development mode explicitly.
**`NOT A BREAKING CHANGE`**
Consider backport to `4.3-stable` branch.

Render theme-gem root only in development

---

.rubocop.yml
rake/rubocop.rake
rake/task_utils/rubocop_config_formatter.rb

Add a new rake task **`rake rubocop:format_config`** to sort Cop directives alphabetically simultaneously maintain readability by separating cops of various departments with a blank line.
- Dumped list values do not have an indentation with respect to parent key.
- New cop directives need to be manually pasted into the config file prior to using the rake task to sort them into appropriate locations.

Format `.rubocop.yml` via a rake task

---

docs/_data/jekyll_variables.yml

I fixed a typo. It said "atoomatically" instead of "automatically".
I fixed a typo.

Fix grammar in the description of `page.excerpt` variable

---

docs/_docs/step-by-step/07-assets.md

The current example of the Navigation include code will insert the attribute separation whitespace even when the `if` statement returns false:
```liquid
<a href="{{ item.link }}" {% if page.url == item.link %}class="current"{% endif %}>{{ item.name }}</a>
```
which results in unnecessary whitespace being inserted into the navigation node of the non-active page:
```html
<a href="/about.html" >About</a>
```
This patch moves the whitespace into the `if` block so that it will be inserted only when the `if` statement returns true:
```html
<a href="/" class="current">Home</a>
<a href="/about.html">About</a>
```
This pull request addresses a problem in the following documentation:
[Assets | Jekyll • Simple, blog-aware, static …

Fix HTML attribute separation whitespace placement in the Navigation include code of Assets step of the Step by Step Tutorial

---

docs/_data/config_options/global.yml

This pull request adds a missing glob pattern support description in the documentation of the `include` and `exclude` site configuration options.
It appears that Regexp is also supported, but I am unable to use it at my end so it will not be addressed in this PR.
Fixes #9696

Fix missing glob matching pattern support description in the documentation of the `include` and `exclude` configuration options

---

docs/_data/config_options/build.yml

This pull request fixes the missing `url` configuration option documentation, which [seems to be a common source of frustration](https://mademistakes.com/mastering-jekyll/site-url-baseurl/).
It also contains a patch to improve the placeholder value of the `baseurl` configuration option so that the audience won't confuse the two similar but different configuration options.
Fixes #9698

Fix missing `url` configuration option documentation

---

docs/_docs/continuous-integration/github-actions.md

GitHub Pages gem updated their [shipped Jekyll version](https://pages.github.com/versions/) to 3.10.0. This small PR updates the docs to reflect that.
Keeps Jekyll docs up to date with the Pages gem.

Link to GitHub Pages Dependency versions page instead of explicitly specifying Jekyll version

---

features/post_excerpts.feature

`role="doc-noteref"` should be an attribute of the `<a/>` tag instead of `<sup/>` in `features/post_excerpts.feature:92`.

Fix expected markup per WAI-ARIA requirements

---

features/post_excerpts.feature

This backports 7072c65 to 4.3-stable

Backport #9737 for v4.3.x: Fix expected markup per WAI-ARIA requirements

---

test/test_filters.rb

Ruby 3.4 has changed the output string of `Hash#inspect`.
Therefore introduce a custom object (within test case only) to maintain old behavior across tested Ruby versions.
Resolves #9721

Test `inspect` filter with custom object

---

docs/_docs/deployment/third-party.md

Thank you for providing such an amazing tool. 🚀 
I removed the link to "Bip" and its description as the link was broken.
Here: https://jekyllrb.com/docs/deployment/third-party/#bip
Closes #9739

Fix: remove inaccessible links and their descriptions

---

Gemfile

This backports 3689b5b to 4.3-stable

Backport #9742 for v4.3.x: Add an optional `:rdoc` group of gems

---

.github/workflows/ci.yml
Gemfile
features/support/formatter.rb
script/cucumber

- Bump gem `cucumber` to 9.x
- Refactor `features/support/formatter.rb`
- Be compatible with Cucumber v9.
- Truncate printed scenario names to improve readability.
- Remove unused code (since existing `script/cucumber` calls upon the `progress` formatter via `--format progress`).
- Avoid printing scenario info when using the default `pretty` formatter (duplication / redundant).

Bump cucumber to v9

---

Gemfile
History.markdown
jekyll.gemspec

- gem `mutex_m` is only required within gem `httpclient` which is a development dependency. Therefore, it shouldn't be listed as jekyll's runtime dependency. (*The necessary change has been made upstream via https://github.com/nahi/httpclient/commit/6d804c17cf8f8a58ad6605c15f5e1544ee4fc78f but not released yet.*)
- Add a entry in our HISTORY doc to mention addition of gem `base64` as runtime dependency since that change is actually a minor enhancement instead of an internal fix .

Remove unnecessary runtime dependency

---

jekyll.gemspec

- This is an 🙋 enhancement.
Allow using any version of gem `mercenary` greater than or equals to `v0.3.6` but lesser than `v1.0.0`

Remove unnecessary constraint on gem `mercenary`
